### ISSUE TITLE
Last theta cell have fewer photons

### ISSUE THREAD

**Issue by nscepi** [sirocco-rt/sirocco#1000]
Using the star.pf file from the test examples of PYTHON, I find that the last theta cell near the disk midplane has a much fewer photons than the other cells. I attached the .pf file that I used as well as a plot of the density number of photons per cell divided by the average density number of photons over theta. Note that this problem does not depend on the number of photons, the use of the wind_radiation flag, the fact that the wind is optically thick or thin and the number of cycles used. Note that there are two ghost cells at the end of the domain but the cell where this is happening is the cell just before the ghost zones. Note that I also ran this particular run with the random seed generator option but the result does not depend on this.

[issue_git.zip](https://github.com/agnwinds/python/files/11706881/issue_git.zip)

**Comment by kslong** [comment]
This is an odd problem.  I can confirm that I can reproduce it, first of all.  The odd part it that the results do not appear to depend on the number of theta bins.  Here first is the result if you plot the nphot/vol along the two "rows" just above the disk plane:

<img width="686" alt="image" src="https://github.com/agnwinds/python/assets/2530901/45673a94-503f-4f92-8d2c-d40ff3340e4f">

and here is the same thing with only 10 theta bins



<img width="595" alt="image2" src="https://github.com/agnwinds/python/assets/2530901/30c31fea-5174-471b-b5d3-35d11d288d0a">

In both cases, thre are a few percent fewer photons in the row right next to the disk plane

**Comment by kslong** [comment]
This problem has been resolved.
