### ISSUE TITLE
Sudden drop in convergence in Quasar model

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#1001]
I've been running a few quasar models lately for the blueshifts paper. I've already been having some issues with models failing in some cases when using the default upweighting mode, but now I'm getting some very strange behaviour in one specific model (attached). The model works when `SV.v_infinity` is set to 1,2,2.5 or 3, but for some reason at 1.5 i get a sudden massive drop in convergence at cycle 28. Here's the convergence over time output from `run_check.py`:

![Screenshot 2023-06-22 at 11 16 01](https://github.com/agnwinds/python/assets/3007249/d41c21f1-3b64-461d-8888-9ed2f9c323f1)

The model drops from 85% converged to like, 9% in one cycle!! 

The spectra look totally bizarre: 
![Screenshot 2023-06-22 at 11 16 53](https://github.com/agnwinds/python/assets/3007249/7dcc105d-347a-407c-ab64-0d9dcd26c948)

and are totally dominated by a wind which is extremely "luminous" at least in terms of the total photons created. 

![Screenshot 2023-06-22 at 11 17 43](https://github.com/agnwinds/python/assets/3007249/19f6df59-b049-4558-94f8-1a50d8f996dc)

I'll take a look at the temperature and so on to get more insight, but my guess this is due to the failure of the upweighting scheme in low temperature regions.

**Comment by jhmatthews** [comment]
I've rerun the same model with upweight off and I can confirm I don't get this behaviour. Convergence over time is much better behaved.

**Comment by jhmatthews** [comment]
just to illustrate the statement above, here is convergence over time and the spectrum for the same model with upweighting turned off: 

![Screenshot 2023-06-23 at 09 36 39](https://github.com/agnwinds/python/assets/3007249/15308095-6a59-4ce4-a772-66b1e3681e65)

![Screenshot 2023-06-23 at 09 37 56](https://github.com/agnwinds/python/assets/3007249/6a5c5aac-bce6-48c5-a7e0-bc2649b8f158)

**Comment by jhmatthews** [comment]
Here are two movies showing temperature, z, and convergence as a function of cycle number, with and without upweighting. You can see that the two runs produce similar temperature structures after 15-20 cycles, but the upweighting run is struggling to converge in the cool wind base. Then, something happens around cycle 28 which presumably produces some crazy weight photons, which then causes **the entire wind** to become unconverged. My guess is these crazy photons pass through some of the wind and heat it massively, and the wind then irradiates the rest of the wind volume suddenly bringing things out of balance. 

Upweighting on:


https://github.com/agnwinds/python/assets/3007249/0ffab1a2-fad6-47e5-a47a-5ca039c7aef1


Upweighting off:



https://github.com/agnwinds/python/assets/3007249/9fb59dcf-f07a-4163-b0ca-023622d55902

**Comment by jhmatthews** [comment]
Forgot to attach the pf file, here it is: 
[run128_vinf1.5.pf.txt](https://github.com/agnwinds/python/files/11846699/run128_vinf1.5.pf.txt)

**Comment by jhmatthews** [comment]
I think there are a few possible paths here: 
* At a minimum, we need better error reporting, e.g. reporting when upweighting factors are large and possibly exiting the program when "catastrophic" reweighting has occurred
* we might consider just turning off the upweighting scheme by default
* alternatively, we might want an adaptive scheme where we turn it off either once factors outside some tolerance occur, or just where electron temperature is low, since this seems to be where problems arise.

**Comment by kslong** [comment]
@jhmatthews  Where are the SEDs for this  ..... never mind.  I see.

**Comment by kslong** [comment]
I was unable to reproduce this error, even with a longer run:

<img width="482" alt="image" src="https://github.com/agnwinds/python/assets/2530901/03258416-8579-488e-8196-3c4600e11a21">

Possibly I am running with the wrong SED, though I doubt it.

It seems to me reasonable to guess that this is an upweighting problem, since we know that this can produce "streaks" in the various plots, and we know that to reproduce such errors you have to rerun a program precisely with the same number of cores and starting seed.  On the other hand, it is not clear to me why such a problem would have been persistent over cycles, and produce such a dramatic effect.  

It would be good @jhmatthews  if you reran this model with a random seed, to see if comes about in the same way for you.  For me to help more, you probably need to put the windsave file, etc on DropBox

**Comment by kslong** [comment]
@jhmatthews  sent me the windsave files for a run that failed.  Run for scratch I cannot reporduce the problem James saw, but I am running on a different machine with fewer processors

I was able to continue that run on my Mac, version 86g (using 8 threads).  This was not exactly the same commit as the original one but it was close enough to accept the windsave file .  On my Mac, the initial convergence is poor but steadily recovers with addtional cycles as is shown here

<img width="480" alt="image" src="https://github.com/agnwinds/python/assets/2530901/2cae4b74-4c45-4677-888d-2438537f98fe">

I believe James runs are on a machine with a larger number of cores than is easily accessible (24 being the maximum for ksl and we would be better off if we could see it with the current branch of dev.)

**Comment by jhmatthews** [comment]
This bug _may_ be associated with upweighting, but it's so hard to debug given that it is extremely stochastic -- for example, it only occurs in 1/250 or so qso models and cannot be reproduced on Knox's machine. I have a hunch upweighting is responsible, but it's hard to prove. We're closing it for now, but there is a chance it will happen in future. The good news is, it is extremely obvious when this happens as long as you check convergence statistics, which you should be!
