### ISSUE TITLE
I/O Bug in mode readins affecting advance mode only

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#1004]
there's an error in diag.c: 

```
  strcpy (answer, "no");
  n += modes.turn_off_upweighting_of_simple_macro_atoms =
    rdchoice ("@Diag.turn_off_upweighting_of_simple_macro_atoms(yes,no)", "1,0", answer);

  strcpy (answer, "zero_densities");
  n += modes.turn_off_upweighting_of_simple_macro_atoms =
    rdchoice ("@Diag.partial_cells(include,zero_densities,extend_full_cells)", "0,1,2", answer);
```

where the answer from `@Diag.partial_cells` is erroneously copied to `modes.turn_off_upweighting_of_simple_macro_atoms`.

Discovered this when trying to use other diagnostics while keeping upweighting on. I think the fix is just:

```
  strcpy (answer, "zero_densities");
  n += modes.partial_cells =
    rdchoice ("@Diag.partial_cells(include,zero_densities,extend_full_cells)", "0,1,2", answer);
```

right @kslong?

**Comment by kslong** [comment]
Yes, that looks right to me.

**Comment by jhmatthews** [comment]
Fixed in dev by commit https://github.com/agnwinds/python/commit/52886ae24d4542555c9fb4853021c97f3aa9a4e8
