### ISSUE TITLE
wind_save very slow

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#102]
NSH has been carrying out profiling work on python in support of a HPC request for the work with DP. Specificially, I have been trying to find out how many CPUs are worth throwing at one python job. I discovered that more than 200 (for the PK04 geometry) was pointless, since the overall execution time does not reduce. Why? It is the act of saving the wind file after each ionization cycle. For example, with 100 processors, the entire photon generation, transport and ionization calculations takes about 1000 seconds. Then outputting the wind file takes about another 1000 seconds. Either this is a bug, and this wind save process needs to be seriously streamlined, or it is simply the way it is, and to my mind we need to make this step optional so we can take advantage of much bigger machines..

**Comment by Higginbottom** [comment]
OK, so I think this is a bug. I notice that the command to save the wind after each ionization cycle is not inside a MPI check statement. Therefore, 200 processes are all trying to save a wind file, to the same wind file, at the same time. This is not good IMHO. I put the wind save command inside a ifdef MPI_ON check, and only write out if I'm process 0. This fixes it.

**Comment by jhmatthews** [comment]
Good spot Nick!
