### ISSUE TITLE
Read-in abundance consistency

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#1021]
For most  of the Sedona/Python, I have been reading in fixed ionization values where H was the only value given and it was fixed at complete ionization.  But the data file for elements/ions inadvertently had both H and He available.  While models calculated in this manner only had H included in the radiative transfer.  The number density of H atoms in these models was less than for a pure H plasma, which resulted in a lower total electron density than I expected.  

There are two possible options to make things clearer:

- The program could be modified to simply provide a warning when there are atoms in the elements/ions file that have no abundances
- One could actually modify the program to exclude elements not contained in the fixed abundances file.

In the absence of comments from anyone (@jhmatthews) I plan to just add comments and document the issue.  This preserves flexibility, and most of the time, I think when we use fixed abundances we are diagnosing a problem that has somehow occurred, and we would not want the density of ions in the wind to change as we explore different fixed abundance inputs.

**Comment by jhmatthews** [comment]
I think a warning is the minimal thing to do here and adding comments seems reasonable, but note also the issue raised by @lazygun37 on this before which already documents some issues: #291

**Comment by kslong** [comment]
I have added warnings both to read the docs and the code itself.
