### ISSUE TITLE
Decrease in flux near end bins of spectrum

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#103]
In doing the CV runs I noticed a weird bug in which the spectrum seems to drop off near the end bins of the wavelength range. This happens with a standard CV model, BB disk, no macro-atoms, and is easiest to spot when you have a large wavelength range, just because each bin is a little bigger. 

Here's an example with a spectrum generated between 3000-7000A for one specific viewing angle

![30007000](https://cloud.githubusercontent.com/assets/3007249/4108084/5c3d56d6-31d1-11e4-9b76-44602f70e73c.png)

when you change the upper wavelength to 8000 then the drop-off occurs there instead, so it's definitely a bug rather than a real feature. It seems to occur in the emitted, disk etc. columns as well, so doesn't seem to be a problem with extract. I'd bet it's either a problem with how we generate photons or how we bin them up, and may be related to the way we deal with photons being doppler shifted out of the wavelength range. A bit of a review of this section of the code is probably in order, regardless.

I'm looking into it but ideas welcome. It should possibly be fixed before we submit the CV paper although I think it's more or less a cosmetic issue, but obviously quite a bad one.

**Comment by kslong** [comment]
This is a feature, James. It arises from the fact that we do not generate photons outside the range of the values entered in the input file. The assumption was, or is, that plots should be made not over that full range, but one that is reduced somewhat. To fix the problem if you want to call it a problem, one would have to generate photons over a larger range. But I think it might cause confusion in the end we start counting photons.

Knox
Sent from my iPad

**Comment by jhmatthews** [comment]
Ah of course, that makes sense. I think it makes sense to keep it as is, so that the question you are asking in the input file is what range to generate photons over rather than what range to plot your spectrum.

Closing.
