### ISSUE TITLE
.c files not in source directory

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#1031]
For reasons that are unclear there are some files on the dev branch that are now in the main Python directory.  We need to understand why they are there and merge them into dev if they are preferreed.  @nico @jhmatthews I will create a branch that has these files in it and remove them from dev, but we still need to determine what is correct.

**Comment by kslong** [comment]
When i do this, Python fails to compile.  It current fails here

````
mpicc -O3 -Wall  -I../include  -DMPI_ON   -c -o estimators_simple.o estimators_simple.c
estimators_simple.c:317:12: error: no member named 'F_UV_ang_r' in 'struct plasma'
  xplasma->F_UV_ang_r[iangle] += flux[0]*sin(theta)+flux[2]*cos(theta);
  ~~~~~~~  ^
estimators_simple.c:318:12: error: no member named 'F_UV_ang_phi' in 'struct plasma'
  xplasma->F_UV_ang_phi[iangle] += flux[1];
  ~~~~~~~  ^
estimators_simple.c:319:12: error: no member named 'F_UV_ang_theta' in 'struct plasma'
  xplasma->F_UV_ang_theta[iangle] += flux[0]*cos(theta)-flux[2]*sin(theta);
  ~~~~~~~  ^
estimators_simple.c:624:14: error: no member named 'F_UV_ang_theta' in 'struct plasma'
    xplasma->F_UV_ang_theta[i] /= volume_obs;
    ~~~~~~~  ^
estimators_simple.c:625:14: error: no member named 'F_UV_ang_phi' in 'struct plasma'
    xplasma->F_UV_ang_phi[i] /= volume_obs;
    ~~~~~~~  ^
estimators_simple.c:626:14: error: no member named 'F_UV_ang_r' in 'struct plasma'
    xplasma->F_UV_ang_r[i] /= volume_obs;
    ~~~~~~~  ^
6 errors generated.
make: *** [estimators_simple.o] Error 1
````
@nscepi  What is correct here.  Does the branch of Python that you are using have these lines?   If so, can you let James and I know what branch of Python you are using, and make sure it is pushed to the git repository.

**Comment by nscepi** [comment]
Sorry it's my fault, I just understood what I did... I will clean that up!

**Comment by kslong** [comment]
@nscepi has resolved this.  The current dev branch does not have extra .c files in the top level directory
