### ISSUE TITLE
Move gsl under lib + adjust Makefiles, Rename test_suite to examples

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#104]
Move gsl under lib + adjust Makefiles, Rename test_suite to examples

**Comment by jhmatthews** [comment]
test_suite to examples, plus inclusion of some standard pf files is done here: https://github.com/agnwinds/python/commit/3bb47cc4865ba49234f5a08b2754f8809d6e86ac

@kslong - regarding gsl and cfitsio. gsl has a "lib" folder it creates, and also an "include" one (as well as a few other bits and bobs). It's a bit messy to then stick all the lib folder and move the stuff around, and creates potential confusion if the cfitsio and gsl libraries are all in the same place. Take a look at your install to see what I mean. We could just keep it all in the software directory.

In a related issue, I realised that the error scripts actually already were in py_progs already.

**Comment by jhmatthews** [comment]
This has now been done. All header files are under include/ and all library files under lib/ 

This also involved an edit to the source code Makefile, so make sure you pull in changes @kslong @Higginbottom and let me know if any problems

**Comment by Higginbottom** [comment]
When I pull the whole structure down as one thing (as I did the other day to get python on my new mac) it works fine. However, I just pulled the dev branch onto the UNLV machine, then pulled the structure, and it fails to compile stating that the gsl libraries cannot be found...

**Comment by Higginbottom** [comment]
I guess that this might mean that the cray doesn't have the gsl libraries???
Maybe I need to load a module...

**Comment by Higginbottom** [comment]
Yes, that was it. Moral of the story, don't assume gsl is installed on machines over which the user has no control. Now, I have band aided so I can do work by just reinstating the link to the python supplied gsl libraries in the makefile, but i'll need to ask the sysadmin about wether gsl can be put on the machine. In any case, we need a way of dealing with the case where gsl is not there before compilation takes place... A check that all the relevant stuff is there.
While I'm here, the compilers on the cray report an odd error when making python:

[nickh@eureka python]$ make python
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to`main'
collect2: ld returned 1 exit status
Compiling with mpicc wrapper, for compiler 4.4.7

seems to compile ok, but a little disconcerting...

**Comment by jhmatthews** [comment]
Sorry Nick, should have made this clearer. It's because when you pull the structure, you then need to either move the gsl libraries to the right place or reinstall - this is just because the actual library files aren't tracked by git, although perhaps they should be, but reinstalling or a manual move will put them in the right place.

Either way, we shouldn't be moving it around again/reguarly so it shouldn't matter in future.

gsl should always be installed as part of the Python install so you shouldn't need libraries on your machine, and the relevant files will be in either include/ or lib/
