### ISSUE TITLE
Suggestion - Eliminate the spec_tot spectrum leaving only the log_spect_tot spectrum

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#1044]
I have wasted a good bit of time in a situation where i plotted the spec_tot spectrum and not the log_spec_tot spectrum.  

The actual situation was I was trying to do a Python Cloud Comparison and I could not understand why the compariison was so poor. The reason was that in a linear spectrum the low frequencies are all compressed and hence one gets something like

<img width="921" alt="image" src="https://github.com/agnwinds/python/assets/2530901/21aa2fbb-28ec-45b1-94aa-e729e1fb1d3c">

instead of what one gets with the log spectrum, namely

<img width="891" alt="image" src="https://github.com/agnwinds/python/assets/2530901/53430871-1058-4c94-8355-5d6448770b26">

I propose to eliminate printing the linear tot spectra.  

I suspect there may be situation where we need both the log and linear detailed spectra and so I don't propose to eliminate both versions of the spectra for the detailed spectra.  Most of the time we will want linear spectra, but there are times we generate spectra over a sufficiently large range that log energy intervals are preferred.  (Of course, one could add additional lines regarding what type of spectra one wants in the rdpar line Spectrum.type to handle this.)

Comments please

**Comment by jhmatthews** [comment]
I think I always use log_spec_tot and are have rather a large number of spectrum files so I'm in favour of this, it seems cleaner.

**Comment by kslong** [comment]
The linear version of the total spectrum has been removed from the output files and the documentation has been updated.  At a result this issue can be closed.
