### ISSUE TITLE
Default number of wcycles and pcycles is 0

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#106]
At present, if you start python on a blank file and just hit carriage return for every variable you will find the program does not run very far and the pf file will not be created because the ionization and spectral cycles will be set to zero.  We would like be able to create a vanilla pf file, that does run quickly, but it should run.

Investigating the problem shows that there is currently a hard to understand interaction between the variables wcycle, wcycles, ..., which are used only in the main program and  the corresponding veraibles geo.wcycle, geo.wcycles, ...

One could fix things so that the default changed, with some kind of if statement near where data were read from the command line, but this is probably just a band aid a better approach is probably to remove just use the geo variables everywhere and delete the variables wcycle, wcycles, etc from the main routine.  

The concern is that there might some failure situations involving things like restarts that would be a problem.

**Comment by kslong** [comment]
I've now committed a change to dev that fixes this problem, and eliminates the variables that were in main in favor of using the same variables in geo.  I could not find anything that looked like it was a problem associated with anything like restarts or multiprocessor issues.  Others should check however.

**Comment by kslong** [comment]
... what I meant was committed and pushed to the dev branch.

**Comment by jhmatthews** [comment]
Commit here: https://github.com/agnwinds/python/commit/0a0fc57ddf103a45733a62e6001b539c1d7a0594

Looks good Knox. I also like the addition of Log_debug. 

The wcycles/pcycles thing reminds me that there may be something similar happening with NPHOT and photons_per_cycle. I'll try and remember to take a look at this.

EDIT: I did and this was done in #115
