### ISSUE TITLE
Monochromatic.wavelength option not prompting. 

### ISSUE THREAD

**Issue by AustenWallis** [sirocco-rt/sirocco#1071]
Upon selecting a monochromatic spectrum option for the Central_object.rad_type_in_final_spectrum(bb,models,uniform,mono) (bb) :mono
and the 
Disk.rad_type_in_final_spectrum(bb,models,uniform,mono,mod_bb) (bb) :mono 
, the user is **not** prompted for the specific wavelength desired with the monochromatic.wavelength parameter. 
[my_new_model14.pf.txt](https://github.com/agnwinds/python/files/15414478/my_new_model14.pf.txt)

The documentation for this option will need to be updated upon solving of this issue.

**Comment by jhmatthews** [comment]
This is due to a mismatch between num_choices, which is hardwired in two places (in get_choices and init_choices). It was changed in one place (init_choices) without the other. Ideally there should be a link between them, so I'll fix that .

**Comment by jhmatthews** [comment]
Proposed fix #1094 -- can confirm this does make Austen's model prompt correctly for specific wavelength.
