### ISSUE TITLE
Py_hydro in regress.py

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#1114]
Regress.py has a function py_hydro, that looks for a file called hydro in examples/regress.

That file does not exist in regress, though it does exist in regress.old

* Is this test something that we still want, or can it be removed from regress.py? My suspicion is the whole test is out of date.
* Can the entire regress.old directory be deleted? It seems superfluous today.  It's likely that some of the regression tests should be updated to be more current with things we are running today, but I would not want that to be part of this issue.

Once these questions or answered, I can fix the test

**Comment by jhmatthews** [comment]
I'm not sure what either of these things are, so if noone is using them I think it's fine to remove them.

**Comment by kslong** [comment]
Will do.

**Comment by jhmatthews** [comment]
Fixed by #1118
