### ISSUE TITLE
unit test 

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#1115]
There are two small problems with the unit_test implementation that should be corrected

* Currently the Makefile for unit tests has to be updated if a change is made to the c files needed to compile sirocdo.  This should not be necessary.  The unit test make file should get the information that a change has been made by importing it from the main source makefile
* When I was experimenting with tightening the requirements for calculating ne in the ionization routines, the unit_tests failed because a variable FRACTIONAL_ERROR was changed.  FRACTIONAL_ERROR should be defined independently in the unit tests, so that the unit tests are more independent of python.h

**Comment by jhmatthews** [comment]
On point one, i think we can do this with these lines: 

```
include $(SIROCCO)/source/Makefile 
SIROCCO_SOURCES = $(sirocco_source) get_models.c
```

I don't know why we need the get_models.c separately, but there's a comment about this in the main Makefile. 

Point two: yes, we can change this to ERROR_TOLERANCE or something, defined only in tests.
