### ISSUE TITLE
Generic problems with using models from data directory

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#112]
At present many of the stellar models files do not work with Python, at least as it set up with Setup_Pydir.  This is because the .ls files do not have the correct prefixes everywhere.  Right now, Setup_Py_Dir appears to work for the atomic datafiles I have tried, but not for kurucz91, for example. 

We need either to fix the .ls files, or change some of the behavior of the files that read the data.  For example, we could change things so that actual spectra, etc are in the same directory as the .ls files, and we look for them there.  

We need to decide how we want to do this, and then systematically verify that all fo the the files in the data directory can actually be read into Python.  It's a bit hard to write a manual until we sort this out. (and it will be a problem for any beta testers).  

Note that the changes are all easy to implement, but we really need a definitive plan.

**Comment by jhmatthews** [comment]
I prefer having the absolute path in the ls file. It's more robust I think, and I also think it's easier if you just want to tweak a file locally in your run directory without having to move the actual data around.

I'm then changing the ls files so they all have the following format:

```
lejeune.ls
kurucz91.ls
tlusty_d14.ls
```

and are invoked from the pf files with e.g.

```
data/kurucz91.ls
```

I'm verifying that this all works currently and modifying the paths accordingly. Then the only remaining issue will be fixing #113
