### ISSUE TITLE
Use bilinear interpolation method on v_grad for dvwind_ds in all coordinate systems

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#126]
In #118 I imposed a rather lazy fix for our incorrect calculation of dvds in spherical coordinates which meant that we now do an on the fly calculation of dvds in spherical coordinates only. 

Ideally, we want to do an interpolation on v_grad here, which is stored at each cell vertex. This should be improved by figuring out out how the velocity gradient tensor ought to be rotated in order to give the right answer for spherical coordinates.

The mystery here is why changing the angle along which the grid is defined doesn't change the angle at which the answer is correct.

**Comment by jhmatthews** [comment]
I'm closing this. Ideally we should figure it out, but it's not really a good use of time. The spherical model works with the on the fly methody, and it will never be a production model anyway.

**Comment by kslong** [comment]
I believe you should redefine this as an enhancement.  I think we are always going to need the spherical model.  Knox
