### ISSUE TITLE
Shooting method solver failing for Fe

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#127]
Nick showed fairly convincing evidence that our shooting method for ionization balance of the Lucy Mazalli method is failing for Fe.  He thinks, and I agree, that the most likely problem is due to the fact that we have a large number of lower level ions, with very low abundances, and this causes a problem when you get to high ionization states. 

If this is the case, then the simple way out of this problem would be to determine in advance where the most abundant ions are for a given set of conditions, and work out from there in determining the ratio.  

It would be desirable to sort out this problem, especially if we are going to leave the shooting method solver in the code when the code becomes public, but also to verify the matrix inversion techique.

**Comment by jhmatthews** [comment]
@kslong - This work is in the matrix_ksl branch. You should be able to see what would happen if we merged matrix_ksl into dev by going to the following link:

https://github.com/agnwinds/python/compare/dev...matrix_ksl

**Comment by kslong** [comment]
James will merge and check that my update works.  We  may want to ultimately delete this method.  James said one could not quite reproduce the Lucy and Mazzlli with the rate matrix.  James said it was because of the assumption about the recombination.

**Comment by jhmatthews** [comment]
I've tested this for thin shells and the results look sensible as Knox found above. However, it seems to produce errors in examples/core/cv_standard.pf. Namely, lots of errors of this type:

```
ionization_on_the_spot: nebular_concentrations failed to converge
```

that are not produced in the current dev version. This is the error that is produced when the code fails to produce a change in ne of less than FRACTIONAL_ERROR inside the maximum number of iterations (MAXITERATIONS). Increasing MAXITERATIONS to the dev value of 200 (Knox had set it to 100) does not help. 

Unsure why this is happening but it seems this method is not more stable in current form.

**Comment by kslong** [comment]
@jhmatthews   I am not sure what the path forward is here.  Do you have a .pf file that illustrates any remaining problems.  Or should we bite the bullet, and remove some of our ionization approaches from python, since we don't use them and would not recommend others using them.  We really need to either include .pf files for all our problems, or put them somewhere and reference them from github.

**Comment by jhmatthews** [comment]
@kslong I always try and use a standard pf file if possible, and simply give the location in the Python directory as I did above. 

I think I would advocate the following way forward here, which is all linked to ionization modes too (see #215):
- Keep the source files for the old method in the code
- Make the shooting method (modes 3,6,7 currently?) only accessible via advanced mode or a compiler flag
- Add in some error logic to stop a user using these modes
- This allows us to test but means we use matrix methods where possible
- Consider changing ionization mode to a string for clarity

Questions to answer include how we want the LTE modes etc to work.

**Comment by kslong** [comment]
@jhmatthews   I think we/I dropped the ball on this one in terms of getting it into dev  But perhaps we should try to recover.

**Comment by kslong** [comment]
The matrix_ksl branch still exists, but this version of the routine is so old it requires the fitsio library to make the code.  

The problem we though we were having was that when you had a lot of ions for an element, and the saha factors between adjacent ions was too great that one could end up with numbers whose exponents were out of range for the computer.  We originally limited this to 10**20 which is too large.  We set the maximum difference between adjacent ions to

```
big=pow(10.,250.)/(last-first)
```
where last and first refer to the first and last ion number. In principle this should address the original problem.  It is  is different from what was there originally ), although ksl does not know if it actually solved the problem.

The version of saha that exists in the matrix_ksl branch is different. For any element, it first identifies the ion that is likely to be dominant (or near dominant), given the temperature, and then works in two directions (one toward lower ionization states and the other toward higher ionization states.  Once you get below a certain density it stops.  This avoids the problem caused by the accumulation of many powers of 10, and is somewhat more "elegant".

However, what is needed is a robust test of the code for this problem. Before we decide there is really anything that needs to be done, since these modes really are mostly out of date at this point.

**Comment by jhmatthews** [comment]
This is a very seldom used mode for calculating ionization states and should only be used in test cases (for example, when comparing the SN model to tardis). As a result this can be closed with caveat, but this may pop up if someone cares for some reason about Fe in, e.g., the Lucy Mazzali scheme.
