### ISSUE TITLE
Macro-atom estimators not communicated between threads

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#132]
I have no idea how I failed to notice this before (sorry), but (as far as I can tell) the estimators contained the macromain structure are not communicated and averaged between threads as they should be. The most important variable that is not communicated is probably matom_abs, although they could all be affected.

This leads to poor estimator statistics especially when one uses a lot of cores, and I think it also leads to estimators from different threads being used in different parts of the wind in my parallelised loop to calculate macro-atom emissivities in get_matom_f.

I will try and fix this ASAP. It should just required an extra loop in wind_updates which loops over all the estimators and averages them for each cell.

I am hoping this will go someway to explaining the patchy emission structure I've been seeing and multiple double peaks in the line profiles in the CV models.

**Comment by jhmatthews** [comment]
The fix to this is to gather up the required estimators and average them between threads. This is done using MPI_Reduce in much the same way we do for the estimators for the spectral model ionization scheme. 

I am implementing and testing this now - the proposed fix can be seen in commit https://github.com/jhmatthews/python/commit/878acfa5a057d4fb1b2f00b3e658ba84a2bfcf1b

**Comment by jhmatthews** [comment]
I've also noticed that there was a mistake in the communication of 'number of photons', in that the 'send arrays' were used, rather than the 'received arrays' after the MPI_reduce (see documentation [here](https://www.open-mpi.org/doc/v1.5/man3/MPI_Reduce.3.php)). This should just be diagnostic and mean that a number of things python reports, such as number of photons, number of photons in each cell, etc, would be wrong. This has been fixed quickly by https://github.com/agnwinds/python/commit/ea488ff0a33e3b274f68808fc5bef26f2c0c61e9 but the fix to this whole issue will tidy it up a bit.

**Comment by jhmatthews** [comment]
I'm still having some problems with the stability of this fix, a problem I'm not quite sure of yet. However, I've got some completed runs which show much improved results as a result of fixing this issue.

The below plot shows level emissivity structure throughout the wind in the benchmark model, computed before ("bench_old") and after ("with_fix") the fix which averages macro-atom estimators over parallelised threads. These were both computed with 48 processors.

The top panels show individual pixel values so one can see the level of noise in the emissivity. the bottom panels are contour plots and have the actual values in the colorbar of level emissivities in erg /s/cm^3.

![imshow_lev3only_with_fix](https://cloud.githubusercontent.com/assets/3007249/5704163/a9ab9c5e-9a66-11e4-9a87-4afa9ab0a72e.png)

Most importantly, we see a big improvement in that the big spikes in emissivity now disappear and our structure is much smoother. We also now do a lot better at recording estimators in the portions of the wind which are less dense and therefore have very low emissivities.

This also gets rid of the the 'quadruple peak' in the line profile we were seeing- it looks like the higher velocity peak was just as a result of a noisy cell at the inner edge of the wind.

![h](https://cloud.githubusercontent.com/assets/3007249/5704401/d3cf8fe8-9a68-11e4-83cc-c266f18bffd2.png)

**Comment by jhmatthews** [comment]
This, in theory now looks to be fixed, but I'm having weird problems on iridis with the CV runs. I'm not at all sure what the problem is and whether it is a problem with iridis itself or my coding.

I have had situations where runs still claim to be running after say 20 hours, but none of the output files have been updated since the first 20 minutes or so. It's therefore very difficult to work out what is going on. Furthermore, when I cancel the run and start it again (from scratch), it sometimes runs completely fine. Very odd - @Higginbottom have you had anything like this before?

**Comment by kslong** [comment]
When we instantiate the threads, do we have a different seed for the random number generator in each thread.  I assume so.  If so it’s quite hard to understand how all would stop at once, from natural causes.  The only way I can think of to help with this would be to make use of “flush” more often.

**Comment by Higginbottom** [comment]
Hi James,
Yes, I have had problems of this nature with not just iridis, but with the UNLV cray as well. I have never been able to get to the bottom of it on Iridis, however on the cray - which is a smaller and more chummy system, we have tracked it down to malfunctioning nodes. So the whole run gets held up by one process which gets held up on a dodgy node. Not sure if this is your problem, but it certainly matches with the problem of replicating the failure. 
As Knox says, my solution in these situations is to stick lots of log statements in followed by flush commands to try to track down where the run is stalling.
Cheers!

Nick

**Comment by jhmatthews** [comment]
Do we know what we mean by dodgy node? I must say that this explanation fits, because there is an MPI_Barrier() call just after the last log statement that I see. So perhaps the other threads are there waiting for one/some which get help up.

It's a little weird that it only happens now, only after I've put this fix in place (i.e. why doesn't it occur where other MPI_Barrier's exist? What is it about my new bit of code which does this?). I wonder if there is a common denominator between the runs with problems you did, Nick, and the ones I've done....

On a related note, it may be worth having an even higher verbosity setting which flushes every time the log statement is called, more or less entirely for problems like these and debugging on multi processor runs.

**Comment by Higginbottom** [comment]
Dodgy node is deliberately vague, coz I never quite found out what was going on. They rebooted a node and the problem went away. I think it has lost its hard disk or some such. 
Why didn't it happen before? 
a: Pure chance - there wasn't a broken node before, or you never encountered it
b: The heavy lifting of doing your complicated macro atom calculations isn't shared equally, and one processor only is going into some kind of infinite loop which holds everything up - but surely this would have held everything up before, and also presumably it would _always_ happen rather than just sometimes.

Your last point is an excellent idea IMHO, although TBH I can't see much of a reason not to just incorporate a flush into the log command. The aim of the buffer is to reduce disk access that could slow a process down, but we write so few logs that it really won't make any difference to runtime. One could easily experiment and prove this of course...

**Comment by jhmatthews** [comment]
Ok, thanks Nick.
- Closing this, fixed by #135 with the caveat that we still don't full understand why the runs are failing (dodgy node stuff) but it would seem to not be a problem with this piece of code
- @Higginbottom  and @smangham - keep each other posted on how often you notice this behaviour when running in parallel, if at all.
- At some point I'll look into flushing every call to see how it affects performance, and implement something depending on results.
