### ISSUE TITLE
DFUDGE inconsistencies

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#133]
It's possible for a photon to scatter in a void cell within DFUDGE of the boundaries of a wind cell. However, the velocity used when doppler shifting after the scatter is that of the photon's current position (which, given it's outside of the wind, may be 0).

**Comment by jhmatthews** [comment]
Sam, do you know what actually causes this? I've been looking at the code and although there are comments from Knox saying that this happened (with commented out code, see l.354 trans_phot.c) I can't actually figure out how a photon can scatter without having it's grid cell designated 

The only place istat (which is like the state of the photon i.e. hit disk, just scattered, coursing through wind) is set to P_SCAT is in calculate_ds. The only way you can get it into that routine is through translate_in_wind, which is called in the following way by translate():

``` C
else if ((pp->grid = where_in_grid (pp->x)) >= 0)
    {
      istat = translate_in_wind (w, pp, tau_scat, tau, nres);
    }
```

...which would seem to update the 'grid' variable as required. Am I missing something?

**Comment by jhmatthews** [comment]
Is this is related to an error I am getting in some QSO models? @Higginbottom you may have seen this one before:

```
trans_phot: Trying to scatter a photon which is not in a cell in the plasma structure
trans_phot: grid 9590 x -5.56e+18 6.84e+18 -4.71e+18
trans_phot: This photon is effectively lost!
```

**Comment by jhmatthews** [comment]
See #154 - @smangham I'm not sure if this is identical in cause to the bug you initially raised here.

**Comment by kslong** [comment]
We need a pf file that shows this error.  dfudge is now computed on a cell by cell basis and I believe this problem has gone away.

**Comment by kslong** [comment]
@smangham  needs to test and see if it is solved or not.

**Comment by kslong** [comment]
@smangham   This was an issue that you raised, but the last comment on it was over two years ago and it asked you to test whether it was solved.  From your perspective, can this be closed.

**Comment by smangham** [comment]
I honestly can't remember at this point. I've not seen it in any of the runs I've done for a while, so I'm happy to close it.
