### ISSUE TITLE
Incorrect normalization when restarting spectral cycles

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#134]
This is a problem of my own making, and I'm just flagging it here for documentation purposes, as it is present in e.g. Python 78b. A short time back (see https://github.com/agnwinds/python/commit/ec8ccec2d2d70d6a130e6e138b9ab965528496c2) I changed get_matom_f() - the function which computes the macro-atom emissivities - so as to only recompute if geo,pcycles was 0. The reason being that one shouldn't have to go through the very lengthy process of computing macro-atom emissivities if you just want to restart a run to get better photon stats.

At the moment a restarted model with 500 spectral cycles has a very different continuum level (green is the restarted run, identical model and wind state):

![screenshot 2015-01-15 17 07 36](https://cloud.githubusercontent.com/assets/3007249/5762301/0e7ecc36-9cd9-11e4-97f9-eadbfd376fb8.png)

I must have made a mistake somewhere, which is probably very simple and related to normalising the photon weights or similar. I will correct ASAP.

**Comment by jhmatthews** [comment]
Ok, so this is nothing to do with macro-atoms or any of my recent changes. I ran a very very simple supernova model as far back as Python 77 with no wind or disk on, 1d, star only. Run 10 spectral cycles, restart running 50 spectral cycles with the same model. Outputs should be identical except the longer run should have better S/N. This is the result (green is restarted). Clearly we are failing to normalise properly in this case.

![spec_old](https://cloud.githubusercontent.com/assets/3007249/5858283/cd029ca8-a249-11e4-8576-1413fd71da63.png)

Name of issue changed.

**Comment by jhmatthews** [comment]
In case it's not clear- this probably means that for all runs which restarted the spectral cycles to get better S/N, the spectrum will have incorrect total flux. This is not a problem in my CV runs where I deliberately did not restart.

**Comment by Higginbottom** [comment]
Uh oh!
I do not believe this will affect any of my published work either - I don't think I've ever restarted spectral cycles. It must be something pretty simple though....

**Comment by jhmatthews** [comment]
It is! The problem is just that when we read in a spec_save file we don't normalise the stuff we read in. 

So for example, I am finding that if I run one model with 1 spectral cycles, then restart then run so that it does 5 cycles in total (4 more), the total flux is out by a factor of 1.8.. i.e we add 1 cycle of stuff to another 4 cycles, but the 4 cycles have a weight normalisation of (1/5) less than the spectrum we've read in. 

The saved spectrum we read in should be multiplied by a factor f:

f = (cycles in old pf file) / (cycles in new pf file)

That was explained terribly but you get the idea. simple change which I'll make when I get a minute.

**Comment by jhmatthews** [comment]
I've fixed this with a simple little function called  spectrum_restart_renormalise() in commit https://github.com/agnwinds/python/commit/3ec1dae68d0f8584fac3d107400bb54512394384

Also verified that it produces correct results when all of the extra cycles are completed, and also if the restarted run is interrupted before the end (i.e. it is normalised correctly each cycle). Closing.
