### ISSUE TITLE
reorganise python.c

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#136]
python.c is messy. Moving some of the input gathering and setting up of the structure would help. There's an example implementation here: https://github.com/jhmatthews/python/commit/6c653b6d5948f5efde3af8aed2c531f75ac041d2

in particular, lines 762-1373 could easily be moved to subroutines. Obviously the danger is always that one breaks something, but I think this should be fairly painless as one always just modifies the geo structure.

**Comment by kslong** [comment]
I agree with the initial statement.  I think it is time to move all of the inputs, or essentially all of them to a separate routine.   Ultimately this could facilitate a different interface to python.

**Comment by Higginbottom** [comment]
This sounds like a really good idea. I can think of lots of 'nice to have' features in a new interface.

**Comment by smangham** [comment]
If python is getting reorganised we could potentially apply to the Software Sustainability Institute (based in Southampton): http://www.software.ac.uk/open-call
They provide free consulting for projects, and apparently are particularly keen on helping rework code for public release. A project in Computational Chemistry recently applied successfully- if we wanted to make an SSI application, I could try and get in touch with them about theirs (a housemate works in their office).

**Comment by lazygun37** [comment]
That's a really interesting idea Sam. By all means, have a chat with your housemate and then you can update us a bit on what's on offer and what's required from us.

Thanks!

C

**Comment by jhmatthews** [comment]
This issue has been mostly addressed by an initial reorganisation by me (#139) and some good work by @kslong in the domain2 branch. It can be closed once domain2 is fully merged (which might be a little while!)
