### ISSUE TITLE
In single star mode still get asked about binary phase

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#137]
Currently if uses single star mode in the inputs, you are NOT asked to describe the secondary, but you are asked what phase the spectrum should be extracted for.  Clearly a small bug.

**Comment by jhmatthews** [comment]
Do we want to remove the phase questions for single stars and AGN?

**Comment by kslong** [comment]
Yes, I think so!

**Comment by jhmatthews** [comment]
Done. phase is already set to default of 0.5 prior to readin so simple if statement added to take out code unless geo.system_type = SYSTEM_TYPE_BINARY.
