### ISSUE TITLE
write standard tests

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#140]
a todo for me.

**Comment by jhmatthews** [comment]
This is slowly being sorted. Tests are hosted [here](http://jhmatthews.github.io/pyregress/) and will be run nightly. Ionization tests and a few key models, gradually being improved. 

Take a look @kslong

**Comment by kslong** [comment]
So, James, this looks nice.  What happens in the sense  of history.  If I make a change in dev and push this, then I assume it get’s run over night.  But how would a difference become apparent.
Knox

**Comment by jhmatthews** [comment]
Yep, it gets run over night regardless.

If a run fails or quits for whatever reason, then I will get an email telling me what broke. Other than that it's really a case of manually looking at the comparison plots at the moment.

I would like to gradually incorporate things that notify me if e.g. there was a change in a quantity such as flux or ion fraction above some noise threshold so eventually it's quite a self-sufficient smart routine.

**Comment by kslong** [comment]
Agreed, and something that simply reports the standard deviation of the difference in spectra might be helpful, both against some baseline time, and the previous nights run.
Stats on convergence might also be something to compare.

**Comment by jhmatthews** [comment]
Standard tests are now here: https://github.com/jhmatthews/py-test-suite
and the website is here: http://jhmatthews.github.io/py-test-suite/

I had to move because of some problems with the old repo and github pages.

This is now run on endjinn, our server, which in theory allows us to run some slightly more extensive tests, perhaps once a week on mutliple cores, and a simple daily test which is currently what is implemented.

**Comment by jhmatthews** [comment]
The above test suite is still run nightly, but I've written something which is more user friendly. This is a good starting point which we can now all work on to improve. It's stored in this repository:

https://github.com/agnwinds/unit_tests/

View the README to take a look at how to use, and get stuck in. Run some tests and improve at your leisure.

Improvements needed I can think of:
- Add scripts to do diffs and check them automatically for "hard" comparison
- Need a way to plot the wind in 1d models and other coordinate systems
- Wind plots are fairly ugly and don't always have the right limits
- Need some way for estimating if something is within photon noise
- Need to add heating and cooling plots
- Need checks of errors and suchlike
