### ISSUE TITLE
Warnings in py_wind_macro

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#144]
My compile of py_wind is generating these warnings

py_wind_macro.c:471:7: warning: variable 'x' is used uninitialized whenever 'if' condition is
      false [-Wsometimes-uninitialized]
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
py_wind_macro.c:486:12: note: uninitialized use occurs here
     wmain[x->nwind].xcen[0], wmain[x->nwind].xcen[1],
           ^
py_wind_macro.c:471:3: note: remove the 'if' if its condition is always true
  if (icell >= 0 && icell < NDIM2)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_wind_macro.c:471:7: warning: variable 'x' is used uninitialized whenever '&&' condition is
      false [-Wsometimes-uninitialized]
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~
py_wind_macro.c:486:12: note: uninitialized use occurs here
     wmain[x->nwind].xcen[0], wmain[x->nwind].xcen[1],
           ^
py_wind_macro.c:471:7: note: remove the '&&' if its condition is always true
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~~~~
py_wind_macro.c:461:14: note: initialize the variable 'x' to silence this warning
  PlasmaPtr x, xdummy;
             ^
              = NULL
2 warnings generated.

They are all about uninitialized variables which would be easy to fix, by initializing things, but it is less clear to me (ksl) that these are not if statements where the logic has not been worked out completely or to check for error conditions.

**Comment by jhmatthews** [comment]
Try now @kslong - I added an error condition.

**Comment by kslong** [comment]
I am still seeing these 2 warnings:

py_wind_macro.c:477:7: warning: variable 'x' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
py_wind_macro.c:492:12: note: uninitialized use occurs here
     wmain[x->nwind].xcen[0], wmain[x->nwind].xcen[1],
           ^
py_wind_macro.c:477:3: note: remove the 'if' if its condition is always true
  if (icell >= 0 && icell < NDIM2)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_wind_macro.c:477:7: warning: variable 'x' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~
py_wind_macro.c:492:12: note: uninitialized use occurs here
     wmain[x->nwind].xcen[0], wmain[x->nwind].xcen[1],
           ^
py_wind_macro.c:477:7: note: remove the '&&' if its condition is always true
  if (icell >= 0 && icell < NDIM2)
      ^~~~~~~~~~~~~
py_wind_macro.c:467:14: note: initialize the variable 'x' to silence this warning
  PlasmaPtr x, xdummy;
             ^
              = NULL

**Comment by kslong** [comment]
Apparently, James, you made some changes to fix this, but there were a couple of places where you used a python language construct instead of a c-language construct.  I fixed these and it compiles now without errors on my machine.  I've pushed this back to dev.  Close if you agree.

**Comment by jhmatthews** [comment]
Woops...my automated build test caught this but it would appear having Knox on your team is just as effective! Closing.
