### ISSUE TITLE
Binning of spectrum output: Freq or lambda?

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#149]
Currently we bin uniformly in frequency space for our .spec output. This happens even if we request an Flambda spectrum, which seems a little silly. I feel like as a user I may feasibly want to generate a spectrum between 2A and 2000A without losing all resolution at around 1000A (in the code at the moment you would only get a few bins in that region, and no lines show up in the UV). 

Proposal to bin in wavelength space for the .spec files when the user requests an Flambda spectrum, but keep the current procedure for .spec_tot, .log_spec_tot and when the user requests Fnu. 

We may want to improve this in general- for example the user could specify a spectral resolution they require. I could make this an 'advanced mode' feature.

**Comment by kslong** [comment]
Sounds reasonable, or at least the first bits do.    I guess it is, in part, preparatory to possibility that we actually want to construct macro-atom spectra over wide wavelength ranges.

With regards to given the user flexibility in selecting the resolution we should think how we would like to do this.  I think I would favor simply expanding the options on the choice of output spectral types, e.g. f_lambda, f_nu, f_lambda(user_specified resoluition), etc.  or something.  For user_specified, there would be an additional question of some kind.

Note that from an observer perspective, one usually either wants a fixed resolution (which means dlambda is proportional to lambda) or fixed steps in wavelength or energy space.

**Comment by jhmatthews** [comment]
That sounds sensible Knox and avoids excessive parameter file variables. I can implement that with different resolution modes if one selects that option. Then that won't require existing param files to be changed.

**Comment by kslong** [comment]
We need a general proposal about what spectra we should be producing.  @jhmatthews & @Higginbottom to make a proposal on what changes we need to make in the spectra that are produced

**Comment by kslong** [comment]
@jhmatthews  and @Higginbottom    Can we close this assuming you are reasonably happy with the way things are, or can you say exactly what you would like so that someone (perhaps you) could implement it?

**Comment by jhmatthews** [comment]
Happy to close. If someone wants to make spectra with a specific wavelength resolution we can reopen. The log spectrum Nick made helps a lot for many purposes.

**Comment by Higginbottom** [comment]
Im happy!

**Comment by kslong** [comment]
Since everyone is happy for now, we will close this issue.
