### ISSUE TITLE
Extra diagnostics option problem

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#151]
Just lost a bit of time getting python to write out windsave files for each cycle.
No problem working out the -d flag, or where to put the new commands, but took quite a while to realise that the new commands _require_ an open parentheses to delineate the and of the command and the start of the answer. This is not how python normally works. One can leave out the (comments) in a command and it works fine. Obviously this is a low priority to fix, because I now know how to do it, bit we should be consistent!
This links to #111

**Comment by jhmatthews** [comment]
My mistake Nick. When there's no ( it doesn't evaluate the wordlength in this case. Fixed now in dev with one extra cmd in the function rd_extra()
