### ISSUE TITLE
segfault from reverb code

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#152]
Hey @smangham - I'm getting segfault from delay_dump_single() when I run a model with geo.reverb set to zero. I think it's because of these lines in extract.c

``` C
    if (pp->nrscat > 0)     // SWM - Records total distance travelled by extract photon
        {
            stuff_v(pstart.x, pp->x);   // Restore photon to initial position (necessary for reweighting)
            pp->path = pstart.path;
                delay_dump_single(pp, 1);       // Dump photon now weight has been modified
        }
```

so we call delay_dump_single, even though we haven't allocated the space for the delay dump structures- a simple if (geo.reverb>0) here should sort this. Agreed? 

Flagged in case it affects @Higginbottom 's runs too

**Comment by smangham** [comment]
Yes, definitely- sorry, I thought I had a check in there for that.
