### ISSUE TITLE
Which atomic species should be included in a model?

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#153]
Currently, we don't include all atomic species in our data files. We tend to go for 

```
H,He,C,N,O,Ne,Na, S,Mg,Al, Si,Ar,Ca,Fe
```

This leaves out e.g. P which is seen in some real spectra of AGN (PV absorption lines, e.g.). 

Is there a good reason for leaving elements out, and should we revisit this?

**Comment by kslong** [comment]
There is no reason for leaving out P, but adding this might be wrapped into the general question of how does the atomic data need to be augmented especially to make the code more X-ray friendly.

**Comment by kslong** [comment]
All of this is true, but there is nothing immediately that we think we should do.
