### ISSUE TITLE
How to check when a photon hits the disk

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#155]
Walls() is the routine which checks whether photons hit the disk or not. e.g., in the case of a thin disk

```
if (geo.disk_type && p->x[2] * pold->x[2] < 0.0)
    {               // Then the photon crossed the xy plane and probably hit the disk
```

The statement of probably hit the disk is clearly not true if the wind scale is much larger than the disk- which it normally is.

I think there's an interesting question here, which is whether this is the correct definition of "hitting the disk". We define a disk radius and typically that is a lot smaller than our wind. You could have significant amounts of radiation backscattering from e.g. north->south in portions of the wind which are outside of the disk radius, which we throw away. We should think about what the most physical thing to do here, related to the boundary conditions of our system. It seems to me that to be self consistent, if a photon crosses from North to South then we should only make it hit the disk if the disk is actually defined at that radius.

**Comment by kslong** [comment]
It seems to me that to be self consistent, if a photon crosses from North to South then we should only make it hit the disk if the disk is actually defined at that radius.  —> I believe that this is what the S/W actullay does.  Please make sure this is a problem.  I think there is/was a check for whether you passed through the disk outside or inside the disk area.

**Comment by jhmatthews** [comment]
Sorry @kslong - I am being stupid and failed to spot the correct portion of the code. @lazygun37 and @Higginbottom - we are in the clear here.
