### ISSUE TITLE
get_atomicdata

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#156]
In trying to research what data we have for use with python, I have encountered several interrelated issues, which may or may not be bugs
1.  get_atomicdata.c was intended to be a more or less standalone routine, which could easily be incorporated into other routines.  At present, because get_atomicdata calls a21 any program which reads get_atomic data has to include lines.c and from there a bunch of other routines.  a21 probably ought to be moved back to get_atomicdata, which is easy, but we need to decide whether there are other routines that should be isolated.  I believe we need to maintain a separation between basic routines that calculate say a cross section or a rate from any routine that invokes a variable in python.h.  
2.  get_atomicdata.c is no longer able to read old versions of our atomic data files.  This was associated with our decision to tabulate the photoinization files, and may be OK, but ... it has some negative implications in terms of understanding whether differences in a model between some older version and a new version are due to atomic data or other changes in the code.  At a minimum, this change should be documented in the header information about get_atomic data.  (Note that this problem is going to cause confusion when we give the program out to others so we need to think what we want to do here carefully.)
3.  There are some errors in get_atomicdata that refer say one needs to read a specific file. This is clearly not what we want.  This error should be more generic.  (This is minor but should be fixed)

Specifically here is what gets printed out

get_atomic_data: file data/atomic73/photo_fkvy.data line 2: photoionization line incorrectly formatted
Make sure you are using the tabulated verner cross sections (photo_vfky_tabulated.data)
1.  For standard78, it looks as if it is possible to have lines that are not connected to levels.  I had written a little routine that looks at each ion and prints out the number of levels and the number of ions

For iron this gives:
ion 151 26  1   68   136
ion 152 26  2   91   222
ion 153 26  3  392   199
ion 154 26  4  415     3
ion 155 26  5  187    42
ion 156 26  6   35    46
ion 157 26  7   11   170
ion 158 26  8    4    51
ion 159 26  9    3     3
ion 160 26 10    7    36
ion 161 26 11    9    33
ion 162 26 12    8    11
ion 163 26 13   10    38
ion 164 26 14    5    17
ion 165 26 15    3     4
ion 166 26 16    2    11
ion 167 26 17    1     6
ion 168 26 18    1    56
ion 169 26 19    3    36
ion 170 26 20    3    11
ion 171 26 21    4    44
ion 172 26 22    2    24
ion 173 26 23    2     6
ion 174 26 24    2    10
ion 175 26 25    1     4
ion 176 26 26    1    18
ion 177 26 27   -1     0

In this tabulation what is printed is the ion number, z, ionization state, the number of levels for that ionization state, and the number of lines for that ion.  It should not be possible to have 18 lines with only one level.   

I believe this is happening because standard78 looks like:

data/atomic78/elem_ions_ver_73.py
data/atomic78/topbase_levels_h.py
data/atomic78/topbase_levels_he.py
data/atomic78/topbase_levels_cno.py
data/atomic78/topbase_levels_fe.py
data/atomic78/levels_ver_2.py
data/atomic78/lines_linked_ver_2.py
data/atomic78/excited.py
data/atomic78/recomb.data
data/atomic78/topbase_h1_phot_extrap.py
data/atomic78/topbase_he1_phot_extrap.py
data/atomic78/topbase_he2_phot_extrap.py
data/atomic78/topbase_cno_phot_extrap.py
data/atomic78/topbase_fe_phot_extrap.py
data/atomic78/photo_vfky_tabulated.data
data/atomic78/coll.data
# Next is dielectronic recombination data from chianti.

data/atomic78/chianti_dr.dat
# Next is badnell style total radiative recombinaion rate

data/atomic78/chianti_rr.dat
# Next is badnell style ground state radiative recombinaion rate

data/atomic78/Badnell_GS_RR.txt
# Necxt if gaunt factor data from sutherland (1997)

data/atomic78/gffint.dat
# Next is direct ionization from dere

data/atomic78/di_dere.dat

I believe this is happening because of the line 

data/atomic78/topbase_levels_fe.py

in the standard78 file.  If I remove this, the problem goes away, and in particular the line associated with Fe XXVI becomes

ion 176 26 26   14    18

So I believe there is bay be a basic problem with standard78 for Fe.  But get_atomicdata should also had enough self consistency checks to have identified this as a problem.

**Comment by Higginbottom** [comment]
I've worked out why there seem to be more levels than lines.

In the first instance, with the topbase_levels_fe.py file in place, get_atomic data reads in the levels from this file, and ignores the levels contained in levels_ver_2.py. There are no topbase levels for iron26 other than the ground state. However, the lines are read in just fine, they are not linked to any levels, but I think that resonance lines will be computed for them in lines.c. The topbase levels are intended to be used for macro atom work as far as I can see. If you try to read in a file containing LineMacro data, it requires matching levels from a topbase file.

Delete the topbase_levels_fe.py and get_atomic data will instead read its levels in from levels_ver_2.py - where all the levels you expect are in place to link up all the lines in the lines_linked_ver_2.py and they are correctly linked to the levels in question. 

Is this a bug? Not sure. I think that the line code should work just fine, because it doesn't use the level populations anyway - it computes the level population on the fly!

**Comment by kslong** [comment]
I  agree you are right about this.  But it must also imply that we have no l-shell lines, which would require a macro atom approach.   These are going to be needed for partial covering.

**Comment by jhmatthews** [comment]
Files of the format topbase_levels_fe.py are not used for macro-atom levels- those will generally have format LevTop and match with normal lines. Macro-atom levels are of the form LevMacro and should match exactly to a LineMacro entry in a separate file. The macro-atom levels do normally have Topbase as their ultimate source though.

**Comment by kslong** [comment]
For py83, I have addressed the issue of making get_atomic_data standalone, by moving a21 and several associated routines back into get_atomic_data.  It is not clear there are any other problems in the end.  I have also switched the default to standard80 rather than standard78.  There is a related issue #451, but I am going to close this one.
