### ISSUE TITLE
Non general power law problem

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#17]
**Problem:**  In creating models for AGN over the last few years, we have added a power law spectrum to Python but we have done this is such a way, that it is difficult to add a generic power lwaw to any other spectra type, e. g. a star.  This is and will continue to be confusing. An example of where this is a problem is to create fast ways to test new banding structures.  

We ought to be able to define a power law say for a star (some systems do have them) with same machinery as for an AGN.  We do need ways to set up defaults for an AGN that are different, than say for a star, but these should be converted into a generic values that don't have anything to do with an AGN.

(Note, that one could argue that a similar problem exists for bl, which implicitly assumes some kind of blackbod is involved.

**Discussion:**
The power law spectrum is initiated in agn_init 

```
agn_init (geo.r_agn, geo.lum_agn, geo.alpha_agn, f1, f2, ioniz_or_final,
                &geo.f_agn);
```

and the photons are generated in 

```
photo_gen_agn (p, geo.r_agn, geo.alpha_agn, weight, f1, f2,
                           geo.agn_spectype, iphot_start, nphot);
```

There are two obvious approaches.
- Use the current routines and add a power law component by defining the variabibles properly for simple stellar system
  - \+ Probably holds least risk for current agn models
  - \- Muddles terminology
- Rename the existing routines to something like photon_gen_pow and rewrite the inputs so it's clearer what is intended.  For example, one could decide that a power law was just a choice for a type of boundary layer
  - \+ Once complete, would likely separate the question of a type of photon source from a particular type of object.  Makes it easier to add models
  - \-  More extensive changes are always risky.
  - \- Requires more testing

**Proposed approach**

The simplest thing to do is probably to go with option 1, and document the results as clearly as possible

**Comment by kslong** [comment]
We will close this.  It's part of a general problem about being able to ask for any SED for any radiation source.
