### ISSUE TITLE
Log spectrum

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#170]
Trying to compute X-ray spectra over a wide range of frequencies, in order to see compton scattering has led me to think that we should be able to generate logarithmically binned spectra in the spectral cycle as well as the ionization cycle. This is a simple process, just requiring log bins to be implemented in extract.c

I also note that the linear and log tot_spec spectra are not comparable, since neither is scaled by the width of the frequency bins. I propose scaling these two spectra in this way, so the input spectra are specific luminosity.

I have already coded and tested this, I'll put it into the dev branch and close this issue after our Friday telecon - just in case anyone doesn't like it!

N

**Comment by jhmatthews** [comment]
See also #149 - which I never got around to doing.

**Comment by jhmatthews** [comment]
@Higginbottom - has this been coded?

**Comment by jhmatthews** [comment]
This was closed by #213
