### ISSUE TITLE
Need for shell_wind?

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#172]
Shell_wind is a diagnostic mode of the current version of Python.  It is very closely related to the stellar_wind model and in setup, calls many of the same routines, with some parameters hardwired.  It ignores some of the parameters in the .pf and replaces them with hardwired values.  

The stated reason having this routine was that with the standard stellar model did not allow one to start the wind anywhere except at the surface of the star (which was not what we want for the AGN, where we would like to investigate the shell far from the origin.

However, the current version of the stellar wind model explicitly allows one to set the minimum radius for the wind.  

Nick, could you please investigate whether this mode is still needed or whether we cannot do the same thing with appropriate parameters for the stellar wind model.  While I have this working with domains, I would prefer to remove it if it does not serve an important purpose that cannot be carried out with the stellar wind model (both for documentation and maintenance reasons).

**Comment by jhmatthews** [comment]
I think this is broadly correct, and I checked you can make a thin shell using the stellar wind mode- however there are a bunch of diagnostic things we use the thin shell mode for. I'd suggest mode 9 is changed to be called 'diagnostic shell' or something, and uses the stellar wind machinery but allows the user to print/save additional diagnostic aspects so we can still run our scripts easily. General philosophy being that 9 is the ideal mode for ionization tests and so on.

**Comment by kslong** [comment]
@Higginbottom  argued that we do need this model, and as this is the consensus we will need this model.  I have added a reference to this issue in the doxygen comments for shell wind, should we want to reopen this issue, but am closing the issue.
