### ISSUE TITLE
Need for proga.c  (and py_ray and balance)

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#173]
As far as I can tell we are not using proga.c even though it is in the repository.  Should it be deleted?  In addition, do we want to maintain py_ray.c or can it be deleted.  it is in our Makefile, but I doubt anyone has been maintaining it, and I suspect no one has used it in a long time.  Balance is another program that we should decide whether we need or not.

**Comment by jhmatthews** [comment]
I have never used balance or py_ray during my PhD, which seems a reasonable enough reason to get rid!

**Comment by kslong** [comment]
I agree these seem no longer useful so we can remove them.

Sent from my iPad

On Nov 2, 2015, at 10:18 AM, James Matthews <notifications@github.com<mailto:notifications@github.com>> wrote:

I have never used balance or py_ray during my PhD, which seems a reasonable enough reason to get rid!

**Comment by Higginbottom** [comment]
I think the need for balance has largely been superceeded by the thin 
shell test mode, and proga.c is certainly now defunct, all the code is 
(should be) in hydro_import.c

N

**Comment by jhmatthews** [comment]
Closed by f2fd61d1012bc90af5b46a9d0ffbf1ddc248de48
