### ISSUE TITLE
Reordering of inputs?

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#174]
Presently, our inputs are ordered so that we define the wind type as the first parameter in the .pf file

Wind_type(0=SV,1=Sphere,2=Previous,3=Hydro,4=Corona,5=knigge,6=homologous,7=yso,8=elvis,9=shell,10=None)

A lot later on later on, we ask

System_type(0=star,1=binary,2=agn)                    0
disk.type(0=no.disk,1=standard.flat.disk,2=vertically.extended.disk)                    1
disk.atmosphere(0=no,1=yes)          

In light of the wide variety of systems, we are now modeling, I propose to change this a good bit, namely to ask the system type at the beginning, and to use this to set up some of the defaults for answers to future questions.  I am thinking the System types might be

star, cv, yso, agn, bh-binary, SN, and Previous  (since we need to know very early on if we want to use an existing model to start.  

Wind_types would I think be mostly what we have (omitting Previous).  Wind_types directly map to a domain in all cases.  disk_atmosphere would also be it's own domain of course.  I'd like to get all of the questions asked that define how many domains we actually are going to need quite early.

Thoughts?

**Comment by kslong** [comment]
Note that an advantage, I think of this approach is that once we decide on the system type and thw wind_type, we can set up all of the parameters for a baseline model, e.g the AGN model we prefer as our benchmark model with an SV wind.

**Comment by kslong** [comment]
This is part of the general question about how to set up the inputs and how to initialize variables in python.  Part of the idea of having the first line of the inputs be agn, cv, etc. was that this would ease some of the initialization issues.

**Comment by jhmatthews** [comment]
I believe this is done and further issues are documented in e.g. #222
