### ISSUE TITLE
zlog_scale, etc.

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#175]
When we set up the grid, we define a quantity zlog_scale which effectively determines how concentrated a logarithmic grid is toward low z.  Specifically we use zlog_scale to define dlogz, given by

dlogz=log10 (rmax/xlong_scale)/mdim
so tha
w[n].z=zlog_scale_10__(dlogz_m)

This assures that the maximum z is rmax as desired.  Similar quantities are defined in the x direction.  

In the x direction, there is usually a natural (though not completely) consistent way in which dlogx is defined:
elvis.c:141:      zdom[ndom].xlog_scale = zdom[ndom].sv_rmin;
homologous.c:82:      one_dom->xlog_scale = 0.3 \* geo.rstar;
hydro_import.c:154:      zdom[ndom].xlog_scale = 0.3 \* geo.rstar;
knigge.c:170:      zdom[ndom].xlog_scale = geo.rstar;
proga.c:150:      geo.xlog_scale = 0.3 \* geo.rstar;
shell_wind.c:138:      zdom[ndom].xlog_scale = 0.3 \* geo.rstar;
stellar_wind.c:98:      zdom[ndom].xlog_scale = 0.3 \* geo.rstar;
sv.c:94:      zdom[ndom].xlog_scale = zdom[ndom].sv_rmin;
sv.c:98:      if (geo.compton_torus && geo.compton_torus_rmin < zdom[ndom].xlog_scale)
sv.c:100:          zdom[ndom].xlog_scale = zdom[ndom].compton_torus_rmin;
yso.c:112:      zdom[ndom].xlog_scale = geo.rstar;

(Note it is not clear why hydro_import needs this defined at all)

In the z direction it is less obvious what you should do, or at least we have not though about it very much.  

elvis.c:142:      zdom[ndom].zlog_scale = 1e15; /\* Big number - for AGN */
homologous.c:83:      one_dom->zlog_scale = 0.3 \* geo.rstar;
hydro_import.c:155:      zdom[ndom].zlog_scale = 0.3 \* geo.rstar;
knigge.c:171:      zdom[ndom].zlog_scale = geo.rstar;
proga.c:151:      geo.zlog_scale = 0.3 \* geo.rstar;
shell_wind.c:139:      zdom[ndom].zlog_scale = 0.3 \* geo.rstar;
stellar_wind.c:99:      zdom[ndom].zlog_scale = 0.3 \* geo.rstar;
sv.c:110:     zdom[ndom].zlog_scale = geo.rstar;
yso.c:113:      zdom[ndom].zlog_scale = 1e7;

Evidently, the hardwired choices are not really very good, in the sense that they imply you could never use for example the elvis model for anything but an AGN.   The hardwired values should be classified as bugs

We should really think why all of these are what they are.  The answers depend somewhat on whether we want to emphasize the region close to the disk or the region where the wind accelerates. 

I plan to set the values in yso.c and elvis.c to something that is not hardwired.

sv_rmin for Elvis (if its a high mass object, and geo.rstar if bigger than say 10*_7 cm)
0.01_geo.rstar for a yso.

**Comment by kslong** [comment]
Note - I find evidence that the number 1e7 for yso, had at one time been the number we used for other winds, e.g sv ... and this was changed when we started thinking about agn.

**Comment by jhmatthews** [comment]
I've added a routine in commit https://github.com/agnwinds/python/commit/5261b4c884bdc840ec0912e7a68dc344da819cae in dev that partially addresses the concern by looping over the entire plasma pointer and checking for large changes. At the moment, it only does this by checking two quantities:
- dv/ds in the x direction
- dv/ds in the z direction
- nh \* sigma_T \* cell_size

It then counts the amount of times these are large (tau > 1 or delta_v > 1000 km/s) and reports to the user, and suggests that if they are large the user may want to change the scale length or grid resolution. 

This could obviously be improved, first by incorporating more checks, and maybe longer term having a smarter way of setting zlog_scale. However, it's rough to know what the real metrics are. It could also be called before each cycle and check for large changes in e.g. IP or temperature.

Let me know if any suggestions, or feel free to add to the routine.

**Comment by kslong** [comment]
As there have been no specific suggestions for how to proceed on this, and as @jhmatthews  has added checks that warn when there are problems, I am going to close this.
