### ISSUE TITLE
Treatment of photons when hit disk

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#180]
Python, nominally, has 3 ways of treating a photon if it hits the disk.  It can be lost, It can be reflected, it can be absorbed and the temperature of the disk modified to account for the energy absorbed.  As far as I can, the last of these options is not working.  All options need to be checked.

**Comment by kslong** [comment]
It looks as if geo.disk_illum is not set in  get_disk_parameters, which is part of setup.c.   There are comments that one cannot immediately set disk_illum because other items (e.g velocities in the KWD model have not been set yet.  get_disk_parmaters returns disk_illum, but python main does not "receive" or use them.  It is possible this got messed up when this routine was created in an attempt to simplify the main routine.

Note - while we do not recalculate the grid on restarts, we do reconstruct this disk and this is a restart issue if our approach has modified the disk temperature.  It seems likely that the disk structure should be saved.

Note that This whole routine is quite confused, with some bits commented out by Nick because he says they caused problems on restart.  But it is clear the never figured out what the underllying problem.  This is a good example of a band-aid, that is now harder to figure out than it would have been at the time.  Restarts, should not need to get material from the command line.

**Comment by kslong** [comment]
These are the nominal meanings of disk_illum as given in python.h

  int disk_illum;               /*Treatment of effects of illumination on the disk. 
                                   0--> Disk simply absorbs the radiation and it is lost
                                   1--> Disk reradiates the radiation immediately via electron scattering
                                   2--> Disk radiation is absorbed and changes the temperature of the disk for
                                   future ionization cycles
                                   3--> Disk illumination is treated in terms of an analytic approximation
                                   04Aug ksl -- this parameter added for Python52

**Comment by kslong** [comment]
This is now at least partially fixed.  In particular, geo.disk_illum should be properly passed to the downstream routines.  

Some issues remain however:
1.  For restarts, it the program will probably fail becasue the disk structures are not saved and read back
2.  One needs to check that the program works properly with multiple threads.  It is not obvious to me what is done with the structures for disk.

**Comment by kslong** [comment]
Note - It is not obvious that we need a structure qdisk and disk.  By adding one more T to disk, which is the effective temperature after accounting for the radiation that has hit the disk we might be able to eliminate qdisk.  We have to be careful though with the way that the annuli of the disk are established or reestablished because this redefines the positions of the annuli.

**Comment by kslong** [comment]
I regard this as a high priority to understand and if necessary fix, especially as we become more interested in activity occurring near the disk surface.   The first thing that needs to be done though is to create examples of each case and determine what is actually happening.

**Comment by kslong** [comment]
geo.disk_illum is set to 0 in the spectral cycles.  This could be a problem on restarts if we save the wind structure
As written the reflection option simply allows photons to continue coursing through the grid. They don't seem to be reflected or scattered. This is clearly a problem for vertically extended disks.  Note that inside the program there are places where we say the photons are scattered at the surface by electron scattering but this is not what is actually happening.

**Comment by kslong** [comment]
At this point,  there are 3 problems to investigate/correct
- Does the routine work properly with multiple processors?  pythons does run with mulitple processors under th absorb and reradiate option, but I verified that it does not produce the correct qdisk file.   This is because, qdisk which is where all of the data is not stored is not transferred to and from the various processors.   For other arrays, this is done in para_update.  This needs to be fixed, but I should resolve the question below of whether we need both disk and qdisk
- Does the routine work properly on restarts?  I do see that qdisk is saved by windsave so that is good.  I have not yet really checked this
- Does the program handle scattering/reflection correctly?  Right now when this option is implemented then the photon just goes through the disk. This effectively is reflection as long as we have updown symmetry which we do and a zero thickness disk.  Some of the commentary int he code suggested we expected it to scatter via electron scattering
- Does the problem handle vertically extended disks correctly?  The answer to this is no at least for scattering and reflection as the program simply allows a photon to continue going in the direction is twas going.

Do we need both disk and qdisk????  I think the answer is no, but I should sort this out before asking James or Nick to help with parallelizing.

**Comment by kslong** [comment]
In python.c there is a clear explanation for why both qdisk and disk are needed.  The reason is that the structure disks get reinitialized every time the wavebands are changed but qdisk boundaries do not and should not change.  

@jhmatthews - Currently the structure qdisk, which records information about photons hitting the disk, is not be handled properly in multiprocessor mode.  What should happen is that the data from the different processes is gathered, up at the same time at the end of each ionzation cycle, as the PlasmPtr info is, and combined.   Then it should sent back.   I assume all of this happens in para_update but I am hesitant to try and to this myself.  Could you do this?

**Comment by jhmatthews** [comment]
So, @kslong -- the merged pull request #217 fixes the parallel issue. I believe your other questions above are still outstanding and so I'm keeping this issue open til they are addressed.

**Comment by kslong** [comment]
All of the issues associated with this are believed resolved.  In particular see #160 for a discussion of the vertically extended disk.
