### ISSUE TITLE
Segfault at the end of a run

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#190]
While carrying out sets of python runs, hydrogen only, varying the temperature of thin shells I have been getting accessional segmentation faults right at the end of the simulation. The output to screen when this happens is:

 Completed wind creation.  The elapsed TIME was 8.563893

Error summary: End of program, Thread 0 only
Recurrences --  Description
        1 -- wind2d.c: Don't know how to check wind mdot for this coordtype %d
Run py_error.py for full error report.
[nicholass-mbp:06386] **\* Process received signal ***
[nicholass-mbp:06386] Signal: Segmentation fault: 11 (11)
[nicholass-mbp:06386] Signal code: Address not mapped (1)
[nicholass-mbp:06386] Failing at address: 0x30
[nicholass-mbp:06386] [ 0] 0   libsystem_platform.dylib            0x00007fff8b4cef1a _sigtramp + 26
[nicholass-mbp:06386] [ 1] 0   ???                                 0x0000000000000000 0x0 + 0
[nicholass-mbp:06386] [ 2] 0   libopen-pal.6.dylib                 0x0000000142af1113 opal_hash_table_destruct + 19
[nicholass-mbp:06386] [ 3] 0   libopen-pal.6.dylib                 0x0000000142b17e85 mca_base_var_finalize + 709
[nicholass-mbp:06386] [ 4] 0   libopen-pal.6.dylib                 0x0000000142b15cd3 mca_base_param_finalize + 35
[nicholass-mbp:06386] [ 5] 0   libopen-pal.6.dylib                 0x0000000142af6008 opal_finalize_util + 72
[nicholass-mbp:06386] [ 6] 0   libmpi.1.dylib                      0x00000001427793e4 ompi_mpi_finalize + 2004
[nicholass-mbp:06386] [ 7] 0   py79d_dev                           0x000000010e413b32 main + 7554
[nicholass-mbp:06386] [ 8] 0   libdyld.dylib                       0x00007fff943915c9 start + 1
[nicholass-mbp:06386] [ 9] 0   ???                                 0x0000000000000003 0x0 + 3
[nicholass-mbp:06386] **\* End of error message ***

On my iMac, on one occasion only I saw this error, which may be linked:

Assertion failed in file src/mpi/comm/commutil at line 257 default_collops[i]->ref_count >=1

Looking at python.c, the next thing the code does, in mpi mode, after writing the error summary is a call to MPI_finalize(), which is indeed mentioned in the segfault dump...

**Comment by smangham** [comment]
Here's a run I've got that hits the same error, input and output files. This requires my domain2 branch to run, though. I'll just do the MPI_Finalise tweak and see what happens.
[lamp_post_m_dump.txt](https://github.com/agnwinds/python/files/82976/lamp_post_m_dump.txt)

Apparently github won't let me attach the pf, so here's the pf.txt.
[lamp_post_m_dump.pf.txt](https://github.com/agnwinds/python/files/82977/lamp_post_m_dump.pf.txt)

**Comment by smangham** [comment]
May have found the problem- MPI_Init is called in **python.c**, but MPI_Finalize is called in **run.c**. Moving MPI_Finalize to **python.c** stopped the crash in the file I was testing with (that crashed on MPI_Finalize 100% of the time). I'm just testing others to make sure it hasn't _introduced_ any crashes

**Comment by jhmatthews** [comment]
Did we check this was this case guys / fix it in dev?

**Comment by smangham** [comment]
I no longer get this problem, and the fix should be included in my reverb push to domain2 and thus dev. Can @Higginbottom confirm he's not getting it now either?

**Comment by jhmatthews** [comment]
Closing this until someone gets the error again!
