### ISSUE TITLE
q_recomb nan when using Dere data

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#197]
When you use direct ionization it's possible to get a lot of the following errors:

``` C
q_recomb is nan for ion 175 at temperature 7.6500e+04, setting to zero
```

It's easy to see why this happens. The expression for calculating q_recomb (collisional three body recomb coefficient) from q)ioniz is (by considering LTE and Saha):

```
q_recomb = constants * T_e^(-3/2) * q_ioniz * exp (h nu / kT)
```

When temperatures are moderately low but the ionization threshold is quite high then hnu / kT can easily be 1000, which gives you and inf for the exponential term. However, in that limit q_ioniz is normally 0. 0*inf = nan!

Doesn't actually affect our calculations at all, as we set it to zero, but throwing lots of errors can cause runs to fall over, and also it's not really an error per se- it's expected in those regimes which are entirely physical.

I'm going to propose we pick some limit for h nu / kT (100?), and beyond that limit, we set collisional ionization AND recombination to zero so we are nice and consistent in cold plasmas relative to the threshold they shouldn't matter anyway. They are barely ever important anyway so we could probably turn it off -- but this is neater and keeps physics in.

**Comment by kslong** [comment]
Hmm … doesn’t q_recomb become large in this case, since the exponential will beat a power law every  time.   Presumably you are counting on the electron density being “more zero”, but one might wonder why we don’t set a maximum rather than a minimum value.  Knox

**Comment by jhmatthews** [comment]
I don't think so Knox, because it's proportional to q_ioniz \* exp (h nu / kT). In our case q_ioniz comes from data, but is vanishingly small in these regimes with the same strength as the exponential, I think. 

Alternative way to show this-- Mihalas gives an approximation for the collisional ionization rate -- q_ioniz -- which is proportional to exp(-h nu / kT), emphasis on the minus sign. This approximation is only really valid for low Z ions, but I think it shows you how you expect it to scale and that it should do so as quickly as the exponential term in our expression above..

I think radiative recombination will always be dominating in this regime anyway.

**Comment by kslong** [comment]
I concede. You are right!

**Comment by jhmatthews** [comment]
I've verified using an approximation for the form of direct ionization and recombination that below hnu / kT of a few hundred the numerics of this calculation should be well behaved. I've therefore added a fix in direct_ion.c which whenever hnu / kT>ALPHABIG_DIRECT_ION return 0 for any collisional coefficient, where ALPHABIG_DIRECT_ION is defined as 100. Pushed to dev so closing this issue :door: :smile:
