### ISSUE TITLE
Error in SHULL radiative recombination rate calculation

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#199]
Whilst trying to understand why python does not agree with cloudy for iron ionization states in the hydro models, I have discovered a small mistake in recomb.c

This is the code to compute the radiative recombination rate coefficient from SHULL type data. 

  else if (total_rr[ion[nion].nxtotalrr].type == RRTYPE_SHULL)
    {
      rate =
    total_rr[ion[nion].nxtotalrr].params[0] \* pow ((T / 1.0e4),
                               total_rr[ion
                                [nion].
                                nxtotalrr].
                               params[1]);

The mistake is that the T/1e4 term should be raised to the negative power of params[1]. So it should read

  else if (total_rr[ion[nion].nxtotalrr].type == RRTYPE_SHULL)
    {
      rate =
    total_rr[ion[nion].nxtotalrr].params[0] \* pow ((T / 1.0e4),-1.0*
                               total_rr[ion
                                [nion].
                                nxtotalrr].
                               params[1]);

Ooooops!!!!!

It seems to make depressingly little difference to anything - but the radiative recombination data output from cloudy now agrees with python for iron (like all the other elements).

It should be noted that _most_ of the ions we are normally interested in, including iron8 and above use Badnell type RR data, and that is done correctly.

**Comment by jhmatthews** [comment]
Fixed by #202
