### ISSUE TITLE
Advance diagnostics and the .pf file

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#201]
Advanced diagnostics, e.g those questions posed, when the -d flag is indicated, should somehow be independent of the main .pf file (or come at the end).  Presently, one has to re-do the .pf file when one invokes this flag, and this is not what one wants.

**Comment by jhmatthews** [comment]
Just while I remember. I think the idea here from a recent telecon was to have the normal pf file, and then when you run with the -d (detailed/advanced/diagnostic) flag, the program would then look for an extra file called something like `root.extras`

This file might be of the following format if you wanted to ask for a load of diagnostic features, and would hopefully not depend on order.

```
write_atomicdata                    1
ispymode(1=yes)                             1
keep_ioncycle_windsaves(1=yes)      1
track_resonant_scatters(1=yes)             1
print_windrad_summary(1=yes)        1
print_dvds_info(1=yes)              1
save_extract_photons(1=yes)         1
```

**Comment by kslong** [comment]
What makes this difficult right now is that our rdpar.c routine assume we have a single file for inputs, and then we record the results for future use.   It is not obvious how to to intersperse reads from two separate files, and keep track of it all.  We could make a duplicate rdpar.c but that seems silly.  

Possibilities that did occur to me would be to add and optional variable to all of the routines that says to read from a different file, or alternatively to require the extra commands to start with something like

diag.write_atomic_data 

which we could trap, and get from another file.  Alternatively I guess we could just trap a set of keywords and direct them from another file.

**Comment by kslong** [comment]
This should be dealt with in the context of a general discussion about IO that we need to have.

**Comment by kslong** [comment]
@smangham noted that there are certain variables that almost never change, and that it seems unreasonable to have to enter them every time.  His example was adiabatic heating. Solutions to this problem are closely related to the question of advanced commands, which are not required except in unusual circumstances.  If one did have a defaults.pf file, which was separate from the input variables. These could be put there as well.

**Comment by jhmatthews** [comment]
Right, prompted by extra diagnostics failing tests on travis, I've had a bit of a look at this and rewritten how I think it should work.

See Pull Request #231 for details.

Please try out and document problems here!

**Outstanding issues:**
* I haven't done anything regarding deprecated modes
* There are some options - for example "select specific numbers of scatters" - that don't really work with this method. At the moment these are broken. Suggestions welcomed.
* there is some code duplication in rdpar which isn't ideal but I decided was a necessary evil if I wasn't to conduct major surgery.
