### ISSUE TITLE
Using Macro Atom Data Sets (h4, h10, h20) in Sobolev escape probability Line_transfer_mode lets Python segfault

### ISSUE THREAD

**Issue by unoebauer** [sirocco-rt/sirocco#206]
Hi,

while using Python on some simple homologously expanding hydrogen atmosphere simulations (ultimately intended for comparisons with Tardis), I stumbled upon the following issue:
### General problem

When using one of the pure hydrogen atomic data sets provided in the data repository, such as h4, h10 or h20, with any line transfer mode that does not include Macro Atoms, Python immediately segfaults in the `wind_rad_init()` routine (in `wind_updates2d.c`). From the comment in any of the atomic data master files (e.g. h10)

```
#This is a standard atomic data set for a 10 level hydrogen model
#that can be treated with or without the full macro atom formalism.
```

I take it that this mode of operation should be in principle possible.
### Details

After some debugging, I think the reason for this first segfault is the following:
- since I selected Line_transfer 3, `geo.rt_mode` is set to 1 (i.e. no macro atom) in `setup.c`
- consequently, `calloc_macro` is not called and `macromain` is not properly allocated
- in `get_atomicdata.c`, however, Macro Atom levels are identified and nlevels_macro > 1 set
- this then leads to the segmentation fault in `wind_rad_init`, since 

``` c
if (nlevels_macro > 1) 
    macromain[n].kpkt_rates_known = -1;
```

To check whether this is the only problem, I've forced nlevels_macro to be 0. With this hack, the first ionization cycle almost completes. At the end of it, another segfault occurs, because now Macro Atom bound-free heating rates are computed (in ionization.c, line 658)

``` c
xxxplasma->heat_photo_macro = macro_bf_heating (xxxplasma, t);
```

which also fails. I didn't pursue this issue beyond that point.

It looks to me as if this mode of operation was not anticipated or is not supported (in which case, the comment in the atomic data master files are misleading).
### Code references
- Python version 80
- atomic data repository githash: b64cbfcf86bef8528ce79b8e9710b0747badcd69

Upon request, I can also post my `.pf` file.

**Comment by jhmatthews** [comment]
Thanks for flagging this @unoebauer 

It seems there are a few issues here. 
- Firstly, I agree we clearly haven't really anticipated this mode of use. I don't know if there's a real need to support this mode. All you really need is an option to turn off the full macro-atom treatment and treat everything as a "simple-ion" which you can do either with a line transfer switch or by providing no matom atomic data. Regardless, it's clear that the code should deal with a user requesting what you've requested by either running or quitting with an informative error message. 
- Second, The documentation for this is poor to non-existent and should definitely be improved. I feel a review of the line transfer modes we really want in the code and a test of how they all work with different atomic data would be useful. e.g. how does a user use standard line transfer, indivisible packet line transfer with no full matoms, and full matom mode?
- There also seems to be a general issue whereby we are sometimes using nlevels_macro and sometimes geo.rt_mode to check for macro-atoms. 

Is this holding up any of your tests at the moment?

**Comment by unoebauer** [comment]
Hi @jhmatthews and thanks for the details. Currently, this issue is not really holding up my tests. I should be able to get by with hacking the source code - just wanted to flag this issue.

**Comment by kslong** [comment]
This is similar to #316
