### ISSUE TITLE
Memory problems with large photon numbers

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#209]
**Description:** In some of my AGN runs I'd been requesting as many as 40,000,000 photons. Being as the size of one entry in the photon structure is around 128 bytes, this can mean that the total size of the overall photon structure can approach 5+ GB. I've checked that enums don't increase the memory load too much.

This can cause runs to fail on certain machines where you request more memory than the server in question has available.

@smangham this may be particular bad for you if running in reverb.

**Proposed solution:** The user should be warned if the photon structure exceeds 1GB in size. Perhaps a maximum size of 4GB or so should be hardwired as well. Thoughts welcome.

It's worth noting that the reason for running with so many photons was because of noisy MC estimators in macro-atoms. Longer term this is therefore linked to improving that problem, see #196. Also relevant to variance reduction discussion that we've had previously.

**Comment by jhmatthews** [comment]
Added a few lines to at least report this, see commit a997c55

``` C
  p = (PhotPtr) calloc (sizeof (p_dummy), NPHOT);

  if (p == NULL)
    {
      Error
    ("There is a problem in allocating memory for the photon structure\n");
      exit (0);
    }
  else 
    {
      /* JM 1605 -- large photon numbers can cause problems / runs to crash. Report to use (see #209) */
      Log("Allocated %10d bytes for each of %5d elements of photon structure totaling %10.1f Mb \n",
           sizeof (p_dummy), NPHOT, 1.e-6 * NPHOT * sizeof (p_dummy));
      if ( (NPHOT * sizeof (p_dummy)) > 1e9)
        Error("Over 1 GIGABYTE of photon structure allocated. Could cause serious problems.\n");
    }
```

**Comment by kslong** [comment]
Python was a while ago configure to handle this situation.  If you asked for too many photons it broke things up into subcycles.   It this is really a problem, we ought to rethink our removal of subcycles.  Knox

**Comment by jhmatthews** [comment]
My personal take is that this is a problem, unless we substantially improve how we deal with low photon numbers. For example, lowering photon numbers from 4e7 to 1e7 in a model caused the model to get some errors in "low photon numbers in cell" and occasionally singular rate matrixes. Whilst the most intelligent solution clearly isn't just to whack up photon numbers, it currently has to be done in certain cases. Again, see #196

**Comment by jhmatthews** [comment]
I'm being a bit silly here. I just realised is that whenever you request this many photons you tend to be running with a large number of cores, and when that happens the photon structure on each core is reduced in size by the ncores. This means this isn't really as much of a problem as I first thought.

**Comment by kslong** [comment]
Right, but it would still not be difficult to re-implement sub-cycles; you just need to look back to old versions of the code to see how this was done.  I think these can go inside the collection of results from the various cores, but one would need to check on that.  Go back to something like Python58 to see how this worked.

**Comment by kslong** [comment]
We decided this was unlikely to be a problem practically.  It does have a solution (subcycles).  We will close for now, and reopen if it reappears.
