### ISSUE TITLE
Filling factor should be specified on a domain by domain basis

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#212]
Currently the filling factor is a variable defined as geo.fill, which assigns it to all domains, e.g. the disk wind and a corona.  This I argue is not what we want.  The filling factor should be assigned on a domain by domain basis.  (This problem is linked a bit to the fact that a variable geo.wind_type still exists and is used a few places in python.  geo.wind_type also needs to be removed and replaced with zdom[ndom].wind_type).

**Comment by kslong** [comment]
I may have conflated two issues here.  In looking at how to eliminate geo.wind_type, I've find some complications associated with shell model.  The global DFUDGE for photons flying outside wind cells is set differently for this, and there are special outputs for the (diagnotic) shell model that basically seem to assume that when a shell model is run, that there is only one domain and it is the shell.

**Comment by kslong** [comment]
Except for the question of the global DFUDGE factor above geo.wind_type is no longer needed in python (dev)

**Comment by jhmatthews** [comment]
So @kslong -- it is easy to make the code use domains for filling factor rather than geo, as in all the places where it's used the domain number or plasma cell is known. The only problem is about setup.

In python.c we set up the wind and atmosphere by calling get_wind_params():

``` C
      /* Describe the wind. This routine reads in geo.rmax and geo.twind
         and then gets params by calling e.g. get_sv_wind_params() */

      get_wind_params (geo.wind_domain_number);

      if (geo.atmos_domain_number >= 0) {
          get_wind_params(geo.atmos_domain_number);
      }
```

But, in get_wind_params we set stuff which seems specific to winds, e.g. there's no get_atmosphere_params() and we ask questions about the wind to the user.

``` C
  /* XXX - This should be part of the individual get_wind_parameters, not here */

  rddoub ("wind.radmax(cm)", &zdom[ndom].rmax);
  rddoub ("wind.t.init", &geo.twind);
...
  rddoub ("wind.filling_factor(1=smooth,<1=clumped)", &zdom[ndom].fill);
```

This is linked to general questions about how to deal with inputs for multiple domains, but we need to decide what to do before this can be implemented, unless we want to put in something like

``` C
  if (ndom == geo.wind_domain_number)
    rddoub ("wind.filling_factor(1=smooth,<1=clumped)", &zdom[ndom].fill);
  else if (ndom == geo.atmos_domain_number)
    rddoub ("atmos.filling_factor(1=smooth,<1=clumped)", &zdom[ndom].fill);
```

Thoughts?

**Comment by kslong** [comment]
For now, I think the simplest most general thing to do would be to replace the line

 rddoub ("wind.filling_factor(1=smooth,<1=clumped)", &geo.fill);

With something like

  rddoub ("filling_factor(1=smooth,<1=clumped)", &zdom[ndom].fill);

That way we are assured that any domain can be assigned a filling factor.

**Comment by jhmatthews** [comment]
This is done and is producing identical output files for a clumpy AGN model. Merged into dev as of latest commit: https://github.com/agnwinds/python/commit/52264fd0216b87c1d348a1041ff4ac2fe9afd87f

Note that currently it reads in a filling factor per domain in get_wind_params():

``` C
int
get_wind_params (ndom)
     int ndom;
{
...
  /* Get the filling factor of the wind */
  // XXX  This may  not in the right place to set the filling factor.  

  zdom[ndom].fill = 1.;

  /* JM 1606 -- the filling factor is now specified on a domain by domain basis. See #212
     XXX allows any domain to be allowed a filling factor but this should be modified when
     we know what we are doing with inputs for multiple domains. Could create confusion */

  rddoub ("filling_factor(1=smooth,<1=clumped)", &zdom[ndom].fill);
...
```

but the question about how to organise this is linked to general concerns about input files and how to deal with multiple domains. This specific issue is now closed, however.

**Comment by kslong** [comment]
That’s great, James.
