### ISSUE TITLE
Crash in pdf_check when there is a cold cell in a hydro model

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#216]
I've started to have crashes in hydro simulations when one cell gets very cold. It occurs when the wind photons are being generated at the start of a new cycle, and we are generating the recombination emissivities.

init_freebound: Creating recombination emissivites between 1.397727e+18 and 4.110507e+18
photon_gen: band 1.40e+18 to 4.11e+18 weight 3.63e+32 nphotons 25000 ndisk      0 nwind    155 nstar      0 npow 24845 
Error: pdf_gen_from_array: all y's were zero or xmin xmax out of range of array x-- returning uniform distribution 0
Error: pdf_check: x problem n 1 x 1397726762721435648.000000 pdf->x[n] 6988633813607178.000000
Error: pdf_check: x problem n 2 x 1397726762721435648.000000 pdf->x[n] 13977267627214356.000000
Error: pdf_check: x problem n 3 x 1397726762721435648.000000 pdf->x[n] 20965901440821532.000000
Error: pdf_check: x problem n 4 x 1397726762721435648.000000 pdf->x[n] 27954535254428712.000000

..... many more lines looking the same for each of the 200 bins of the pdf

Error: pdf_check: x problem n 198 x 1397726762721435648.000000 pdf->x[n] 1383749495094221312.000000
Error: pdf_check: x problem n 199 x 1397726762721435648.000000 pdf->x[n] 1390738128907828480.000000
Error: pdf_check: x values in pdf should be monotonic
Error: pdf_check 10 0 0 1 0
Error: pdf_gen_from_array: error 10 on pdf_check
Error: one_fb after error: f1 1.39773e+18 f2 4.11051e+18 te 1048.25 ne 2.99485e+16 nh 2.47773e+16 vol 4.82601e+28
Error: Giving up

Its hard to reproduce, just rerunning the last cycle doesn't generate the error, so there must be an element of randomness here.

I _assume_ it must be to do with trying to generate photons from a cell which is too cold to possibly make photons of this frequency. I'm going to do a little digging, including trying to make a simple run that reproduces it.

**Comment by Higginbottom** [comment]
There is something a little more worrying going on here....

looking at the error, Error: one_fb after error: f1 1.39773e+18 f2 4.11051e+18 te 1048.25 ne 2.99485e+16 nh 2.47773e+16 vol 4.82601e+28

The cell in the wind_save file with vol=4.82601e+28 has t_e=6.25E+06 and n_e=1.81E+12 so I'm confused!!!! It appears that something is getting out of sync!!

**Comment by Higginbottom** [comment]
Well, I can recreate the error, but it is really hard!
If I _force_ the code to generate a wind photon from the very cold cell we see above, and then _force_ it to produce a free-bound photon from that cell, then I can get the same error message. This is to be expected since a cell with 1050K has zero fb luminosity. Since the generation of photons is all random, I guess that if you get just the right random number then you may (given machine accuracy issues) by chance generate this photon and cause the crash. So, it seems that some kind of protection might be in order. If we are asked to generate a photon that cannot be generated, however that happens, rather than crash perhaps we should cycle back and ask the code to try again. 
I'm generating 100 million photons each cycle, and this is cycle 200 odd. So that is a _lot_ of photons.... With this sort of numbers we need to be sure we can cope with even a 1 in 20 billion chance!!
I'm going to carry on digging a little, now I have recreated the error.

**Comment by kslong** [comment]
I’m glad you have located the error, but I doubt it is a round-off error precisely.  It’s more likely I think that there is some place where the logic of the code is not exactly right.  Rather than doing a simple check and eliminating the error.  I think one should actually track it down.  Band-aids are dangerous, as they can hide deeper problems.

**Comment by Higginbottom** [comment]
Yes, I'm sure you are correct.
I've done more digging, and to be honest I'm getting more confused. I've set up a run which starts from the last wind save file. It wants to generate the same number of wind photons as in the full run, but it works just fine, the pdf for FB emission is good and it makes the photons without a problem. Its hard to see why it is going wrong in the full run, and since it takes a day to fall over, running on 400 processors is pretty hard to debug it! Hmmmmmm

**Comment by kslong** [comment]
I agree this looks nasty to debug.  I think what I would try to do is to understand is why you are getting the first error:

Error: pdf_gen_from_array: all y's were zero or xmin xmax out of range of array x-- returning uniform distribution 0

This should be deterministic, not associated with any randomization.  I suspect if the plasma is incredibly cold, what you have is a plasma with no free electrons, and hence no free bound emission.  But if that is the case then you should never be able to get into the routine that tries to generate a free_bound photon.  So you should also look at the routine that chooses what type of wind photon to generate.  

Aside: The segfault problem I solved for #100 this past week involved init_freebound, so I would be sure to merge this in to your version if you have not done so.  I don't think it is related to this though.

**Comment by Higginbottom** [comment]
So the problem appears to be that a freebound photon is being generated from a cell with zero fb emission. As you say, this shouldn't happen, and when I try to reproduce the error it doesn't. In fact the problem doesn't arise because the cell that is generating the error in the big run _does_ have some fb emission when I rerun. If I force fb photons to be created in cells with zero fb, then I can get the error.
SO the question is, it the error in the large run that somehow the fb pdf is being corrupted between the decision to make a photon, and actually making it, or something else.

**Comment by kslong** [comment]
It makes sense to me that if you try to generate a free bound photon in a cell in a given bandpass with no free bound emission in that band pass that you would run into a problem.   So I don’t think the corruption of the pdf  is your real problem.

Your real problem is why you have a cell with fb emission that does not create a proper pdf.

What is the temperature of the cells we are talking about?

**Comment by Higginbottom** [comment]
The cell that seems to cause the crash is 1050K. In my run, the pdf is fine for the band in question and 1050K produces a few fb photons, and the pdf is non zero at that temperature. In principle the same pdf is used to calculate the total fb luminosity for a cell and also to select the frequency of that photon. So, if all the elements were zero for a given band/cell, then no photons would be made and no problem. However, because we recycle the fb space, we actually regenerate the pdf in between the two actions. So this is probably the point. I wonder if, in a multi threaded environment, we can in some way get out of step. Maybe changing the ionization state in a cell between the two actions. I'll try to pick apart the logic...

**Comment by jhmatthews** [comment]
I think this also got fixed by various things in Autumn 2017 - Can you confirm @Higginbottom or at least that we haven't seen this in a while?

**Comment by Higginbottom** [comment]
It has certainly gone away for a range of reasons. Since we don't have a way of making it happen again I agree that it should be closed.
