### ISSUE TITLE
How many types of users?

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#224]
As part of the io redesign #222 we need to clarify how many types of users there are and who gets access to what commands, etc.    We want to handle a wide range of optional inputs (and options within inputs).  These include deprecated options, extra diagnostics, and what I would call beta features, which the "normal user" will not have access to.  Can each of you try to enumerate the user options we try to employ.  My thought is to have two options, but that we allow both to get extra diagnostics. The users would be:

normal user - Sees only supported modes and options.
power user - Sees deprecated and beta features, which would be enabled by a switch, e.g --beta

and the extra diagnostics would be triggered by the -d flag (as presently) and probably --diag.

Is that reasonable @jhmatthews @Higginbottom and @smangham   Note:  I am not thinking of actually checking answers to make sure a normal user does not enter an option for a power user, at least not currently.  Right now I only want to classify users.

**Comment by jhmatthews** [comment]
sounds sensible to me. Also think it's fine that only power users can get extra diagnostics, but I don't think it makes much difference.

**Comment by kslong** [comment]
Implementing this would minimally mean adding an if statement to determine what the user saw in terms of wording, but this is tied up in the more general question of how do we deprecate anything.

**Comment by kslong** [comment]
This seems rather an academic question at this point.  We do have a general plan for how the IO should evolve and so I am closing this issue for now.  If others wish to re-open it, they can.
