### ISSUE TITLE
warning: iteration 1001u invokes undefined behavior, integ_planck[n]

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#225]
Compiler warning I'm getting that sounds like it could be an issue, possible related to #100 which involved loop optimizations. I get the following warning:

```
bb.c:544:21: warning: iteration 1001u invokes undefined behavior [-Waggressive-loop-optimizations]
     integ_planck[n] = qromb (planck_d, 0.0, x, 1e-7);
                     ^
bb.c:540:3: note: containing loop
   for (n = 0; n <= NMAX + 1; n++)
   ^
```

latest dev version, commit 7ae346c338793a318ccb03a53928f2c4e4a33103

Here's my compiler version:

```
$ mpicc --version
gcc-mp-5 (MacPorts gcc5 5.4.0_0) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jhmatthews** [comment]
I think this is a simple bug. integ_planck stores the values of the dimensionless blackbody function which we then sample later (I think):

``` C
double integ_planck[NMAX + 1];
```

This array gets initialised here, where there's a mistake in the loop:

``` C
int
init_integ_planck_d ()
{
  double x;
  double planck_d (), qromb ();
  int n;
  for (n = 0; n <= NMAX + 1; n++)
  {
    x = ALPHAMIN + n * (ALPHAMAX - ALPHAMIN) / NMAX;
// 1e-7 is the fractional accuracy in my modified version of qromb -- ksl
    integ_planck[n] = qromb (planck_d, 0.0, x, 1e-7);
  }

  return (0);
}
```

the iteration should be over `< NMAX+1`, not `<= NMAX+1`.

**Comment by jhmatthews** [comment]
Verified that this fix produces the same log_spec_tot file (ie. is generating the blackbody) in star.pf. Closing.

**Comment by kslong** [comment]
Good job, @jhmatthews  in finding an error that must have been made when you were in elementary school.
