### ISSUE TITLE
Units in spectrum output files

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#226]
Spectral output files should include units to prevent confusion. I think these are the units adopted if one chooses "flambda" units in the parameter file:

* .spec: erg/cm^2/s/A (Flambda)
* .log_spec: erg/cm^2/s/A (Flambda)
* .spec: erg/s/Hz (LNU)
* .log_spec: erg/s/Hz (LNU)

Do we agree, @Higginbottom @kslong ?

**Comment by jhmatthews** [comment]
I therefore propose that the following is added to spectra.c:

```C
// distance to the source in parsecs
#define D_SOURCE 100.0
int
spectrum_summary (filename, mode, nspecmin, nspecmax, select_spectype, renorm, loglin, iwind)
.
.
.
[inside function]
  /* JM 1611 -- let's also give the user some unit information */
  if (select_spectype == 1)     /* flambda */
    {  
      fprint (fptr, "# Units: flambda spectrum (erg/s/cm^-2/A) at %.1f parsecs\n", D_SOURCE);  
    }
  else if (select_spectype == 2)
    {  
      fprint (fptr, "# Units: fnu spectrum (erg/s/cm^-2/Hz) at %.1f parsecs\n", D_SOURCE);  
    }
   else if (select_spectype == 0)
    {  
      fprint (fptr, "# Units: Lnu spectrum (erg/s/Hz) at %.1f parsecs\n", D_SOURCE);  
    }    
.
.
.
}    
```

**Comment by kslong** [comment]
I think this a good idea, but before we settle on exactly how to do this I think we should explore writing our data out in astropy table format, and they have a specific way of handling units
See:

http://docs.astropy.org/en/stable/table/

Astropy tables also have a way of handling keywords more generally as metadata.

http://docs.astropy.org/en/stable/table/access_table.html

The reading of the meta data is not documented very well.

**Comment by jhmatthews** [comment]
We do already adopt astropy table formats in every output (all that really means is that the columns have single string headings without a # in front) in our output files. They can then be read with either 

```python
import astropy
table = astropy.io.ascii.read("root.spec")
```

or using the scripts in py_progs:

```python
import py_read_output as r
table = r.read_spectrum("root.spec")
```

See some documentation here: https://github.com/agnwinds/python/wiki/Useful-python-commands-for-reading-and-processing-outputs and also in py_progs/html_docs

we could do more with units and formats, clearly, if we wanted, for example by having a formatting file attached. However, I'm not sure this is much more useful.

**Comment by kslong** [comment]
I that items starting with # are metadata.  What I am not sure of is whether we actually have the file format of the metadata correct so that we don’t have to write our own parser to interpret it.

**Comment by jhmatthews** [comment]
I think the point is Knox, that the metadata in most of those examples is set by an astropy assignment command, rather than in the file on is reading. The exception is if you provide a formatting file. I would probably be in favour of searching for a units string in the spectrum output file and assigning that to the table object, but I'm open to suggestions. Bottom line is that astropy units functionality is neat, but it would still require a degree of maintenance on our part. We can discuss in telecon.

**Comment by kslong** [comment]
While looking into some problems related to the optically thick case, I went ahead and implemented @jhmatthews suggestion above.  Headers for the spectral files now have the following format

```
# Python Version 81c_dev
# Git commit hash 0aaaf49d70b8978b7750049cf6aa04d00445c05c
# Date  Sun Jun 18 09:02:49 2017
#  

# Units: L_nu spectrum (erg/s/Hz)

# Var    System_type(0=star,1=binary,2=agn,3=previous)  0
# Var    disk.type(0=no.disk,1=standard.flat.disk,2=vertically.extended.disk)   0
...
```

This doesn't address any of the side issues raised regarding meta data, but the fact is that the astropy S/W developers have not developed a robust way to handle this problem, and it's hard to guess what they will ultimately do.

(Note: right now this fix is just on one of my local branches but I will eventually propagate it into dev)
