### ISSUE TITLE
Error reporting not working on python compiled on iridis4

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#233]
I'm trying to run py81b (latest dev) on iridis4, and I'm getting peculiar error reports at the end of a run:

Error summary: End of program, Thread 0 only
Recurrences --  Description
        1 -- Trying to get grid params for a non-existent domain!
     2004 -- getatomic_data: line input incomplete: %s
        1 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        1 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
        1 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model
        1 -- translate_in_wind: Grid cell %d of photon is not in wind, moving photon %.2e
        1 -- translate_in_wind: photon %d position: x %g y %g z %g

This is nonsense, there are about 5 line input errors, and lots of other ones. It works fine on my mac, or endjinn etc. The correct error report should say:

        1 -- Trying to get grid params for a non-existent domain!
        7 -- getatomic_data: line input incomplete: %s
     1971 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        1 -- error_count: This error will no longer be logged: %s
       32 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
        2 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model

Input file attached

[input.txt](https://github.com/agnwinds/python/files/745484/input.txt)

**Comment by Higginbottom** [comment]
I've worked my way back not to py80 - and the number of errors reported still bears no resemblance to the summary at the end.

**Comment by Higginbottom** [comment]
Think I've found the error. Its a doozie!
In log.c, error_count

The code first finds what error we are dealing with 

  n = 0;
  while (n < nerrors)
  {
    if (strcmp (errorlog[n].description, (format)) == 0)
    {
break;
}
    n++;

so n is set to the number of the error in question. Fine, 
it then tries to see if we have too many of this type of error

  {
    n = errorlog[n].n++;
    if (n == log_print_max)
      Error ("error_count: This error will no longer be logged: %s\n", format);
    if (n == max_errors)
    {
      error_summary ("Something is drastically wrong for any error to occur so much!\n");
      exit (0);
    }
  }
  return (n + 1);

See the problem? It redefines n even as it is using it. We want n to refer to the error, not the number of errors of type n!
So, I insert a new variable, n1, which will be the *number of errors*.

Think this fixes it. What is really odd (and deeply worrying to me) is that the compilers on the mac and endjinn, seem to cope with the mistake. How on earth do they do this???

**Comment by kslong** [comment]
I am not sure I understand why this is a problem.

You would not say that

n=n+1

Is a problem.

So why is

n = errorlog[n].n++;

A problem

**Comment by jhmatthews** [comment]
I think this is a little bit of an unclear way to do it but I think it is strictly correct. Let us know what the output is though.

Is this a threading issue? what happens if you run the py_error.py or watchdog.py scripts I wrote on it? Does the issue depend on number of cores?

**Comment by Higginbottom** [comment]
the first n in errlog[n].n is the identification number of the error, the second is the number of that type of error.

**Comment by Higginbottom** [comment]
My change means that the same input file run on my mac and iridis produces the same number of most types of error.
Output on my mac:
Error summary: End of program, Thread 0 only
Recurrences --  Description
        1 -- Trying to get grid params for a non-existent domain!
        7 -- getatomic_data: line input incomplete: %s
     1971 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        1 -- error_count: This error will no longer be logged: %s
       32 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
        2 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model
Run py_error.py for full error report.
Thread 0 Finalized. All done

output on iridis

        1 -- Trying to get grid params for a non-existent domain!
        7 -- getatomic_data: line input incomplete: %s
     1971 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        1 -- error_count: This error will no longer be logged: %s
       32 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
        2 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model
        1 -- translate_in_wind: Grid cell %d of photon is not in wind, moving photon %.2e
        1 -- translate_in_wind: photon %d position: x %g y %g z %g

now, another worry is why I get two translate in wind errors in iridis and not on my mac.

**Comment by jhmatthews** [comment]
Glad it works! Still confused though. Process for assignment should surely be find value of errorlog[n] in memory, then assign it's stored value to variable n, at which stage it doesn't care whether you've just changed n? I might be being dense...

**Comment by Higginbottom** [comment]
I have no idea what clever optimisation happens when you translate the code into machine code. The old version doesn't work tho. When I stick a load of printfs, in (sorry knox) what happens is that when you get a new typeof error, errlog[n].n = 0 (because its the first error of this type). When you then do 

n=errlog[n].n++

n gets set to 1, irrespective of what it used to be and error 1 gets incremented. 

So, you end up with all errors adding onto error 1 - the second error to be found.

Like I say, I don't know whats going on in the black box, but that is the behaviour.

**Comment by jhmatthews** [comment]
Cool, thanks. Good spot 👍

**Comment by Higginbottom** [comment]
OK, so the fundamental problem here was that the intel mpicc compiler on iridis was not behaving in an ANSI C manner. Ensuring that the mpicc is the gnu version fixes it.
