### ISSUE TITLE
py_wind_macro.c:copy_plasma does not copy plasma

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#241]
Simple one. Copy_plasma does:
``` 
    [...]
    x2->t_e = x1->t_e;
    x2->w = x1->w;
    x2->partition = x1->partition;
    x2->density = x1->density;
    [...]
```

`t_e` and `w` are variables, but `partition` and `density` are pointers. As such, they aren't copied. This means if you copy a plasma cell then call `saha(copied_plasma,[...])` you alter the densities of the **original** plasma cell. This function is only used twice, in `py_wind_macro.c:depcoef_overview_specific` and `level_popsoverview`, but both uses trigger this issue. In fact, calling either function multiple times will give a different output each time. Easy fix- actually declare a new array and do an element-by-element copy, and probably write a 'free_plasma' function or something to dealloc the memory afterwards. Shame C doesn't have destructors.

**Comment by jhmatthews** [comment]
great spot Sam. I think this is probably my fault. I'm hoping that the level population plots I presented are still correct - I think they must be, because they were compared to another code, so perhaps I got away with that one. Sorry for the inconvenience.

**Comment by jhmatthews** [comment]
we fixed this in dev @smangham ?

**Comment by smangham** [comment]
Er, I think I fixed it locally but haven't pushed it yet. I'll double-check.

**Comment by jhmatthews** [comment]
This is fixed in dev by this commit https://github.com/agnwinds/python/commit/adbd6ebe7df186957131e78c794f5d6fd118276b (thanks Sam), closing.
