### ISSUE TITLE
Extra wind save command in wind2d.c slowing MP execution

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#242]
Following my comments about MP python not scaling correctly I poked around and discovered a rogue wind_save command at line 325 in wind2d.c. Its not protected by ifdef commands to check that only one process writes, so its almost certainly the cause of my slowdown.
No idea how it crept in, but it needs to either go or be protected.
I vote go..

Nick

  /* Save the wind file as "test_plasma" */
  Log ("Saving test wind file NPLASMA %i\n", NPLASMA);
  wind_save ("test_plasma.wind_save");

**Comment by jhmatthews** [comment]
I think this is maybe from when Knox was testing domains. @kslong - is it still being used?

**Comment by kslong** [comment]
If this is not the command which allows one to print out the windsave file at the end of each cycle if one wishes, then it should go. But we should make sure we do a windsave at the end of each cycle if we want to.
Knox

**Comment by Higginbottom** [comment]
That command is in run.c, and is protected so only one thread prints out… I’ll fix it later.

N

**Comment by jhmatthews** [comment]
Fixed by #243
