### ISSUE TITLE
number of ionizing photons reported might not be what you expect

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#255]
Just been confused for a while by looking at nphot and nioniz (the number of photons and the number of ionizing photons in a cell). I was surprised that I was getting almost all of the photon in the cell reported as ionizing. I thought that ionizing photons would have been defined at those over 13.6eV. They are actually defined as any photon that could in principle cause an ionization (even from a very high level!). 

This is really just a question - but I'd have though a normal user would have assumed nioniz would be photons that can ionise unexcited hydrogen....

**Comment by jhmatthews** [comment]
I agree that n_ioniz being "number of photons above 13.6eV" would make most sense.

**Comment by kslong** [comment]
I agree with you, Nick
