### ISSUE TITLE
Scaling concerns

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#26]
Two variables, traditionally set to constant velues in Python, have been shown to cause big effects in certain situations.

**the scale length in the wind**
This has been shown to have a big effect online emission due to resolving the densest regions of the wind properly.

**DFUDGE**
Nick has found this produces problems when set to small (and it seems to have an impact when set large as well).

We need a way to set these  a little more dynamically for all scales- for example, we need a grid which will produce the correct results for a YSO model (when we need ~1e7cm, rstar being 3.828e11) right up to an AGN (rstar being around 8e14cm and unsure as to the scale length needed yet...around 1e13cm). 

likewise, is a DFUDGE of 1e5cm appropriate when the smallest cells are only ~50 times bigger?

**Comment by kslong** [comment]
We are closing this in favor of #175
