### ISSUE TITLE
Reflection issues associated with the star and disk

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#260]
At present, we have various options on how to treat photons that hit the disk,  but photons that hit the central source are lost from the system.  This is a significant problem in situations where the optical depth of the plasma immediately above the surface is significant.  In a self-consistent calculation we would like the star (and possibly all other radiation sources) to be treated the same, that is as "reflective" or absorbing and increase the temperature to compensate.

There are a couple of issues however

- What do we do with the boundary layer and the AGN?   If the boundary layer is thermal, I guess we can treat it like a star, that is as either reflective or by increasing the apparently luminosity. For a power law spectrum, though I assume we increase the luminosity.
- Technically, what do we want to do?  Add an input variable that globally controls how the radiation hitting a "radiative surface" should be treated.  This seems the cleanest thing to do.  It implies that we will need to work some of the internals of the program for this new variable which would be in geometry, and change some of the current choices for the disk.

Comments @jhmatthews and @Higginbottom   My view is this is a problem we need to address in the short term.

**Comment by kslong** [comment]
I have looked at this problem a bit, and I can describe what actually happens at present.

Firstly, what one does when a photon hits a surface is handled in the walls function in photon2d.c (around line 550).  For a star, the routine determines whether the photon is currently inside the star and flags it (for destruction).  For a disk, the routine checks whether how the geo.disk_illum variable is set.  Unless it is set to DISK_ILLUM_SCATTER, a flag is set and the photon is ultimately destroyed (though it may heat the disk).  If it is set to DISK_ILLUM_SCATTER, the photons is allowed to pass through the disk unaffected.  So despite the wording, DISK_ILLUM_SCATTER is as if the photon were specularly reflected from the disk.

So the question is what we want?  Do we want specular reflection which has somewhat odd consequences, or do we want something else, e.g the same distribution we use to generate photons at a surface in the first place.

Comments, anyone?

**Comment by kslong** [comment]
OK, regardless of what we decide regard how scattering is supposed to go (specular reflection or something else.  I propose to eliminate the rdpar line Disk.illumination.treat,ent and replace is with something like Reradiation, which will be further up in the .pf and will apply to all surfaces that radiate.  I propose to move the option 3 extra heating from star which was set up for YSO's (and created a non-standard temperature profile) into Disk.temperature.profile, which is really what it is.  There will be some changes to the internal geo variables to reflect this.  

If you have objections, suggestions for a better rdpar line name, please let me know.

**Comment by kslong** [comment]
These are the changes that have been made to address this issue, as of this date.  There are a few items still to address, but I went ahead an merged it back into dev at this point.

* Instead of geo.disk_illum there is a new variable geo.absorb_relect which is intended to govern all processing of photons which hit either the disk or star
* The rdpar variable has been renamed to Surface.reflection.or.absorption.  Updates have been made to synonyms so the old variable has been understood.  Updates have been made to the .pf files in regression.py for those .pf files which do not have the absorb reflect keyword, since this is now needed for all models
* The option of having an analytic approximation for the stellar temperature has been moved to the disk.temperature.profile rdpar line, and to the geo.tprofile variable
* #defs have been created for use with geo.tprofile
* implemented scattering off the star, assuming it hits the star is is “scattered” so that fhe final directions are determined randomly as they would be if the photons was radiated from the photosphere
* Changed the way scattering from the disk works, so that instead of simply passing through the disk these are also redirected.
* renamed alls the disk illum variables
* Added geo variables, e.g lum_star_init, and t_star_init so we have can separately track the current temperature and luminosity of the star from the intrinsic (nuclear) luminosity of the star.  
* Added similar variable for the disk
* Modified star_init, so that it would calculate a revised temperature, including the back scattered radiation in depending upon the treatment of reheating.  (This does run, but I need to make sure it is only happening in the ionization cycles)
* Make hitting the disk or star  a scattering site  from the point of view of extract


Deficiencies
* Right now in the scattering mode we don’t keep track of how many photons hit the star
* Replace the scattering model with zero limb darkening (or both).  
* Make reheating the default model
* Check the remainder of the .pf files to make sure they include the reflction parameter

**Comment by kslong** [comment]
For stars and the disk , we use randvcos to generate the direction.  It is not clear to me that this includes any kind of limb darkening.  @lazygun37  can you check that I am correct.

**Comment by jhmatthews** [comment]
I think it does Knox - haven't checked thoroughly but the PDF is built from the vcos() function which has the standard Eddington approximation a * (1 + b cos(theta)) built in.

**Comment by jhmatthews** [comment]
Closing this issue, since the original issue was addressed and there are two open issues regarding reflection treatments #524 #180
