### ISSUE TITLE
Correctly reporting absorbed flux

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#265]
One of the useful diagnostics that is reported as python is running are the Absorbed flux, Wind heating, Wind luminosity and Wind cooling lines. 
The Absorbed flux is incorrect, since it actually only reports the wind cooling for photoionization. This is particularly important in testing the new recomb cooling/lum fix. 
I'm going to try and implement a more useful value which will be the photon flux absorbed by PI processes - i.e. including the binding energy.

**Comment by jhmatthews** [comment]
Good idea 👍

**Comment by Higginbottom** [comment]
fixed by pull request #266 

Very interesting.
