### ISSUE TITLE
python no longer working with stellar models

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#270]
On the current dev branch, python is unable to generate cdfs for either a star or a disk when Kurucz models are used instead of bb.  

@lazygun37 , @Higginbottom is correct that python is not working with stellar models for a star.  

These errors are among those being generated:

   100001 -- pdf_check: x problem n %d x %f pdf->x[n] %f
        7 -- error_count: This error will no longer be logged: %s
      502 -- pdf_check: x values in pdf should be monotonic
      502 -- pdf_check %d %d %d %d %d
      502 -- pdf_gen_from_array: error %d on pdf_check
      502 -- In one_continuum after return from pdf_gen_from_array
      503 -- pdf_get_rand: %d
      503 -- pdf_get_rand: %g %d %g %g

**Comment by Higginbottom** [comment]
This is more complex hat it first seems...

Here is a file which fails:
[stellar_1em16_kuruz.pf.txt](https://github.com/agnwinds/python/files/1173126/stellar_1em16_kuruz.pf.txt)

however this one - which uses the same kurukz file runs fine
[star.pf.txt](https://github.com/agnwinds/python/files/1173129/star.pf.txt)

There are many differences between the files, and its possible that the first one breaks all kinds of rules about what we should do with models, but it should fail gracefully..

**Comment by kslong** [comment]
@Higginbottom has "settled" more or less on a new formulation of levels in cdf.p, but as of today, the following input files sv.pf file that ksl first tested is still failing with the same error as above.

[sv.pf.txt](https://github.com/agnwinds/python/files/1185933/sv.pf.txt)


Nick reported that he has some files that do seem to work with kurucz models and some that do not.

star.pf above has no ionization cycles, but there are no problems even if these are added. There are also not problems seen when the T is lowered to 1000 K or raised to 100,000 K which is outside the grid.  


The stellar_1em16_kurucz.pf file does fails, but if fails for different reasons than sv.pf does, viz

one_continuum: f too large %e

... which is weird.  Somehow what is happening is associated with using kurucz models though because if you drop back to a bb spectra, you do not get errors with same file.

Note however, a little debugging revealed that the code is going through one_continuum in both cases, so the errors are not completely unrelated.

**When exactly did the problem appear:**

It was present

commit 20682080a2ce4c07e1106bfa71e17fd94525bf97
Merge: 872490e 365f4d5
Author: jhmatthews <jimim@hotmail.co.uk>
Date:   Tue Jul 12 18:01:02 2016 +0100

    fixed merge conflicts


It was not present

commit 872490e7b0eacac3483d0c7aedab9b9d76d48a1f
Author: jhmatthews <jimim@hotmail.co.uk>
Date:   Tue Jul 12 17:42:10 2016 +0100

    added qdisk_plot.py to py_progs

tsk ... tisk @jhmatthews

**Comment by kslong** [comment]
This merge where the error got into the dev branch was a large one, with lots of changes in lots of the routines.   Among other things it was at the point where the recombination data stopped being recorded in files which were written out and read back.

**Comment by kslong** [comment]
I have to quit for the day @Higginbottom  but the problem is on line 694 of cdf.c,  where for Kurucz models, q is turning out to be negative.  What is happening is the m is being incremented in the earlier loop, so that x[m] is greater than xmax.  It occurs in the case of the Kurucz models regularly, because they are on a coarse grid, and I expect the reason it only occurs for some models has to do with exactly where the limits were set.

**Comment by kslong** [comment]
@Higginbottom  I am ready to hand this problem back over to you.  There is a mistake in cdf_gen_from_array  (around line 620), in that when some of the input array values are zero you reset xmin and xmax to exclude those values.  But this was done without considering what the values of xmin and xmax were  input from the calling routine.  The result is that cdf is not generated over the range requested and in particular it can be over a larger range than requested.  This results in lots of errors having to do with photons out of range and eventually a crash of the program.  

(Note that this did not happen in the old way we subsampled the input array to try to produce and equally spaced grid.)

If is not immediately obvious what the riight thing to do here.  One possibility is to make sure the first and the last elements extend to the original values of xmin and xmax, but that the cdf in the region where pdf was zero does not rise.  This has the advantage that the limits which are returned are the same as requested.  But it's probably ok for the cdf's to change the limits of the cdf to exclude regions with zero value, if it is done taking into account that you do not want the cdf to cover a larger range than requested.

Note: It is not obvious to me how the current routine catches the possibility that the requested range of wavelengths is outside the wavelength range of the model.  It looked like to me that this might also be happening in the .pf file that fails.  Specifically, it looked like to me that there is a band that is requesting wavelengths from 517098 to 1240001 A, which goes way into the IR and is not covered by the Kurucz models.  This also needs to be handled.

**Comment by Higginbottom** [comment]
Ah, OK. So I think the way to fix this within the ethos of the way I’ve coded cdf_gen_from_array is for the calling routine to send an array that only contains data in the range xmin to xmax. That way cdf_gen remains a dumb routine that just processes what it is sent. This is how I intended it to work….

Nick

**Comment by kslong** [comment]
No. This is getting worse as a philosophy. We should fix the error within CDC. We seem to be trying to make cdf..c brain dead

Sent from my iPhone

On Aug 2, 2017, at 1:26 AM, Higginbottom <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah, OK. So I think the way to fix this within the ethos of the way I’ve coded cdf_gen_from_array is for the calling routine to send an array that only contains data in the range xmin to xmax. That way cdf_gen remains a dumb routine that just processes what it is sent. This is how I intended it to work….

Nick

**Comment by kslong** [comment]
This is fixed however there are still some issues with reading in models that are still existent. See #294.  Nevertheless, I am closing this issue
