### ISSUE TITLE
CDF generation - artefacts caused at bands ends due to photon stats

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#280]
This is a long running item, and one we all know about but I think we should discuss at some time.
When there is a quickly changing spectrum, like the wien tail of a BB, we 'run out' of CDF part way through a band. In other words, if we are making 100 photons, but we reach a CDF value of 0.99 half way though a band then we make no photons in the upper end. 
Of course this is energetically fine, there really is little power there, but it does give rise to gaps in the photon distribution. And it can be important at frequencies lower than on the attached figure if you make lots of recombination photons. 
And of course this is all allied to a larger problem when if the around a central source wind is very hot ad dense, you might make no central source photons at all if the wind is hot enough.

Here is an example:

![stellar_1em16_created_vs_emitted](https://user-images.githubusercontent.com/3329213/28623563-44950bca-720e-11e7-8eea-7ef8118c366f.png)

Vertical dotted lines are band boundaries. You can see the photons peter out in a load of noise (basically when you can only make one or no photons to get the right luminosity). Then the BB picks up again at the next boundary.

Solutions:
Automatically split bands?
Once a source ends in one band - zero it in bands above that point - then at least you will get an end to a sources contribution, not a dropout...

**Comment by kslong** [comment]
I agree that this is a long running problem.  Indeed I spent a considerable amount of time on it more than a decade ago, and it was one of the reasons for the institution of jumps, and gradients in the code to generate the cdfs.  My feeling is that while one could adopt a more complicated approach the easiest thing to do would be to up the sizes of the cdf arrays, and/or to adopt some criteria that assure that there is a certain density of points even when the pdf drops to a low value.  Note that it is unclear why these distortions should have a practical effect. We should try to find out it there are.

While I agree there should be a discussion about this, it would be best to wait until everything has settled down.

**Comment by Higginbottom** [comment]
Agreed - I'm just putting these up to make sure I don't forget about them!!

**Comment by kslong** [comment]
@Higginbottom   - This is another problem we need to document better and decide what if anything we want to do about it.  It looks like there was work that might have changed the situation

**Comment by kslong** [comment]
@Higginbottom   Can we close this issue, or can you  describe what remains that should be investigated.

**Comment by Higginbottom** [comment]
Closing - this is a fundamental thing with banding, user should just choose better bands!
