### ISSUE TITLE
CDF generation - artefact in BB due to switch over between CDF and exp treatment

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#281]
Here is an oddity. When generating BB photons, we need to work out when to switch between using a CDF to make the photons (up to h\nu/k_BT =30) and when to generate it using an exponential function. 
This is done by performing integrals from zero to the band start, zero to the cross over point, and zero to the band end. We then do a little arithmetic to convert these points into points in the space of 0>1 which is generated by the random number generator.
It seems that this maths is going a bit wrong, probably because all these integrals and up being very similar, 0.999999 + little bits when we are in thew region around alpha=30.
This means that we get it wrong where to swap from CDF to exp, and end up making no photons in the range between alpha=30 and the band end. See below.

![stellar_1em16_created_vs_emitted](https://user-images.githubusercontent.com/3329213/28624220-60ad08ce-7210-11e7-8284-cd36f372a057.png)

The vertical red line is alpha=30 - note also the incorrect gradient caused by bug #279 in the last bin.
There is plenty of flux, but the exponential photons are just not made.

Solution - we should probably come up with arithmetic that doesnt end up subtracting almost identical numbers and carrying out huge integrals when we are really only interested in a tiny fraction of them

**Comment by kslong** [comment]
@Higginbottom   What do we want to do, if anything about this.  3 or 3 related CDF issues.

**Comment by Higginbottom** [comment]
I honestly don't know - we should discuss this at the telecon. Its likely to take some time - and is most likely pretty inconsequential....

**Comment by Higginbottom** [comment]
This problem seems to have gone away - I suspect the old pull request a bit higher up where I comment on some mistakes actually fixed this...

![star_fine_zoom_hi](https://user-images.githubusercontent.com/3329213/116417054-d75d9e00-a832-11eb-91b3-9374bad9f82d.png)

We still see the last CDF band step - due to the problem with the gradients at the end. 
Increasing the number of CDF points doesnt affect this - it is basically driven by the enforced jumps, because by this point we have integrated almost all of the blackbody.

A linear extrapolation for the gradient goes very wrong - because we are on the exponential tail - we need a fancier way of extrapolating...

We can however make a very small final enforced jump, which works in the blackbody case..

![star_zoom_hi](https://user-images.githubusercontent.com/3329213/116422675-e09d3980-a837-11eb-9908-6ee05b043708.png)

Fundamentally, I think this bug is fixed. And can be closed. The remaining bits are just #279.

**Comment by Higginbottom** [comment]
This appears to have gone away!!
