### ISSUE TITLE
Co-moving frame energy conservation w/ indivisible packets?

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#285]
This issue was raise by @ssim a few weeks back, and I don't want to forget about it so I'm documenting here. When real photons resonantly (or electron) scatter off real plasma in a flow, they conserve energy and frequency in the _co-moving frame of the plasma._ In the case of an outflow, doing the frame transformation from system->flow->system over the course of an interaction results in a redshifting of a photon, and as a result an energy loss - in other words, the photon does work on the flow even though energy is conserved in the co-moving frame. 

Indivisible packet schemes (such as macro-atoms) should enforce strict energy conservation in the frame of a given cell (physically, but see also Lucy 2002,2003). This means that, when keeping track of packets in the observer frame, one needs to correct the energies (not just the frequencies) using a Doppler shift. Having looked at the code, I can't find anywhere where we do this, and I believe we should. I guess this introduces errors on the order of (v/c) in photon weights in some cases.

**Comment by jhmatthews** [comment]
On a related note, when I reread my thesis I noticed the following lines:

_"The formulae are the non-relativistic case, which was used for this thesis. However, this should in general be improved to use the more accurate special relativistic formula,
as the current treatment introduces errors of order 5˚A at the blue edges of the highest
velocity absorption lines in the models described in chapters 4 and 5."_

**Comment by jhmatthews** [comment]
It was agreed that the test here is for me to try a macro-atom run where co-moving frame energy conservation is enforced (by transforming photon weights as well as frequencies), and see the magnitude of the difference. This should probably be done for a model with quite high velocities since this is the worst case.

**Comment by kslong** [comment]
@jhmatthews   Ideally we would address this before the release, but it looks like there is a good bit of work to do, as it affects various portions of the code, including the estimators, as discussed in Lucy 05.  The argument against doing this is that for a wind with a velocity of 10**4 km/s it is a 3% effect. It needs to be done though if we really have high tau systems with this kind of velocity. It looks like to me we might have tried to make corrections in a few cases, see, e.g Compton scattering (compton.c) but we are certainly not consistent overall.

**Comment by lazygun37** [comment]
Just a quick note to make sure we'll on the same page here: this issue is exactly what Roth and Kasen, for example, call "adiabatic reprocessing". Ed's tests for TDEs seem to show that we do treat at least deal with the redshifting in frequency space for electron scattering.

**Comment by kslong** [comment]
I believe that is only part of the issue.  You need to read Noebauer & Sim again in the CMF  section, as I suggested to you previously,  and also Lucy 05, where he discusses the issue in terms of SN models.  It not only affects things like energy loss in Compton scattering, but also all the basic estimators.  “Adiabatic Reprocessing”, which seems like a truly made up term, is better thought about in the general framework of the difference between the CMF and the lab frame.

**Comment by jhmatthews** [comment]
Yeah - for this I think we just need to be a bit careful whether about saying that "we treat adiabatic reprocessing" or anything. We currently treat the frequency shift but not the energy shift. This means we will presumably make redder spectra than we should, because the redshifted photons have too high a weight, so our treatment is not accurate.

Regarding the practical aspect of how to implement CMF conservation in the code, I believe we talked about this in Southampton and @ssim identified some possible issues, but I can't recall what they were. I think I was supposed to do a test or two where I tried adding some statements in macro_gov to conserve energy in CMF - see above - but (sorry) I haven't got around to doing this.

**Comment by jhmatthews** [comment]
The plan is to carry out a review of this and other (special) relativistic / CM frame effects once we've had the journal club on "relativistic radiative transfer" from Stuart. With that in mind, leaving open until we have a way forward.

**Comment by kslong** [comment]
With the completion of the Belfast20 effort, I believe this issue is addressed.
