### ISSUE TITLE
Model spectra - the hydrogen edge

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#287]
I've been looking very closely at my rad-hydro simulations, and I've been reminded of one interesting 'feature' of the code. When we produce model cell spectra, we use bands that are initially set to 

    nxfreq = 10;
    xfreq[0] = freqmin;         
    xfreq[1] = 1e15;            
    xfreq[2] = 3.162e15;
    xfreq[3] = 1e16;
    xfreq[4] = 3.162e16;
    xfreq[5] = 1e17;
    xfreq[6] = 3.162e17;
    xfreq[7] = 1e18;
    xfreq[8] = 3.162e18;
    xfreq[9] = 1.2e19;       
    xfreq[10] = freqmax;

Just set logarithmically. Now, I note that 3.162e15 is awfully close to 13.6eV!!! This means that in a dense model, with a very deep hydrogen PI absorption edge there is a *very* narrow band that defines this band. Remember, we reset the upper frequency band to that of the highest frequency photon seen in the band. 
There could also be significant noise introduced into the model by this approach. If one photon with e>13.6eV  edges into the cell, the upper band boundary will be increased, and you could get a much more ionised cell. The exact upper boundary could jump around, meaning that the PI rate could be very variable, perhaps explaining the chaotic behaviour in the rad hydro models, because FF cooling is proportional to ne * nH2, so it kinda goes as the square of the ionisation state. This is often the dominant cooling rate....

How to address this? Don't know, but I do want to do a little more investigations...

**Comment by kslong** [comment]
@Higginbottom   you initiated this issue.  Can you label and prioritize it (high medium or low) and more generally state how you would like to proceed.

**Comment by Higginbottom** [comment]
This is not a bug - merely a note that we need to think more carefully about banding.....

**Comment by jhmatthews** [comment]
Since there is an issue open about banding strategies, I'm closing this note with reference to #410
