### ISSUE TITLE
Spherical model - ask for 10 cells, don't get that many

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#289]
Trying to grid up a stellar model I note that if you ask for 10 cells via

Wind.dim.in.x_or_r.direction               10

you actually only end up with 7. I think this is due to our ghost zones, used to allow differentials of velocity etc however I think these ghost zones should probably get added onto the requested grid like in 2D models.

Here is a .pf file so you can see the problem! Look at the t_e report, you will see that there are some zeros - this is because some of the 10 cells are not in wind...

[stellar_1em6..pf.txt](https://github.com/agnwinds/python/files/1248064/stellar_1em6.pf.txt)

**Comment by Higginbottom** [comment]
Oh, OK.
So we don't get 100x100 real cells in a 100x100 model either. 
Might be a good idea to fix this in the longer term - comes as a bit of a shock when you forget that this is the way we do it...

**Comment by kslong** [comment]
Yes, this has always been the case. Obviously it could be changed, but it has never been a priority in part because the wind cells and the plasma cells usually differ in number.

Sent from my iPad

On Aug 24, 2017, at 3:52 AM, Higginbottom <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, OK.
So we don't get 100x100 real cells in a 100x100 model either.
Might be a good idea to fix this in the longer term - comes as a bit of a shock when you forget that this is the way we do it...

**Comment by kslong** [comment]
@Higginbottom @jhmatthews @lazygun37   What is our pleasure here?  Do we want to leave this as is where the "guard" cells are counted in the dimension we put in or do we want to exclude them.

**Comment by jhmatthews** [comment]
Happy leaving it as it is for ease of backwards compatibility if nothing else. Perhaps a print statement explaining it to the user might be useful

**Comment by kslong** [comment]
It is true not just of the spherical model but of every model.  There are always guard cells, and moreover for most wind models only a fraction of the cells are actually used..  As a result, I don’t think a warning for this case really helps.  This is something that should (a) be in the manual, or (b) fixed, if we really think it’s an issue.  But if we doit we need to do if in all instances, and that seems to be a good bit of work.

**Comment by jhmatthews** [comment]
I think a) is the best option, it's a manual issue for me. I'm going to close, we have more pressing concerns.
