### ISSUE TITLE
Cell 200 SEDS not working with Python

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#294]
Nick has tried to create a shell model in which the illuminating source are SEDs he has generated from spectra of found in Cell 200.  For reasons, that are unclear these SEDs do not work as inputs to Python.    

The problem is that the output spectrum does not resemble the input.   Input:

![orig](https://user-images.githubusercontent.com/2530901/30037021-a8fbdfe2-917d-11e7-84e6-9fb89890cdc3.png)

Output in log_spectot

![result](https://user-images.githubusercontent.com/2530901/30037024-b27786e8-917d-11e7-8d9b-f948fd6e61d5.png)

@Higginbottom is this a clear statement of the problem?

**Comment by kslong** [comment]
Aside - I have claimed that one could use an AGN as well as a star for doing this kind of modelling but even though the AGN model has the possibility of getting its spectrum from a file (or series of them) it is not clear that the AGN inputs are set up to choose the parameters properly, that is, one needs to provide parameters to select which model is correct in the AGN case.  Also, I believe, but have not checked that for the Kurucz case, when you get outside of the range of the models (say with a higher T) the routine takes the best model and then multiplies it using bb models.  This all needs to be checked into.

**Comment by Higginbottom** [comment]
This is the problem I was having! My attempt was to create 4 identical model files, and tell python that these represented models for the corners of a grid running from 50K to 1e9K in temperature and 0 to 7 in log(g). 
I set up a model with a star as the central source, with T=1e6K, M=0.8Msol R=1e10cm (which gives log(g)=6 (in cgs units). 
The results are as KSL posts above.
The tar file below contains the input file (input.pf) the cell spectrum (cell_200.spec) the python script that converts it into model files (py_cell_2_model_input.py) - just do py_cell_2_model_input.py cell_200.spec, and also the outputs.
[model_test.tar.txt](https://github.com/agnwinds/python/files/1276410/model_test.tar.txt)

**Comment by kslong** [comment]
Notes:

The model reading program assumes that a model grid will have one or two parameters, and that the first parameter will always be some kind of T.  This only matters though if one goes outside of the range of the grid.  If you do this then the input spectra are modified using BBs.

(For our example case, we are NOT outside of the input range.)

The input spectra are assumed to be lambda, f_lambda.  

This is what the model structure looks like:

//#include      "pdf.h"

int ncomps;                     // The number of components that have been read.  
int nmods_tot;                  // The total number of models that have been read in 


/* This is the structure that describes an individual continuum model. 
 * mods is the set of all models that are read
 */
struct Model
{
  char name[LINELEN];
  double par[NPARS];
  double w[NWAVES];
  double f[NWAVES];
  int nwaves;
}
mods[NMODS];

/* There is one element of comp for each set of models of the same type, i.e. if
one reads in a list of WD atmosphers this will occupy one componenet here */

struct ModSum
{
  char name[LINELEN];
  int npars;                    // Number of parameters that describe the model
  int nmods, modstart, modstop; //number of models of this type and the index into the model struct
  double min[NPARS];            // The minimum and maximum for each "free" paratmenter of the model
  double max[NPARS];
  int nwaves;                   //All models in each comp should have same wavelengths;
  struct Model xmod;            //The current intepolated model of this type 
  struct Cdf xcdf;              //The current cumulative distribution function for this component
}
comp[NCOMPS];

Notice that the wavelengths are actually not part of comp

**Comment by kslong** [comment]
Notes:

In inspecting what is happening in the SED case it is clear that there is something very odd in continuum.c near line 187.  in the line,

nwav=model (spectype, par)

nwav is coming back 0, because the parameters are identical to the last call to model, and these is causing lots of problems in what follows.  In particular, emittance continuum is being called by star_init.  One is apparently trying to calculate the emittance in a spectral range, but the result of all of this is the value returned to star_init is 0.  

This explains the phenenon, we are actually seeing.  Either model should not be returning 0, or it should be handle in emittance_continuum.

**Comment by kslong** [comment]
After making the changes to cdf_gen_from_array and a smalll change to continuum.c, I get somewhat more plausible outputs, but more checking is still required.

Here I believe is the input SED

![input](https://user-images.githubusercontent.com/2530901/30350658-4b6f0096-97dd-11e7-95c2-479b717a47a3.png)
and here is what Python produces for spectot

![created](https://user-images.githubusercontent.com/2530901/30350666-55d3fdac-97dd-11e7-8aec-6e1bc743ea4d.png)

Note what I still am not sure I understand is whether I am plotting exactly the same thing in both places. The wavelengths look about right but the overall shape (the flux at the blue end) is not quite right.

**Comment by kslong** [comment]
The reason the spectra above look different is that the input spectra are in flambda whereas the spect_tot output spectra are in f_nu.  Here are plots for lambda * f_lambda = f_nu * nu

Input

![input](https://user-images.githubusercontent.com/2530901/30387867-8cc1cdf8-9873-11e7-97b1-4055f44a5a08.png)

Output
![created](https://user-images.githubusercontent.com/2530901/30387875-9504aa08-9873-11e7-9cdd-f4cbdbbe6b88.png)

with the modifications I made to pdf_gen_from_array, this looks to be working.

**Comment by jhmatthews** [comment]
Model SEDs are being discussed in #301 , so I'm closing this.
