### ISSUE TITLE
Compton heating - energy leak

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#295]
When we originally implemented Compton heating, we did it via a continuum opacity which attenuates passing photon packets and transfers energy to the cell it is passing through. This is logged as heat_comp. This approach is based upon the idea of averaging the Compton heating effect over electron velocities and scattering angles. 
This method changed slightly in late 2015 when we tried to implement a method that would give rise to a Compton hump (at least in part) - i.e. we wanted to properly change the frequency of photons scattering off electrons. Now, we still work out the heating effect via the opacity method, but we do not attenuate photon packets at that point. Instead, when a photon scatters via electron scattering, we work out a new direction for the photon, and use this to compute an energy change. We use this to reduce the photon frequency, and the photon weight is reduced by the same amount.

This seems to work correctly however there is a disconnect between the energy added to the cell, and lost from photons. In the most extreme case, in optically thin cells, there might be no interactions at all, so energy is added to the cell via the opacity but not lost from the photons. 

Compton heating is dominant in low density gas exposed to an intense radiation field. Just because the radiation field is intense doesn't necessarily mean lots of photon packets though, each of a few packets might have huge weight. This would mean that if we just went over to only heating via scattering events we would not reach the Compton temperature.

So, we have three choices:

1: Keep the code as is - this introduces a (usually small) energy leak where photons don't lose weight even though the cell is being heated

2: Go over entirely to a scattering model - so we only transfer energy during scattering events. Unless we come up with something very clever this will result in catastrophic problems in models where we expect to reach the Compton temperature.

3: Go back to attenuating the photon packets via opacity. If we then do *not* attenuate the packets when scattering, we will violate photon numbers. We take a packet of weight w, frequency nu, and hence n=w/hnu then reduce nu and increase n. How bad is this exactly??

**Comment by Higginbottom** [comment]
I've done a small number of tests, and it looks like if you make cells optically thick, then the Compton heating from opacity and the energy loss from photons during Compton scattering become similar. So it looks like the method we do at the moment is about right. Its just that we do not assure that the energy balance is maintained.

**Comment by kslong** [comment]
It seems to me we should stick with our existing model for now.  

Just to confirm my understanding, with our current approach, the reason for the energy leak is basically because we are calculating the heating at a different time from the change in photon weight.  Since we don't change the photon weights until a scatter occurs, but calculate the heating along the path, the heating can differ (in either direction) for the net photon flux into and out of the cell.  When the cell is optically thick to Compton scattering, this does not matter much because there will be lots of Compton scatters within the cell, but when it is optically thin one can get discrepancies.  There is a tendency to see this as excess heating in the optically thin case, because most photons never scatter within the cell, but all these photons do contribute to the heating.

Could you explain a bit more about a pure scattering model?  Why would we expect "catastrophic problems near the Compton temperature?

**Comment by kslong** [comment]
@Higginbottom   Should this issue be closed?  If so would you do it please.  If not, would you describe what needs to be done.

**Comment by Higginbottom** [comment]
A pure scattering model would in some way mean that heating is only computed when a photon's fate is an electron scatter. We would no longer attenuate a photon via compton 'opacity' as it passed though the cell. I'm not quite sure how to do this, and the risk would be that you would need enough photons to interact to ensure you get to the compton temperature in cells where one would expect that to be the case. This is likely to be in optically thin cells and so my guess would be that you would not get the right temperature if you rely on interactions. 
I'm happy to put this as 'not a bug' because the code is doing what we ask of it, but its just that the approximation can break down sometimes...
Should we close it? Well it is still a valid point - we should discuss our policy about such things.

**Comment by jhmatthews** [comment]
This issue can, in principle, lead to energy not being conserved in a non macro-atom model, but in a converged model energy should still be "asymptotically" conserved. Any choice here will lead to a compromise and our current approach seems reasonable, so we are closing this with caveat.
