### ISSUE TITLE
CDF generation - cdf_gen_from_array

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#297]
In py82,  cdf_gen_from_array does not allow one to generate a cdf from a subset of an array.  Instead, as written one must modify the the array so that the minimum and maximum frequencies desired for the cdf agree exactly with values in the array.  

Instead, cdf_gen_from_array should be able to deal flexibly with situations where the edges of the cdf do not correspond exactly to the boundaries provided.  

The is related to #270 and #294.

**Comment by kslong** [comment]
Before fixing this problem, one needs to understand how @Higginbottom  changed the funtionality of pdf_gen_from_array, aside from renaming arrays.

Inspecting the old and new code, I believe this was the change.  In the old code,  the routine accepted a set of wavelengths and fluxes, and a set of limits for the desired cdf.  It took the array, and the limits, and constructed a new aray which was more or less uniformly space in cdf space, within the prescribed limits.  This process allowed one to take an array which was quite large and produce a cdf that in terms of the size of the array was smaller.  The old routine attempted to deal with jumps, but this did not work properly.

The new routine assumes that the input array is really what you want, and that one can afford to store it at the full resolution.  This means there is no reason for jumps.  The new routine also tries to eliminate regions at the end of the array which have no probability density.  

cdf_gen_from_array is called from 3 other routines:

continuum.c:145:    if (cdf_gen_from_array
emission.c:836:    if ((echeck = cdf_gen_from_array (&cdf_ff, ff_x, ff_y, ARRAY_PDF, f1, f2)) != 0)
recomb.c:676:    if (cdf_gen_from_array (&cdf_fb, fb_x, fb_y, nnn, f1, f2) != 0)

**Comment by kslong** [comment]
I have updated the code so that it can handle situations where xmin and xmax do not correspond to the the wavelengths in the input array.  As discussed in #294 it is now possible to read in Nick's cell 200 SEDs.  

What remains is to make sure that this routine is functioning as we want in detail.  To check this have been using Kurucz models.  Here is an example of the results:

in

![star_in](https://user-images.githubusercontent.com/2530901/30398901-a94a20d2-9897-11e7-9aff-f8390e4cd840.png)

out

![star_out](https://user-images.githubusercontent.com/2530901/30398909-ad86d0fa-9897-11e7-913e-e84ad5495b87.png)

(Note this is the log_spec_tot spectrum.  The spec_tot spectrum does not have enough resolution)


[ktest.pf.txt](https://github.com/agnwinds/python/files/1300854/ktest.pf.txt)F

For the most part the agreement is very good.  However, note the issue where there are "jumps" in the input spectrum, where we get negative jumps in the output spectrum.  I am suspicious that the trapisoidal rule or the gradient calculations, perhaps.

I've looked at the way the trapisoidal rule is implemented, and that certainly seems the best way to do it.

**Comment by kslong** [comment]
Further investigation makes it look like this is problem with end points.  Currently a new cdf is generated every time a new photon wavelength range is selected.  

I made some modifications to the high end of the wavelength range requested, and this is the result

![star_out](https://user-images.githubusercontent.com/2530901/30403050-889eec42-98a5-11e7-8a29-336fbab84f9d.png)


Note this is a gazillion photons, so it is still a bit odd to me why the photon statistics do not look a little better in a few places.  At any rate this is some improvement over what was there before.

**Comment by smangham** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/VmiWSGHt/8-test)

**Comment by kslong** [comment]
From the commentary, it is not obvious there is a bug any more.   There is a residual worry that not as many photons are being generated in some bands as might be expected.   In the absence of any more concrete information, I am closing this.
