### ISSUE TITLE
Not all collision strengths read in

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#298]
I was confused as to why Mg II and Si IV lines no longer showed up in my model with atomic dataset h10_standard80. It turns out it's because not all the collision strengths are read in. In get_atomicdata, we read collision strengths of the following format:

```
CSTREN Line  1  1  949.742920  0.009300   2   4     0.000000    13.056184    0    8       1     19   9.600e-01   1.860e-02   7.750e-02    5    1   1.500e+00
SCT   0.000e+00   2.500e-01   5.000e-01   7.500e-01   1.000e+00
SCUPS    1.617e-02   2.461e-02   3.367e-02   4.794e-02   7.749e-02
```

The SCT and SCUPS tell us the scaled temperatures and upsilons that we will interpolate on (see Burgess & Tully 1992, and Chianti userguide. the third last digit in the CSTREN record, in this case 5, tells us how many of each to read in. This can be as high as 19. The two lines of fitting data are read like this:

```C
    //We now read in two lines of fitting data
    if (fgets (aline, LINELENGTH, fptr) == NULL)
    {
      Error ("Get_atomic_data: Problem reading collision strength record\n");
      Error ("Get_atomic_data: %s\n", aline);
      exit (0);
    }
    nparam = sscanf (aline, "%*s %le %le %le %le %le %le %le %le %le %le",
                     &temp[0], &temp[1], &temp[2], &temp[3], &temp[4], &temp[5], &temp[6], &temp[7], &temp[8], &temp[9]);

    for (nn = 0; nn < np; nn++)
    {
      coll_stren[n_coll_stren].sct[nn] = temp[nn];
    }
    if (fgets (aline, LINELENGTH, fptr) == NULL)
    {
      Error ("Get_atomic_data: Problem reading collision strength record\n");
      Error ("Get_atomic_data: %s\n", aline);
      exit (0);
    }
    nparam = sscanf (aline, "%*s %le %le %le %le %le %le %le %le %le %le",
                     &temp[0], &temp[1], &temp[2], &temp[3], &temp[4], &temp[5], &temp[6], &temp[7], &temp[8], &temp[9]);

    for (nn = 0; nn < np; nn++)
    {
      coll_stren[n_coll_stren].scups[nn] = temp[nn];
    }
    n_coll_stren++;
```

Which clearly cannot read in more than 10 records, and ends up copying 0s to the other entries. The simple fix is just e.g.

```C
              /* JM 1709 -- increased number of entries read up to max of 20 */
              nparam = sscanf (aline, "%*s %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le %le",
                               &temp[0], &temp[1], &temp[2], &temp[3], &temp[4], &temp[5], &temp[6], &temp[7], &temp[8], &temp[9],
                               &temp[10], &temp[11], &temp[12], &temp[13], &temp[14], &temp[15], &temp[16], &temp[17], &temp[18], &temp[19]);
```

which works, but is possibly not the most elegant way of reading variables numbers of entries. The loop over np ensures that the right amount of records are copied over to the coll_stren structure.

**Comment by jhmatthews** [comment]
My fix can be seen here: https://github.com/agnwinds/python/pull/299

@kslong perhaps you know a cleaner approach, although it does work fine.

**Comment by kslong** [comment]
There are options other than sscanf that break lines words/tokens using strtok.  I remember trying them at various times, but they always seemed a bit “fragile”.    But this allows you to construct do loops that can parse a string of numbers.

**Comment by jhmatthews** [comment]
Ok. I've done a few more tests and this works fine, so I'm merging and closing for the moment. We do now get Mg II and Si IV lines. Will be documented here: https://sites.google.com/site/agnwinds/bugfixes-and-tests/ciii-and-updated-collision-strengths-impact-on-16-model
