### ISSUE TITLE
Regression challenge

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#304]
Right now I do not have a set of regression tests that provide a quick way to test very basic aspects of python that have and continue to be used in papers we want to write, e.g macro atoms @jhmatthews  reverb (Sam) hydro @Higginbottom 

I think we need them, as I think I have mentioned a few times in our telecons.  

My immediate motivation is that I have been working on reflection and this gets into the "guts" of the code, and it's not completely obvious what one is affecting when one makes a change.  I also think we might have avoided some problems over the summer had we had a more robust set of quick tests.

The current set of quick regression tests, which can be run with regression.py is in the directory examples/regress.

We should discuss what is required, but I would like to see a test of each of these items (and others that you think) that take no more than 3 minutes apiece to run with a few processors on a mac laptop, where I think most of do our development.  

The tests do not need to be astrophysical, in the sense that they are for a physical problem. But they should be geared to making sure that I (one of us) does not break some fundamental aspect of the code, and they should have some kind of result that we can interpret.   For example, the matom test, might very well be a simple shell model.

**Comment by kslong** [comment]
Just to follow up on the message above.  The program regression.py runs all of the .pf files in the directory regress, if it is run without any switches (in an astroconda environment).  It produces runs everything in a directory that depends on the version py82a of the program directory and produces a Summary.txt file that gives some information about what happened.  An example of a successful run is here:

[Summary.txt](https://github.com/agnwinds/python/files/1385051/Summary.txt)

and one that requires investigation because some runs failed is here.

[Summary.txt](https://github.com/agnwinds/python/files/1385052/Summary.txt)

**Comment by jhmatthews** [comment]
I believe I can make a suitable "Case A/B" recombination shell that should be good for this. Will get back to you.

**Comment by kslong** [comment]
@smangham  - Could you also respond by figuring out a very short test of reverb.  As many of us are working on various aspects of the code, we may not fully understand how what we are doing affects this.  What is needed is a very short run that basically validates the reverberation part of the code, and a clear method, possible a little python script that reads the outputs, and produces something (a plot) that tells one that things are basically working.  We are not looking for astrophysics, just code validation, on a run that lasts hopefuly no more than a couple of minutes with a few processors.

**Comment by jhmatthews** [comment]
Here's a first attempt for matoms. balmer_test.pf should be run with fixed temp flag "-f". Will improve this, and include in examples.

 Basic idea should be to reproduce Fig. 2 of Matthews et al. 2015. It does not at the moment (optically thick H alpha maybe?!?), but I will dig out the exact files when I get time. would be good to have a few benchmark case A/B examples, and comparisons to Tardis examples, and a simple model that uses more than just H and He. 

BalmerDecrement.py has docstrings. 

[BalmerDecrement.py.txt](https://github.com/agnwinds/python/files/1399256/BalmerDecrement.py.txt)
[balmer_test.pf.txt](https://github.com/agnwinds/python/files/1399257/balmer_test.pf.txt)

**Comment by jhmatthews** [comment]
I realised that this script uses an updated version of py_progs that I haven't pushed to dev yet - will address this today!

**Comment by Higginbottom** [comment]
Hi,
So I have generated a blazingly fast test of the hydro import and restart bits of the code. Its a totally non-converged, non-physical hydro simulation with just 10x13 cells. It takes about 30s to run through python for two ionisation cycles, then the same to reread it and run with an extra cycle. How do you want the files? 
I attach them in case this is OK. 
[hydro.dat.txt](https://github.com/agnwinds/python/files/1407497/hydro.dat.txt)
[input.pf.txt](https://github.com/agnwinds/python/files/1407499/input.pf.txt)
[input_restart.pf.txt](https://github.com/agnwinds/python/files/1407500/input_restart.pf.txt)

You would need to do

py -z input

to run the first model, then copy input_restart.py to input.py and run

py -z -r input

I'd recommend comparing the py_heatcool.dat files as a test of the code. You would get one after each run, but they would be overwritten, so a test after each step with a stored version of py_heatcool each time

Hope that helps..

Nick

**Comment by kslong** [comment]
@jhmatthews @smangham   As you may have noticed from the discussion in of issue #292 which I just closed, the infrastructure (basically the naming of the subdirectories in examples is complete.  Nick has provided tests for zeus, but we do not have any tests of macro atoms (though James has suggested one above) or reverb, which I believe we need.  Could you please add the tests that you want.  

If it is a test that simply involves a a parameter file and nothing else, then all you need to do is add the .pf file to the regress directory.  Our standard regression routine basically checks how long a routine runs, and prints out the errors, on the theory that if something has gone awry the errors are a good test of this.

For Nick's test of zeus, he provided a separate routine to evaluate the outputs, which in the end says that things have changed or they have not.  If they have changed, then one has to do more investigation.  I believe that is a good approach, especially as we now have a machine independent random number generator, so he can do a very detailed check.

If it is more complicated than this, and James' suggestion is an example because it requires special switches, we may need to figure out an different approach, e.g create a separate directory for a specific test, e.g regress_macro, and put a command file in that directory, e.g. RunRegress, which contains the commands that need to be run in what order, and which calls any checking routine, eg. balmer_test.py.  At the end of the day, we need to return something pretty simple to the screen, to say whether everything seems OK.  James, you checking routine produces a figure but no up-down statement about whether the regression succeeded or failed, which is what I think is needed.  One can produce the figure, and that is a good idea for a second tier check, but yes/no is the first thing we want.

**Comment by jhmatthews** [comment]
I have worked out a reasonable "pass/fail" test of hydrogen macro-atoms in the Case B limit. I am in the process of incorporating it into the travis and regression test suites - this needs a bit of thought as mentioned by Knox above as special flags are needed, so I have a few things to do before it is merged into the main repository. 

I think the test scripts and new structures are looking good @kslong

**Comment by jhmatthews** [comment]
The initial version of the macro-atom test (balmer_test.pf) has been merged into dev by pull request #353 

The changes are documented there, but the bottom line is that this is now in the repository and is run on travis, which took a bit of fiddling. 

It still needs to be incorporated into the regression.py script.

**Comment by kslong** [comment]
@jhmatthews  So I was looking whether we could close this issue today, and I see there is a balmer_test that you have placed in a subdirectory of regression and therir are comments above about incorporating it into the regression.py script.  Does that mean you want certain of the logged outputs, e.g the Macro Atom level emissivities,  compared to earlier runs.   @smangham  There is also an issue of how do we test the regression part of the code,  which I worry about in the sense that I don't know how often this portion of the code will be exercised and so we need to make sure it does not get broken.   The issue in both of these areas (sort of like what affects Nick's hydro runs, is that one would like to avoid byte for byte comparisions that change if the seed changes.

**Comment by kslong** [comment]
While we have not perhaps the very best regression tests, and of course we need to improve, we do have something that is adequate. It seems unlikely that we want to invest more time in this issue, so I am closing this issue.
