### ISSUE TITLE
Setup routines

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#308]
In working on the IO redesign #222 it has become clear that the Setup routines are quite complicated and not very well organized from the point of view of maintenance and updates.  The setup files (setup1.c and setup2) were intended to make python.c easier to read, but they don't really accomplish this task as the input section of python.c is quite long.  Furthermore, the setup include routines like photon_checks which have nothing to do with initialization.   Basically, what I propose to do is to move some parts of what is now in setup1.c and setup2.c into their own routines (e.g a separate file  that contains the code that parses the command line) and to try to rearrange some of the setup routines so that they are more "logically" organized.

**Comment by kslong** [comment]
I have created two new routines parse.c and init.c.   Parse.c contains the code for parsing the command line, and init.c contains some or the pieces of setup and setup1 that did not involve actually reading inputs.  I also moved some of the code that was there that seemed to more appropriately belong in disk.c and photon_gen.c.   As a result the setup routines are shorter and contain fewer routines (but it is not obvious that they are internally logically organized).

**Comment by smangham** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create input guide](https://trello.com/c/2FbwB9vW/2-create-input-guide)

**Comment by smangham** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/VmiWSGHt/8-test)

**Comment by kslong** [comment]
I think we have worked on this over time, and more work on this is simple on-going work so I am closing this now.
