### ISSUE TITLE
Elvis model

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#310]
I would like to propose that we delete the so-called Elvis model.  We really have never used it and it seems to me we never will.  It just adds confusion.

**Comment by jhmatthews** [comment]
Agree. It's a distraction to maintain and obviously we can always dig out the old version from previous commits too.

**Comment by Higginbottom** [comment]
Agreed!

**Comment by kslong** [comment]
I have removed the Elvis model from Python, since are not using it, and it had never really been tested with domains.

The last commit containing the elvis model is e02afab245b8d0ae226b3eff7e144437de529a48
