### ISSUE TITLE
Segmentation fault - after one_line: lumin from lum_lines insufficient

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#311]
Testing associated with issue #290  I have run into a segmentation fault with this .pf file
[original_small.pf.txt](https://github.com/agnwinds/python/files/1441130/original_small.pf.txt)

The last portions of the log are
```
init_freebound: Recycling freebound, storage for NFB (10), need 12 to avoid 
init_freebound: Creating recombination emissivites between 0.000000e+00 and 1.000000e+50
init_freebound: Recycling freebound, storage for NFB (10), need 13 to avoid 
init_freebound: Creating recombination emissivites between 1.000000e+14 and 1.000000e+15
!! xdefine_phot: lum_tot 0.00e+00 lum_star 0.00e+00 lum_disk 9.21e+43 lum_bl 0.00e+00 lum_agn 1.00e+43 lum_wind 2.59e+44
!! xdefine_phot: f_tot 2.64e+44  f_star 0.00e+00   f_disk 5.36e+42   f_bl 0.00e+00   f_agn 6.35e+42 f_wind 2.52e+44   f_matom 0.00e+00   f_kpkt 0.00e+00 
!! xdefine_phot: wind  ff 4.90e+42       fb 1.44e+43   lines 2.47e+44  for freq 1.00e+14 1.00e+15
!! xdefine_phot: star  tstar  0.00e+00   0.00e+00   lum_star 0.00e+00 0.00e+00  1.66e+42 
!! xdefine_phot: disk                               lum_disk 9.21e+43 9.21e+43  1.10e+41 
photon_gen: band 1.00e+14 to 1.00e+15 weight 2.64e+37 nphotons 10000000 ndisk  203232 nwind 9556149 nstar       0 npow 240619 
one_line: lumin from lum_lines insufficient
```

It fails on my mac, whether running in single or multiprocessor mode.  And on linux, with gcc.

**Comment by jhmatthews** [comment]
I've also seen this while testing #301 - I will document how to reproduce it there too.

**Comment by kslong** [comment]
The error occurs at the beginning of ionization cycle1; ionization cycle 0 has been completed.

The segfault is occurring on line 537 of emission.c, at this point in the code:

![screenshot_712](https://user-images.githubusercontent.com/2530901/32406085-b91bf348-c13f-11e7-9063-146ccbb940bc.png)

xlumsum is 0 when it crashes, but xlum is a large number.   Looking at the code the crash seems guaranteed once the error is triggered.  lnmin and lnmax are both 0.

As far as I can determine lin_ptr->pow  is always 0.  

The error is occurring in plasma cell 0.  pdf_x and pdf_y are only 3 elements long, and all of the elements are 0. this is why xlumsum is 0, at the beginning.

**Comment by kslong** [comment]
As a test, I ran the same model but changed the line transfer mode to 3, which should avoid macro atoms, and (sigh) this also produced a segmentation fault.  This time it was at the beginning of the first ionization cycle, and it was in rad_init in wind_updates2d.c line 1108.   This is the code:

![screenshot_713](https://user-images.githubusercontent.com/2530901/32408320-158b6428-c164-11e7-87fe-a291a41ccf10.png)

This should not be happening.  Note that we are using h10_standard78 for the data.  I wonder if in moving things around in the inputs, something has gotten messed up.  And indeed it appears that the atomic data are being read in before we have decided on the line_transfer_mode.   See below:

![screenshot_714](https://user-images.githubusercontent.com/2530901/32408418-74d20ddc-c165-11e7-9fb7-883322ffeb57.png)

This is clearly part of the problem!

**Comment by kslong** [comment]
Updated dev so that the atomic data is read in after the line_transfer_mode, but this did not fix the problem.  With line_transfer_mode set to 3, the program still segfaults.  

Historically, one could switch between a macro atom and a non-macro atom approach without changing the data files.  Apparently, this capability has been lost, possibly because we have not tested this for a long time.  We need to understand what happened. @jhmatthews @Higginbottom   

Note that although both of the issues being tracked here result in segfaults, it is not clear that they are related.

**Comment by kslong** [comment]
The original segfault problem seems to be arising because we are trying to generate line photons in a band that has no lines.  I've added code that should get rid of the segfault, but does not explain why we are trying to generate line photons in this case.

**Comment by kslong** [comment]
The reason this is failing is that limit_lines has not been called and so nlines_min and nlines_max has not been set.  But plasma[n].lum_lines exists.  In cycle 0, no line photons are generated so this does not matter.    The luminosities for the domains are set in xtotal_emission in that cycle, and there the line luminosities are set to a calculation of total bb that has no frequency limits

All of this is pretty bizarre, @jhmatthews   I don't understand why this is only happening with this particular case, and why is was not seen in the fiducial AGN model.  

Note that here is a way to generate the errors quicker than the original_small.pf.  If you can set a break point at the Error which is around line 420 emission.c you can get a better idea what is happening.

[very_small.pf.txt](https://github.com/agnwinds/python/files/1528918/very_small.pf.txt)

**Comment by kslong** [comment]
@jhmatthews  I am not longer able to generate this error using very_small.pf.  Perhaps sufficient fixes were made.  So I have closed the issue.  I guess we should be sure to include the version number in any bug message.
