### ISSUE TITLE
branch philosopy - master vs dev

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#317]
In trying to explain how to install and update python and the data directories, it seems to me we need a specific philosophy for using the master and dev branches.  Currently, we install the master branch of data,  and the dev branch of python.  Right now we do not have a dev branch of the data directory, or a master branch of python, but this appears to me confusing at best.

It seems to me we ought to clarify/synchronize what we mean by the branches and that the philosophy should be similar.  Basically, I think master should be the branch where we have  "released" versions of the code, and "released versions" should include the versions of the codes used for various papers or which add a major capability which we intend others to use.  "dev" should be used for our on-going development of the code.  

How we get from here to there is not completely obvious to me.  I know we can rename the remote dev branc to master, but I suspect we need to pick a point in the dev branch for this. 

If we adopt this philosophy, then I believe our install procedures probably need to be adjusted so that we clone the master branches (and perhaps) make sure there is a local dev branch, which one can retrieve, or alternatively we make sure we have retrieved both.  I believe what should be compiled are the master branch versions.   (Or possible there should be an option to clone the dev branch instead)

I note that  @jhmatthews  and perhaps others  has been pretty good about adding versions of Python.  And there have been some releases of the data repository as well.  That said, it's not entirely clear to me we would be able to recover say the exact state of python for each of our publications.  Also, I note that we do not seem always to have remote tags for each of the released versions; the last remote tag refers to python78, though it looks like git is capable of doing this after the fact.

Anyway, I would appreciate a short discussion of this.

**Comment by jhmatthews** [comment]
I have renamed the "release" branch to "master". At the moment I will keep dev as the main branch, however. Note that in the past I was fairly good about documented releases: https://github.com/agnwinds/python/releases

but I have fallen down over the past year. I suggest in future that we merge releases into master, and update it once again when we next have a reason to define a version (e.g. for Nick's paper). Ideally bugfixes and enhancements would be documented with each release and each release would be tested.

Below is relevant to all programmers if you make use of the release branch so tagging! @mandyhewitt @kslong @Higginbottom @smangham @saultyevil . If anyone has used the release branch I would suggest renaming it locally with ```git branch -m release master``` or you can set up a new master branch locally with 

```
git fetch upstream master
git checkout -b master upstream/master
```

which you can then also push to your forked repository.

Relevant to all programmers if you make use of the release branch so tagging! @mandyhewitt @kslong @Higginbottom @smangham @saultyevil 

I believe this closes the specific github issue.
