### ISSUE TITLE
kpar

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#32]
We have now changed kpar to accommodate parallel operations.  This is a good thing, but it is not on our git hub site, but has to be retrieved by a separate mechanism.  kpar and logging were/are general purpose routines which Knox had created for a lot of different c programs, which was why they were installed separately.  But if we are going to modify them significantly, we probably should just incoporate them directly into python's main distribution.   The alternative, if we think kpar will settle down shortly, would be to create a separate "branch" for kpar.   In any event the latest versions of kpar should be retrievable from git, and the install pages of the git wiki should be updated.

**Comment by jhmatthews** [comment]
Either is fine by me. I think encorporating them into python might be best in general, as we may want to make more usability changes and that would make tracking the versioning easier.

**Comment by kslong** [comment]
I also  think this is  reasonable.  It would simplify installation for others.     I will simply keep my own version of kpar somewhere else for my personal programs.  The only reason I can think not to go this route, is that at some point (when we want to make the release public), we will want to remove the unsupported test routines from the python and py_wind.  If we were doing much in the way of developing c – programs other than python it would be better to keep it all split up.  But this is not an issue for right now and so putting them together in one directory seems reasonable.  Knox

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
It is now encorporated and seems to work.
- log.h no longer needed as prototypes goes into log.h
- makefile edited (are these correct changes?)
  - -lkpar flag removed
  - rdpar, lineio and log added to both python_source and python_objects lists
- as far as I can tell, the other kpar routines are for other things and are not currently used by python.

Note that this means I can improve things in kpar a little now, as before we pass things like verbosity and rank to kpar, whereas now we could just use global variables defined in a log.h header file.

**Comment by kslong** [comment]
I am running into problems with this.  Did you test a clean distribution of everything.  Knox

Knox S. Long
Space Telescope Science Institute

**Comment by kslong** [comment]
I have fixed this problem,  log.o and rdpar.o, were not included in the py_wind objects.  But I find I cannot push back this for some reason.
Knox

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
Ah ok, woops.

It's because I deleted a quick test line I had left in log.c -

if it says this:

```
jamess-imac:python_dev jmatthews$ git push origin dev
To https://github.com/agnwinds/python.git
 ! [rejected]        dev -> dev (non-fast-forward)
error: failed to push some refs to 'https://github.com/agnwinds/python.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

then you need to pull, which will merge your branch with the remote branch. You can then check the changes and push back to github.

**Comment by kslong** [comment]
No, that did not work.  In the end I have tracked the problem down to the fact the version of git on our linux systems is out of date.
Knox

Knox S. Long
Space Telescope Science Institute
