### ISSUE TITLE
Python scripts documentation, etc

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#323]
Our directory for python scripts is largely undocumented.  Some of the scripts have no information at all about what they are for or even who authored them.  Some routines work only in python2.7

Per our conversation today, I have tried to recreate the documentation for the scripts in a directory called docs/pydocs, with a routine write_docs.py which is a wrapper around the standard pydoc routine.  pydoc is not able to run on some of the routines, in part because of the 2.7 issue

I think we need to change this. We should decide (a) which of the routines in py_progs directory are for general use and which are not.  We should remove those which are not (to our private directories).  (b) We should agree on a standard header for those that we want to keep; the one I currently use can be found at the top of import1d.py, but I am not wedded to this.  (c) We should bring the routines we do want to keep up to python3.

Comments?

**Comment by kslong** [comment]
This remains a problem.  I have created an google doc  [here](https://docs.google.com/spreadsheets/d/1NS0-V-6pb86VpJlMO11SaME0msKY7Fw2ojxuGqeaI_c/edit?usp=sharing)  that everyone can use to claim ownership of various routines and to enable us to figure out how to clean this up.

**Comment by jhmatthews** [comment]
Made a decent amount of progress with this on sphinx. Our readthedocs site now has a bunch of the scripts documented using sphinx's autodoc capability: https://agnwinds.readthedocs.io/en/dev/py_progs (remember to clear your cache if needed). 

Docs can easily be added to this using the ```automodule``` command (see the py_progs folder in docs for examples). 

Note our main issue is really that about 4 of us had independently written code to read outputs and we don't have, say, a single nice package to do it all. But it's probably a bit much to solve that and package it up neatly.  At least it's there and documented largely. 

So, I'd be inclined to declare partial success here unless anyone wants to go through and reorganise scripts and so on.

**Comment by kslong** [comment]
This is an ongoing issue, but I see no reason to leave it open.
