### ISSUE TITLE
Free free gaunt factor - frequency integrated vs frequency dependant

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#33]
Whilst the use of gffint (the gaunt factor integrated over frequency for a maxwellian distrubution of electrons) is probably fine for computing the free free luminosity for a wind cell, I now believe we should be using the gffgu (gaunt factor for a given frequency for a maxwellian distribution of electrons) for opacity and also producing individual photons. This might be a little tricky to implement, and the change should be relatively small, since the gaunt factor tends to be of order 1.

**Comment by kslong** [comment]
@Higginbottom  @jhmatthews  This is our oldest bug, but I have no idea whether any of this is relevant anymore.  Can you please, since we are looking at gaunt factors write now, restate this as it applies to the current version of the code.
