### ISSUE TITLE
Power law low frequency cutoff

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#34]
At the moment, the 'normal' power law photon production scheme does not have a low frequency cutoff. This means that in some cases, the low freqeuency tail of a power law can poke up above the low frequency end of the disk spectrum. Not good.
we should either improve the implementation of a broken power law (this is already implemented to a certain extent), or put an automatic feature where the power law ends where it equals the disk.

**Comment by jhmatthews** [comment]
This is addressed by https://github.com/agnwinds/python/commit/7718aac3112f0cc52e828a6f963017f4c528eb54

One can add a power law cutoff in frequency units below the power law index command in the parameter file with the question

```
agn_power_law_cutoff     1e15
```

This is only accessible in 'detailed' mode - by running with the -d flag.
