### ISSUE TITLE
fixed array dimensions in fixed concentrations

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#354]
Trying to fix ion concentrations in the rad-hydro models I note that as written one can only import 10 ion concentrations.
This is because, in fix_concentrations the structure for storing fixed ion concentrations is set to only have 10 elements - i.e. 10 different ions. This is checked later when only the first 10 lines of the concentration file is read in.
I wanted to set all iron to Fe26, and started by making a big file with all ions set to fully ionised and iron set to iron 26. It was ignored because only the first 10 elements were read in.
I next thought I could *just* set Fe26 to 1,  and leave everything else. This ended up setting all the iron densities to NANs and INFs. 
So, the obvious fix is to just set the number of elements in the fixed ion concentrations to something huge, say 1000 which would allow all ions up to something crazy to be set. One could thing of dimensioning it to NION, but this is not great because one would have to ensure that one sets the concentrations of ions in the atomic file, and no more. This makes life fiddly.

Is it OK to just increase the size of the force_con structure to 1000? I'm only asking because I want to be sure there are no other reasons for not doing it. I've done it locally and am running a model. So should see if there is any horrible behaviour.

**Comment by kslong** [comment]
I don’t see any reason not to increase the structure to something like that size.  I think James may have noted this before.

**Comment by Higginbottom** [comment]
fixed by pull #355
