### ISSUE TITLE
very minor bug in p_escape

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#38]
**Brief Description:** There appears to be some erroneous code in p_escape, in lines.c.

**Discussion:** This bug probably shouldn't do anything that bad, but I thought I would flag it up.

``` C
struct lines *pe_line_ptr;
double pe_ne, pe_te, pe_dd, pe_dvds, pe_w, pe_tr;
double pe_escape;

double
p_escape (line_ptr, xplasma)
     struct lines *line_ptr;
     PlasmaPtr xplasma;
{
  double d1, d2, tau, two_level_atom ();
  double escape;
  double ne, te;
  double dd;            /* density of the relevent ion */
  double dvds;
  double w, tr;         /* the radiative weight, and radiation tempeature */

//Populate variable from previous calling structure
  ne = xplasma->ne;
  te = xplasma->t_e;
  tr = xplasma->t_e;      <-------------------------------bug 1
  w = xplasma->w;
  dd = xplasma->density[line_ptr->nion];
  dvds = wmain[xplasma->nwind].dvds_ave;
// Band-aid to prevent divide by zero in calculation of tau below
  if (dvds <= 0.0)
    {
      Error ("Warning: p_escape: dvds <=0 \n");
      return (0.0);
    }
  if (pe_line_ptr != line_ptr
      || pe_ne != ne
      || pe_te != te
      || pe_dd != dd || pe_dvds != dvds || pe_w != w || pe_tr != tr)
    {
...
```

**bug 1** 

tr should be set to xplasma->t_r, not xplasma->t_e.

**bug 2** 

the variables pe_te, pe_ne... were introduced as a way of ensuring that when p_escape was called again with identical variables it wouldn't redo the calculation. They way I understand it, whenever it's getting called then pe_te, pe_ne... aren't assigned, so the if loop is always entered. 

I think this means that we get by a more serious bug which would have occurred if bug B had been done correctly which is that bug A would have had an effect because we would not have recalculated in situations where t_r was different but the other variables were...although in practice this is probably unlikely. 

**Priority:** Not urgent, unless I've misunderstood this, but we should fix.

**Comment by kslong** [comment]
I agree, James, that the first of these seems to be an obvious error.

However, I do not believe the second one is an error, unless I misunderstand James' concern.

Here is the entire if statement that is the heart of the routine

  if (pe_line_ptr != line_ptr
      || pe_ne != ne
      || pe_te != te
      || pe_dd != dd || pe_dvds != dvds || pe_w != w || pe_tr != tr)
    {

```
  if (line_ptr->macro_info == 1 && geo.rt_mode == 2
      && geo.macro_simple == 0)
    {
      // macro atom case SS
      d1 = den_config (xplasma, line_ptr->nconfigl);
      d2 = den_config (xplasma, line_ptr->nconfigu);
    }
  else
    {
      two_level_atom (line_ptr, xplasma, &d1, &d2);
    }

  tau = (d1 - line_ptr->gl / line_ptr->gu * d2);
  tau *= PI_E2_OVER_M * line_ptr->f / line_ptr->freq / dvds;

  if (tau < 1e-6)
    escape = 1.;
  else if (tau < 10.0)
    escape = (1. - exp (-tau)) / tau;
  else
    escape = 1. / tau;



  pe_line_ptr = line_ptr;
  pe_ne = ne;
  pe_te = te;
  pe_dd = dd;
  pe_dvds = dvds;
  pe_w = w;
  pe_tr = tr;

  pe_escape = escape;
}
```

pe_te, etc are external variables so they keep their values after the subroutine is exited.   They my be undefined at the beginning of the program,
but they get defined the first time through the routine.    Do you agree, James?

If so, James, I suggest you fix bug 1, and then close this.

Note that it is quite possible that we should not be going to all of the trouble of holding the old values.  Nearly all of the time one of the variables needed to calculate p_escape is going to changed.  When I wrote this, I was concerned about the possibility of trapped photons, which took a long time to escape a very small region.   But I don;'t think we have noticed this problem, and I suspect this routine is never important in the overall run time.

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
Ah yes, silly me. Agreed, and closed, and I've also fixed the same error which came up in the scattering fractions function.

**Comment by kslong** [comment]
It is good though to fix these simple errors, as we see them, before one comes back and bites.

Knox S. Long
Space Telescope Science Institute
