### ISSUE TITLE
Recording electron scatters in each plasma cell

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#383]
Currently there are variables in the plasma domain that is supposed to identify the number of electrons scatters or resonant scatter that are occurring in a cell.  

There are significant problems with this:

-As currently written the routines simple count the number of times that a photon has nres of a given value.  But they do not, check to see whether a scatter has occurred
- The current check is whether nres is less than 0, but nres less than 0 can occur for either es or ff, which is also treated as a scattering process in Python in simle mode
- Furthermore, there are differences in the problem in macro atom and simple mode, because in macro atom mode photoionization is treated as a scattering process (whereas in simple mode photoionization is treated just as absorption. 
- Finally, it is not obvious where these plasma values are zeroed, e.g after each ionization cycle

If we need these plasma variables then the right place to increment them is when a photon is actually scattered, which occurs in the routine scatter in resonate.c.  For the time being, I am actually going to comment out the lines in photon2d (around 675) where the values are accumulated (with a reference to this issue, but @Higginbottom  and @jhmatthews  I need to know whether we think we should keep track of these two variables 

```
  int nscat_es;                 /* The number of electrons scatters in the cell */
  int nscat_res;                /* The number of resonant line scatters in the cell */
```
are needed, and if they are needed what we mean by them, e.g the number an ionization cycle.

**Comment by kslong** [comment]
@Higginbottom @jhmatthews - I asked about this some time ago, but there was no response.  We at least need to decide what we want to do here.

**Comment by Higginbottom** [comment]
I guess they could have some utility - in order to work out where the wind is optically thick - but they aren't variables I routinely use...

**Comment by smangham** [comment]
For the purposes of release, we could simply remove these. If they would be useful later, then it wouldn't be *much* more work to add them back in from scratch.

**Comment by kslong** [comment]
Either of these approaches is fine.  Note that I assigned this to be a Release issue, but it's not really as no one sees this.

**Comment by smangham** [comment]
Yeah, though it'll break windsave backward compatibility so we should do it before release. I think we'll probably have to be a bit tighter about windsave compatibility post-release.

**Comment by kslong** [comment]
We lose backward compatibility for windsave every time someone changes one of the structures,  and that is going to happen from time to time no matter what we do.  The only thing we can do is make sure that windsave2table (and py_wind) produce nice errors when they fail to read a windsave file in properly.

**Comment by jhmatthews** [comment]
This concerns the nscat values in each _plasma_ cell rather than per photon. While this variable isn't used often, we think this should be fixed, i.e.:
* the nscat_es and nscat_res variables should be zeroed correctly
* the nscat_es variable should only be incremented if nres is right for Thomson scattering (i.e. it must exclude free-free)

**Comment by kslong** [comment]
This has been corrected. The variables are now properly intialized in wind_update, and nscat_es refers only to electron scattering (ff scatters are not counted.)
