### ISSUE TITLE
Treatment of simple atoms in macro-atom mode

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#394]
At present as documented under issue #391 the spectrum produced by python run  in macro-atom mode for a simple ion (one without all of the atomic data needed to fully describe a macro-atom)  differs significantly from the spectrum produced in when the radiative transfer is carried out using simple-mode radiative transfer because recombination is not accounted for in the same way.   It would be highly desirable to correct this, both for comparison with runs using the two-level approach and because it will indicate when we should be adopting a correct macro-atom approach.  

@jhmatthews  and @ssim  have identified a way to fix this problem.  This issue is separate from that described in #391 and the point of opening this as a separate issue is to allow fixes to proceed indepenently.

**Comment by jhmatthews** [comment]
This is documented on evernote and copied here:

**Aim**
To alter how "simple macro atom” mode treats bf absorption. Specific aim is to make it more like the original “simple implementation”. We think this means:
* avoid assumption of “detailed balance” in interactions with ionisation energy pool
* instead, don’t try to directly impose energy balance in ionisation pool by using thermal balance

**Procedure**
Whenever a packet interacts with a “simple-bf-macro atom” we pay attention to only the heating and cooling. In particular, this will means that the rates of all bf-emission will be governed by the emissivity of the bound-free process.

What this means is that we’ve basically made two changes to the code for ionization cycles: 

1. whenever a k-packet is eliminated via a bf-channel of a simple macro atom (simulating energy flow from the k-packet pool to the radiation pool), we have that packet carry additional energy corresponding to the required ionization energy for that particular bf process. I.e. we boost the weight of the packet by a factor of nu / (nu - nu_0) = total energy carried by photons in packet / energy supplied to photons in packet from the thermal pool
2. whenever an r-packet is “absorbed” by a simple macro atom bf-process we track explicitly only the flow of energy to the thermal pool. This means we take the contribution of the absorption to heating only: i.e. we downright the packet energy by a factor (nu - n0) / nu.

Also need to make two changes for spectral cycles:
1. in the spectral cycles interactions with simple bf macro now kill the photon (interaction with bb simple macro proceed as before)
2. in the spectral cycles k-packets produced for k-packet emission are also unweighted as above

**Comment by jhmatthews** [comment]
The current state of affairs is that we have implemented the above procedure in the branch https://github.com/agnwinds/python/tree/bf_simple_alternate but there are outstanding issues. 

The main issue is that the spectrum produced in the spectral cycles does not seem to match that produced in the ionization cycles. Here is an example of the problem:
![bf_simple_comp](https://user-images.githubusercontent.com/3007249/43594101-4a5e1ece-9671-11e8-9707-f9ab9e29b8e2.png)

Here is the parameter file used to produce it: 
[star_alternate.pf.txt](https://github.com/agnwinds/python/files/2254089/star_alternate.pf.txt)

One should run this file with the bf_simple_alternate branch.

**Comment by jhmatthews** [comment]
The above issue has now been fixed by Stuart and I've run some tests of the scheme in general. My tests are described here: https://www.evernote.com/l/AS-uZxLo4jpOHa9WkV3lP1a5uc8QD8UEXOY

Deciding on a successful test here is difficult, but probably this can be merged to dev soon.

**Comment by jhmatthews** [comment]
This has been closed by #433.
