### ISSUE TITLE
Spectrum output does not include decimals in headers

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#398]
Ugh, an infuriating morning of trying to work out why the ascii read routines in astropy were not correctly reading in my spectral file from the rad hydro spectra revealed....

ascii.read can't cope when two columns have the same name.
if you have spectra at say 88 and 88.5 degrees then they both get written out into the .spec file with the name A88P0.50

So the spectrum has two identical column names.

We either need to stop users inputting fractional angles, or think of a header name that allows this to be output. The obvious choice is to allow one or two decimals in the angle so, 

    sprintf (xxspec[n].name, "A%04.1f", angle[n - MSPEC]);

in spectrum.c 

We really just have to decide how many decimals we want to allow....

**Comment by kslong** [comment]
“I feel your pain!”     One might hope that astropy would add a suffix to the second time a column name appears, as it does when you join to tables.

It should be fairly rare that we end up with two columns the same though, so here is what you can do.  Read the file in as a normal file with standard python, check for a duplicate name in the header line, and modify it.  Then dump the updated file back to disk.  Then you should be able to read it with astropy.    There are other possibilities, all similarly klugey.

My feeling is we should lead the Python code the same, even though it seems our need to use fractional degrees for the angle seems like it would be fairly rare.

**Comment by kslong** [comment]
Having discussed this with @Higginbottom we have decided to close this.  If it should turn out that we want to make note of fractional angles, then we could add code which in the even that one gave an angle like 51.3 degrees, recognized this and modified the name of the output column.  As a general run we agree that we do not want to print out every angle with a decimal point.
