### ISSUE TITLE
py -h requires updates for extra diagnostics

### ISSUE THREAD

**Issue by mandyhewitt** [sirocco-rt/sirocco#405]
Currently python help command does not give information about how to use the extra diagnostics option. The help code needs to be updated to advise how extra diagnostic options work. Currently we are aware that -d is undocumented however other options may exist.

Current output:

_$ py -h
This program simulates radiative transfer in a (biconical) CV, YSO, quasar or (spherical) stellar wind 
	Usage:  py [-h] [-r] [-t time_max] xxx  or simply py 
	where xxx is the rootname or full name of a parameter file, e. g. test.pf 
	and the switches have the following meanings 
	-h 	to ge this help message 
	-r 	restart a run of the progarm reading the file xxx.windsave 
	-e change the maximum number of errors before quit- don't do this unless you understand	the consequences! 
	-t time_max	limit the total time to approximately time_max seconds.  Note that the program checks for this limit somewhat infrequently, usually at the ends of cycles, because it is attempting to save the program outputs so that the program can be restarted with 
		-r if that is desired. 
	-v n	controls the amount of print out.  The default is 4.  Larger numbers increase  
		the amount printed; smaller numbers decrease it.   
   --dry-run	Create a new .pf file and stop 
   --version	print out python version, commit hash and if there were files with uncommitted 
                changes 
      --rseed   set the random number seed to be time based, rather than fixed. 
(Certain other switches exist but these are largely diagnostic, or for special cases) 
If one simply types py or pyZZ where ZZ is the version number, one is queried for a name 
of the parameter file.__

**Comment by kslong** [comment]
@mandyhewitt   You may want to check what I did here but I have made some modifications to the help message and am closing this issue.
