### ISSUE TITLE
Python script to create graphs and various plots

### ISSUE THREAD

**Issue by mandyhewitt** [sirocco-rt/sirocco#406]
It would be beneficial to have a single python script which could plot graphs quickly from a number of Python output run files e.g. linear vs log wind spectra. This would enable quicker testing.

It would be anticipated that the script could capture a number of ascii files and plot various data based on user prompts or an input file.

An example of python commands is given below:
[input_script.txt](https://github.com/agnwinds/python/files/2257633/input_script.txt)

It would be good if it could be easily prompted for filenames etc

**Comment by jhmatthews** [comment]
@mandyhewitt just a note that there are some scripts already. Namely:

py_read_output.py 
py_plot_output.py
py_plot_util.py

Documentation in $PYTHON/docs/pydocs/ and on the wiki here: https://github.com/agnwinds/python/wiki/reading-and-processing-outputs

**Comment by kslong** [comment]
I've added information about two additional routines, plot_spec.py and plot_tot.py  on the wiki page James mentioned above.  These routines run directly from the command line.

**Comment by jhmatthews** [comment]
One more thing here, is that it would probably be useful to have a jupyter-notebook as a tutorial - these can now be hosted on github and render inline, so it's the perfect format for a tutorial really. I think a subfolder in the docs directory would be neat. 

(see an example here: https://github.com/CRPropa/CRPropa3-notebooks/)

**Comment by kslong** [comment]
While this would certainly be a good thing to do, it seems unlikely that anyone has the time or inclination to work on this, and so I am closing this issue.  I've added a label documentation to indicate that it is something that might be revisited when we think about a formal public release.
