### ISSUE TITLE
Python speed-up

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#408]
Speeding up Python by even a factor of 2 would help us to be able to work faster.  We have not profiled Python in a long time, and we have not considered generically whether there are ways to speed up Python more generically, e.g by trading storage for speed.  This issue is intended to capture efforts in this regard.

In a general sense what needs to be done is to run a profiler on the code, e.g gprof, and see if the parts of the code we think should dominate are actually dominating, or if something we did not expect comes out.  

We should also think about strategies that would speed the program up without loss of final accuracy.

One possibility that ksl mentioned was increasing the number of photons as one progressed through ionization cycles.  In principle one could start with 1e5 photons in the first cycle and arithmetically increase to say 1e7 at cycle 10 as one approached the end of the cycle.  This is very aggressive but if this turned out to be just as good as running 1e7 photons for calculating the ionization, then one could do the ionization cycles in 1/4 of the time (assuming photon generation and transfer was the bulk of the time.)  If you thought that you could go from 1e6 to 1e7, a factor of 10, you would still get a factor of 2 speed improvement.

Another general possibility in this regard would be to try to start the program off closer to where it was going to come out, e.g allow the electron temperature to move more rapidly in the early phases of the calculation than earlier on.

**Comment by kslong** [comment]
What ever we do needs to be generic so that it can accommodate any number of cycles.  For this reason I would try pure logarithmic first.

I could imagine holding the first couple of cycles constant and the last few constant, … but I think one would need to be clever, and show that it helps.

Regarding all of this, I could also imagine allowing the temperature to change more rapidly early on than our current fixed amount.

**Comment by saultyevil** [comment]
Since I've merged this code into Py83, I'm going to close this issue. We can reopen it if I've programmed something disastrous.
