### ISSUE TITLE
single domain hydro no longer reads in temperature correctly

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#415]
For reasons I have not yet worked out, the *single* domain hydro code no longer reads in a correct temperature, and other things seem to go wrong. I believe this happened with commit dc513899394cb928d03a76f549609461c58f2eb8 which did a lot of fiddling round with geo.rmin.

There is a most peculiar scaling factor that seems to have appeared, might be some kind of indexing error. 

Oddly, it seems to work fine with multiple domains. 

if you want to reproduce, and it is complicated, then run

[py_hydro.pf.txt](https://github.com/agnwinds/python/files/2270071/py_hydro.pf.txt)

with this hdf file

[hdf000002nsh_dw33.txt](https://github.com/agnwinds/python/files/2270073/hdf000002nsh_dw33.txt)

and the company py82h -z py_hydro

then open up the resulting py_heatcool.dat and compare it on a cell by cell basis.

Density is fine...

Temperature is odd..

it works fine at commit c4f96fe0f6fde73a27fc1b80db3a2bbc891ff8c8

baffled at the moment.....

**Comment by Higginbottom** [comment]
OK, so that particular error was due to a couple of lines that had been erroneously deleted in hydro_import.c around line 100

geo.rmax and geo.rmax_sq were no longer being defined. 

This was bad...

This would have been easily seen if the regression tests had been run - since the number of 

spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model

errors went from 700 to 7000.....

**Comment by kslong** [comment]
Maybe, but I think something else is odd then, because geo.rmax should be calculated after all domains are read in.  It should not be necessary to add a special case for hydro.  Anything that involved geo.rmax within the hydro read should be carried out with zdom[ndom].rmax

**Comment by Higginbottom** [comment]
OK, so the problem is that in the hydro mode, it looks like geo.rmax isn't set unless it is set in get_hydro_wind_params
Or at least thats what it looks like....

**Comment by Higginbottom** [comment]
Update -
The issue here is that the intention was that when one reads in a hydro model - the size of the domain is set by the input data, rather than the wind.radmax parameter - which is essentially defunct in this case. 
When KSL commented out the lines that reset geo.rmax to the outer radius of the input model, it just used the value of wind.radmax which was set well inside the model - because I never worry about that parameter.
Its clearly not ideal, and should be fixed. Indeed the code that reads in the initial parameters in get_wind_params (in setup_domains.c) is a bit dodgy, with a slew of XXX comments.
Definitely a bit of code to discuss...

**Comment by kslong** [comment]
Right.  geo.rmax is the max value in all of the domains, and it is calculated once all of the domains have been read in by looking at zdom[].rmax in the domain pointer.  So what needs to happen is that zdom[ndom].rmax is initialized properly in the routines that read in the hydro model.  

Otherwise, one will not be able to put a domain outside of the hydro domain.

**Comment by Higginbottom** [comment]
Are you sure it is decided *after* they are all read in? It looks like it is set as they are read in.
If it *was* after, then all would be well. However, what happens in get_wind_parameters is that the wind_radmax parameter is read, and compared to the current value of geo.rmax. If it is larger then geo.rmax is reset. Then all the rest of the wind parameters is read in. In the case of hydro, if the actual wind is bigger than wind_radmax, then that is increased, but that is after the assignment of geo.rmax. Hence the problem. 

Is there a problem with having the test 
  
  if ((ndom == 0) || (zdom[ndom].rmax > geo.rmax))

after all the wind parameters are read in?

If there is, then we have to force the user to set wind_radmax correctly before reading in the data. 

I believe this is also a problem with the other model import code - since this also sets zdom[ndom].rmax *after* geo.rmax is set. Its fine if you set wind_radmax correctly, but if you didn't, then because the routines like spherical_make_grid_import don't reset geo.rmax after they reset zdom[ndom].rmax you could lose lots of photons like I was doing after the chance to hydro import.

**Comment by kslong** [comment]
@Higginbottom  - Can you check to see if this problem is resolved?

**Comment by Higginbottom** [comment]
This looks to be fine now…

Nick
