### ISSUE TITLE
Initialising the temperature of the wind

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#42]
Having just confused myself by trying to get a constant temperature for the thin shell, I thought it was worth posting this 'feature' for discussion

When one sets the initial temperature of the wind, using the keyword wind.t.init in the parameter file, this gets set to geo.twind.

When the wind is initialised, this gets assigned to t_r in all cells.

Then, the normal behaviour is to set t_e to 0.9x this value (lucy guess).

This seems a bit counter intuitive - for my money, I feel that when I'm setting the wind temperature, I want to be setting the electron temperature, not the temperature of the radiation field. This would be pretty simple to change - just set t_e to geo.twind, and by all means set t_r to t_e/0.9 - just to give it a value.

Thoughts?

Nick

**Comment by kslong** [comment]
I guess I don't understand your concern here.  

The original rationale for this was to duplicate more or less the set up and nomenclature from some of Leon's early papers.  The radiative temperature is something one can guess from the sources of radiation, but the electron temperature is harder to guess.  I believe this may be the way, all of our models start out, i.e by setting the electron temperature to 0.9 of the electron temperature.

 So in that sense, our current choice is not counterintuitive.

You must have a "use case" in mind, that makes counterintuitive to you.  Perhaps you could explain more fully.

**Comment by Higginbottom** [comment]
Ah, I see.
I'm coming from the point of view of the cases where I'm using temperatures from a zeus file to initialise the wind, or in the case where I am hacking the wind to have a constant temperature.
I realise this is a bit niche. Perhaps the real question here is whether we need to implement some kind of mode whereby the user can force the code to keep the wind at a constant temperature without having to fiddle with the code.

**Comment by kslong** [comment]
I'm not opposed, but I think you need to describe more completely the "use case" and why it is important to have it.

Knox S. Long
Space Telescope Science Institute

**Comment by Higginbottom** [comment]
The primary 'use case' is when one wants to fix the temperature of the wind. One needs to hack the code to do this, by disabling calc_te in the ionization, but one also has to set the wind temperature to what you want /0.9, so that the te=tr/0.9 means you get what you want.
This is slightly annoying, but compared to having to hack the code to make the temperature fixed it is minor.
I think I'll leave it as it is - apart from a slight change to the code where I set the wind temperature according to the temperature from a zeus run. I'll just set t_r=temp/0.9, so the next line sets the temperature to what I want.
