### ISSUE TITLE
Review of "homologous model"

### ISSUE THREAD

**Issue by ssim** [sirocco-rt/sirocco#422]
Review of issues associated with parameters of homologous model.

Model to be tried for comparison to Vogl SN simulations with "new" Tardis.

...update (5 Oct 2018) - currently trying to run the homologous model I used for the TARDIS paper in 2014 simply produces a segmentation fault. Will need to track down why...

**Comment by jhmatthews** [comment]
In November Stuart and I succeeded in getting a run that roughly matches Vogl et al. 2018. Details on Evernote and  a spectrum. @ssim might be good if you could review the homologous model params and check the tardis comparison model runs, then we can probably close this issue.

**Comment by kslong** [comment]
There is no specific need for this issue at this time.
