### ISSUE TITLE
Output to screen from define_phot with banding

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#424]
When we use banding for photon generation, one gets *a lot* of information printed to screen from !! xdefine_phot:. While you probably want a print out for each band, we seem to get two for each band because we call populate_bands, which calls xdefine_phot for each band to determine which photons to put where, and then xdefine_phot gets called again once the bands have been populated to **actually** define the photons. 

I propose that a "mode" variable is passed to xdefine_phot to tell it whether to print out the information or not. That way the information is only printed out when the actual photon_gen is taking place, not when the preparation of bands is being done. 

All in favour?

**Comment by kslong** [comment]
I disagree.  Use Log_silent instead.  One can force it to the screen by changing the verbosity.  I think we should avoid using modes unless they are absolutely necessary.

**Comment by Higginbottom** [comment]
I think that the information is really useful, and one would almost always want to see it. So I'm with James on this - in principle at least. If there is a way of doing it without a mode then all the better, but just one set of outputs in the log file would be best...

**Comment by kslong** [comment]
Then we need to discuss this.  If you want to see it, then you should argue we need to see it.  If most of us do not, then it should we should use Log_silent, which just means you have to look in the log file.  Modes were intended for diagnostics that produce special diagnostics or approaches.  I note that the photon diagnostic messages are set up so they are eary to grep out of the larger log file.   I generally agree with James to the extent that I think we are printing too much to the screen.

**Comment by jhmatthews** [comment]
We decided in the telecon that my approach was sensible, so I've fixed this and merged into dev - a late surge which sees me top the leaderboard (made by me...) for the week 😄 🍾
