### ISSUE TITLE
Improving treatment of the ends of a CDF

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#428]
When we work out a CDF for emission, we work out the gradients at each point, based upon the points in the CDF around each point. We then use these gradients to improve our guess for exactly what frequency (for example) we sample in a given bin. 
The way that the ends are dealt with is not great - we should really try to come up with an extrapolation rather than just fill in the same gradients for the second and penultimate cells into the first and last cells.
This is very much a second order fix (using gradients is the first order fix) but it was logged as an XXX in CDF.c.

**Comment by saultyevil** [comment]
@Higginbottom is this related to the changes you recently merged in? Could we close this issue?

**Comment by Higginbottom** [comment]
Yup - this is indeed partially addressed by pull #846
