### ISSUE TITLE
Indenting woes

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#430]
Indenting is causing a problem with git comparisons.  We have been discussing this as part of issue #318 but ksl believe this merits its own discussion, since #318 is entitled Parameter Naming conventions.

The status of this issue has mostly been worked out by @saultyevil .  There is a command in the make file, which we probably all should have been running. This indents all of the .c and .h files, but if you run it on dev right now it will cause large numbers of changes to appear.  This is a problem for comparison.

One way out would be if on github one could cause the diffs to ignore white spaces, but it is not obvious how to get that to work, see:

https://blog.github.com/2018-05-01-ignore-white-space-in-code-review/

but ksl has not found how to get this to work.

Alternatively, it appears one can add ?w=1 to the url for a diff and this is supposed to get rid of the whitespace differences.

Locally, git does have the capability to ignore white spaces when making a diff

Clearly we need to understand how we want to proceed here.

**Comment by saultyevil** [comment]
It's also possible to merge whilst ignoring whitespace, `git merge -Xignore-space-change`. I believe you can use git merge and then git mergetool and whitespace should still be ignored, but I haven't tested it myself.

**Comment by kslong** [comment]
Having heard of no problems, I am assuming the indenting issue is solved.
