### ISSUE TITLE
Exiting due to errors

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#439]
Whenever we exit from Python due to an error, we generally exit in the standard C way using the `exit` function, with the error code 0. Usually, exiting with 0 indicates that the program has exited after running successfully with no errors. But in Python, exiting with 0 means both a successful and unsuccessful exit. This is slightly confusing to users and very confusing to `mpirun`.

`mpirun` will kill all processes if it notices that a process has exited with a non-zero exit status. However, as errors in Python exit with 0, `mpirun` doesn't detect that a process has exited due to an error and assumes everything is fine. This eventually leads to communication problems, such as causing Python to deadlock. It can also happen that Python appears to exit correctly, but MPI processes still continue to run in the background hogging resources; which is bad manners on a shared machine.

A fix for this problem would be to use a wrapper function to exit from Python depending on if the code has been compiled with `-D MPI_ON` or not. The most basic approach could look something like this,

```c
/*
 * Note: error_code should be positive and non-zero.
 */

void Exit (int error_code)
{
  #ifdef MPI_ON
    Log ("MPI Exit: MPI is exiting all processes with error code %i\n",
         error_code);
    MPI_Abort (MPI_COMM_WORLD, error_code);
  #else
    Log ("Exit: Python is exiting with error code %i\n", error_code);
    exit (error_code);
  #endif
}
```

But, it seems sensible to output more information than just aborting all the MPI processes. For example, JM and KSL proposed that Python should first flush the log and then output an error report to the logfile and exiting MPI more gracefully with `MPI_Finailze`. 

This should have the benefit of making error checking simpler and more robust, as well as avoiding any confusing exits in multiprocessor mode.

**Comment by kslong** [comment]
@saultyevil  There are problems with your exit function when python is invoked with command line options that are supposed to to print out a little information and stop, e.g

py -h
py --version

and I suspect when one decides to abort in a interactive read in of the parameters.

Because we have gone through Exit these produce extra spurious outputs that we do not want.  In these case, we need to be able to silently close things off, not print out any error summary, etc.  It's possible we should use Exit(0) for this kind of close, and Exit(non-zero) for all of the others.  At any rate I think you have a bit more work to do on this.  Sorry!

**Comment by saultyevil** [comment]
I agree, exiting with return code 0 should indicate that Python ran successfully without any major errors. It should be easy enough to catch these cases with just an extra bit of logic so we don't print an error summary when error_code is 0. Unfortunately, if we compile with -DMPI_ON, we wouldn't be able to suppress the output from MPI_Abort. But if we really want to suppress all output like that, I think we can assume that when someone is using py -h or running in interactive mode, they are most likely running one MPI task, so we *might* be able to get away with using the standard library exit in those situations.

We should also think about errors and non-zero exits a bit harder, i.e. appropriate error codes to give to the wrapper function.

**Comment by kslong** [comment]
I tried this, I believe, and it seemed like everything just hung.   I don't remember this happening in the past.  Is -DMPI_ON new?  

My understanding, based on spending a little time reading about this,  is that MPI_Abort really is intended for an abnormal termination, which these situations are not.  Possibly one needs to make some use of MPI_Finalize and then exit.

**Comment by saultyevil** [comment]
No, -DMPI_ON is the conditional compilation flag we use to build with MPI code. 

Hmm, using `exit (0)` instead seemed to work for me. But, using MPI_Finalize to allow OpenMPI to clean up before calling exit (0) seems to be the proper way to exit in situations such as py -h.

**Comment by saultyevil** [comment]
I noticed today that py_wind and windsave2table were both behaving oddly when exiting via the new wrapper function. Essentially, as neither programs call MPI_Init, mpirun complains that MPI was never initialised. The program would still exit, but with some unnecessary information and errors printed to screen.

Since both programs are not designed or meant to be run with MPI in mind, I have reverted back to the standard exit function for these programs. I've also made a few changes to fix compiler warnings in py_wind and windsave2table as well! 

I'm currently running the regression tests to make sure I didn't break anything in Python, so I will merge the changes in when that is done!

**Comment by kslong** [comment]
@saultyevil   What is the status of this. Can it be closed?  Note that I have seen an example, e.g. when py -h was invoked, that Exit(0) was called when the comment right beside it said that the normal exit(0) should be used.  I have fixed this, but I wonder what happened.  If we are happy with the function Exit(0) then I guess I favor going ahead and closing this, even as we continue to adjust when exactly we should use exit(0) and when we use Exit(0).

**Comment by saultyevil** [comment]
Yeah, I think we can close this issue now. We have a better idea of when we should use `Exit` or `exit`. All that is really left to do is the switch `Exit` and `exit` in some places, and possible change exit codes.

**Comment by kslong** [comment]
Then you should go ahead and close it, and get credit.
