### ISSUE TITLE
On restart, one cannot add a disk radiation to a model if it was not there originally

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#44]
In running the Proga models, Nick wanted to try a case where he calculated the ionization with only a central component.  But for spectra he wanted to add disk emission.  So he tried adding a disk component to a parameter file and restarting the model for additional spectral cycles.  He found that although the model ran, no disk photons were produced.  Knox confirmed this with some very simple SV models.  

Some checking with DDD shows that the problem arises in python.c because when the old wind file is read in around line 565, geo.wind_mdot is read in as zero.  [I do not really know why this is; geo is written out by the first program and read in in this program.  One would have thought it would have been whatever I set it to in the first .pf file and it was not that.) Furthermore, reading geo.disk_mdot is skipped (because of statement at line 868).

Later on there is a check to see whether whether, disk_mdot is zero, and if it is then disk radiation is turned off.

What should we do about this?  The software is a bit of a mess here.  The intent was when you read in an old windfile to prevent you from doing anything silly, like changing the wind dimensions.  But this means that the python code is complicated.  It looks like a solution is to reexamine which variables are read in from the .pf file, and adjust python.c accordingly.  

We need to document this well, because this is an area of the code that will continue to change as we add new features.

**Comment by jhmatthews** [comment]
Closed by #139 

If you want to do this, you have to specify the disk properties but turn disk radiation off. It's a fairly obscure thing to want to do anyway, but this works!
