### ISSUE TITLE
qromb failing with negative AGN.bremsstrahlung_alpha

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#443]
I've been trying to run a modified standard AGN model using Bremsstrahlung radiation. The default value of AGN.bremsstrahlung_alpha is -0.2. However, using a negative value of alpha causes Python to grind to a halt and qromb to report that it has reached the maximum number of steps during photon generation. It seems to be failing at initialising the Bremsstrahlung CDF, specifically lines 174-176 in brem.c, or when qromb is integrating brem_d, i.e. lines 206 and 212 in brem.c.

A bit of further investigation into qromb made it look like that something odd is happening in polint. More specifically that the variables dss and ss, which control qromb's exit criterion, are both NaN.

I've attached two parameters files I've been playing around with. I've also also tried a negative value of AGN.bremsstrahlung_alpha for the hydro regression test to the same effect.

I don't know much about this part of Python, so hopefully I haven't missed anything obvious! 

[qDNe.pf.txt](https://github.com/agnwinds/python/files/2534747/qDNe.pf.txt)
[xagn.pf.txt](https://github.com/agnwinds/python/files/2534756/xagn.pf.txt)

**Comment by Higginbottom** [comment]
I’ll take a look - this should certainly not be happening…..

Nick

**Comment by Higginbottom** [comment]
Both run fine for me!
Are you sure you have made clean after any modes to the code?

**Comment by Higginbottom** [comment]
Oh wait - was using py82e - re-running on the latest 82i. Its certainly *much* slower to start....
Hmmmmm

**Comment by Higginbottom** [comment]
OK, I see the failure. Now running with older versions of python to find the error...

**Comment by Higginbottom** [comment]
Right - I see whats going on. 
The brem part of the code is modelled on the blackbody part of the code. Part of the way this works is to integrate between 0 and infinity to work out the total emissivity of the blackbody (or in this case brem) so we can work out where in the cdf we are. 
If we have a negative power of nu, then of course we have an infinity at the nu=0 end of the integral. so this approach only works for positive or zero power of nu. 
If you really need to have negative alpha - I need to work out how to deal with this....
Let me know. If it is not important, I'll fix it but slow time.
If you really need it - then I'll do it now!
N

**Comment by saultyevil** [comment]
Ah, ok. So I'm still a bit confused why the default value of alpha is negative.. did bremsstrahlung used to be handled differently? 

I think for now, at least, I can just skirt around this issue and use positive alphas!
Cheers!

**Comment by Higginbottom** [comment]
an excellent question. I'll change the default to +0.2!!
So at least if people use the default it won't crash...
But this does need fixing....

**Comment by Higginbottom** [comment]
Ah, it is noted that the cloudy form of brem uses alpha -0.2 - optically thin pure hydrogen emission
I've only ever used zero, to match xstar, which Blondin used - thermal bremsstrahlung

I should really fix this...  seems like all I need to do is set a reasonable number for the min frequency 
in the qromb stuff. say the min frequency of photons we are generating, or ALPHAMIN/10. if the min frequency isn't low enough. watch this space

**Comment by Higginbottom** [comment]
I think this is fixed.
What I did was to replace the 0.0 in lines like

cdf_brem_tot = qromb (brem_d, 0.0, BREM_ALPHABIG, 1e-8);

with

cdf_brem_tot = qromb (brem_d, brem_alpha_tiny, BREM_ALPHABIG, 1e-8);

where brem_alpha_tiny is set to 

  brem_alpha_tiny = H * xband.f1[0] / BOLTZMANN / geo.brem_temp;

  if (brem_alpha_tiny > BREM_ALPHAMIN)
    brem_alpha_tiny = BREM_ALPHAMIN / 10.;

i.e. it is set to the start of the lowest frequency band *or* 10% of BREM_ALPHAMIN - the point in the BB spectrum where one is in the power law - so the CDF is not required.
