### ISSUE TITLE
get_atomic_data is called twice for restarts with -r flag

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#448]
As part of efforts to fix #425 , I'm restarting models from a wind save file using the command 
```
mpirun -n 3 py -r fiducial_agn
```
When you do this, get_atomic_data() is called upon readin of the wind save file but called again in where you read in the atomic data file from the file. I swear this didn't used to happen, but looking back at previous commits suggests the code has been like this for a few **years** and also seems to happen when using system type previous. 

I've no idea what this actually does but I am getting strange macro-atom behaviour in these runs like jumping to a ground state without de-activating, which should be impossible, and I am wondering if it is due to this. 

As an aside, one gets a lot of Errors from atomic data about not being able to interpret lines that we should cleanup, because it hides actual errors.

**Comment by kslong** [comment]
A related problem which we should correct at the same time is that get_atomicdata is run before the log file is set up.  As a result, errors from this are not included in the diag files and as a result are hard to track down.

**Comment by kslong** [comment]
First, I agree that we do not want to read the atomic datafile twice as when we do this we allocate various structures.  

The two places get_atomic_data are called are  in wind_read (which one needs to do for restarts), and in get_line_transfer_mode (which is part of another routine init_ionization, which is called from python on line 552 currently.

The case for RUN_TYPE_RESTART is clear.  We can avoid reading the data in twice by 
not calling init_ionization on a restart.  This would be easy to do, just by looking at geo.run_type (assuming this has not already be altered by read_wind).   

But the case for RUN_TYPE_PREVIOUS is not as clear.  The idea of this was that one could change certain things about the way the calculation was done, including possibly the line transfer mode. and then be able to compare the results using the same "structure", e.g from single scattering to multiple scattering.   Clearly, though this would only work for some of the line transfer modes, and not from non-macro to macro and vice versa.  It may be we want to give this up.

Thoughts @jhmatthews  @Higginbottom
