### ISSUE TITLE
Interpolation between data points for topbase data

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#45]
As of python76, the subroutine sigma_phot_topbase in radiation.c interpolated linearly between tabulated values of cross section. This gives rise to an overestimate of the cross section since the cross section actually drops off as something like 1/nu^3.

The obvious fix is to simply interpolate in log frequency space. 

Taking logs on the fly is slow, and this subroutine is called a lot - so I propose a second frequency array in log space in the topbase structure (this will take very little extra memory). 

The only change that is needed in sigma_top_phot is to take the log of the incoming frequency, and then use the log_freq tobase array in the routine.

We also need to call linterp with log_freq rather than freq.

**Comment by kslong** [comment]
Perhaps, but I'd like to know the answer to some questions first:
1.  What fraction of the time in python in now taken up by calculating the photon x-sections?  If I remember correctly it is large, but I'd like you to confirm.
2.  How many logarithms and power law calculations do we have to do to implement a logarithmic interpolation with and without storing the the logarithmic frequencies.
3.  We also have the option of simply giving more data points and keeping with a linear interpolation.  Is this viable?

Knox S. Long
Space Telescope Science Institute

**Comment by Higginbottom** [comment]
I have done some profiling in order to answer these questions.
I have run the benchmark QSO model, with only 2million photons in one cycle as a quick test.

1: With the parameters above, python spends 68% (380s)  of its time in variable_temperature. Of this, a full 210s are spent in compute zeta (see new enhancement posted) and 160s are spent in pl_correct_2. Now here is the suprise. In total, across both of these subroutines, 1067ms are spent computing topbase cross sections and a whopping 229 SECONDS are spent computing verner cross sections. Almost all when doing integrals over a blackbody. This is because for some reason qromb needs a lot more points to converge for a verner cross section, and each call is a lot longer due to two calls to 'pow' which are quite time consuming. So the simple answer is - during the ionization statge, python spends 60% of its time computing cross sections, but almost all of this is spent doing integrals over blackbodies with verner cross sections. But this is beside the point.

2: I have implemented a scheme that uses three log calls, (to work out the correct interpolation between adjacent points in log space) and an exp and two log calls (to work out the correct cross section in log log space). Natural logs and exps are slightly faster than log10 and pow(10,x) calls. The total times spent in computing topbase cross sections increases from 1067ms to 4642ms. This is negligible - and since it will only ever scale with number of cells, number of ions and number of bands, it would take massive increases in these to ever make this part of the code significant. 

3: Yes - I agree that this is viable - however given the modest performance hit, I think it is correct for us to do log log interpolation, even if in the future we also increase the resolution

**Comment by Higginbottom** [comment]
I have incorporated this into python_76c  in commit c3b0918576375e2ed7c99e279a0e0a1e52151a85
Simple tests show it is doing what I want.
