### ISSUE TITLE
Something very odd with MPI on iridis

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#455]

**Comment by Higginbottom** [comment]
Trying to run my new py_pluto on iridis4 - I was dismayed to come back after a day or so to see that only a few cycles had been completed - despite using 256 cores.
In the past, using py82e, a cycle of a large (100x200) model took about 500s
Using py82k commit 7a99289ad8c42a1426ccd8c879292fbfd1d233ae took 7000s!

This is very concerning - 2 hours per cycle isn't good. I now know that I had accidentally turned on the wind radiation. This may well be the reason for the slow runs....

But, whilst trying to understand this - I ran a much smaller run - with very odd results.
Here is a .pf file and a .zeu file (the hydro file).

[input_82e_8.pf.txt](https://github.com/agnwinds/python/files/2679753/input_82e_8.pf.txt)
[hdf000197nsh_dw44.zeu.txt](https://github.com/agnwinds/python/files/2679755/hdf000197nsh_dw44.zeu.txt)

So, first I ran with py82e - listing the times in the .sig file for finished init, finished ion 1, finished ion2

8 cores took 26-866-2406s
16 cores.     26-445-1330
32 cores.    26-250-970

NB- of 256 cores the numbers are 7-236-440 (so not actually much speed up really....)

All very understandable.

Now py82k - all ran to completion

8 cores      26-268-800  (eh???? - can it really be faster than 32 cores on 82e???
16 cores.   26-266-750  (hmmmmm)
32 cores.  27-275-736   - I smell a rat here...

How about errors

Uh oh - the main difference is that spectral_estimators: too few photons......
has jumped from 63072 to 111619 - nearly double, but we also get 283 Alpha cannot be bracketed errors, and 64 qromb a>b errors which are not present in the 82e run....

don't know what is going on - but it looks potentially very sinister....

I guess it could be down to our changes to the matrix ionization error checking...

I'm going to see where the jump in behaviour happens - so see if it is wanted...

**Comment by Higginbottom** [comment]
Hmmmm, not sure about using the same MPI compiler - the 82e version was compiled a long time ago….

The .o files show the expected number of cores in use.

**Comment by Higginbottom** [comment]
This may well be the same problem as #456 i.e. a probably bug in photon2d.c...

**Comment by Higginbottom** [comment]
OK - I think it isn't. I'm now using 82j - commit 86b7b582613d78b993fc1839eebf4d09e4f4e784 sand I'm re-running an old zeus/python run that I ran this morning. 
This mornings run with 82e - first call to python
 Tue Dec 18 09:24:30 2018      0.0 START                input 
Tue Dec 18 09:24:30 2018      0.0 NOK                  Initializing variables for input
Tue Dec 18 09:25:40 2018     69.5 NOK                  Finished initialization for input
Tue Dec 18 09:25:40 2018     69.5 NOK                  Starting 0 of 3 ionization cycle 
Tue Dec 18 09:29:09 2018    279.1 OK                   Finished 0 of 3 ionization cycle 
Tue Dec 18 09:29:10 2018    279.7 NOK                  Starting 1 of 3 ionization cycle 
Tue Dec 18 09:32:30 2018    480.2 OK                   Finished 1 of 3 ionization cycle 
Tue Dec 18 09:32:32 2018    481.6 NOK                  Starting 2 of 3 ionization cycle 
Tue Dec 18 09:35:52 2018    682.2 OK                   Finished 2 of 3 ionization cycle

This afternoon with 82j
Tue Dec 18 14:24:22 2018      0.0 START                input 
Tue Dec 18 14:24:22 2018      0.0 NOK                  Initializing variables for input
Tue Dec 18 14:25:33 2018     70.5 NOK                  Finished initialization for input
Tue Dec 18 14:25:33 2018     70.5 NOK                  Starting 0 of 3 ionization cycle 
Tue Dec 18 15:19:09 2018   3286.1 OK                   Finished 0 of 3 ionization cycle 
Tue Dec 18 15:19:09 2018   3286.8 NOK                  Starting 1 of 3 ionization cycle 

it is as if it isn't running on multiple nodes......

Boggled....

**Comment by Higginbottom** [comment]
Commit c517d42c08a60e6807e90b6ee492a45aa8aee552 (82i) also runs slow on the old zeus_python run.
Am going to try to re-compile 82e and re-run just to see if it is a compiler issue..

**Comment by Higginbottom** [comment]
Recompiled 82e - it is running fast - so it seems that there isn't a compiler issue....

what on earth?

**Comment by Higginbottom** [comment]
Commit 7c1ea3295b81f143ed216f18f43bd4f63260b5b3 runs fast

Commit 685b5440695a6423e5c05c47bcf9a33813d8da6a crashes - possibly due to the bug #440

This was the commit when KSL started introducing the new input file.
Next I'll go to the commit after the bug fixes. I'm assuming this is the time that it starts to go wrong.
It seems likely that it is due to a change in the input file...

**Comment by saultyevil** [comment]
If you're still interested in the commits I've been using... I've been use commit bee0b86 on Iridis and 86b7b58 on Excession. At least on the small TDE runs I've been doing, scaling seems fine but I've only gone up to 80 cores on Iridis. 

I could set up some scaling tests on Iridis/Excession using my pf if that would help?

**Comment by Higginbottom** [comment]
Commit 5d781b6724a0faede93e51bf048bf618f4948956 (after my fixes) runs but is slow.
So, now I just need to work out what is going wrong....

Ed - If you are sure it is scaling OK - then no need to rerun. But if you post your .pf file here - I'd like to take a look and see if it helps me understand why \I'm going so slow...

**Comment by Higginbottom** [comment]
Edited my zeus_python script so it makes a python parameter file using text inputs rather than numbers where appriroate. Still very slow.

**Comment by saultyevil** [comment]
Sure, I've attached the two main pfs I've been playing around with. 

I've also just set off some tests for 1, 2, 4, ..., 48 cores on Excession with less cycles to see what the actual scaling is like! I'll get back to you once they've finished running.

[tde_agn.pf.txt](https://github.com/agnwinds/python/files/2696076/tde_agn.pf.txt)
[tde_cv.pf.txt](https://github.com/agnwinds/python/files/2696077/tde_cv.pf.txt)

**Comment by Higginbottom** [comment]
It depends on why the scaling isnt working. 
If it is some kind of excessive inter-process communication, it might only show up on Iridis, when it spreads over nodes….

N

**Comment by saultyevil** [comment]
Ah good point - I could just do the same on Iridis then.

**Comment by saultyevil** [comment]
Scaling seems OK for my tde_agn.pf runs for 1-7 Iridis nodes..

Cores  | Wall Clock (s)
112      | 1111
96       | 774
80       | 899
64       | 1095
48       | 1420
32       | 2061
16       | 4008

I think I can believe it taking longer to run for 112 cores than on 64, 80, 96 since with 96 cores, each cycle only takes about ~17 s to complete. So short cycles and an extra nodes worth of communication could be the slow down there. This is on version 82i, bee0b86.

**Comment by Higginbottom** [comment]
Here are the errors after the first call - 3 cycles - to python. This is process 0

firstly, a fast run - commit 7c1ea3295b81f143ed216f18f43bd4f63260b5b3

 Completed wind creation.  The elapsed TIME was 317.527644
 Completed wind creation.  The elapsed TIME was 317.527658

Error summary: End of program, Thread 0 only
Recurrences --  Description
       14 -- getatomic_data: line input incomplete: %s
     3942 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        2 -- error_count: This error will no longer be logged: %s
       64 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- trans_phot: Trying to scatter a photon in a cell with no wind volume
        1 -- trans_phot: %d grid %3d x %8.2e %8.2e %8.2e
        1 -- trans_phot: istat %d
        1 -- trans_phot: This photon is effectively lost!
      118 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model

and now a slow run - commit - 5d781b6724a0faede93e51bf048bf618f4948956

 Completed wind creation.  The elapsed TIME was 6309.793107
 Completed wind creation.  The elapsed TIME was 6309.793121

Error summary: End of program, Thread 0 only
Recurrences --  Description
       14 -- getatomic_data: line input incomplete: %s
     3942 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        2 -- error_count: This error will no longer be logged: %s
       64 -- get_atomicdata: No inner electron yield data for inner cross section %i
        2 -- Error qromb: a %e>=b %e
      118 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model


The thing that sparks my worry is the qromb error - these things can be real time sinks as the code struggles to do an integration - but an hour????

Anyway - its a lead...

The actually error is during photon generation - band 1: looks like

Error: Error qromb: a 2.141114e-04>=b 2.141114e-04

happens each time through - ISTR I did a little fiddling with the bremstrahlung photon gen.... Uh oh!!
If (and it is a big if) there is a problem here, it would affect every core identically - because each core has to do the same integration, so no speed up..

**Comment by Higginbottom** [comment]
OK - so the brem thing wasn't the case.
But I may have found it.

On my Mac - wind_rad_init takes a fraction of a second in commit 7c1ea ,but hundreds of seconds in commit 5d78. This isn't the thousands of seconds on iridis - but it is significantly odd.

It is spending all the time in these lines:

        plasmamain[n].recomb_simple[i] = alpha_store = alpha_sp (&phot_top[i], &plasmamain[n], 2);
        plasmamain[n].recomb_simple_upweight[i] = alpha_sp (&phot_top[i], &plasmamain[n], 1) / alpha_store;

which were put in in September. 

They appear to not be required in a non-macro atom run, which this is supposed to be - but are running anyway. 

Running on iridis with some time stops to confirm this is what is slowing the run down.

Assigning james in on this to help...

**Comment by jhmatthews** [comment]
Hmm ok. These were the things me and @ssim put in to calculate the alpha_sp quantities from Lucy's 2003 paper for simple ions in indivisible packet mode. So the first thing to do might be to put an if statement around them that only runs them in macro-atom mode and if BF_SIMPLE_EMISSIVITY_APPROACH == 1 (which is a flag to turn our new mode on and off). 

The deeper issue though is perhaps why those integrals in particular are such a time sink, because we don't want to lose all our scaling. One way of not losing our scaling is to parallelise wind_rad_init, or at least the portion that does the macro-atom estimators, which seems like it is worth doing to me

**Comment by Higginbottom** [comment]
So there was a commit - which changed the sense of the if statement that protects these commands

it used to be

      if (geo.macro_simple || phot_top[i].macro_info)

and it became 

	      if (geo.macro_simple==0 && phot_top[i].macro_info==1)

in commit 7cc7139addfc2172eaa8b5e5e300c1cff9d36178. This has been all messed up in the time line, I assume it was pulled into dev sometime after 7/9 - because it was *not* being called in my runs then but the commit above was 1/8! 

geo.macro_simple seems to equal 1 in my run - which I assume means treat things as simple - this is confirmed by this comment in setup_domains.c:      

geo.macro_simple = 1;	// This is for test runs with all simple ions (SS)

Still waiting for confirmation that this is why my runs are taking so long - but this change in sense definitely seems incorrect - well, either geo.macro_simple shouldn't=1 for non-macro - *or* the sense of the if statement *is* wrong....

**Comment by jhmatthews** [comment]
I think geo.macro_simple shouldn't really be used in the non-indivisible packet mode and I'm not really sure what it should be in that case, because it's a flag to treat all ions as simple ions in indivisible packet mode. So I think the new if statement is "correct" in the sense that ```if (geo.macro_simple==0 && phot_top[i].macro_info==1)``` catches *full macro-atoms* but incorrect in the sense that it doesn't catch "standard mode". I think probably it should become:
```if (geo.macro_simple==0 && phot_top[i].macro_info==1 || geo.rt_mode == RT_MODE_2LEVEL)```

**Comment by Higginbottom** [comment]
OK - so its definitely looking like this is the root cause of my woes. 
We need to back off KSLs commit in dev - that broke things a few days ago - and apply a fix for this issue. Is it best to protect just this bit, or better to put an overarching if statement that doesn't go near all this if we aren't in macro mode. What is the safest way of avoiding doing macro stuff....

**Comment by jhmatthews** [comment]
I think my above if statement is safe. that is

if (geo.macro_simple==0 && phot_top[i].macro_info==1 || geo.rt_mode == RT_MODE_2LEVEL)

but you can also put the rt_mode if statement around it

**Comment by Higginbottom** [comment]
Actually, don't worry - I'll just work in my own branch till dev is fixed. Looks like it is too hard to back things off - particularly if people have already pulled.
I'll just work in my own branch until KSL is back in the loop and able to fix the bug....

**Comment by kslong** [comment]
I would try profiling efore and after here.

Sent from my iPad

On Dec 20, 2018, at 6:24 AM, Higginbottom <notifications@github.com<mailto:notifications@github.com>> wrote:


OK - how do we back off KSLs commit?
I can't fix this on dev until that is removed or fixed - and since nobody understands how to fix that, we should just back off the commit...

**Comment by Higginbottom** [comment]
Run had just finished on iridis - it was taking all the time to compute the macro stuff in wind_rad_init - have implemented james suggested 'fix' on my branch which simply doesn't call those lines in a non-macro atom run. 
Have submitted job - will see if that fixes it.

NB, the reason Ed didn't see it is that he only has about 100 cells in his model that actually contain any material  - I have 20000 so the wind_rad_init takes 200 times as long - 3000s instead of 30. 

Longer term, I guess we need to assess why this function is such a time sync and parallelise it, as James suggests.

**Comment by Higginbottom** [comment]
Yup - that fixed it....

**Comment by Higginbottom** [comment]
Fixed with pull #459

**Comment by jhmatthews** [comment]
General issue for this opened in #460, closing this one.
