### ISSUE TITLE
Serious bug in py82k

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#456]
Trying to see what a more 'normal' run does comparing 82k and 82e I have tried to run the fiducial_agn.pf parameter file in the examples/basic folder.

In 82e, it is still running - gets to the end of the 9th cycle in 8000s on my laptop - serial - NB I set the ionization mode to 9 so it is comparable to the run below...

In 82k, after fixing the ionization mode - still has ion mode 7 - to mode 9, it crashes after 9 cycles which it reaches in just 1700s.

Why I get at the end is:

Error summary: Something is drastically wrong for any error to occur so much!

Recurrences --  Description
       15 -- rdchoice: Deprecated use of rdchoice. NO ERROR CHECKS! For %s replace answer %s in %s with its string equivalent 
        1 -- Over--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

so it is dying due to lots of some kind of error - that is isn't telling me....

Uh oh....

**Comment by Higginbottom** [comment]
I suggest we wait for Knox to fix it - just revert to the commit before this bug crept it….

**Comment by kslong** [comment]
@Higginbottom  I believe this is now fixed in py82k on dev, but urge you to check that you agree, if so to close the issue.

**Comment by kslong** [comment]
@Higginbottom   I assume you have had plenty of time to check this, so I am closing this issue.
