### ISSUE TITLE
SV model Lyman edge slight regression disagreement

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#46]
I'm just regression testing a release and wanted to flag something up as potentiallyproblematic before I release it. I was plotting a CV model, and comparing it to 74b4, which was when I carried out a pretty rigorous regression test. 76b is in green and 74b4 in blue.

![sv76b_compsources](https://f.cloud.github.com/assets/3007249/1067798/aa11f436-13da-11e3-8d93-0db186329125.jpg)

![sv76b_compsummary](https://f.cloud.github.com/assets/3007249/1067802/b63160ee-13da-11e3-92ab-917bfc820c18.jpg)

The thing I was concerned about was the difference beyond the lyman edge and if we understand why there is a difference here- I couldn't spot anything specific in what ahs changed over the versions

Should I be worrying about this? Or can I go ahead and make a 76b release which will then be used as our testing baseline? 

These were run with identical pf files and the only difference was that sv76b was run in parallel. I will do a non parallel run to check if that is the problem.

**Comment by jhmatthews** [comment]
pf file:

```
Wind_type(0=SV,1=Sphere,2=Previous,3=Proga,4=Corona,5=knigge,6=thierry,7=yso,8=elvis,9=shell)   0
Atomic_data atomic/standard39
photons_per_cycle   100000
Ionization_cycles   20
spectrum_cycles 10
Coord.system(0=spherical,1=cylindrical,2=spherical_polar,3=cyl_var) 1
Wind.dim.in.x_or_r.direction    30
Wind.dim.in.z_or_theta.direction    30
Wind_ionization(0=on.the.spot,1=LTE,2=fixed,3=recalc_bb,5=recalc_pow,6=pairwise_bb,7=pairwise_pow)  3
Line_transfer(0=pure.abs,1=pure.scat,2=sing.scat,3=escape.prob,6=macro_atoms,7=macro_atoms+aniso.scattering)    3
System_type(0=star+disk,1=star+disk+secondary,2=agn)    0
Star_radiation(y=1) 1
Disk_radiation(y=1) 1
Boundary_layer_radiation(y=1)   0
Wind_radiation(y=1) 1
Rad_type_for_star(0=bb,1=models)_to_make_wind   0
Rad_type_for_disk(0=bb,1=models)_to_make_wind   0
Rad_type_for_bl(0=bb,1=models)_to_make_wind 0
Overall_system_type(0=single_object,1=binary)   0
mstar(msol) 0.8
rstar(cm)   7e+08
tstar   40000
disk.type(0=no.disk,1=standard.flat.disk,2=vertically.extended.disk)    1
disk.mdot(msol/yr)  1e-08
Disk.illumination.treatment(0=no.rerad,1=high.albedo,2=thermalized.rerad,3=analytic)    0
Disk.temperature.profile(0=standard;1=readin)   0
disk.radmax(cm) 2.4e+10
lum_bl  0
t_bl    10000
Torus(0=no,1=yes)   0
wind.radmax(cm) 1e+12
wind.t.init 40000
wind.mdot(msol/yr)  1e-09
sv.diskmin(wd_rad)  4
sv.diskmax(wd_rad)  12
sv.thetamin(deg)    20
sv.thetamax(deg)    65
sv.mdot_r_exponent  0
sv.v_infinity(in_units_of_vescape   3
sv.acceleration_length(cm)  7e+10
sv.acceleration_exponent    1.5
Rad_type_for_star()_in_final_spectrum   0
Rad_type_for_disk(0=bb,1=models,2=uniform)_in_final_spectrum    0
spectrum_wavemin    850
spectrum_wavemax    1850
no_observers    5
angle(0=pole)   10
angle(0=pole)   27.5
angle(0=pole)   45
angle(0=pole)   62.5
angle(0=pole)   80
phase(0=inferior_conjunction)   0.5
phase(0=inferior_conjunction)   0.5
phase(0=inferior_conjunction)   0.5
phase(0=inferior_conjunction)   0.5
phase(0=inferior_conjunction)   0.5
live.or.die(0).or.extract(anything_else)    1
Select_specific_no_of_scatters_in_spectra(y/n)  n
Select_photons_by_position(y/n) n
spec.type(flambda(1),fnu(2),basic(other)    1
Extra.diagnostics(0=no) 0
Use.standard.care.factors(1=yes)    1
Photon.sampling.approach(0=T,1=(f1,f2),2=cv,3=yso,4=user_defined)   2
```

**Comment by kslong** [comment]
I assume you mean the relatively small difference below 912 A in the continuum.  This indicates a slight change in the amount of neutral H.  I've seen similar things in the past, and indeed this might be associated with the free-free fix for which you saw less emission.  I am not concerned about this.

Knox

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
Ok, great, issue closed and release imminent.
