### ISSUE TITLE
Slow down caused by macro atom checks in non-macro atom runs

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#460]
This was bug #455 - where NSH noted that there was no speed up in large hydro runs over many MPI nodes.
This turned out to be because of these lines:

    for (i = 0; i < ntop_phot; i++)
    {
      /* 57h -- recomb_simple is only required for we are using a macro atom approach, and only non-zero when
         this particular phot_tob xsection is treated as a simple x-section. Stuart, is this correct?? I've added
         checks so that macro_info is only 0 (false) or true (1), and so the logic of the next section can be
         simplified.  0608-ksl */
      if (geo.macro_simple == 0 && phot_top[i].macro_info == 1) 
      {
        plasmamain[n].recomb_simple[i] = 0.0;
        plasmamain[n].recomb_simple_upweight[i] = 1.0;
      }
      else
      {                         //we want a macro approach, but not for this ion so need recomb_simple
        plasmamain[n].recomb_simple[i] = alpha_store = alpha_sp (&phot_top[i], &plasmamain[n], 2);
        plasmamain[n].recomb_simple_upweight[i] = alpha_sp (&phot_top[i], &plasmamain[n], 1) / alpha_store;
      }
    }

in wind_updates2d.c around line 1150 in the subroutine wind_rad_init.
Specifically, the calls to alpha_sp are time consuming, and not parallelised. It is not important to do this for a non macro atom run, so a fix was implemented where the lines are only executed in a macro atom run. however the problem clearly needs to be dealt with to obtain proper speed up in macro atom runs...

In fix - if statement becomes...

      if ((geo.macro_simple == 0 && phot_top[i].macro_info == 1) || geo.rt_mode == RT_MODE_2LEVEL)

**Comment by kslong** [comment]
@Higginbottom   I have assigned this to you.  It seems to me we should figure out what fraction of the time is being spent on this, in a .pf file that illustrates how bad it can be, but is still one of interest.  If is a big deal, because of runs that interact with Pluto, we should definitely fix it.

**Comment by Higginbottom** [comment]
I think this bug was fixed by not calling the relevant lines in non-macro atom runs. So, the problem is really a macro-atom one. I don't use macro atoms in rad-hydro, since we are not interested in the kind of details provided by that method - only overall heating/cooling rates and now fluxes/forces. I'm happy to close it - if those who do macro atom runs are finding these calls to alpha_sp a problem, then we need a relevant macro-atom parameter file as a starting point. I don't really have the experience..

**Comment by kslong** [comment]
I think I would just go ahead and close this, Nick.

**Comment by Higginbottom** [comment]
Original bug fixed with pull #459. This new pug report was to flag up that the underlying slow performance in the macro atom code was not fixed - however no problems have since been flagged up by macro atom users - so bug is closed once more
