### ISSUE TITLE
Py83 - Remaining tasks

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#461]
This issue is intended to track of the migration from py82 to py83.

From my perspective there are two items that need to be occur before we can switch from one version to another.

* As agreed, py83 should force people to use modern inputs (and in particular) alphanumeric entries for rdchoice (instead of supporting integer entries as well.  Also, synonyms -- old keywords -- should not be supported.

* The FU ORi branch (which contains work @jhmatthews  did in support of the FU Ori paper should be integrated into dev.

For, the former ksl plans to implement a scheme where Py accepts numbers (and synonyms) but halts after reading the .pf file.  The user must then edit the .pf file to have the correct format before Python will run.  Then, probably in py85, we will drop this capability altogther.

**Comment by kslong** [comment]
@Higginbottom @mandyhewitt @saultyevil 

These are instructions for updating old parameter files  to new ones in py84.

- Download and compile py83
- cp the parameter file you want to update to a working directory in which you can run python
- Try running this file.  Usually what will happen here is that the program will run through and create a whatever.out.pf file.   
- Look at this file.  If it contains comments that say "Deprecated ..." one must fix parameters from integers to strings do so.  Fix these, and delete the comment lines.  If not, got to the next step anyway (as there will be differences between the whatever.out.pf file and the whatever.pf file)
- Now copy whatever.out.pf to whatever.pf and try again.  You may have to do this several times as there are two things happening.  (a) some of the parameters are changing names, and (b) some of the parameters require strings instead of numbers.
- Once you have a working .pf file copy it back to the appropriate examples directory.  (Note that you do not need to run the program to completion, you just need it to get through the input steps.)
- Once you are all done, commit the changes, and push back to the py83 branch

For agn models, you may encounter an additional problem, where there is no whatever.out.pf file.  So far, ksl has only seen this in the instance where python ends with the following message:

get_bl_and_agn_params: When using models with an AGN, there should be exactly 1 model, we have 0 for ion cycles

In this case, go to .pf file and look at the lines that have this kind of keyword:

Rad_type_for_agn(0=bb,1=models,3=power_law,4=cloudy_table,5=bremsstrahlung)_to_make_wind

and replace the number with the string you want, brems for bremsstrhalung, power for power law, bb for blackbody, and try again.  This time you should get a whatever.out.pf file, which will allow you to go back to the procedure above.

Aside: the reason that one has problems with Rad_type is somewhat complex, but has do do with issue #463 as well as the fact that some types of radiation, e.g power laws are only used for some types of sources, e.g AGN and BHs, but not stars.

If you have trouble, compare the parameter files in the regress directory between py82 and py83. This should clarify how the parameter files have changed, as all of the paramter files on the py83 branch have been updated.

**Comment by saultyevil** [comment]
I've updated the extended parameter files now. But, I've left `Thermal_balance_options(0=everything.on,1=no.adiabatic)` as a rdint choice due to a comment in setup.c saying this part of Python needs to be re-written when FU Ori is merged.

**Comment by Higginbottom** [comment]
Would I be correct in thinking that once the inputs are corrected, one should get identical results between py82k and py83?

If so, this is a good check that the examples are correct, if not, then its rather tricky to make sure one has done it correctly…..

N

**Comment by kslong** [comment]
Yes, there should be no differences if the .pf files have been created correctly.  This is an effort obviously for some of the examples that take a long time to run, but I have checked that this is the case for all of the runs in the regress directory.

**Comment by kslong** [comment]
I have closed this issue as the FU Ori branch has been merged with dev, reflecting the fact that we have settled on how to treat kpkts in the event we are running FU Ori like models, with extra heating.
