### ISSUE TITLE
Travis .pf files

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#462]
Currently we have a number of models which we use to check updates to Python on github.  There we run most of this models just to parse the the .pf files.  However, if one tries to actually run all these models to completion, they would take a very long time.  @jhmatthews  @Higginbottom I believe we should shorten these runs so that they can actually all be run in a reasonable time.  That will make them much easier to check with our standard regression.py routine.  The alternative, I guess, would be to add a switch to regression.py so that the models are all run with the switch that just updates the parameters files.  The downside of this, is that we would to modify the regression checks so they they do not look for the various normal outputs that you get when the programs are run normally.  Thoughts,   @jhmatthews  @Higginbottom.  This has come up in connection with #461

**Comment by kslong** [comment]
On the py83 branch,  I have modified the .pf files in the travis directory so that they use words to respond to rdchoice commands,  relevant for #461 but I have not addressed the question of whether we want these files to represent short runs of python.

**Comment by jhmatthews** [comment]
I don't think we should be running real python tests on travis unless they are really small, just because there's a sort of "honour" system there - we are using someone else's server that's really for testing code builds and so on. However, if we really can make tests short enough (seconds) then we can run them, or as I mentioned a while back we can use gitlab-CI linked to a server of our own to run any slightly longer tests.

If we can write a script that returns pass or fail for every test for a short run, then that's useful and can be used fairly easily with CI generally. The issue I have always had is deciding what level of complexity I want to test.

**Comment by kslong** [comment]
Basically I agree James, @jhmatthews.  
-  Specifically, I agree we should not be burdening travis.  I  also do not think we need to revise the travis tests to run all of the models.  What we do now to check the inputs for several of the tests is reasonable
- But for testing purposes and to avoid confusion, I think we should be able to run (on our own machines) all of the models that are that in any of the examples directories.  The easiest way to to do this, is, where possible, to avoid models that take days to run.   And in the case of the .pf files in the travis directory, I don't see any valid purpose for any of these to take a long time ... since we are not going to run them on travis that way.

So my suggestions was to replace the current versions of the .pf files for travis, with ones that run in a reasonable period of time, which I define to be no more than a few hours to run all of the .pf files to completion using regression.py on a Mac.  

If you agree with this, the only question is whether is any smart way to reduce the long runs, where by smart I mean we actually might want a few of the .pf files to have models that converge if run to completion.

**Comment by jhmatthews** [comment]
Ah ok, I'd misunderstood slightly. I guess the only issue is that some of the models struggle with low photon number errors and so on. It's possibly we want to come up with a lower spatial resolution AGN run that can run with lower photon numbers sensibly. Alternatively a model with a lower mass-loss rate might be useful for testing purposes (less shielding, easier to converge maybe?).

**Comment by jhmatthews** [comment]
Subtext: yes I generally agree with that.

**Comment by kslong** [comment]
One of the problems with these right now is that agn_ss_2010_modela.pf does not run.
This is obviously because a problem with KWD.d see below, but someone needs to track down what the right value is.

```
### Parameters for Domain 0
Wind.mdot(msol/yr)                         0.1
KWD.d(in_units_of_rstar)                   6.34728e13
KWD.mdot_r_exponent                        -1
KWD.v_infinity(in_units_of_vescape)        1
KWD.acceleration_length(cm)                6.34728e13
KWD.acceleration_exponent                  1.0
KWD.v_zero(multiple_of_sound_speed_at_base)   0.0
KWD.rmin(in_units_of_rstar)                100
KWD.rmax(in_units_of_rstar)                150
Wind.radmax(cm)                            5e16
Wind.t.init                                1e5
Wind.filling_factor(1=smooth,<1=clumped)   1
```

**Comment by jhmatthews** [comment]
I've had a go at this using model A parameters from Stuart's 2010 paper here: http://adsabs.harvard.edu/abs/2010MNRAS.404.1369S

It's done in this commit: https://github.com/agnwinds/python/commit/a927e16bf846b9368adc054dffec9acb09129b74

I've only run one cycle so don't know if it will run to completion. Note I've never used this model, I just put it in the files anyway, but it would be good if it worked.

**Comment by kslong** [comment]
Currently one cannot run agn_ss_2010_modela.pf.  And the error is troubling.  One get a lot of sane_check errors and then Python seems just to go away, without causing regression.py to exit.  It's clear python itself is hung.  After some period of time, it does crash, with a segfault.

**Comment by kslong** [comment]
@jhmatthews   I have tried to actually run the models that are in the travis directory as a regression test with 3 processors.  Aside from the original problem, which is that it takes too long to make this practical .... now 3 days and still not past the XRB model, agn_ss_2010 and the Balmer model failed, with what look like segfaults, which suggests this problem has not been dealt with @saultyevil .  

For the first problem, either I need to give up on the idea that we will regular test these models as a group, or we need to shorten them by reducing the number of photons or numbers of cycles.

The second problem (that some actually fail) needs to have high priority.

**Comment by saultyevil** [comment]
I quickly ran these on the server (with not much better do in self-isolation on a Sunday) and Balmer seemed fine. I don't think agn_ss_2010 is crashing because of a seg fault, there's are a couple of weird things I didn't expect though.

Firstly, it crashes before photon transport because there are no inwind cells, all of them are partially inwind. Increasing the resolution fixes this. Secondly, photons aren't scattering in the wind. They escape as soon as they are emitted - I'm not familiar with the context of the pf, but I'm probably right in thinking this probably wasn't intended? The model seemed to be happy to run till completion though. 

The XRB model is taking a lot longer to run though, there's 1e8 photons per cycle (!!). Maybe that's why it crashes? 1e8 photons is a decent chunk of memory...

**Comment by kslong** [comment]
Yes, agn_ss_2010 just went away and for a long time top just indicated python was not using any cpu.  Ultimately,  failed because of some failure between the threads. There were lots of sane_checks before it got into this condition.  I was able to run it completely through to the end (on a pure linux machine) on a single thread compiled with gcc.    

By contrast, the balmer routine failed because of very definite segfault errors:

```
Running mpirun -np 3 py balmer_test.pf >balmer_test.stdout.txt
Stderrs were reported!!
[pescado.local:14131] [[13690,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file base/grpcomm_base_receive.c at 
line 441
[pescado:14132] *** Process received signal ***
[pescado:14132] Signal: Segmentation fault: 11 (11)
```

**Comment by kslong** [comment]
OK ... this is what is causing agn_ss_2010 to die:

```
Error: spectral_estimators: too few photons (1 or 0) in cell 161 band 8 to produce a model
Error: spectral_estimators: too few photons (1 or 0) in cell 161 band 9 to produce a model
Error: ionization_on_the_spot: t_r exceptionally small -50367
```
It's not clear to me, how t_r could every be negative.

However, my suspicion is that it's the earlier sane_checks that are the real problem

Regarding balmer ... I am not able consistently to produce the error.  I am fairly sure this indicates we still have a problem in the process of transferring variable to and from the threads.

**Comment by kslong** [comment]
@saultyevil  I don't understand your statement that for the agn_ss_2010 model there are no cells fully in the wind.  I find:

````
Allocated        312 bytes for each of   900 elements of             totaling        0.3 Mb
Define wind coord_type 1 for domain 0
cylind_make_grid: Making cylindrical grid 0
cylind_make_grid: rmax 5.000000e+16 for domain 0
wind2d: For domain 0 there are 900 cells of which 384 are in inwind, 84 partially in_wind, & 468 with pos. vol
````

**Comment by saultyevil** [comment]
Sorry Knox, I think I accidentally ran the agn_ss_2010_model.pf in examples/beta rather than examples/travis.

**Comment by kslong** [comment]
No worries, @saultyevil 

The reason for the sane_checks in the agn_ss_2010  model is that for some reason  the velocity exceeds the speed of light. When the photon is doppler shifted it gets shifted to a negative frequency.  I think we can agree that this is not good.

It's not obvious why this is happening:  The wind parameters look plausible:

````
KWD.d(in_units_of_rstar)                   16.666666
KWD.mdot_r_exponent                        -1
KWD.v_infinity(in_units_of_vescape)        1
KWD.acceleration_length(cm)                6.34728e13
KWD.acceleration_exponent                  1.0
KWD.v_zero(multiple_of_sound_speed_at_base)   0.0
KWD.rmin(in_units_of_rstar)                16.666666
KWD.rmax(in_units_of_rstar)                25
Wind.radmax(cm)                            5e16
````
The only thing that  might be odd is that the wind radmax is much much larger than the acceleration length.

Running windsave2table, makes it clear that the  wind does have speeds greater than the speed of light along its inside edge, mostly just outside the windcone, but in some areas which are at least partially inside the wind.    The mass of the system is 4.3e6, and the central object radius is 6.3e11.  @jhmatthews Looking at table 2 of Sim+10 it looks like to me, Stuart had the radius of the central object 3.8e12, which would explain why Stuart did not run into a similar problem.  

Regardless of whether we used some unphysical input parameters, Python should have trapped this problem.

**Comment by kslong** [comment]
Regarding the balmer_test.pf, that failed with a segmentation error.  I have not been able to get this to fail again. There is also a version of the balmer_test routine in the standard regression tests, which we run regularly.  The pf file there has been updated for modern versions of rdchoice, but the one in travis is older, using numbers instead of words as input.  In one sense this is good, as the one in travis tests our ability to interpret old .pf files.

**Comment by kslong** [comment]
The issue is real, in the sense that we are using a different set of models on Travis, and we do not run the models on  Travis, which is a problem. But resolving this is very low priority, so I am labelling this a zombie issue and closing it.
