### ISSUE TITLE
Many agn inputs are nonstandard

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#463]

**Comment by kslong** [comment]
Many of the keywords associated with agn are non standard.  There are two type of problems:
* In one instance there are keywords that do not conform to the basic format for an input, namely, that the format is keyword(options).  Instead some have keyword(options)more keywords
* Secondarily, the names are not consistent.  In some cases, the keywords start witth QSO_BH.  In another case, they are lum_agn.  In yet another Rad_type_for_agn, in yet another AGN.  Probably since we are using the same software for X-ray binaries and AGN we should use BH as the starting point that is lum_agn, should be come bh.agn.

This should be fixed before moving to a major mod. If  @Higginbottom @jhmatthews  have suggestions about this, they should make them quickly.

**Comment by jhmatthews** [comment]
Knox, am I write in thinking this has now be done? I see BH. keywords now.

**Comment by kslong** [comment]
No. The problem of the AGN models goes deeper than the keywords.  It is built into the routine agn.c, which provides options for creating spectra that are not available for other systems.  This forces us to pretend that a BH systems is an AGN with a small mass, and prevents us from using a bremsstrahlung spectrum as the boundary layer emission of a CV, without writing new code.  The fact that agn’s were incorporated the way they are makes it more difficult to build new systems into Python as a whole.

**Comment by jhmatthews** [comment]
I agree, I just thought this issue was for the more superficial matter of input names and keywords. We have other issues that discuss some aspects of the problem (e.g. #307)

**Comment by kslong** [comment]
I would not mind if we wanted to close this, I guess, if we renamed #307 to make it clear what the full scope of the problem was.

**Comment by smangham** [comment]
I think this is close enough to being closed.
