### ISSUE TITLE
yaml files and yaml file generator

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#464]
There are a several problems with the yaml files that are supposed to provide help for the various input parameters

- Many of the names have been changed since these files were last updated
- The routines that generate yaml files have not been updated to understand the rdchoice commnds (that have replaced many of the rdint commands)
- There is not obvious way to determine whether the yaml files are up-to_date

**Comment by smangham** [comment]
A 'generated from commit' field on the YAML would probably be a good idea. I can look into getting that in once I've done paper stuff/corrections.

**Comment by kslong** [comment]
@smangham   I know you have updated autogenerate_parameter_docs.py, but it does not work for me with the -p or -w options.   The problems seem to be with encoding.  

Also, there is very little documentation on how the routine is to be used.  Could you check this, and some discursive documentation on how this routine is to be used..  

I want to get our yaml files up to date to account for the use of rdchoice and various name changes that have been made.

**Comment by smangham** [comment]
I spent all today in meetings, didn't get to work on this. I'll get to work on Monday.

**Comment by smangham** [comment]
Knox, could you let me know what your issues with encoding were?

Checking to see if something's out of date is possible but more limited. The script can check if variable types/units or enum choices differ- but it can't begin to validate descriptions or parents, or the descriptions of choices. It could add a 'Outdated=True' field for parameters where they differ? I'm going back on adding commit versions a bit, because many variables don't change for a large number of commits so it doesn't really add more information than, say, just having people add a timestamp, or using the file modified dates from the yaml to build the rst files.

**Comment by kslong** [comment]
@smangham   I reran autogenerate_parameter_docs.py just now and did not seem to have a problem with encoding with the -w switch, so I am not sure exactly what I meant.

Note that it looks like this routine has been modified one should be able to run it from the command line, that is to simply run it with

auto_generate_ parameter_docs.py

but this does not work, and it gets into a weird state. 

I think all that is needed to make this possible is to put 

#!/usr/bin/env python 

as the beginning of the script, and then making it the routine executable.  Unless you see a reason not to do that we should, and modify the documentation.

**Comment by smangham** [comment]
I did this, then got distracted redoing all the documentation to double-check the output. Whilst doing so, I discovered that thermal_balance is being included even though it's commented out everywhere. I'm going to identify why.

**Comment by smangham** [comment]
I did this, then got distracted redoing all the documentation to double-check the output. Whilst doing so, I discovered that thermal_balance is being included even though it's commented out everywhere. Figured out I was accidentally trimming the first / off the line, stopping it from being parsed as a comment.

**Comment by smangham** [comment]
Fixed with pull request #529.

**Comment by smangham** [comment]
Fixed with pull request #529.
