### ISSUE TITLE
Redundant files

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#48]
When looking at what github tracks I noticed the following files which are not used in the makefile anywhere but are tracked by the repository

```
constants.c
get_atomicdata_new.c
get_atomicdata_partial.c
goo.c
hub.c
ionization_old.c
kurucz.c
rand_func.c
sim.c
test_diectronic.c
```

Can these be removed and no longer tracked by github? If so I will do so and close. If anyone requires looking at them they can do so by looking at an older version of a release, and download the files if they so require.

**Comment by kslong** [comment]
I think it is reasonable to clean these from the distribution.  We can recover if need be.
