### ISSUE TITLE
regression checks are failing on hydro

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#490]
Somewhere since
a8a8a603007f2929b8c047c62f9a1bba23f1da86  Merge pull request #485 from saultyevil/dev
the regression tests are failing on dev.  This commit was on March 13, to this in the last 8 days or so.  I am currently on commit 
dd8843f24df9eeeae1516a9622954883c8f45e2a  which was from March 20

This also fails
 cd4a4249c9baa752f0e53a312c374f67f596edfc (HEAD)
Merge: 46c69173 b697f6a3
Author: Knox S. Long <long@stsci.edu>
Date:   Thu Mar 14 11:49:52 2019 -0500

This also fails

commit cd4a4249c9baa752f0e53a312c374f67f596edfc (HEAD)
Merge: 46c69173 b697f6a3
Author: Knox S. Long <long@stsci.edu>
Date:   Thu Mar 14 11:49:52 2019 -0500

    Addition of python scripts

**Comment by saultyevil** [comment]
I believe py_hydro fails because it uses `Thermal_balance_options(0=everything.on,1=no.adiabatic)   1` instead of `Wind_heating.extra_processes(none,adiabatic,nonthermal,both)                    1`. Updating the parameter file will probably be a simple fix.

The restart hydro run seems to fail because it can't open a wind_save file. I'm not sure how to go about fixing this since there doesn't seem to be a wind_save file in the regress directory? There were some changes to the structures in commit 3757443, so I'll check to see if the hydro restart works before this commit.

**Comment by saultyevil** [comment]
Sorry, I think I'm actually wrong for py_hydro. The parameter file in regress/hydro/py_hydro is out of date but regress/py_hydro is fine. But, regress/py_hydro_restart is using `Wind_heating.extra_processes(none,adiabatic,nonthermal,both)                    1` which I guess would cause it to exit once reading in all parameters?

I've also run both regress/py_hydro and regress/py_hydro_restart in the regress directory manually and both exit with something like,

```
Creating a wind model using a Hydro calculation = domain 0
Error: Could not open hdf000002nsh_dw33.zeu
Para: !!Exit: error codes should be non-zero!
Para: --------------------------------------------------------------------------
Aborting rank 0000: exiting all processes with error 1
```

It looks like the zeus file isn't copied into the regression run directory anymore?

**Comment by kslong** [comment]
Right. I am trying to figure out why its not copied.

Sent from my iPhone

On Mar 22, 2019, at 6:37 AM, Edward Parkinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I think I'm actually wrong for py_hydro. The parameter file in regress/hydro/py_hydro is out of date but regress/py_hydro is fine. But, regress/py_hydro_restart is using Wind_heating.extra_processes(none,adiabatic,nonthermal,both) 1 which I guess would cause it to exit once reading in all parameters?

I've also run both regress/py_hydro and regress/py_hydro_restart in the regress directory manually and both exit with something like,

Creating a wind model using a Hydro calculation = domain 0
Error: Could not open hdf000002nsh_dw33.zeu
Para: !!Exit: error codes should be non-zero!
Para: --------------------------------------------------------------------------
Aborting rank 0000: exiting all processes with error 1


It looks like the zeus file isn't copied into the regression run directory anymore?

**Comment by kslong** [comment]
OK, I understand it now.  When I updated the parameters for py_hydro.pf and py_hydro_restart.pf, I put the parameter files in regress, whereas they should have been in regress/hydro.
