### ISSUE TITLE
Fluorescent data for inner shell ionization ignored

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#499]
As part of the effort to include inner shell ionization, and the subsequent Auger effect whereby multiple electrons are emitted by relating electrons, an attempt was made to read in the Fluorescent photon yield data from http://vizier.cfa.harvard.edu/viz-bin/VizieR?-source=J/A+AS/97/443
This was in kaastra_fluorescent_yield.data but although read in was not used.
During investigations into #451,  it was discovered that not only is the data not used, it was also read in rather incorrectly, and is not in a state to be used. Further, it seems like a significantly non trivial effort to correctly include this process.
Therefore NSH commented out the data input in get_atomicdata.c , and the structures in atomic.h
This was done in pull request #496 and #497

**Comment by kslong** [comment]
This is implemented for MacroAtoms, and is inappropriate for the Simple Case. MacroAtoms are recommended when fluorescence is important.
