### ISSUE TITLE
TRANSLATE BUG - Dealt with by error logging changes, but not fixed,  in python74b2

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#5]
**Current Status:** Dealt with by error logging changes, but not fixed,  in python74b2
**Priority:** Low, as the problem is dealt with but not solved. See Discussion.
**Version discovered in:**  Python 74b2
**Brief statement of problem:** Huge numbers of Error: translate: v same at both sides of cell, which caused the code to bail when it got more than 1 million.
**How to reproduce:** This bug began to manifest itself in winds with narrow opening angles (70-82), and large values of wind_radmax (1e19cm).

**Discussion:** 
- This bug began to manifest itself in winds with narrow opening angles (70-82), and large values of wind_radmax (1e19cm).
- The problem gets worse with increasing wind density
- All errors come from "partially in wind" cells at the top of the wind
- It shows up as huge numbers of Error: translate: v same at both sides of cell, which caused the code to bail when it got more than 1 million
- During the ionization cycles - we see a few problems, all with photons with trajectories wrt the Z axis of about 70 (or 120).
- During the spectral cycles, a small number of photons give rise to huge numbers of errors- these are all wind photons with theta = 70 degrees - one of the sightlines is the same angle as a wind cone angle.
- The exact location of the problem was not located, but it appears that what is happening is that photons get translated in space into a "partially in wind" cell, but due to roundoff errors when solving the quadratic equation which works out the intercept between the wind cone and the photon trajectory (two very long lines with a tiny angle between them) the photon doesn't quite make it to the boundary, but has been registered as being in the wind. If the difference in angle is non zero - it makes it into the wind after a couple of tiny steps, however if the difference is actually zero - as in a photon packet that has been generated by the extract part of the code when a sightline=a wind cone angle it can take a long time
- The first fix was to log each time a photon packet is moved by DFUDGE*1.1 - if it makes more than 100 steps like this, it is discarded. Also the v same at both sides error was modified so it does not report if the ds small error has already done so - so we don't double count. 
- The second fix is to change dfudge in python.c to make it rmax/1e10, so bigger geometries have bigger pusthorugh distances. I think this change alone would actually fix the problem, since once this was implemented I saw no dv small or ds small errors.
- The DFUDGE fix was applied after spectra had been obtained following the implementation of the first fix, and it changed the spectra slightly. This could be simply adding back photons that were being thrown away from the first fix. I'm doing some more testing - but we call this problem solved!

NSH 121225 (Yes - christmas day - hows that for commitment) Oh dear  - Running py74b2 on the standard cv parameter file results in over a million ds too small errors- this is my new error, and suggests that considering 1.1x DFUDGE as an excessively small step is wrong. This leaves me with the worry of what is a sensible value -1e-6xDFUDGE? Hmmmm. Perhaps the error needs fixing at source...

NSH 130101 - I have changed my ds too small check so it now uses the standard very small number EPSILON. This means that if a photon will be moved by 1e-6cm it will flag as an error. This is tiny compared to dfudge. The CV runs work as before now. I think it still does the right thing in the AGN scale. Will check tomorrow.
I attatch the standard CV parameter file I use (cv_bb_nb.pf) and also the parameter file which generated the problems in the first place is still attatched (run85a.pf)

NSH 130104 - The fix above revealed a truth that I had ignored (a bit) before. Changing DFUDGE to a suitalbe value actually removes all the errors, with no need to have the check I had before (looking for small ds). This seems a much cleaner fix (well fudge) since it requires just a couple of lines. 
I did some runs with run85a.pf with 5 versions of python. Each divided the maximum size of the wind by a different ammount, and here are the results for an interesting angle.
10 means DFUDGE=geo.rmax/1e10 =1e9
11 gives DFUDGE=1e8
12    1e7
13    1e6
14    1e5 - and this one is as original python - so crashes in the first spectrum cycle.
All others run to completion - and give very slightly different spectra.

![image](https://f.cloud.github.com/assets/3007249/703621/f9c2264e-ddad-11e2-8b2b-547b6e6e49f0.png)

NSH 130107 - I've run the CV case on py74b4, and it works fine. I think perhaps this bug can be closed off - the only remaining question is what divisor to use to get DFUDGE. rmax/1e13 works for the problem case, and has the smallest value of DFUDGE - but even rmax/1e10 would make DFUDGE just 1e9cm in that case - which is pretty small. I've uploaded py74b4 with rmax/1e10 set as DFUDGE to the confluence site. Can we call this fixed?

130307 - ksl - My only question here is why things got stuck.  As far as I can teel, the claim is that round off errors are causing the problem.  But what is done here, I believe is to solve a quadratic.  It sounds to me like this means that there is something about the way the quadratic is being solved that is causing it to repeatedly underestimate the distance the photon needs to travel.  To me this sounds like an error that begs for a reformulation of the way the quadratic is being solved.  I also do not understand the connection of this to the fact that it seems to be associated with another error namely, that the velocities do not change on two sides of the a cell which is partially in the wind.  That said, DFUDGE has always been a "fudge".

**Comment by kslong** [comment]
We still have a general problem of what to do when the velocity difference is small, but we made modifications to DFUDGE, so we are going to close this.
