### ISSUE TITLE
Python apparently quits with error

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#504]
When running py/pluto, sometimes, with absolutely no apparent cause, the script exits with the error (in the script.exxxxxxx file)

subprocess.CalledProcessError: Command 'mpirun -n 256 /home/nsh2m14/python/bin/py82k -z -r  input.pf > 00000011.python_log' returned non-zero exit status 255

checking the log file, and all of the diag files, python seems to have completed entirely normally - so what is the 255 error, is it a bug in python, a bug in python (the other one) or something totally different. 

I can probably get the script to ignore the error and press on - but its odd....

**Comment by saultyevil** [comment]
As far as I know, 99.99% of Python exits are either 0 or 1, so I have a strong feeling that it probably isn't related to an exit within Python. Have you checked stderr output from subprocess? Mpirun could be sending an error to subprocess...

**Comment by Higginbottom** [comment]
I've not been capturing the errors, but I'm trying this:

try:
                subprocess.check_call(cmdline,shell=True)   
except suprocess.CalledProcessError as error:
                out.write(error)

where cmdline is the call to python, and out is a log file.

Of course I'll not know if this does anything useful until the code does this unusual and impossible to predict thing. So we'll see.

**Comment by kslong** [comment]
I agree with Ed that this does not sound like Python.  But what I would do is run this exact command outside your python script.  That should tell you for sure.

**Comment by kslong** [comment]
I doubt this is really related to the problem described here, but I am seeing a repeatable premature exit from python with the following error

```
photon_gen: band 6.00e+14 to 3.53e+15 weight 3.49e+28 nphotons   125000 ndisk   74132 nwind       0 nstar    2087 npow 0 
Error: cdf_gen_from_array: input x not in ascending order at element 16601/16602  5.000000e+03 5.000000e+03
Para: !!Exit: error codes should be non-zero!
```

with the following .pf file

[sv.pf.txt](https://github.com/agnwinds/python/files/3142222/sv.pf.txt)

Note that this is a macro atom run.  It is failing during the first spectrum cycle.

**Comment by kslong** [comment]
The error described above is not occurring in the current version. of Python.  I tried running it with 1 and 8 processors on my mac and the routine ran to completion both times.  @Higginbottom I am tempted to close this issue unless are still seeing problems, as there is nothing we can really do at this point.

**Comment by Higginbottom** [comment]
Yes - I've not seen it again - happy to close
