### ISSUE TITLE
anisotropic scattering 

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#507]
AS discussed in #505, there seem to me issues in the way we consider anisotropic scattering that are likely be increasingly important in situations where the optical deptths are high.  Our approach right now for anisotropic scattering is to look for a direction where the optical depth is low enough for a photon to escape the interaction region.  

If one considers a simple interaction region, where the velocity is increasing along one direction, say the z axis, a photon encountering a resonance, will be equally likely to be scattered in a direction toward positive z and toward negative z.  This is reasonable as long as tau is small,

But in reality, if the optical depth is high, the photon will tend to be "reflected" rather than transmitted in this situation.  This is because the photon will random walk it's way into the "interaction region" and be more likely to diffuse back to the near surface rather than make it all the way through, unless the photon moves in frequency space, in which case an isotropic scattering profile might be more appropriate.

The physical question here is what really is the correct thing for us to do, which it would be good if @ssim @jhmatthews @Higginbottom and @lazygun37 commented upon before we did anything more.

Note that from ksl's perspective this is closely related to the question of how we modify Python to accommodate higher optical depths.

**Comment by ssim** [comment]
This is interesting but I don't understand fully. Do we think that what underlies this is that the Sobolev approximation is no longer valid - i.e. at some point the thermal profile of a line matters and the velocity gradient no longer dominates. It should be possible to quantify this - comparison of Sobolev length to e.g. grid cell size? - but maybe we're orders of magnitude off.

If the issue is that the Sobolev approximation fails then I guess we're plausibly way off: the optical depth will not be right etc. It would make sense in that case at least to assume isotropic scattering, I suppose - just because we want to get out of trouble quickly?

On the other hand, if the Sobolev approximation for the opacity is still well justified then I wouldn't be too sure about swapping to some other angle redistribution scheme. If the Sobolev surface is well localised for a line then it's not obviously true to me the reflection must dominate - at least not locally - I guess I'd still agree that reflection might be the likely end result, but this would happen by sequentially encountering a bunch of Sobolev surfaces (for different lines) each of which has a 50:50 chance of getting through or going back, in the limit? (Does that sound right?)

**Comment by kslong** [comment]
I think what we/I am trying to understand, is what is the best thing to do as the Sobolev approximation begins to fail, although I think there is some question about what to do when the optical depths become large, even when the Sobolev approximation is well justified.

In part this was triggered by the imported model questions which arose, because dv_ds was very small in all directions, which lead to photons being “trapped” in the while loop used to generate the angle distribution.  But I wondered about this whole issue at other times as well.

Even if the Sobolev approximation is well justified,  I think there is a question about the right approach when the optical depths become large.    Is really true, as we currently have it set up that the likelihood of scattering in the forward direction is the same as in the backward directions.  (I tried to explain this in more detail in the earlier note).

Stated more precisely perhaps, suppose we had done a proper calculation without the Sobolev approximation.   As a photon passed through now a finite sized interaction region, and the total x-sectionn was large, wouldn’t photons interacting tend to “reflect” ( using the same argument as is made for electron scattering reflecting off the surface of the disk) .  For our optically thick interaction region  wouldn’t the photon be trapped on the inner edge of the interaction region, and also reflect as long as thermal frequency shifts were not important.  On the other hand if there were frequency shifts, then at some point wouldn’t the photon get to a frequency with a long mean free path, and radiated more or less isotropically.   But in any even, the number of scatters in the reaction region would not be that predicted by our current approach, and hence since at every scatter a collisional dexcitation is possible,  our estimate of the energy carried by the photon (which we use for simple macro atoms) be incorrect.

My feeling is that this issue needs to be understood, if we are going to attack the optically think problem generally, since most/many of the situations where we have envisioned things becoming really optically thick – e.g disk atmospheres – we will find ourselves in the region where the Sobolev approximation can be questioned.

Cheers,
Knox


P. S. It might not be too hard to create a program with say a simple linear outflow and one resonance line, where could do the calculation properly and in the Soboleve approximation and see how different the angular distributions turn out.  It might even be possible to do this in a python script, if we were clever.

**Comment by kslong** [comment]
This just needs a discussion with Stuart, CK, Knox, and James to see what we want to do.

**Comment by kslong** [comment]
James, Stuart and Knox discussed this issue.  Our conclusion was that what we doing is correct in the assumption complete redistribution occurs, but would be wrong if scattering was coherent (in reality of course, partial redistribution occurs). 

The basic question here is whether if you have a very optically thick resonance would one in real life expect the distribution of resonantly scattered photons to be symmetric with respect to the Sobolev surface (as is currently the way Python works), or would you expect more photons to be back scattered.  

![scat](https://user-images.githubusercontent.com/2530901/61046764-d8aba580-a3d5-11e9-885d-07335c5296ad.jpg)

According to Stuart, when as long as you have complete redistribution the emitted frequency profile is the same as the absorption profile (including all types of line broadening, and in particular including thermal and microturbulent broadening).  But this also means effectively that (on average) the photon has forgotten the direction from which it has come, and in that case one would expect forward and backward scattering to be symmetric with respect to the Sobolev surface.
