### ISSUE TITLE
Installation issues with gsl and Mac High Sierra

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#519]
I tried a fresh install of Python on my new Mac laptop which runs High Sierra and it is not installing correctly.  

It seems to install gsl properly  but when the mpicc complilation takes place, it produces the following errors

```
mpicc -O3 -Wall  -I../include -DMPI_ON python.o bb.o get_atomicdata.o photon2d.o photon_gen.o parse.o setup_files.o saha.o spectra.o wind2d.o wind.o  vvector.o recipes.o trans_phot.o phot_util.o resonate.o radiation.o wind_updates2d.o windsave.o extract.o cdf.o roche.o random.o stellar_wind.o homologous.o hydro_import.o corona.o knigge.o  disk.o lines.o  continuum.o get_models.o emission.o cooling.o recomb.o diag.o sv.o ionization.o  levels.o gradv.o reposition.o anisowind.o wind_util.o density.o  bands.o time.o matom.o estimators.o wind_sum.o yso.o cylindrical.o rtheta.o spherical.o cylind_var.o bilinear.o gridwind.o partition.o signal.o agn.o shell_wind.o compton.o zeta.o dielectronic.o spectral_estimators.o matom_diag.o xlog.o rdpar.o direct_ion.o pi_rates.o matrix_ion.o para_update.o setup_star_bh.o setup_domains.o setup_disk.o photo_gen_matom.o macro_gov.o windsave2table_sub.o import.o import_spherical.o import_cylindrical.o import_rtheta.o reverb.o paths.o setup.o run.o brem.o synonyms.o setup_reverb.o setup_line_transfer.o rdpar_init.o cv.o   -L../lib -lm -lgsl -lgslcblas -o python
ld: library not found for -lgsl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Now if I look in PYTHON/lib, I see
```
README          libgslcblas.a   libgslcblas.la
```

In older installations the gsl libraray is there also, but I am not finding this anywhere in gsl area

When compiling with gcc, I get a different set of problems
```
Pescado:source : make CC=gcc python
Compiling with gcc 4.2.1
YOU ARE COMPILING FOR LARGE RUNS, -03 -Wall flags
MPI_FLAG=
echo "#define VERSION " \"83a\" > version.h
echo "#define GIT_COMMIT_HASH" \"ef987a55d146266c7a0745e362a4ad33debdf5a2\" >> version.h
echo "#define GIT_DIFF_STATUS" 1\ >> version.h
gcc -O3 -Wall  -I../include    -c -o python.o python.c
gcc -O3 -Wall  -I../include    -c -o bb.o bb.c
In file included from bb.c:34:
../include/gsl/gsl_rng.h:23:10: fatal error: 'gsl/gsl_types.h' file not found
#include <gsl/gsl_types.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [<builtin>: bb.o] Error 1
```

This header is in gsl-1.15, but is not being put into our include folder.   I see the file and a bunch of others in software/gsl-1.15, but this is not transferred into lib/gsl

@saultyevil @smangham could you two do a fresh install onto your mac's and see if you encouter similar problems, even if you have an older version of the operating system on your machine (after making sure that you have installed the lastest security upgrades on them).  We need to sort out whether this is peculiar to my machine/operating system.

Aside: we are running gsl version 1.15 and probably need to upgrade to the current version wich is gsl 2.5

**Comment by saultyevil** [comment]
So I think I have good news and bad news about this.

For a clean install, if I run `./configure && make install` in the root Python directory, then GSL and Python compile without issue. But, if I then go into the source directory and run `make python`, then I see the same errors as Knox above. 

As an aside, I think that the gsl includes in bb.c are redundant. Python compiled fine on my Linux machine when I removed these two include statements and we do not seem to use any gsl types or functions in this file.

**Comment by kslong** [comment]
Great, Ed. Did you compile both with mpicc and with gcc? The two produced different results/problems for me.

**Comment by saultyevil** [comment]
Yes, compiling with `make CC=gcc python` and `make CC=mpicc python` gave me the same error. Do you know which version of OpenMPI you are using?  You should be able to use `mpicc --showme:version` to find which version you're using. I'm using version 3.1.2.

**Comment by kslong** [comment]
bash-3.2$ mpicc --showme:version
mpicc: Open MPI 1.10.7 (Language: C)

bash-3.2$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
bash-3.2$

**Comment by saultyevil** [comment]
I think I made a mistake earlier. I've had a look at the Makefile and everything seems correct and the Makefile hasn't been changed in over a year. But I think my problem was that I had the PYTHON environment variable configured incorrectly. When I updated it again as a last ditch double check and re-ran the install script, I now get all of the correct headers and libs such as the libgsl which Knox said he was missing.

 @kslong, could you check that this was not the issue for you?

**Comment by kslong** [comment]
I am quite sure that my environment variable for PYTHON was correctly configured.

**Comment by kslong** [comment]
@smangham At present, when one tries to clone Python on a Mac one gets a conflict because filenames are case insensitive.  

```
Sakana:PyInstall : git clone https://github.com/agnwinds/python.git Python
Cloning into 'Python'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 21262 (delta 56), reused 93 (delta 45), pack-reused 21077
Receiving objects: 100% (21262/21262), 191.48 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (13004/13004), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/rst/parameters/Wind.autogen.rst'
  'docs/rst/parameters/wind.autogen.rst'
```

**Comment by smangham** [comment]
I mentioned this in #530; are you happy with renaming the parameter `wind.fixed_concentrations_file` to `Wind_ionisation.fixed_concentrations_file` as a solution?

**Comment by kslong** [comment]
OK, I have made some progress on understanding what the problem is here.  If I download the gsl version we are using and simply make and install this, I do get all the requisite libraries, but there is something about the way we are running make so that the libgsl library is never being created when I install with Python.  It's odd because I believe I am using exactly the same configuration command that is in our Python makefile, when I compile it in my standalone (just downloaded version of gsl-1.15

The commands I used for the standalone version were

```
  565  ./configure --disable-shared --prefix=`pwd` CC=gcc CCP=ccp
  566  make
  567  make install
  568  ls lib
```
and what's in the lib directory is

libgsl.a                libgsl.la               libgslcblas.0.dylib     libgslcblas.a           libgslcblas.dylib       libgslcblas.la          pkgconfig

**Comment by kslong** [comment]
OK ... continuing to work on this issue.  If I replace the gsl library with a clean downloaded copy of the same version of gsl, then Python compiles without errors. This suggests that there is some difference between the gsl version we have, and the version that this should be.

To further explore this, I have downloaded a clean version of the repository and complied this with:

make install  2>&1 | tee make.txt

I have compared this to what I get if I replace the gsl library with a clean down load, as shown in the file below

[diff.txt](https://github.com/agnwinds/python/files/3312210/diff.txt)

When using the newer version gsl-1.15, there are a whole set of library related commands that are not being executed when use the version of dev that is on github, and this is why the library I need to complye Python is not being found.  When using the github version there are errors that are seen by these errors are not evident because we don't actually check that the various stages of create gsl have ben caught.

For the github version, grepping make.txt, gives
```grep Error -n make.txt
2750:make[3]: *** [Makefile:344: gsl-ref.info] Error 1
2752:make[2]: *** [Makefile:656: all-recursive] Error 1
2754:make[1]: *** [Makefile:373: all] Error 2
4870:make[2]: *** [Makefile:344: gsl-ref.info] Error 1
4872:make[1]: *** [Makefile:656: check-recursive] Error 1
5289:make[2]: *** [Makefile:344: gsl-ref.info] Error 1
5291:make[1]: *** [Makefile:656: install-recursive] Error 1
5854:make[1]: *** [Makefile:180: python] Error 1
5871:make[1]: *** [Makefile:206: py_wind] Error 1
5878:make[1]: *** [Makefile:229: windsave2table] Error 1
5880:make: *** [Makefile:50: install] Error 2
```
I get no errors when using the clean version of gsl.  I suspect there is some difference in gsl-1.15 in the two instances, but I have not been able to find it.  Note that it is also possible that my problem has to do with the version of make or something, since this problem first occurred on my new mac which has new S/W installed.

**Comment by kslong** [comment]
I have confirmed that the same problem does not exist on my old Mac, so this must be an interaction between things like make and what we have in the repository.

On my new mac, I am running gnu make 4.2.1

on my old mac, I am running gnu make 3.8.1

**Comment by kslong** [comment]
So the reason this fails, when it does, is because make is invoked in doc.  When this happens, make for gsl aborts on my new Mac.  But at this point the libraries or some of them have not been  made.  So to solve this problem, one needs to figure out why make in doc is failing.  

The problem is that as far as I can tell doc is the same in gsl as downloaded from gnu, as it is in the github.

As a quick fix to this issue, I have modified Makefile.in (using the -i option for make and make install of the gsl routines) so that make continues to try to compile the gal libraries even if there are errors along the way.  This is not really the ideal solution, but does allow all the libraries to be created.

**Comment by jhmatthews** [comment]
Knox, can this issue be closed now?

**Comment by kslong** [comment]
Yes, this issue can be closed and I am doing it now.  @jhmatthews 

Note that right our installation procedure currently not only compiles gsl, but also runs the tests of gsl.  it is not obvious this is necessary, and may be an especially poor idea in light of the fact that these tests are part of the travis compilation.  We could save time there, by deleting them.
