### ISSUE TITLE
Coronal approximation

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#52]
A possible requirement to do better where we have a hot plasma but no photons was seen in the PK04 geometry close to the disk, in the central source only case. This is rather specialised, but a fix might be simple.
The case of moderate density, but no photons is called the coronal approximation.
I wonder if reading in data from this paper: http://arxiv.org/abs/astro-ph/9806391
which is computed ion fractions for a range of T_e in the coronal approximation and using it as a backstop for cells with no photons might work.
This is not necessarily totally trivial, and as Knox points out, if there are no photons in a cell, why do we even care about it!

**Comment by lazygun37** [comment]
I think we probably need to think a bit more about the underlying 
physics that apply in these conditions. Here are some 
stream-of-consciousness thoughts:

1) If there are no photons in a given cell in a given ionization cycle, 
and therefore the cell reaches an unrealistic ionization state, can we 
be sure that, if the cell (and those around it) _had_ reached the 
correct ionization state, it would still have received no photons?

2) If we absolutely and completely insisted on radiative equilibrium -- 
in particular that radiation was the only source of energy input into 
and output from the wind -- then if we did have a cell at the end that 
received no photons, that cell presumably shouldn't be allowed to emit 
anything. Allowing it to emit would violate radiative equilibrium.

3) I think part of our problem is that, particularly in the Proga 
models, adiabatic heating and cooling can be significant. These 
represent non-radiative energy input and output. So, for example, a cell 
that is heated adiabatically can still emit quite a bit of radiation 
thermally, at least in principle.

4) Suppose we adopted coronal equilibrium for cells that receive no 
photons. I don't think it's blindingly obvious that such cells would not 
become significant sources of line emission in the model. Plasma in 
coronal equilibrium tends to emit basically everything in lines, so one 
could imagine such cells to produce significant line luminosity that, 
depending on the cell temperature, might be relevant to the wavelength 
ranges we care about.

5) I wonder whether there would be any problem with _thermal_ 
equilibrium for cells for which we adopt _coronal_ equilibrium...

Cheers,

C

**Comment by kslong** [comment]
I agree with Christian that there are no simple solutions here.  I think the problem needs to be a lot better defined, that we need to assess whether it is important, and that then and only then should we consider what to do about it in Python.  

I think work  on this should be done outside of Python by researching under what conditions we expect radiation to dominate the ionization structure of a plasma and under what conditions collisions dominate.  This involves working with the rate equations, and trying to understand if there is literature on how to deal with this regime.  

Finally, I'd suggest that github may not be the right place to document such an effort.

**Comment by Higginbottom** [comment]
OK, so I agree with the two comments above. I'll certainly be putting this firmly on the back burner for the time being - but having it on github at least puts a stake in the ground that hopefully we wont forget!

N

**Comment by jhmatthews** [comment]
Moved [here](https://sites.google.com/site/agnwinds/home/python---bugs) and thus closed with caveat.
