### ISSUE TITLE
xscatters is not used

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#526]
We have a variable in plasmamain  xscatters that does not appear to be used.  The comments in python.h say that it was there for diagnostic purposes.  Unless someone can think of a reason to keep it, then it should be removed.  

See #525 for slightly more information as this is where this was noticed.

**Comment by jhmatthews** [comment]
Hey Knox - looks to me like this is used in phot_history_summarize () which is called by extract - although unclear whether these routines are needed.

**Comment by jhmatthews** [comment]
@kslong any thoughts on this one, can we just close?

**Comment by jhmatthews** [comment]
Can we close this issue Knox, or alternatively should the phot_history_summarize () routine that uses xscatters be removed?

**Comment by jhmatthews** [comment]
My take on this is this looks like xscatters is used both in python and in py_wind, so I'm closing this. If there's a desire to remove the functionality of phot_hist then the issue can be reopened.
