### ISSUE TITLE
Output wind properties to VTK for debug

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#532]
We're (@saultyevil in particular) interested in outputting the wind properties each cycle to VTK for rendering and debug purposes. I previously developed this on this old branch:
https://github.com/smangham/python/tree/vtk/source
Annoyingly, I ran indent and touched half the codebase with the last commit. The only files that actually contain convent are `vtk.c`, `vtk_ion.c`, and `run.c`. 

```
      /* Save the various wind properties to a vtk file */
      char *property_names[] = { "temp_e", "density_c4", "density_h1" };
      void (*property_pointers[]) (WindPtr, FILE *) =
      {vtk_temperature_e, vtk_ion_c4, vtk_ion_h1};

      output_vtk (wmain, 0, geo.wcycle, 3, property_pointers, property_names);

```
You provide it with property names and function pointers to the functions that return the properties you want. This is the result of me attempting to write Python-style code in C, so...

**Comment by saultyevil** [comment]
This isn't a bug, or a top priority enhancement and is probably going to sit around for a long time. I have a copy of the code now (thanks Sam!) so I can work on this whenever I have a very empty work schedule (or boring weekend during the COVID-19 pandemic).
