### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#534]
We are turning the GitHub wiki into the main hub for documentation. We want:
- A page on papers, with some discussion of the physics in each
  - Frame as capabilities/usage?
- A page of references
  - Associate with the papers/applications?
- A basic quickstart users guide
- A series of worked examples (or links to the ipython notebooks in the Examples folder)
- Link to the RTD/Sphinx/other docs
- We want solid 'how-to-contribute-to-documentation' guidelines
- We need a list of action items for progress on the code release

**Comment by smangham** [comment]
I've ported the sphinx docs to wiki pages. Example is up on my fork wiki here: https://github.com/smangham/python/wiki
Tweaked the formatting until I was relatively happy. Some examples of ones that're well-filled are:
https://github.com/smangham/python/wiki/Central_object-Parameters
https://github.com/smangham/python/wiki/Reverb-Parameters
(links to the file are to the master branch, so the setup_reverb.c one won't work)

Not pushed to the main branch pending integration with Knox' changes. Still not quite sure whether to break each parameter out onto a separate page to allow for us to put categories on them like 'AGN input' instead of just relying on the parent info.

**Comment by smangham** [comment]
We want to show:
- How you add LaTeX
- How you add images
I'll convert some of Knox' wiki pages to rst as an example.

**Comment by lazygun37** [comment]
Closing -- the move to the wiki has happened, and the rest is just ongoing continuous work.
