### ISSUE TITLE
Interpolating model spectra with >2 parameters

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#539]
At present, when we read in spectra from a file we assume that there are two parameters associated with the model, nominally t and g, when we interpolate the models.  We need a better approach which can interpolate any number of parameters in a sensible manner.  

There have been a variety of complaints about this over time, and we need to decide exactly what we want here.

**Comment by lazygun37** [comment]
In principle, this isn't hard -- it's fairly straightforward to code up linear interpolation in N-dimensions. However, as always, there are complications, such as
- how to deal with extrapolation (going beyond grid edges)
- whether to (optionally?) interpolate on logarithms of parameters (useful for sparse grids spanning wide dynamic range); could of course leave this up to the user to define the grid appropriately
- how would we deal more generally with more complex models -- i.e. how we we tell Python what parameters are relevant etc...

For now, I'm rating this medium, but if there were specific projects for which we need this capability it would become high, presumably.
