### ISSUE TITLE
Create user case studies

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#545]
We want to build 3-5 'worked example' user case studies, as Jupyter notebooks. We also want to include them in the online documentation: https://nbsphinx.readthedocs.io/en/0.2.8/

**Comment by smangham** [comment]
@kslong and @lazygun37 are independently developing iPython notebooks with usage examples in.

**Comment by smangham** [comment]
Created one for reverb: https://github.com/smangham/reverb_example
Currently re-running an old run on `master` to see if I can get the same line profiles, as I was having difficulty getting a good TF with the `reverb.pf` example file and unsure if it's because that file was always bad, or if it's that something has changed in the interim...

**Comment by kslong** [comment]
If we carry out more reverberation studies (or others wish too), then this should be resurected, but for now I am labelling this a zombie issue and closing it.
