### ISSUE TITLE
Replace hardcoded indexes with DEFINES/enumerators

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#549]
In `spectra.c`, we have a ton of hardcoded array indexes that don't communicate well what they actually refer to. We want to replace them with defines, e.g. SPEC_CREATED=0, SPEC_EMITTED=1, SPEC_CENTRAL_SOURCE=2, SPEC_DISK=3, SPEC_WIND=4, SPEC_HIT_SURFACE=5, SPEC_SCATTTERED=6. That sort of thing.

**Comment by kslong** [comment]
I agree.  I noticed this yesterday.  I think this is the only routine in which these are used though.


.

**Comment by saultyevil** [comment]
This has been done with PR #647.
