### ISSUE TITLE
Default X-ray binary model

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#561]
We now have a source type called 'bh', which is intended to be a BH binary.  We now need to  have a reasonable set of defaults for this model, as we do for an AGN, star, and CV.  Ideally, this would produce an X-ray spectrum that showed some Fe lines.  

Does anyone have suggestions on what this might be, especially @Higginbottom

**Comment by jhmatthews** [comment]
This is now included in examples/basic/XRB_standard.pf (Thanks Nick!). Nick sent around some spectra from a model which was around 75% converged:

![image001](https://user-images.githubusercontent.com/3007249/71827023-3bd17880-3097-11ea-851f-2752f97494ee.png)

see also commit https://github.com/agnwinds/python/commit/5b4370f9978ab97c39b79567f8978d9f1b9680c3

closing.
