### ISSUE TITLE
Checks for model success (for ourselves and others)

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#564]
Given Python's very lengthy outputs, it is clear that for the release we need to provide a procedure for users to check their runs for convergence and excessive numbers of errors.  Additionally, for ourselves we need to codify the properties of a "good run".  There are two separate things to consider - for a given number of photons per cycle has the run reached a "steady" state and whether the run has actually "converged.   

We have starts on this, based on run_check.py, but this needs to completed.  It may also be advisable to add more of a summary at the end of the program outputs to indicate whether the program has converged.

One reason we need such a procedure for users, is to limit the difficulty of documenting what users need to look for.

**Comment by kslong** [comment]
One simple change to run_check that is needed is to adapt it so that it can check mulitiple runs, either all of the .pf files in a directory or all of them are on the command line.

**Comment by kslong** [comment]
@Higginbottom @mandyhewitt  @jhmatthews   I am hoping that all of you have been using run_check.py for looking at runs.  Does it basically satisfy what you think are the needs of typical users.  If not, what specific features would you add to the output, and why?  I do regard this program as moderately important, but would also like to close the issue, if nothing specific comes up.

**Comment by jhmatthews** [comment]
Closing this issue since run_check works well, and we have a separate issue about summaries at end of run #615
