### ISSUE TITLE
sv_detailedmode no longer runs

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#566]
When run with the `-i` flag in the Travis tests, `examples/travis/sv_detailedmode.pf` runs fine. When you run it *without* `-i`, it dies with the error:
```
wind2d: For domain 0 there are  25 cells of which 0 are in inwind, 5 partially in_wind, & 5 with pos. vol
wind2d: There are no wind cells in domain 0.  This seems unreasonble
```
Given there's only a 5x5 grid, it's not surprising that there are no cells that are fully in the wind. 
Issues here are thus:
* `-i` flag ends the tests before it actually checks the domains, we should move where `-i` stops the run.
* either
  * `sv_detailedmode.pf` has too low a resolution and it needs upping OR
  * the code should be happy with a model with only partially-filled cells

For the moment I'll commit my docu/variable rename branch with a non-working `sv_detailedmode.pf` because it's not actually any more broken than I found it...

**Comment by jhmatthews** [comment]
It's not clear to me if the -i flag should quit after the domains have been checked or not - it's supposed to only check the inputs, primarily for travis CI tests. I think it's reasonable that the code complains about only partially filled cells. 

I've modified the SV detailed mode pf file in commit https://github.com/agnwinds/python/commit/62cc701539b40a9db9ee7b824ec963d4c0bef27e

@smangham I'll leave it up to you what we do about the -i flag, but if you're happy with current behaviour this issue can be closed I think.

**Comment by jhmatthews** [comment]
Bit more cleanup in https://github.com/agnwinds/python/commit/49e9b31f785ba2046c59d719f529867dece4124c including a message for the user in the case where there are only partially in wind cells.

**Comment by jhmatthews** [comment]
Closing this - it can be reopened if @smangham thinks that the -i flag should quite later in the program.
