### ISSUE TITLE
Cycle numbers no longer print

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#567]
When running, the code outputs:
```
Cycle 0/0 of ulx1 : Photon    8000000 of   20000000 or   40.0 per cent
```
The code corresponding to this is:
```
    if (nphot % nreport == 0)
    {
      Log ("Cycle %d/%d of %s : Photon %10d of %10d or %6.1f per cent \n", geo.wcycle, geo.pcycle, basename, nphot, NPHOT,
           nphot * 100. / NPHOT);
    }
```
Which seems to be off- `wcycle` and `pcycle` are both markers for the current cycle. I'll fix this.

**Comment by kslong** [comment]
Be careful with this. Changing what’s printed out may be okay, but changing this internally is not desirable. Cycles run from zero.

Sent from my iPad

On Jul 22, 2019, at 9:20 AM, Sam Mangham <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #567<https://github.com/agnwinds/python/issues/567>.
