### ISSUE TITLE
Accessing beyond array boundaries in recomb.c

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#574]
There is a memory leak currently in the function macro_pops.  We currently allocate memory to *populations for each iteration of a while loop, but never free the memory at the end of each iteration. I'll merge in a fix which frees this memory  at the end of the loop in the mean time. 

I'm also going to attempt to run Valgrind on some small macro models to see if there are any other memory warnings elsewhere, but I have encountered a bit of trouble trying to run Python in Valgrind. But, I'll update this issue with the results when I finally get it running.

**Comment by jhmatthews** [comment]
Thanks for sorting this Ed. I think @kslong did run valgrind on python successfully a while back, but perhaps it was for a non-macro situation so this didn't show up. He might know how to get it working though.

**Comment by kslong** [comment]
Yes, last year we were looking into issues with Valgrind, and here is one of the notes I created at the time:

180915 - Continued working on Keara’s problem.  Checked h10_standard80 dataset; it also produces an error well into the program.  Installed Valgrind on science4 and begin to use it.  It indicates there are memory issues, on top of everything else. 

so valgrind did indicate there were memory problems, including with macro atom models.  But my notes indicate that we thought these were due to some of the arrays needed for macro atoms being too small, rather than the memory leak being descibed here.  Like so many other things we do, we tended not to follow up (in this case by continuing to work with valgrind), once we had solved the immediate problem.  We do have an Evernote page on how to use valgrind, for what that is worth.  It would be a good idea to run valgrind on something now, just to see what it says, if anyone has the energy.

**Comment by saultyevil** [comment]
I've been trying to get Valgrind to work again, but I'm greeted with this error:

```
saultyevil@ASTRO-REX:~$ valgrind python/bin/py
valgrind: mmap(0x40f000, 1585651712) failed in UME with error 22 (Invalid argument).
valgrind: this can be caused by executables with very large text, data or bss segments.
```

So you can use GNU size to see how big a binary is and how its split up. This basically shows that Python's bss segment is fairly large - the bss segment is pretty much where all statically allocated variables and arrays are stored, [wikipedia](https://en.wikipedia.org/wiki/.bss) has an ok article on it.

```bash
saultyevil@ASTRO-REX:~$ size python/bin/py
   text	   data	    bss	    dec	    hex	filename
1060136	  10088	1585652064	1586722288	5e9375f0	python/bin/py
```

To cut a long story short, basically when an executable is too large, the memory Valgrind requires to run can overlap into these sections and then it isn't able to run and just exits. There are a few bug fixes and workarounds floating about, but it's just finding the one which works on my machine when I have the energy :-). 

Anyway, since the memory leak is fixed, I'll update the title of the issue.

**Comment by kslong** [comment]
Please put the files needed to duplicate the error here.  Otherwise, we will have to start from scratch to investigate this.

**Comment by saultyevil** [comment]
I'm testing with a reduced version of the cv_macro_benchmark, using valgrind 3.13.0 and the latest version of dev.

[cv_macro_benchmark.pf.txt](https://github.com/agnwinds/python/files/3481060/cv_macro_benchmark.pf.txt)

**Comment by saultyevil** [comment]
I've noticed large memory usage again, so I have decided to look into this some more.

I built the latest version of valgrind (3.15.0). The underlying problem is that we have a large amount of statically/globally declared memory, which due to how Valgrind is designed, would result in Python's memory overlapping into the memory Valgrind allocates to itself.

Unfortunately, this has been in Valgrind for a long time and looks like it's just a limitation of the tool. I found a [workaround](https://sourceforge.net/p/valgrind/mailman/message/36744406/) to the problem though! Supposedly you can compile with the linker option "-Wl,-Ttext-segment=0x68000000" which changes something about the memory layout of the binary (this is some CS stuff above my pay grade). 

Valgrind now seems to work, so I shall try again to check for memory leaks.

**Comment by saultyevil** [comment]
I've run valgrind for both a simple atom and macro atom CV model. I ran valgrind with these options,

`valgrind --tool=memcheck --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no --xml=yes --xml-file=python --gen-suppressions=all`

Here is an overview of what I found:

**The Good**

* No memory leaks which are our fault
    * Known (and fairly harmless) memory leaks exit in MPI, e.g. MPI_Init()

**The Bad: actual bugs and SHOULD be fixed**

* Out of bounds array access, i.e. recomb.c: lines 416, 423, 431 total_fb  // 826 fb 
    * nion + 1 is used regularly when nion = nions. The arrays are only nions elements big, therefore the last index is nions - 1
* Off by 1 indexing errors, i.e. recomb.c line 691 num_recomb
    * Adding nions to an index to get the last element, instead of nions - 1 (off by 1 due to arrays in C being 0 indexed) 


**The Ugly: probably harmless, but less important**

* Uninitialized variables
    * Some if statements can depend on uninitialized values
    * Some uninitialized variables are used in calculations
* Write(buf) points to uninitialized bytes
    * string2int has a couple of scanf statements which trigger this

**Comment by saultyevil** [comment]
One of the out of bounds array accesses is particularly confusing to me. 

```c
for (nelem = 0; nelem < nelements; nelem++)
{
    imin = ele[nelem].firstion;
    imax = imin + ele[nelem].nions;
    
    for (i = imin; i < imax; i++)
    {
      if (xplasma->density[i] > DENSITY_PHOT_MIN)
      {
        if (mode == OUTER_SHELL)        //outer shell
          xplasma->recomb[i] = xplasma->ne * xplasma->density[i + 1] * integ_fb (t_e, 0.0, VERY_BIG, i, FB_RATE, mode);
        else if (mode == INNER_SHELL)   //innershell
          xplasma->inner_recomb[i] = xplasma->ne * xplasma->density[i + 1] * integ_fb (t_e, 0.0, VERY_BIG, i, FB_RATE, mode);

      }
    }

    xplasma->recomb[imax] = 0.0;        // Can't recombine to highest i-state
    xplasma->inner_recomb[imax] = 0.0;  // Can't recombine to highest i-state
  }
```

What was going wrong was imax was 1 too large on the very last loop iteration, i.e. for the final element.

`nions` is the number of ions that element has, from the neutral `istate = 1` all the way to the maximum ionisation state.

As an example, for Nitrogen,

* firstion = 12 (istate = 1)
* nions = 8 (istate = 8)
* firstion + nions = 20

Well, when I looked into the `ions` array and look at the Z for each ion, I found this..

```
----------------------------------------
 Ion number       : 12    (firstion)
 Atomic number    : 7
 Ionisation state : 1
----------------------------------------
 Ion number       : 19    (firstion + nions - 1)
 Atomic number    : 7
 Ionisation state : 8
----------------------------------------
 Ion number       : 20    (firstion + nions)
 Atomic number    : 8
 Ionisation state : 1
----------------------------------------
```

The take away from this is that, I think, the correct index for the last ion is infact **firstion + nions - 1**. Would it be sensible to add an "lastion" variable for each element?

I get a feeling that the above loop over imin and imax is then not correct. As imax is one larger than the highest ion... imax is actually the "netural ion" for the next element.

Have I understood this correctly?

**Comment by jhmatthews** [comment]
I think that's right Ed, at least in the sense that the highest ion in each element should be bare and imax should correspond to this and not the next elements neutral atom. Having a last_ion seems sensible to me to avoid this in future, since it's a very easy thing to miss. 

It does strike me that this is not completely general though - it might be possible in the code to not include the bare ion, but I suppose in that case you never have an ion above it to recombine from, so perhaps it's ok. @kslong @Higginbottom might want to confirm.

**Comment by saultyevil** [comment]
The purpose I had in mind for a `lastion` variable, is the same for the `firstion` variable really. It would be the index of the last ion for that element in the ion array, bare atom or not.

Anyway, the out of bounds accesses have been fixed now and I will be merging in the changes as soon as the final regression checks finish running after merging into dev on my fork. According to a previous regression test, it doesn't look like any of the spectra have changed incidentally as the OoB access usually ended up being 0 or rare enough for it not to matter.

I have run Python through valgrind with a couple of other parameter files as well, notably imported models. None of them report any additional OoB array accesses.
