### ISSUE TITLE
python won't compile on iridis

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#576]
Its been a while since I compiled on iridis - probably before the gsl change.... so I thought I should do it again.
Pulled latest version, and failed due to gsl issues.
So I deleted the whole repo, and tried to re-install from scratch according to the info on the git page.
Fails - looks like its due to the gsl change - here is the today.txt file!

[today.txt](https://github.com/agnwinds/python/files/3476849/today.txt)

hmmmmm

**Comment by saultyevil** [comment]
I just had a quick look through today.txt and I saw this,

```
mkdir /home/nsh2m14/python/include/gsl/; mv /home/nsh2m14/python/software/gsl-2.5/include/gsl/* /home/nsh2m14/python/include/gsl; mv /home/nsh2m14/python/software/gsl-2.5/lib/lib* /home/nsh2m14/python/lib/;
mkdir: cannot create directory `/home/nsh2m14/python/include/gsl/': File exists
```

It could be possible that Make gave up with the whole command when it couldn't create include/gsl since it already existed. Maybe we could replace mkdir with mkdir -p in the future to avoid this error.

**Comment by Higginbottom** [comment]
Will take a look.
The reason python won't compile is because the file gsl_types.h isn't in the gsl directory. It is in the directory on my Mac....

**Comment by Higginbottom** [comment]
OK - that does it. Are we all OK with me putting this change into Makefile.in on dev?

**Comment by Higginbottom** [comment]
Nope - that doesn't fix it. I not that on my Mac - when it is installing, there are lots of tests that seem to get done. Not on iridis...

**Comment by Higginbottom** [comment]
trying to install gsl in its own directory - I get errors like

/home/local/software/gcc/4.8.1/lib/gcc/x86_64-unknown-linux-gnu/4.8.1/include/varargs.h:4:2: error: #error "GCC no longer implements <varargs.h>."

like the compiler is trying to use some other path... This is also in today.txt

**Comment by Higginbottom** [comment]
This is sounding awfully familiar actually.... Let me look at some old error reports...

**Comment by Higginbottom** [comment]
here #235

**Comment by saultyevil** [comment]
That's interesting, are you using one of the intel compilers as your default c compiler? I just built Python with no issue using gcc 4.8.5 which I loaded on Iridis using `module load openmpi/3.0.0/gcc`. Although I'm on Iridis 5 so that may not be much help..

**Comment by kslong** [comment]
Once we sort this out, we need to test it everywhere.  

Furthermore, I think someone @smangham maybe needs to look at our installation  procedure to make sure that it is "standard" and robust.  I am not sure that is the case.  

Note that I believe that one should not specifically have to put moving a .h file some place. The gsl make should do this.   

I did recall that when I put the upgrade to gsl in, that one of the issues is that one could not tell if gsl had errored.  Instead the installation procedure just proceeds  One needs to capture the outputs and look for an Error message.  I think in reality the procedure of installation should stop if gsl was not successfully installed.

**Comment by Higginbottom** [comment]
@saultyevil No such module on iridis4

**Comment by Higginbottom** [comment]
OK, so it is still due to some kind of module clash. 
I removed all the modules from iridis, logged back in 
did ./configure and compile install, and it works.
Ugh.

**Comment by Higginbottom** [comment]
So I suppose what we need is someone who knows what they are doing (i.e. not me) to write a configure script that detects what is needed to compile everything (including gsl) and advise the user if something isn't right.
Normally, I think codes would expect the user to have gsl installed if it was necessary, and set the library paths correctly. Since we do it in this odd way where we supply a favoured version of gsl, we need to make sure that gsl can be compiled...

**Comment by kslong** [comment]
I agree.

I did change some of the installation instructions after I ran into this problem when updating to a newer level of gsl, but probably not all to suggest that one capture what is printed to the screen and then grep for an Error message.  I don’t know if you would have found your problem that way though.

**Comment by jhmatthews** [comment]
Closing this, since the more general issue is the gsl install, which has it's own ticket #587
