### ISSUE TITLE
photons lost with thick ghost zone in spherical model

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#592]
I'm unsure if this is a bug, and if it is I'm not sure where the bug lies.
Here is the background.

I have tried to set up a shell one radial cell thick, 90 theta cells, to compute the flux. 
It is my understanding that I need to explicitly set up an inner and outer ghost cell in radial coordinates, however the thickness of the inner ghost cell changes the number of photons seen in real cells near the disk.

Here is the .pf file:

[shell2.txt](https://github.com/agnwinds/python/files/3520509/shell2.txt)

essentially it sets up a central source with radius 1e10cm and reads in the model wind.

and here are two model files. They both have a shell running from 1e11 to 2e11
Model one has the ghost cell starting at 1e10 - i.e. right at the outer edge of the central source.
[model1.txt](https://github.com/agnwinds/python/files/3520523/model1.txt)
model two has the ghost cell starting at 9.9999e10 - i.e. just inside the inner edge of the shell
[model2.txt](https://github.com/agnwinds/python/files/3520528/model2.txt)

The version of the code with the flux logging isn't in dev yet, but you can see the same issue if you just look at the photon numbers per theta cell..

![nphot](https://user-images.githubusercontent.com/3329213/63346475-f7924580-c34c-11e9-874c-967208652271.png)

You see that the number of photons turns over in the thick ghost version - my best guess is that photons that cross the midplane whilst travelling in the ghost cell are not properly tracked. But I have no proof of this. 

The question is - have I just stuffed up making my model wind file - if so this is another thing we need to be very clear with users about how to set up.

If the case should deal with any width of ghost cell, then it may be a bug..

**Comment by Higginbottom** [comment]
It should be noted, that setting the inner radius of the ghost cell to the same number as the inner radius of the real cell results in an error. So the inner shell must differ but not too much. This is looking a bit bug-like...

**Comment by Higginbottom** [comment]
what seems to happen - for the first photon I've looked at in detail is that the photon is transported in space, allegedly to the first wind cell. However, it is still just in the ghost cell, but then transport in wind is called with an odd result that pushes the photon clear through the real cell...

**Comment by Higginbottom** [comment]
OK - this is a bug, and its a doooooooozy!

when we start a photon off, it is often not in the wind, and we have to translate in space to get it to the inner edge of the wind.
Translate in space moves a test photon through the grid, until it hits a bit of wind.

The first thing it does is work out the distance to the wind - by doing

ds = ds_to_wind (pp, &ndom);

this doesn't necessarily move the photon into a real wind cell however, it might not really be in the wind - I think this in only the case in an imported model, where you can set up your own ghost cells.

We now search for the first real wind cell by initially moving a test photon to the start of the wind

move_phot (&ptest, ds + DFUDGE); - note that we move it ds+DFUDGE!!!

We now enter a loop 

while (s < smax && where_in_wind (ptest.x, &ndom_next) < 0)

which jumps the photon through the grid until we either go smax or get into a real wind cell.

each time, we jump by

move_phot (&ptest, delta + DFUDGE)

where delta = ds_in_cell (ndom, &ptest)

so we jump from cell to cell. When the while loop drops us out, we have a distance s which is the total sum of all the jumps - this sum is s, incremented by s += delta + DFUDGE for each jump.

We now know how far to move our original photon, it is actually (ds+DFUDGE)+s

when we now move the photon however, we only compute ds= (ds + s - DFUDGE) - we subtract a DFUDGE because when we actually move the photon we do

move_phot (pp, ds + DFUDGE);

however, if you recall, right at the start, ds doesn't include the initial DFUDGE to get us into the start of the wind. So, we end up out by a factor of DEFUDGE. So we end up moving *exactly* the distance to the wind - which causes all the trouble. So, the fix is to add DFUDGE to the initial ds.

god this was hard to find....

**Comment by Higginbottom** [comment]
With the change:

![nphot](https://user-images.githubusercontent.com/3329213/63434565-43142480-c41d-11e9-9cbc-7ab8fe9cba36.png)


I think this has fixed it.
The fixed is over plotting the thin model line

**Comment by Higginbottom** [comment]
I was asked to see if this affects any other kind of wind. I believe that the problem only arises in an imported wind.
This is because the assumption is that the ghost cells are properly set up in normal models, so we don't have to deal with the possibility that an idiot user has made a very deep ghost cell. For non-imported models, the ds is added on at the end of the translate_in_space routine. For imported models, there is a process of jumping the photon through the ghost cells, and the last jump subtracts ds - which is then added back on. 
Basically I think its fine

**Comment by Higginbottom** [comment]
It is in the general code for checking where a photon hits the wind. So, any kind of imported model will use this code - so the fix applies to any model…

Nick

**Comment by kslong** [comment]
Great.  Close #592
