### ISSUE TITLE
Photons getting stuck in vertically extended disks

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#604]
This is more of an issue for documentation purposes, until we look more seriously into using vertically extended disks more, i.e. with our TDE models.

Whilst investigating issue #584, I took a closer look at how photons were behaving in the same models but with a vertically extended disk - though this may have been complicated by the fact that the winds I tested were spherical which are unaffected by disks (see the function header for stellar_velocity in stellar_wind.c).

What can happen is that photons can become "stuck" in the accretion disk, which reports the error,

```
Error: walls: 863 The previous position  1.2871e+13  2.6187e+13  4.9844e+10 was inside the disk, correcting by  -2.7487e+05
```

There are a couple of confusing things which are happening here which could be causing this error to trigger.

Firstly, it seems sometimes the distance to the disc surface can be large in comparison to the z coordinate. Which can result in the photon being moved to the other side of the domain, i.e. from -ve to +ve z. I'm not 100% sure how reflections work for vertically extended disks, so this may or may not be the behaviour we want. But either way, it appears that the photon is not being pushed all the way through to the surface of the disk.

Secondly, in `walls()`, we call `s = ds_to_disk(pold, 0)` where `allow_negative = 0` meaning we should not be expecting the function to return a negative value. However, `ds_to_disk()` is quite clearly returning negative values, as in the error code above `s = -2.7487e+05`. Incidentally, because we move a photon s - DFUDGE, this negative value often works out in our favour and seems to push the photon past the disk surface so it no longer becomes stuck. 

We need need to think about a test model with with a vertically extended disk so we can understand this problem better, as well as to include in our example pfs.

**Comment by kslong** [comment]
@saultyevil   Is this still happening, and if it is, please put a .pf file here.
