### ISSUE TITLE
Very occasional but very damaging errors in shell model

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#608]
I've been playing with getting models of J_nu from a thin shell model to use to compute line driving forces to compare with cloudy.
I have been driven mad for a day or so with occasional totally bonkers models that look for example like this:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3329213/65139993-7db1b280-da05-11e9-9d18-eab6ad8206ea.png">

*reducing* the number of photons makes it nice - or doing serial rather than parallel. 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3329213/65140068-a5087f80-da05-11e9-89b7-002496e7033d.png">

It turns out that just one photon in 10 million was screwing up royally. When the ds_in_cell was being computed, ds_to_sphere is called twice, once for the inside of the current shell, once for the outside. Both calls returned VERY_BIG. I'm unsure of exactly the geometry here, but I think it must be that the photon is right at the edge of the sphere, travelling at a tangent - so it never intersects either the inner or outer edge. Because both s and smax in spherical_ds_in_cell are the same number, this is returned. It is then reduced to length(p->x)/2 but the photon still flies 5e10cm in a 1cm thick cell. All the estimators end up totally dominated by this one photon, coz a million going 1cm cant compete with 1 going 5e10! 

The solution? Well, I think since it is *so* rare, and most likely only happens in a spherical thin shell model where the geometry is extreme - I think the best thing to do is throw away a photon where s and smax are both equal to VERY_BIG in spherical_ds__in_cell - this number is a flag for an error after all..

Here is the .pf file is anyone wants to play along - but it is very fluky.
[input.pf.txt](https://github.com/agnwinds/python/files/3625836/input.pf.txt)

**Comment by Higginbottom** [comment]
Hmmmm, turns out that it is almost impossible to easily throw away a photon at this point. It might be better to tell the photon to move a tiny amount - DFUDGE might make sense - to break the deadlock...
Or perhaps add additional checks to catch that we are in a place that isn't going to work..

**Comment by Higginbottom** [comment]
OK - I think that nudging the photon by DFUDGE is the simple band-aid. The failure is basically because when a photon is flying close to the edge close to a tangent, you might need a could of nudges to get it fully out of the cell. This is very unlikely to happen often. I've added an error condition..

**Comment by Higginbottom** [comment]
Regression tests show no changes in the example runs.
I propose pulling this in if there are no objections.

**Comment by jhmatthews** [comment]
I've closed this based on the above discussion and merged pull request, if I'm wrong please reopen @Higginbottom
