### ISSUE TITLE
boundary layer blackbody not computed fully

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#609]
I've been trying to make a nice blackbody SED using the boundary layer in a thin shell.

This the the .pf file:

[input_bb.pf.txt](https://github.com/agnwinds/python/files/3627658/input_bb.pf.txt)

Basically I'm requesting photons from 1e-6eV to 20000eV from a 5.49e4K black body to match the SED used in Stuarts test calculation 

Now, oddly enough only two photon generation bands get filled and the input spectrum looks like this:

![input_bb_created](https://user-images.githubusercontent.com/3329213/65171397-adcb7680-da42-11e9-9fe9-ebdec2e1a81a.png)

Very odd. Looking into it - the init_bl code uses integ_planck_d which only returns a result if the frequencies are between the ends where the bb function is tabulated. This is not correct - it should actually call emittance_bb, which itself calls integ_planck_d if we are between the tabulated ends, or does more simple numerical integrations outside those limits.
This is why the frequency is cut off  top and bottom.

Replacing

*f = q1 * integ_planck_d (alphamin, alphamax) * lum_bl / STEFAN_BOLTZMANN;

in bl_init in photon_gen.c with

*f =  emittance_bb (freqmin, freqmax, t_bl)*lum_bl/(t_bl*t_bl*t_bl*t_bl*STEFAN_BOLTZMANN);

gives this improves input spectrum...

![input_bb_created](https://user-images.githubusercontent.com/3329213/65172802-8e821880-da45-11e9-96cc-26d6e7e07670.png)

**Comment by Higginbottom** [comment]
Regression tests all fine

**Comment by jhmatthews** [comment]
Looks like @Higginbottom fixed this one with #610 and #633, so closing.
