### ISSUE TITLE
calculation of recombination coefficients slow

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#612]
This issue has cropped up since the move from the old numerical recipes codes to gsl - in particular for Romberg integration.
NSH noticed that the py-pluto runs were going significantly slower, and traced this to the computation of the recombination tables (init_recomb) which had increased in time from a few seconds to a few minutes. Not a big problem for a long run but when python is restarted every couple of cycles and is running on hundreds of cores. init_recomb is not parallelised.

Investigation showed that the Romberg implementation on gsl is a little slower than qromb, but this is not important. What *is* important is that a few calls were taking *seconds* and maybe a thousand where taking 1/10s. These long runs were refining to use up to 2^29 refinements, a lot of calculations. Oddly some qromb calls were also using similar numbers of refinements, but clearly the resulting calculations are just longer in gsl.

The fix - 1: We could simply *force* the gsl Romberg implementation to only use up to 2^10 subdivisions by setting the size of the workspace to 10 rather than 30 as it is currently set. This speeds things up - makes little difference to the answers for the tests I did - but seems a little dodgy.

The fix -2: Change the gsl integrator to use gsl_integration_qags - which is a slightly cleverer integrator which can cope with singularities. This got the speed, and does a better job of getting the same answer with the tests I did. Unfortunately it does throw more errors, and these need to be captured and dealt with. In particular, it is prone to GSL_EROUND errors, which is where the roundoff errors exceed the requested accuracy. This can be caught, and the answer at the point where the error is thrown can be used as the best guess. I've done this and created an error for counting. This will essentially replace the "qromb - too many steps" error that we sometimes see and always ignore!!

I have run the regression tests - no significant changes.

I've added everyone in on this, since any change will effect anyones runs. But if nobody can see any major problem I'll putt in the fix..

**Comment by kslong** [comment]
@Higginbottom it seems to me we ought to try to figure out what is going on in the "bad" cases.  I wonder if it relates to the sorts of things that @jhmatthews found in other integrations, where the limits were such that most of the region was zero, and hence it kept subdividing.  Perhaps, the first step would be to print a bunch of information out about what happens when the error occurs.  I think this would be useful no matter what integration method we use.  Is there an example .pf file, where the whole issue arises early on, or is there something we can set up to make it happen quickly (ideally in single processor mode).

**Comment by Higginbottom** [comment]
Yeah - probably correct. We've not bothered in the past - but I guess we can hope to do better... I'll do it once I've fixed a knotty problem I'm currently working on.

**Comment by Higginbottom** [comment]
I have been unable to work out any reason for the code to throw these errors. However, my suggested fix is to simply default back to romberg integration if tags throws the error. Initial testing shows that we can successfully integrate all the cases that error in qags.

**Comment by Higginbottom** [comment]
My new code which tries romberg if qags fails gives identical (to within the noise) results in the regression tests, runs faster the romberg only, and there are no errors suggesting romberg fails if qags fails
Suggest pushing to dev...

**Comment by kslong** [comment]
@Higginbottom  Can this be closed?  If so would you do so.
