### ISSUE TITLE
Simplification and collation of atomic data files

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#614]
There are a large number of atomic data files in the data directory - some going back many years. They are summaries here: https://www.evernote.com/shard/s303/nl/133638373/e7ba67ee-0400-4139-8c1d-88aef22e4d7f/

It has been decided that we should simplify this - making the assumption that the atomic80 collection is the best set.

The procedure followed is as follows:

1: Set up new directories called atomic and atomic_extra. The atomic directory is essentially a copy of atomic80 with totally redundant files removed, and some files moved into atomic_extra. Some files from atomic78 are temporarily put into atomic_extra to cope with regression testing.

2: Run regression tests:

**Comment by Higginbottom** [comment]
The change from atomic78 to atomic80 for the regression tests has caused a lot of changes. For example the agn_short:

![agn_short](https://user-images.githubusercontent.com/3329213/66564877-fc0ef980-eb58-11e9-9181-0d323f2eae3d.png)

and the cv

![cv](https://user-images.githubusercontent.com/3329213/66564895-03360780-eb59-11e9-9d90-40729449a137.png)

**Comment by Higginbottom** [comment]
The change in the hydrogen recombination spectrum is due to the change from top base cross sections for Hydrogen to VY cross sections to allow for inner shell processes - admittedly not really needed for hydrogen. It makes no odds for emitted spectrum, since all these photons are locally reabsorbed. - hence the almost identical emitted spectrum. The remaining small changes are due to the small changes in the number of lines modelled and the change in collisional line excitation.

Comparing runs made with new innershtell style sections with full atomic 80 - i.e. only levels and collisions are different 

![cv](https://user-images.githubusercontent.com/3329213/66565628-d71b8600-eb5a-11e9-8d2e-b244f9a26588.png)


However, the AGN changes are more complex.

**Comment by Higginbottom** [comment]
Changing from the old collisional data coll.data to the upsilon linked is making some difference. Here we compare the atomic78 run, to a run with mostly atomic80 data, but the collisional line data from the 78 version.

![agn_short](https://user-images.githubusercontent.com/3329213/66569037-932c7f00-eb62-11e9-91bd-7c594378ccba.png)

Only the CIV line is different.

**Comment by Higginbottom** [comment]
OK, so using the atomic78 PI cross sections and the 78 collision strength basically makes them very similar. So it is probably getting slightly different temperatures.

![agn_short](https://user-images.githubusercontent.com/3329213/66578240-a5aeb480-eb72-11e9-8d02-cb98efc6edf5.png)

**Comment by Higginbottom** [comment]
Now, the 1D sn example is more problematic. It uses the Kurukz line list and a different set of atomic abundances. This is a comparison between the old run and one using mostly atomic80 data - but with some elements removed to match the old atomic data file.
Pretty different


![1d_sn](https://user-images.githubusercontent.com/3329213/66579245-6aad8080-eb74-11e9-89fa-030e120760e2.png)

**Comment by Higginbottom** [comment]
OK, so those huge differences were because I hadn't changed the atomic abundances to the crayzeee ones in the elem_ion file for the SN version. Below is everything as for the atomic80 apart from the abundances changed to the SN
The line list is the Verner one in atomic80 - the SN usually uses the Kurukz line list...

![1d_sn](https://user-images.githubusercontent.com/3329213/66609006-d3feb500-ebaf-11e9-9ed0-5b4d5fe788f4.png)

**Comment by Higginbottom** [comment]
Changing to the Kurukz line list gets us more wiggles - this is interesting in itself...

![1d_sn](https://user-images.githubusercontent.com/3329213/66609222-6010dc80-ebb0-11e9-8f51-4c3c4c5062ee.png)

**Comment by Higginbottom** [comment]
The remaining change is due to the use of VFKY cross sections in atomic78 rather than innner/outershell rates. i.e. the new is more accurate because auger ionization is included.

**Comment by Higginbottom** [comment]
To summarise:

For the atomic80 - I'm going to basically just leave atomic80 as it is - there are differences between the old regression tests (with atomic78) and the new, but these are understood and not errors - we don't know how different the runs would be if they were allowed to converge anyway!

For the sn test - it is essentially all atomic80, but with a different elemental abundances file (stored in atomic_extra) and kurukz line lists. It is also different, but again the results are now understood and the new data is better. This does leave the question as to wether we should use the kurukz or Verner line lists more generally.

I'm going to modify the atomic data - removing all the old standard_ files, and changing all the examples to point to atomic80..

The macro atoms files are more complex - need to consult on this..

**Comment by kslong** [comment]
This is essentially closable at this point. Further work in this general area is in  #623
