### ISSUE TITLE
Merge atomic data repository into the main python repository

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#630]
It is possible to merge repositories (and keep all the history).  I am wondering whether as part of the release, we should merge the atomic data repository into the main python repository.  Here is the reason, I think this might be desirable.

We have recently changed the structure and removed versions of the atomic data from the data repository.  This means that if we want to go back to earlier versions of python, and run, for example, the regression tests, we must checkout both an earlier version of python and an earlier version of the atomic data.  This is fairly common activity and a fairly annoying problem, at least for me.   If we merged the repositories we would avoid this problem, I believe, because I think that the atomic data changes would be interleaved with the Python changes.  If we make more change to atomic data as we go forward this problem will get worse.

This would simplify installation in a sense, because one would not have to put download two repositories, but I don't see this a a major determinant right now. 

As I recall, our argument for keeping the repositories separate was that we thought the data repository was large and fairly static.  The first is still true, but the last is not.  

Anyway, this is the time to think about this and decide what the best approach is for the long-term.

**Comment by jhmatthews** [comment]
I take the point about compatibility. I'm not really sure what the best solution is. The data repo is 1.6G which is a bit large given how github stores files - as snapshots, albeit probably in some clever compressed way. I think this can in principle make checking out, pushing and so on quite a slow process. Git recommends keeping repos below about 300 MB. 

The data hasn't actually changed enough for this to matter - so it must be that if one wants to simply check out an old version and run the test, it can't find standard78 or whatever? In other words, it's an issue of "pointing" to the right file, as much as anything?

**Comment by kslong** [comment]
Yes @jhmatthews  the basic problem is one cannot find the files and so when you want to go back to try to repeat something that was done last year, you have to checkout both the correct version of the data directory and the correct version of Python.  Furthermore, where as you can keep old versions of the python executable around in the bin directory, we do not have the same situation for the data directories.  I suppose one could say that we should have updated all our master files to work with the new directory structure.  

Github currently says:

We recommend repositories be kept under 1GB each. Repositories have a hard limit of 100GB. If you reach 75GB you'll receive a warning from Git in your terminal when you push. This limit is easy to stay within if large files are kept out of the repository.


The current data repository is 1.6 GBytes and Python is 247 MB, so I agree we would be a bit large, but nowhere near the limits.

**Comment by jhmatthews** [comment]
Ok, so perhaps it's not crucially big then. That might be ok, although I am a bit worried about the amount of commits we make and whether git is clever enough to keep things small enough.

Regarding the merging of the repositories - I suppose this will help in future if similar things happen again, but this won't sort out the current issue - as in, the issue will only be solved for future changes of a similar kind, but the old versions of the code will still have a problem. In which case, we could probably design another scheme that preserved backwards compatibility (in future) without merging the repos. I don't have a problem with it though if the size is really going to be ok.

**Comment by kslong** [comment]
I  think it does sort out the current issue, because the histories are not lost, but are  merged.  If you go back you actually always have consistency.

**Comment by jhmatthews** [comment]
Ok, I'm a bit confused how this can work but I'll try it out when I get a minute.

**Comment by jhmatthews** [comment]
This doesn't seem to work Knox. The histories are unrelated and have no way of knowing about each other, so when I actually try and checkout old commits you either just see the data repo or just the python repo at a given commit snapshot.

**Comment by kslong** [comment]
Sigh!  You are right.  It looked fine, but isn't really.  

It seems like you have to do something more complicated, see

https://stackoverflow.com/questions/40976798/how-to-merge-several-git-repos-into-one-and-interleave-histories

This may also work

https://stackoverflow.com/questions/34760674/how-to-combine-two-unrelated-git-repositories-preserving-history

or possibly this

https://dev.to/detunized/git-fu-merge-multiple-repos-with-linear-history-4kci

I think what all these things do is to start at some early commit and then to one by one update the repository in chronological order from each repositiory.

**Comment by Higginbottom** [comment]
This all seems like a nightmare. Are we doing it so future users will see the code and the data as one repo?
Maybe we should make an entirely new repo for our first release. Then new users won’t see our billions of old commits. We can go over to using the new repo for future work?

Just an idea…

N

**Comment by jhmatthews** [comment]
How many files are we talking here Knox - Isn't it only a handful of standard78 files? in which case, should we just keep those masterfiles in the data repo?

**Comment by kslong** [comment]
Well, James, since we changed the extensions, it is essentially all of them.

And to answer your question, NIck, both for ourselves and our users as was outlined in the very first message.

I am not sure this is a good idea, but ...  we have only gotten away with two repositories because we kept all the old data and because we did not change the data directory often.

An alternative, I have thought about is to write a script that would find the appropriate data commit  based on the python commit.

Another thought when we run a model is not only to record the python commit but also the data commit in the header of the spec files, etc.

**Comment by kslong** [comment]
I should modify what I said slightly.  We could update the standard78 file itself to point to names with the  new extensions, and this would tend to minimize the problem.

**Comment by kslong** [comment]
This link advertised a procedure  (located on github) that one could use to merge two repositories

https://stackoverflow.com/questions/40976798/how-to-merge-several-git-repos-into-one-and-interleave-histories

I tried it, and it ran, but did not merge the two repositories into one.  it created the first repository, and said it was going to do something with the second, but does not seem to have.  I tried it using the python repository first, and with the data repository first.

```
../git-tools/join-git-repos.py -n -o xxx ../Python.191031:dev /Users/long/Projects/PyMerge/data:master >foo.txt

../git-tools/join-git-repos.py -n -o xxx  /Users/long/Projects/PyMerge/data:master ../Python.191031:dev >foo.txt
```

**Comment by kslong** [comment]
I guess I am resigned to the following approach

- When we want to go back to test an earlier version of the program, we either go back using the tag on data called data83, which is prior to when Nick started to make changes
- We recreate masterfiles pointing to the old data, with their new extension names, but we do not delete any of the old atomic data from the repository.  (This will not work if we change any of the underlying files)
- Going forward, we implement some procedure such that we record commits from both repositories whenever we run python.  If we do not do something like this, I don't see how we will ever  be able to separate changes in the data files from changes in the code when we encounter a problem.

**Comment by kslong** [comment]
It looks like the idea of merging the repositories is infeasible.  We still need a better design for the atomic data repository IMHO, which allows straightforward access to the old data for us, while keeping the repository simple for new users.  However, This aspect of the what to do about the atomic data repositiories is perhaps dealt better in #614 or #623.
