### ISSUE TITLE
Inconsistencies with Converging Cells

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#631]
There are currently some inconsistencies and possibly some sub-optimal choice with how we define and control converging cells.

**Inconsistent Definitions**

In python.h, converging is defined as:

*converging is an indicator of whether the program thought the cell is on the way to convergence 0 implies converging*

I find this counter intuitive to begin with, since it would make more sense to me to label converging cells as 1 (true), rather than 0 (false).

In the actual code in convergence(), we do this:

```c
if (xplasma->dt_e_old * xplasma->dt_e < 0 && fabs (xplasma->dt_e) > fabs (xplasma->dt_e_old)) // The cell is converging
{
  xplasma->converging = 1;
}
```

There are a couple things wrong here. Firstly, if this if statement evaluates as true then the attached comment implies that we think a cell is converging. However, we contradict the comment in python.h and set converging = 1 for the converging cell. Secondly, above the if statement, we define converging:

*Converging is a situation where the change in electron temperature is dropping with time and the cell is oscillating around a temperature.*

This is inconsistent with the if statement as we check `fabs (xplasma->dt_e) > fabs (xplasma->dt_e_old)` implying, if I understand correctly, that a cell is converging if the change in electron temperature is increasing. This is probably is a typo for the relational operator used and is easy to fix.

Anyway, in check_convergence(), we count the number of converging cells by:

```c
if (plasmamain[n].converging == 0)
  nconverging++;
```

This is at least consistent with the definition in python.h, but is inconsistent with the code in convergence() which is flagging (probably incorrectly) converging cells as 1. So when we output the number of converging cells, we aren't outputting anything we previously flagged as converging. The output would actually include cells which are consistently increasing/decreasing in temperature, as well as legitimately converging cells (due to the mistake in the if statement).

While this probably makes very little difference on the operation of the code, I think we should clean up this up before we release Python to avoid future confusion.

**Controlling Gain**

As a really brief aside, after having a conversation with Christian, we are not sure if damping the gain for how much the electron temperature can change is optimal for converging cells.

Ignoring the error in the if statement above, we are concerned that if the gain is damped enough, we may create a situation where it takes multiple cycles to oscillate around a temperature; rather than one step. 

This would mean the cell would be flagged as not-converging (as xplasma->dt_e_old * xplasma->dt_e would be > 0) and the gain will be increased for next cycle. This doesn't seem entirely optimal and would be worth thinking about more - it maybe something worthwhile to discuss in a future telecon.

**Comment by kslong** [comment]
I tend to agree that the nomenclature for conversion is odd and not as useful as one might hope. However, I would note that using zero for converging is consistent with what we do for converged. 

The tactics we use to change the gain are old, and certainly merit rediscussion, but we would need to go slowly and do a lot of testing before altering them. I am not convinced that the gains and speed that would greater than can be achieved by gradually increasing photon numbers between ionization cycles. 

I have spent a little time recently trying to understand what is required for a cell to remain converged and that also needs to be part of the discussion.

**Comment by kslong** [comment]
@lazygun37 I agree. The code looks broken.  For sure it should be, 

```
 (xplasma->dt_e_old * xplasma->dt_e < 0 && fabs (xplasma->dt_e)< fabs (xplasma->dt_e_old)) 
```
A cell is converging if it t_e is oscillating about a point and the change in temperature is decreasing in magnitude.

Note, that if we get seriously into this, we should probably say that it can only be converging, if it is not "converged", so we have 3 categories of cells, converged, converging, and not yet converging (which are those cells which are marching in one direction or the other).  

Note also, that we may want some measure of convergence that is not tied to a specific value of 5%,  e.g quantities like   the mean fractional temperature change  and the standard deviation of the fractional temperature change  (or I note that James has defined a weighted version of convergence in his paper)

**Comment by saultyevil** [comment]
I agree, having a converged cell labelled as not-converging or converging is confusing and should be avoided.  

On another note, I switched the relational operator to a < in the if statement and labelled converging as 0 (which is the definition of converging according to python.h) and ran the standard CV model. On the left is the changed converging code and on the right is the original code,

![Screenshot from 2019-10-31 14-44-22](https://user-images.githubusercontent.com/19627279/67957189-23536680-fbed-11e9-92d4-a966273e9b3e.png)

I think this makes more sense. It doesn't seem likely that all the cells are converging at the start and we now start with no cells or very little actually converging. Then we see that the number of cells which are converging increases with cycle which, given that we generally start converging towards the solution after a few cycles, makes sense to me. 

I'm not sure what will happen to converging line as the convergence increases. But I can only guess that a converged cell could actually be labelled as converging, so that would be interesting to see if converging continues to increase if I run for more cycles.

**Comment by saultyevil** [comment]
So apparently I managed to merge in my proposed changes into upstream/dev instead of into my own fork (sorry). I'm really not sure how that happened - it happened on a Friday so maybe I was distracted by something). Good news is that my changes don't change the regression tests or *convergence* results - but obviously this does effect how many *converging* cells there are. 

Unless we want to discuss gain more, I think we can close this issue as the main problem has been solved.

**Comment by saultyevil** [comment]
Since I have merged in the fix for the original issue here and that we want to clean up the number of open issues, I'm going to close this. If we want to discuss our philosophy regarding gain, we can re-open this issue or open a new issue.
