### ISSUE TITLE
Mistake in CIV luminosity in py_wind? [diagnostic only]

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#643]
I think I've discovered an error in how CIV line luminosity is reported in py_wind. Pressing "L" allows you to get the line luminosity for certain lines, but this seems to be too high when I try for CIV for my AGN model - in fact the cumulative total is higher than the system luminoisity.

The bit of code is:
```C
if (lin_ptr[nline]->macro_info == 1)
        {                         //If this is a matom line
          d2 = den_config (&plasmamain[nplasma], lin_ptr[nline]->nconfigu);
        }
        else
        {                         //If this is not a matom line
          two_level_atom (lin_ptr[nline], &plasmamain[nplasma], &d1, &d2);
        }
        x = (d2) * a21 (lin_ptr[nline]) * H * lin_ptr[nline]->freq * w[n].vol;

        if (geo.line_mode != 4)
        {
          x *= z = scattering_fraction (lin_ptr[nline], &plasmamain[nplasma]);
        }
```
which looks different to the equivalent function in lines.c. I would have thought a simpler approach is simply to replace the above lines of code with something like:

```C
    x = lum_lines(&w[n], nline, nline + 1);
```
which will be consistent with the normal operation of the code.

This might mean that there is an error in Fig. 8 of Mangham et al. 2017 (first reverb paper) where we show CIV emissivity, and possibly also in Fig. 2 of my 2016 paper, although it looks like the code was changed in between those two papers.

**Comment by jhmatthews** [comment]
I can fix this issue easily, but do we need to do anything about past publications? (see comment above)

**Comment by kslong** [comment]
We should definitely fix this error so it does not propagate.  And we should track down when py_wind changed to make sure we know what papers were actually affected.

**Comment by jhmatthews** [comment]
This change seems to have been made in commit c085393ea on 2017-06-16 - but this involves a commit called "Updating dev" so it may have been made earlier in reality. This places it during the review stage for the first reverberation paper so I'm guessing that the emissivity plots for CIV are not quite right, but that the figures in my 2016 paper are safe. Not sure what we want to do about that @smangham

**Comment by jhmatthews** [comment]
Note that the fix above isn't quite right because this routine was seemingly supposed to be called for macro-atoms too (although one can also use macro-atom level emissivities for this), and lum_lines calls two_level atom which doesn't work for macro-atoms (exits if line is macro-atom). One could either duplicate code or put the relevant code from lum_lines into a subroutine, i.e.:

```C
      two_level_atom (lin_ptr[n], xplasma, &d1, &d2);
      x = foo1 = lin_ptr[n]->gu / lin_ptr[n]->gl * d1 - d2;

      z = exp (-H_OVER_K * lin_ptr[n]->freq / t_e);


//Next lines required if want to use escape probabilities

      q = 1. - scattering_fraction (lin_ptr[n], xplasma);

      x *= foo2 = q * a21 (lin_ptr[n]) * z / (1. - z);

      x *= foo3 = PLANCK * lin_ptr[n]->freq * xplasma->vol;
      if (geo.line_mode == 3)
        x *= foo4 = p_escape (lin_ptr[n], xplasma);     // Include effects of line trapping
      else
      {
        foo4 = 0.0;             // Added to prevent compilation warning
      }
     lum += lin_ptr[n]->pow = x;
```

Would become:

```C
    two_level_atom (lin_ptr[n], xplasma, &d1, &d2);
    x = get_one_line_lum(lin_ptr[n], d1, d2, xplasma);
    lum += lin_ptr[n]->pow = x;
```

The routine get_one_line_lum could then be called from py_wind in both the non macro and macro case, passing different d1 and d2 in each case.

**Comment by jhmatthews** [comment]
I tested whether this appears in Sam's 2017 paper. It looks to me like it's OK, actually. Here's Sam's CIV emissivity in figure 8:
![Screenshot 2020-01-16 at 12 08 12](https://user-images.githubusercontent.com/3007249/72524181-43440f00-3859-11ea-8e4f-f188608778a3.png)

Here's a comparison of the m16_agn.pf model with and without the fix to the line luminosity calculation, on the same colour scale as Sam's figure:

![c4_test](https://user-images.githubusercontent.com/3007249/72524169-3cb59780-3859-11ea-839d-5a5bffec4ae0.png)

The 'fixed' version looks closer to the published figure with some small changes, and this probably uses different atomic data and less photons.

**Comment by kslong** [comment]
Great.  I hate having to be involved in errata.  Cheers, Knox
