### ISSUE TITLE
Travis not running on Pull Requests

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#672]
We were having a discussion elsewhere about Travis not running on Pull requests, but that issue #667 is closed, and not really relevant for this.   But we need to continue this discussion.

One can which pull request had Travis run on them from 
https://travis-ci.org/agnwinds/python/pull_requests
It looks like they stopped 2 months ago.

There is some chatter on the internet about this problem, dating around the end of the year, see

https://github.com/scala/nanotest-strawman/issues/45

If you follow this though it looks like they did something to their yml file to fix it, see

https://github.com/scala/nanotest-strawman/pull/46/commits/8eab5f0f6b0f59bf9669d6e3a2588e10536f598d

Another possibility I guess is that something changed, when we changed the type of account we have on github.

At any rate, @jhmatthews , I think this is something for you to solve.

**Comment by jhmatthews** [comment]
I think I've fixed this. It seems travis wasn't working at all, for any pushes or PRs, the only recent build is one that I triggered manually.

I think it was to do with crossing over to an organisation, which meant travis was no longer authorised to access the account. I've changed this and pushed to dev. You can see which third parties have access to the agnwinds organization by going to Settings->Third part access in the organization settings.

Today, I pushed a cleanup commit to dev that successfully triggered a build. 

This issue can be closed but please check next time we open a pull request that travis runs as normal @kslong @mandyhewitt @kslong @Higginbottom - and reopen this issue if it doesn't.

**Comment by kslong** [comment]
Thanks for fixing this, James.
