### ISSUE TITLE
Settting a Minimum temperature - Arguments that it should be 1000 K

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#68]
This issue has been noted by NSH in some runs testing the effect of 'fixing' the FB cooling bug on the PK04 geometry.
Some cells that are in the very dense part of the failed wind, with very few ionising photons, cool to very low temperatures despite heating being very much higher than cooling. This appears to be due to a discontinuity in the FB cooling brought about by a line which sets the FB cooling to zero if t_e is less than 1000K.
The figure below shows this effect. The top panel is all the heating mechanisms over a 50 cycle run, with the blue line showing the total cooling. The lower panel is the cooling mechanisms with the blue line as total heating.
![pk04_large_disk_agn_cell_474](https://f.cloud.github.com/assets/3329213/2149506/599af700-93f5-11e3-8bd0-6a7ed1090b1e.png)
You see that once t_e drops below 1000K, FB cooling (which is dominant) vanishes, and after that I'm not exactly sure what goes wrong.
The main point is that there is an implied minimum temperature of 1000K, below which bits of the code start to give up. In fact there are at least three more minimum temperatures.

TMIN - 2000K - the temperature that cells with no photons are set to.
MIN_TEMP - 100K - the minimum temperature used to compute n_e in the initialisation of the ionisation loop.
total_free - 100K - below this free free emission is set to zero - this _may_ be the reason why the cell above never drops below 100K.

It seems to me, that we pick some kind of global minimum temperature (2000K??) that we do not permit cells to cool below, we can flag a warning if this happens, so we can count them, but it seems less than ideal to just have various bits of the code bug out when they hit various temperatures.

Comments??

**Comment by kslong** [comment]
@Higginbottom to document whether there was actually a solution to this problem, and if so what it was.  If not, he should describe where this is a problem or not, and then close.

**Comment by Higginbottom** [comment]
As far as I can make out, this was never solved. And indeed I do see very very cold cells in the current hydro work. So we should discuss this at some point!

**Comment by kslong** [comment]
We have moved on from this in the sense that we have systematically reduced the minimum temperature to 100 K in low_temp2.  There a lot of issues about including low temperatures including whether we have the right physical processes and data in the program, but these need to be broken up into individual topics in the future.
