### ISSUE TITLE
Python not exciting properly in multiprocessor mode on Exit comnand

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#682]
In #462 there was a problem that the 2010 AGN model had velocities exceeded c.  I made a fix that is supposed to check when a wind model has such velocities and then exit via the Exit command.  However, this does not seem to be fully exiting when running multiple threads.
The relevant  .pf file is here

[ulx1.pf.txt](https://github.com/agnwinds/python/files/4376794/ulx1.pf.txt)

**Comment by saultyevil** [comment]
I can't replicate the problem on different three machines (linux desktop, MacBook and linux server). I wonder if this was one of those one time hiccups? Or did you see it not exit properly multiple times? The code looks correct to me.
