### ISSUE TITLE
Example ulx1.pf is failing because it has velocities greater than c

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#697]
We recently fixed/band aided a problem where velocity of a wind exceeded the speed of light.  Our fix was to cause Python to exit.

However, one of the models in the examples directories ulx1.p has this issue.  There are at least two possibilities here.

- The only place that the speed exceeds c is outside the actual wind region.  In that case, we may want to improve the check an allow the model to remain.

- The model has a speed that exceeds the wind in the actual wind region.  In that case we need to replace this model with something more suitable.

But we should determine which is the issue before deciding how to proceed.  I think the ulx1.pf model was intended to replicate some of the models @Higginbottom used in some of the XRB papers.

**Comment by Higginbottom** [comment]
The XRB_standard.pf parameter file in examples/basic was supposed to be the XRB file. The ulx1.pf is much older - it was moved into position in 2016 by James but was probably written before that. Happy to try and get it running, but we should work out what it is supposed to be there fore before expending energy...

**Comment by kslong** [comment]
Interesting.  I agree, Nick, we need to figure out what we want, and if we cannot figure out anything sensible we should remove it. But it's part of the Travis build so if we remove it, then it needs replacing.  (The original reason I raised this issue was because I think one ought to be able to run the all of the .pf files in the examples directory and this one does not run.)

Ideally, I think we would have something that represents an X-ray binary since as far as I can tell we have no other examples of an X-ray dominated spectrum in our examples. AGN have a hefty disk component.  Two possibilities occur to me.  Rework one of your zeus inputs for one of the models into a model that can be imported, something you implied you were working on anyway  Alternatively, simply dummy up a wind that kind of represents what you came up with in one of your X-ray binary papers -- that is a slow wind with about the right mass loss rate and angular distribution.  Check it enough to make sure it produces some Fe absorption. (If we were trying to be clever, we would take one of the hydro sims, and actually see how closely it approximated a KWD or SV model, but that is probably more effort than this is worth right now.)

Whatever one does, we should add a Readme file or something to capture what the model is.  Ultimately we probably should do that with all of the pf files in beta, but I'm just suggesting here that we put a brief paragraph somewhere so that when we get to documenting the beta .pf files better, we don't have to scramble to remember what this one was.

**Comment by Higginbottom** [comment]
We do have something that represents an Xray binary - its XRB_standard.pf - in examples/basic

**Comment by kslong** [comment]
Ah.  In that case, why don't you remove the ULX .pf file, but re-do Travis so it uses this.  You have to make a mod to the .travis.yaml file.  It's pretty obvious what you need to do there, but if it's not obvious to you on inspection, either James or I can do this.  If XRB_standard takes a long time to run, the version used by Travis should be cut down so it would have a shortish run-time, and different name, e.g. XRB_short, not because the routine is actually run in Travis, but because I think we should be able to fully test the Travis files.

**Comment by Higginbottom** [comment]
Wilco!

**Comment by Higginbottom** [comment]
I’m a bit boggled. I copied the fiducial_agn parameter file from the travis directory - it looks like this would take hours to run on a normal machine. I’m assuming travis has lots of cores? Or something. Presumbaly as long as I give the XRB_standard run about the same number of photons, grid cells, and cycles as fiducal_agn then all will be well?

**Comment by Higginbottom** [comment]
Oh wait - the travis file doesn't actually run anything - it just does py -I  to check the parameters are ok..

**Comment by Higginbottom** [comment]
We don't know what this parameter file was meant to be - and XRB_standard was the one for XRBs. This has now been put in the travis directory, and ulx1.pf has been expunged.
