### ISSUE TITLE
Bizarre rdpar problem when asked for imported file name

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#698]
When working with a .pf  file that you need to enter the name of the imported file, the question now gets asked is:

````
Wind.type(SV,star,hydro,corona,kwd,homologous,shell,imported)   imported
Wind.coord_system(spherical,cylindrical,polar,cyl_var)   spherical
Switching to interactive mode for this variable.
Additional inputs from the terminal may be required to complete the .pf file
Wind.model2import (spherical,cylindrical,polar,cyl_var ) 
````
but the actual rdpar statement in import.c is:

```
  rdstr ("Wind.model2import", filename);
```
and so the part in parenthesis should not be there.  Instead one should get

```
Wind.model2import :  
```

In commit from last August

commit c36573afb8864ece63acf9ed0f34f474f3a2d7a0

One gets instead
````
Wind.type(SV,star,hydro,corona,kwd,homologous,shell,imported)   imported
Wind.coord_system(spherical,cylindrical,polar,cyl_var)   spherical
Switching to interactive mode for this variable.
Additional inputs from the terminal may be required to complete the .pf file
Wind.model2import ()
````

which is better.  

The changes in rdpar.c don't make it obvious what is happening.  

@saultyevil  do you have any idea what is going on, since you have been working on imported models the most.  I don't seem to see this problem in other instances when enter everything interactively.    Here is the .pf file that illustrates the issue:

[foo.pf.txt](https://github.com/agnwinds/python/files/4541776/foo.pf.txt)

**Comment by kslong** [comment]
It does not help to add (xxx) into the "question".  When you do that the printed question becomes.

````
wind.model2import (xxx) (spherical,cylindrical,polar,cyl_var)
````

**Comment by kslong** [comment]
On linux, with dev, I get

````
Wind.coord_system(spherical,cylindrical,polar,cyl_var)   spherical
Switching to interactive mode for this variable.
Additional inputs from the terminal may be required to complete the .pf file
Wind.model2import (var )
````

**Comment by saultyevil** [comment]
It's probably because we never initialise filename to something, i.e.

```c
  char filename[LINELENGTH];
  rdstr ("Wind.model2import", filename);
```

I suspect `filename` will sometimes be blank and other times it may have something in it, and probably depends on what the compiler feels like doing. I assume `filename` was left blank, because there is no "default" imported model name, unless we choose to put something like "imported.model".

**Comment by kslong** [comment]
Yes, that is what I just figured out as well.  I will fix it.  K

**Comment by kslong** [comment]
The previous messages explains why this problem.  rdstr expects one to provide a suggested answer for all variables and this had not been done. The fix was simple, but we should be careful in future to avoid instances like this.
