### ISSUE TITLE
Incorrect calculation of dv/dy

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#70]
**Brief Description:** The calculation of dv/dy, and hence div_v, appears to be wrong.
**Version:** 77a_dev, but old, very old.
**To Reproduce:** Any model, in particular a macro atom model with a slowly accelerating wind will fail.
**Discussion:** I've discovered what I think is a potentially serious bug in how we calculate dv/dy in a cell. This could have implications for @Higginbottom 's Proga models and we should look into it sharpish.

I was running macro atom models with adiabatic cooling implemented and was getting some models crashing, as I had a loop which quite if adiabatic cooling was negative. Obviously, adiabatic cooling shouldn't be negative in an SV model, so I had a look at what was happening. Adiabatic cooling was negative because div_v was calculated as negative- so this was a basic problem with when the wind is first set up. div_v is calculated in wind2d.c. This is a little tricky to follow- but basically I was getting the error message and this was because the dv/dy value was negative, and if you have a slowly accelerating wind model then this can make the whole div_v negative. Ok, so why was it negative?

**problem:** I realised that, if your only y velocity can come from conserving angular momentum from the disk, then I think that div_y will **always** be negative if calculated as above, because the calculation is not quite right. 

Imagine a cell with it's centre at y0. Go dy along the y axis. The rotational velocity you now have will be less, because the radius of the curve you lie on will have increased and these velocities are Keplerian initially. here's a schematic:

![dvdy 1](https://f.cloud.github.com/assets/3007249/2207550/de618a74-9974-11e3-872b-0b06decafab6.png)

So, what we do here, by evaluated vy at y0 and y0+dy should instead be evaluated at y0-dy and y0+dy. Then I think you get the correct answer, which is **in a model with rotational velocity only then dv/dy should be zero**.

So, when I fixed this, did negative values go away? yes. Was the dvdy zero? no.

I thought this was because there were problems in how we interpolated to get dvdy, but actually this is just a simple misinterpretation by me. The reason dvdy is not zero is because, in general, there is a radial component to v_y and we have a non zero radial velocity. So, the v_y evaluated at y0+dy is different to the v_y evaluated at y0-dy because the radial component makes a different angle with the y axis there, even though the angular component is the same.

This fix does stop div_v being negative, which is the most obvious requirement.

**Comment by kslong** [comment]
James,

vwind_xyz gives you the velocity in cartesian coordinates.  That is what 
it looks like here, and I would not have named the routine this, if that 
was not the intention.   Most of the calculation is carried out in 
cartesian coordinates, as it should be.  This is also by intention, so 
that it would be relatively easy to adopt an arbitrary grid..   Note 
that we support, spherical polar, polar, and spherical coordinates.

The velocity stored in the wind structure is  the velocity in the xz 
plane, which will be the same in cartesian and polar coordinates.

If there is a problem about any of this, it would hae to be in 
coord_fraction, not in vwind_xyz.  I'm not yet convinced there is a problem.

Knox

**Comment by jhmatthews** [comment]
This is all good now- I've tried to summarise this issue as best as I can on this issues page to keep the bug report concise. When I've tested this, I'll merge and @Higginbottom should run a Proga model to see what it does to collapsing cells and adiabatic effects in general (not much, fingers crosses!)

**Comment by Higginbottom** [comment]
I don't think I will - coz in the paper I have turned off all adiabatic effects!!

**Comment by jhmatthews** [comment]
Ah yes, of course Nick. This issue is now fixed in the dev branch and closed.
