### ISSUE TITLE
Addition of fiducial TDE model for examples and regression test

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#714]
Knox correctly pointed out last telcon that there are no example parameter files for any of the TDE models. Ideally, we would want a "tde_fiducial.pf" model to sit in the examples directory, and a model which can become part of the standard regression tests.

It would also be beneficial if I added the CNO data files to the repository as well.

**Comment by kslong** [comment]
I don't necessarily think it should be a regression test.  I think that will probably run too long.  I simply meant we should have something in the examples directory, so that if a worry arises we can run it.

**Comment by saultyevil** [comment]
This issue can be closed with PR #719
