### ISSUE TITLE
Dielectronic recombination - small bug

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#72]
Playing around with making figures, I have found that a small oversight in the subroutine compute_zeta which calculates the ground state recombination rate correction factor defaults back to CKs tabulated results if there is no dielectronic recombination data.

This is a mistake, that has probably never impacted anything, since DR has never been turned off for any production runs.

More broadly, having the DR correction bundled up with zeta is probably not a great idea in the long term, but we will probably start to move towards a whole new ionisation approach…

This can be fixed with a simple change - I'll do it next Monday when I can liase closely with James to make sure I'm up to date.

I may also try to do some fixed to compute Zeta that will smooth out the interpolation carried out over GS and Total recombination rate data from Chianti.

**Comment by jhmatthews** [comment]
Yes, let's fix this on Monday, as I may want to have DR switched off for my macro atom models.

**Comment by jhmatthews** [comment]
@Higginbottom Has this been tested, i.e. can we remove the diagnostic Log statements?

**Comment by Higginbottom** [comment]
It has been tested in a very simple manner - just looking at the output via an artificial loop over t. It looks smooth and continuous for carbon.
It would be great if you could take a look as well, check the logic…

**Comment by jhmatthews** [comment]
I've checked the logic and removed log comments. Looks Ok to me.
