### ISSUE TITLE
volumes in wmain and in plasma

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#748]
We store the volume in two places in the code.  in wmain and in plasmamain.  

Currently 
* wmain vol is the observer frame volume in the wind.  
* plasma vol in allowing for clumping

With cmf, wmain will probably stay unchanged, but plasma vol will be the cmf value.  

Unfortunately making sure that vol are used properly is made difficult because wman vol is used a proxy for saying as cell is in thew ind or not, in many places in the code.

This should be replaced, so that we use wmain inwind instead of volume for all checks.  Once this is done, a check needs to be performed to make sure the right volume is used everywhere in the working part of the code.

**Comment by kslong** [comment]
Note that there are other issues that should be cleaned up at the same time.  There are a number of routines, e.g cooling, where the loop is being made over wind cells, which would be more transparently made over plasma cells.

This goes back at least a decade where the wind and plasma structures were combined.  

Fixing this is made a bit more difficult by the fact that some of these routines are fairly hierarchical, that is one needs to go down to where a calculation is actually made, and make sure a plasma cell and not a wind cell is being called.

**Comment by jhmatthews** [comment]
Obviously there are some more general issues here regarding historical stuff, but I had a few thoughts on the CMF side. At the risk of rehashing earlier discussions, it seems to me that we will rarely actually need to use a CMF volume - depending a little on how we decide to store estimators and so on. 

On the density side, we might use both - for calculating wind emission, for example, I think we'd probably want the CMF values of density (or we can use observer frame and transform an energy at the end). For calculations of ionization states I think you can actually store either - the important thing is really that the calculation itself is done in a consistent manner (i.e. all rates must be in the same frame). I was envisioning rate estimators to be stored in the CMF, so that was why I originally in favour of storing densities as CMF. I do think there's an argument for keeping as much of the plasma structure as possible as an observer frame value, but I'm not sure yet.

**Comment by kslong** [comment]
For what is worth, the current version of Belfast20 has CMF volumes for the plasma density

Sent from my iPad

On Aug 3, 2020, at 5:27 AM, James Matthews <notifications@github.com> wrote:

﻿

Obviously there are some more general issues here regarding historical stuff, but I had a few thoughts on the CMF side. At the risk of rehashing earlier discussions, it seems to me that we will rarely actually need to use a CMF volume - depending a little on how we decide to store estimators and so on.

On the density side, we might use both - for calculating wind emission, for example, I think we'd probably want the CMF values of density (or we can use observer frame and transform an energy at the end). For calculations of ionization states I think you can actually store either - the important thing is really that the calculation itself is done in a consistent manner (i.e. all rates must be in the same frame). I was envisioning rate estimators to be stored in the CMF, so that was why I originally in favour of storing densities as CMF. I do think there's an argument for keeping as much of the plasma structure as possible as an observer frame value, but I'm not sure yet.

**Comment by kslong** [comment]
Just a continuation of my quick note above.  My view is that the decision to keep the plasma variables mostly in the observer frame is identical to the question of whether we work as I much as possible using CMF properties to calculate CMF parameters, or whether we use an "ansatz" to allow us to perform most of the calculation in the observer frame with a "fudge factor" in the equations.  i am going to go with the former approach for now to see how bad the issues are with teh approach I favor.  But if someone wants to go ahead with the other approach, that is also fine.  Presumably that will allowwus to check for consistency between the two approaches, which could be a good thing.  If anyone takes up this challenge, they should begin with the current version of Belfast20 and make a new branch from it.  All you need to do to get back to the second approach is to remove the redefinition of density and volume.  All of the other changes I have made, except for these are a bit of refactoring so that functions were split up more cleanly and a good bit of documentation, including noting where more possible changes to the code are needed.  This are all marked by XFRAME.

**Comment by kslong** [comment]
At this point, I have dealt with most, if not all, of the places in the program where we used a positive volume in an if statement to say whether a cell was in the wind or not.  There are still some examples of this, but the number is greatly reduced. 

However, the aspect of this that remains is whether we actually are using the volumes we want in the structures.  The reason there is an issue is that volume in the observer frame is a proxy for the invariant product of volume and time.  Ideally there would be a variable with a more descriptive word for the variable e.g invariant_vol_time or something, as good programming standards suggest a name should be fully descriptive of what the variable represents.

**Comment by kslong** [comment]
We settled on using the CMF volume, and this is fully implemented in the code.
