### ISSUE TITLE
double counting xplasma->j and xplasma->ave_freq increments in indivisible packet mode

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#751]
The variables xplasma->j and xplasma->ave_freq are currently increment twice per photon ds in indivisible packet mode (geo.rt_mode == RT_MODE_MACRO). Once in translate_in_wind() just after bf_estimators_increment, and once in update_banded_estimators, which is called from within bf_estimators_increment. 

the fix is just to remove the duplicate lines of code in translate_in_wind(). 

Having looked through the code it looks like these are mostly diagnostic and used to report to the user. we have banded versions of average frequency which is more important and is used to get spectral models. One exception to this, is that when there is no spectral model in a band, we do use xplasma->j in compton.c (but normally we try and integrate over Jnu). So this could in principle make a difference to some runs, but I expect the effect is relatively small. 

It might be good @Higginbottom if you could just check you agree with what I've said so we can be sure this doesn't affect any published work.

**Comment by jhmatthews** [comment]
Actually - the above is not right, because t_r and w (dilution factor) are also calculated based on ave_freq and j, in wind_updates2d.c. So, this could feasibly have quite a few impacts - either on any work using matrix_bb, but also on any simple ion level populations that use dilute boltzmann approximations. So tests should definitely be run for published macro-atom models.

**Comment by Higginbottom** [comment]
But this is only if running in macro atoms mode right? 

Nick

**Comment by jhmatthews** [comment]
Yes. it only happens if you enter the geo.rt_mode==RT_MODE_MACRO if statement in translate_in_wind. Although as Stuart often says, this is not really macro-atom mode, but indivisible packet mode, but that's another discussion.

**Comment by Higginbottom** [comment]
OK, so I’m in the clear :-) But others who have published work with that mode might need to double check…

Could be over-ionized or over-excited…

**Comment by jhmatthews** [comment]
In a stellar model with h10_standard80, this seems to make remarkably little difference. I don't quite understand why. The t_r is more or less unchanged because you divide the double counting out, but the dilution factor is a factor of two different - which in matrix_bb mode should (and does) change all the ion fractions by a factor of 2. 

This probably means the impact on the other models will be fairly small but we should check. It might affect your comparisons with CMFGEN @kslong - might explain some of the differences.

Here is the old and new version in a stellar model with matrix_bb ionization mode:

![old](https://user-images.githubusercontent.com/3007249/89559176-36930280-d80d-11ea-9c78-77e9f1a16377.png)
![new](https://user-images.githubusercontent.com/3007249/89559183-385cc600-d80d-11ea-9e3f-438adf54f695.png)


I've fixed this in dev. It can be closed when we've run published macro models with and without the fix. For most things it will only affect dilute level populations.

**Comment by jhmatthews** [comment]
@saultyevil it looks like xplasma->ntot might also be double counted in macro-atom mode - in translate_in_wind and update_banded_estimators - do you agree?

**Comment by saultyevil** [comment]
Yes, definitely agree. It looks like in update_banded_estimators is trying to avoid double counting the same photon entering the cell as well, rather than the one in translate_in_wind is just adding up all photons. To me, I would keep the one in updated_banded_estimators as it's consistent with how we count the number of ionizing photons.

**Comment by jhmatthews** [comment]
Agreed. I'll make that change in dev and pull into belfast20.

**Comment by kslong** [comment]
@jhmatthews   Can this b closed?

**Comment by jhmatthews** [comment]
It's been done in dev and belfast 20 - but could remain open until we've tested the effect.

**Comment by kslong** [comment]
We have nominally fixed this; I am going to close it now
