### ISSUE TITLE
Incorrect degeneracy in last listed ionised states for metals including and beyond Rb in simple atom _elem_ion files

### ISSUE THREAD

**Issue by rgupta106** [sirocco-rt/sirocco#752]
Whilst fixing bug 749, I found a potential issue in the _elem_ion files. In the xdata/atomic_macro/*_elem_ion.dat files, the last listed ionised state (for metals Rb and heavier) is incorrectly labelled as "Bare" and for some have an incorrect degeneracy factor (g). The final listed g is labelled as 2 all the way down from Rb but the correct g depends on that ions shell structure. However, unless these ions are used, this is a relatively low priority bug and should be considered if using these atoms.

e.g. See the following in python/xdata/atomic_macro/CIIICIVCV_c10_CV1LVL_elem_ions.dat around line 615

IonV   Rb  37   1   2    4.17700 1000   0     ..3p^63d^{10}4s^24p^65s(2S_{1/2}) 
IonV   Rb  37   2   2 1.0000e+20   0   0     Bare                                                     <--- This is the last listed ionised state for Rb

The singly ionised ion is incorrectly labelled as "Bare" and also has an incorrect g (which should be 1 after looking at the NIST database). This issue continues for the heavier metals (i.e. the final listed ionised state is incorrectly labelled as "Bare" with a potentially incorrect g). Note that the g in this last ion can be different and must be looked up on the NIST database. (e.g. Mb II (listed as having a g of 2 should actually be 6).

The same issue can be seen in the other _elem_ions.dat files.

**Comment by kslong** [comment]
@mandyhewitt   Can this be closed now?  I thought you all had updated all of the files.

**Comment by mandyhewitt** [comment]
Stuart and I propose removing all atomic data beyond Nickle as there is unlikely to be any requirement for these heavier elements to be tracked. Additionally, required information to calculate correct atomic values would be difficult to locate..

**Comment by kslong** [comment]
Sounds reasonable to me.

**Comment by kslong** [comment]
As recommended, all Ion beyond Ni have been removed from the element ion tables in xdata.   The elements are still there, commened out, but the ion information has been completely removed.
