### ISSUE TITLE
luminosity, heating and cooling flows in plasma and geo structures

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#756]
We have a bunch of variables like lum_ff in the plasma and geo structures, where we tend to have an individual double variable for each quantity. It would be neater and allow for easier code if we instead had an array for luminosities, cooling and heating, indexed by define statements. for example, xplasma->lum_ff would become xplasma->lum[FF]. This would make it easier to store, for example, different quantities in different frames, and would enable us to clean up certain bits of code like wind_updates and the heating and cooling routines. 

The only problem with this is a) it's a bit tedious to do and b) it touches a huge portion of the code and one has to make sure it's all done right - probably with careful checks and sed/find-replace scripts or similar. You'd presumably want to then make sure the code produced identical output before and after the change. 

Here's how I would imagine this would look in python.h:
```C
  double lum[N_RAD_PROCESS];
  double cool[N_THERMAL_PROCESS];
  double heat[N_THERMAL_PROCESS];

/* these lines define the different thermal and radiative processes */
/* radiative processes must be listed first! */
#define LINES       0    /* line transitions */
#define RAD_BF      1    /* radiative recombination and photoionization */
#define FF          2    /* free-free */
#define COMPTON     3    /* compton and inverse compton scattering */
#define IND_COMP    4    /* induced compton */
#define DR          5    /* dielectronic recombination */
#define DI          6    /* direct/collisional ionization */
#define AUGER       7    /* auger ionization */
#define ADIABATIC   8    /* adiabatic cooling and heating */
#define SHOCK       9    /* additional shock heating */
#define CH_EX       10   /* charge exchange */
#define N_RAD_PROCESS      3   /* the number of possible radiative processes for generating wind photons */ 
#define N_THERMAL_PROCESS  11  /* the number of possible thermal processes */
```

Perhaps something to do once we've got a basic frame version working, rather than right now?

**Comment by jhmatthews** [comment]
I have written a hacky SED script that appears to work for this purpose, but it can be run on the code at a later time.

**Comment by Higginbottom** [comment]
That seems like a fine idea - but I also think it is something to do once the dust has settled on the frame stuff...

**Comment by jhmatthews** [comment]
Closing this at least for the moment since it's not a priority. If someone has the time to do it, they should reopen.
