### ISSUE TITLE
Inconsistencies in the calculation of theta_min and theta_max of KWD wind in knigge.c

### ISSUE THREAD

**Issue by rgupta106** [sirocco-rt/sirocco#760]
We found that the calculation of the theta_min and theta_max dimensions for the KWD wind in knigge.c is inconsistent. Namely, in the input files, the d parameter is asked for in units of r_star whereas in the calculation of theta_min,

Secondly, the calculation of the outer wind theta_min in the code involves the use of the the disk radius however, we want to use the input parameters r_max and d to calculate this. See Fig. 1. of Multidimensional modelling of X-ray spectra for AGN accretion disc outflows (Sim et. al, 2008).

I have made some proposed changes to the code.

**Comment by rgupta106** [comment]
lines 118-125 (original) knigge.c
-----------------------------------
zdom[ndom].wind_rho_min *= geo.rstar;  
zdom[ndom].wind_rho_max *= geo.rstar;  
zdom[ndom].wind_thetamin = atan (1. / zdom[ndom].kn_dratio);
/* Somewhat paradoxically diskrad is in cm, while dn_ratio which is really d in KWD95 is in units of WD radii */
zdom[ndom].wind_thetamax = atan (geo.diskrad / (zdom[ndom].kn_dratio * geo.rstar));

updated lines
---------------
zdom[ndom].wind_thetamin = atan (zdom[ndom].wind_rho_min/zdom[ndom].kn_dratio); /* units of r_min and d are now consistent (RG) */
zdom[ndom].wind_thetamax = atan (zdom[ndom].wind_rho_max/zdom[ndom].kn_dratio); /* units of r_max and d are now consistent (RG) */
zdom[ndom].wind_rho_min *= geo.rstar;
zdom[ndom].wind_rho_max *= geo.rstar;
/* Somewhat paradoxically diskrad is in cm, while dn_ratio which is really d in KWD95 is in units of WD radii. (Re-arranged the ordering of this however, the previous comment still applies for subsequent calculations. (RG)) */

**Comment by rgupta106** [comment]
Subsequent calculations below line 125 will need to looked at further as related issues may still be present.

**Comment by kslong** [comment]
What has been done so far looks correct for a flat disk, but is definitely now correct for a vertically extended disk.  It also appears that the normalization was not adjusted for the fact that all of the mass loss has to come from a portion of the disk

**Comment by kslong** [comment]
The changes that I have made to knigge.c do seem to produce properly normalized mass loss rates in when wind rmin and wind rmax are not the innter and outer radius of the disk.  I now get approximately correct rates for both flat disks and vertically extended disks.   Here are the models that were used to test the resluts, and  ipynb script to get the mass loss rates.   The comparison was between py84g and py84h (the versions of these that exist on 201116)  There is a Doit file that must be moved up, but then one can run regression tests.  


[z.models.201116.tar.gz](https://github.com/agnwinds/python/files/5549546/z.models.201116.tar.gz)
