### ISSUE TITLE
macro atom estimators for bb transitions

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#770]
The routine bb_estimators_increment contains the following note, written by Stuart at some point:

 * For the moment, the increment to the estimator is taken to be
 * weight * (1 - exp(-tau))/ tau / dvds
 * This is slightly different from what I do in my code (not
 * accurate to v/c corrections). If calculations where accuracy to
 * order v/c is needed then this routine should be improved.

Assuming this note is still correct, this routine needs to be fixed as part of the co-moving frame project.  If the note is not correct, then it needs to be removed.

**Comment by ssim** [comment]
I think this is an old comment. I think it's referring to the fact that w would previously have just been the observer frame energy (effectively) and that tau_s would be effectively neglecting an eta, I think.

I think that if the tau is now all correct and the energy consistently transformed (i.e. the weight) then, at least internally, this routine is ok.

**Comment by kslong** [comment]
To avoid confusion, the comment has been removed from the code.
