### ISSUE TITLE
Reverb documentation symlink deleted?

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#780]
In @kslong's pull request #722, the `docs/sphinx/source/examples/reverb.ipynb` symlink was removed, which has removed the example from our ReadTheDocs page. As I'm a bit out of the loop, was this intentional- are the examples supposed to be moved? Or was this just a bug with git failing to commit a symlink? Happy to do a quick fix if so.

**Comment by kslong** [comment]
I don't recall why the symlink was dropped  I don't think though that the top level directory of examples is the right place to put this.  Everything else in examples has its own subdirectory.  In the current distribution, the reverb script is in basic.   I think it merits its own subdirectory, that is that there should be a subdirectory reverb and the script should be there.

**Comment by smangham** [comment]
OK, I'll create a new directory `examples/reverb`, shuffle the reverb stuff to there, and a new `examples/reverb` directory in `sphinx` and a symlink within it.
