### ISSUE TITLE
Negative frequencies and opacities in calculate_ds lead to negative optical depths

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#783]
This is related to the "odd tau" negative optical depth bug I mentioned in this week's telecon. I really have no idea what's going on... I'm going to try and be descriptive as possible, which means this became a bit long.

One problem seems to be that in the while (smax > DFUDGE) loop, where we check to see if a linear approximation for the frequency shift is reasonable, i.e. 

```c
while (smax > DFUDGE)
{
  stuff_phot (p, &p_now);
  move_phot (&p_now, smax * 0.5);
  observer_to_local_frame (&p_now, &p_now_cmf);
  diff = fabs (p_now_cmf.freq - 0.5 * (p_start_cmf.freq + p_stop_cmf.freq)) / p_start_cmf.freq;
  if (diff < MAXDIFF)
  {
    break;
  }
  stuff_phot (&p_now, &p_stop);
  stuff_phot (&p_now_cmf, &p_stop_cmf);
  smax *= 0.5;
}
```

What I've found whilst debugging is that `p_start_cmf.freq` changes. Not really sure how, but at the start of the while loop the frequency is positive and by the end of it, it has somehow become negative. I can't see how, or where, the frequency is being modified. This results in a negative value for mean_freq, which doesn't actually seem to bother `klein_nishina()`. Also, since `freq_av = freq_inner` for macro atoms opacities, this means both `kappa_bf()` and `kappa_ff()` are given negative frequencies to evaluate at. Neither of them seem top bothered either and return tiny *positive* opacities.

The next fun now starts when calculating the observer opacity, `kap_cont_obs = kap_cont / observer_to_local_frame_ds (p, 1);`. For some reason, the return value for `observer_to_local_frame_ds (p, 1) = -5.1972478971517701e-06` which means kap_cont_obs becomes negative. Then `ttau += kap_cont_obs * (smax - ds_current) < 0` since ttau at this point is small, ~6e-6, and `kap_cont_obs * (smax - ds_current)` = -9e-3.

This seems to create the negative optical depth problem. Since the photon hasn't escaped yet, it keeps getting transported with "ttau" (p->tau, I think?) or the running optical depth being negative. Eventually after a few transport steps, the problem seems to resolve itself. As a caveat, this seems to be the problem for photon 29 at least. I haven't checked the other photons which have this error yet.

I think this could potentially be related to Issue #782. During the macro atom emissivity calculations, I get a lot of these errors:

```
kpkt: Setting adiabatic kpkt destruction probability to zero for this matom.
```

As well as a truly tremendous amount of weight generated by kpkts, with a negative contribution from adiabatic cooling:

```
Kpkt emissivities (summed over cells): kpkt_abs 5.3395e+196 kpkt_emiss 4.4820e+193
Totals: f_matom 2.662893e+43 f_kpkt 4.481992e+193
!! xdefine_phot: lum_tot 5.11e+43 lum_star 0.00e+00 lum_bl 0.00e+00 lum_bh 0.00e+00 lum_disk 5.11e+43 lum_wind 0.00e+00
!! xdefine_phot:   f_tot 4.48e+193   f_star 0.00e+00   f_bl 0.00e+00   f_bh 0.00e+00   f_disk 4.94e+43   f_wind 0.00e+00   f_matom 2.66e+43   f_kpkt 4.48e+193 
!! xdefine_phot: wind ff 6.32e+41       fb 4.45e+42   lines  9.83e+42  for freq 3.00e+14 3.00e+16
!! xdefine_phot: disk                               lum_disk 5.11e+43 5.11e+43  9.93e+39 
!! xdefine_phot: heating & cooling  due to adiabatic processes:         -4.49e+34 8.15e+36 
photon_gen: band 3.00e+14 to 3.00e+16 weight 8.96e+188 nphotons    10000 ndisk       0 nwind       0 nstar       0 npow 0 
photo_gen_kpkt  creates nphot 10000 photons from     0 to 10000, weight 8.9640e+188 
```
I have a wind_save and pf file for this model on my Dropbox, here:

https://www.dropbox.com/sh/4kh4g4n50jal1i1/AABedd5XSCDnRq9u_kkZlVQPa?dl=0

**Comment by kslong** [comment]
I do not believe that this is the same problem as that in #782.  I have checked that the fixes I made for #782 do not solve the problem.   

Although the problem manifests itself in the frequencies of p_stop_cmf first and p_start_cmf after that, the real problem is that the directions cosines of the photon that enters the routine are messed up. 

The first photon that has the problem in photon 5474 in the second ionization cycle.  The properties of this photons as ut enters the routine are listed:

print p_start
$3 = {x = {-24606338217147052, 46059526198439368, 1.4289599070788602e+17}, lmn = {-0.61505627818807707, 0.37260897776538088, 2.1110056328032938}, freq = 4523126821483852, freq_orig = 6180378358585897, 
  w = 6.6822960702120232e+39, w_orig = 9.1311322279209805e+39, tau = 0, istat = P_INWIND, frame = F_OBSERVER, nscat = 11, nrscat = 8, nmacro = 8, nres = -1, nnscat = 1, grid = 7786, 
  origin = PTYPE_DISK_MATOM, origin_orig = PTYPE_DISK, np = 5474, path = 2.4487921594900304e+17, ds = 7528672070778469}

Note that the length of lmn is greater than 2.  This will surely mess up everything that occurs after that.   Note that this looks to be a Disk photon that has passed through at least one macro atom scatter, possibly a number of them.  (The problem occurs about 40 times in the example pf file that Ed created, but really there are perhaps 5 photons involved.  

I agree this is a high priority bug to track down.

**Comment by kslong** [comment]
OK, so I have checked this photon, and it was created with an odd value of lmn.  Here is it at the beginning

$2 = {x = {30743445562755.523, -36699918331693.062, -9.9999999999999995e-07}, lmn = {-0.10192106082486858, 1.1321829925022926, -0.33856354632303104}, freq = 6180378358585897, freq_orig = 6180378358585897, w = 9.1311322279209721e+39, w_orig = 9.1311322279209721e+39, tau = 0, istat = P_INWIND, frame = F_OBSERVER, nscat = 0, nrscat = 0, nmacro = 0, nres = -1, nnscat = 1, grid = 5750, origin = PTYPE_DISK, origin_orig = PTYPE_DISK, np = 5474, path = -1, ds = 0}

I'm wonder if the disk at this position has a speed which is greater than C, but the photon does not seem to be anywheeclose in to the center. It was created at a distsnce of 4.8e13 from the center and the inner radius of the disk is 8.9e12.

**Comment by kslong** [comment]
OK, the problem is in local_to_observer_frame_disk.   Photons come into this routine with the correct length for lmn, but are leaving with an incorrect one.  It's not immediately obvious why, though it is obvious that something could go wrong.

**Comment by saultyevil** [comment]
Looking at one photon generated during the spectral cycles, I can see that it's a wind photon generated with a z position 2e17 cm. So this photon is already way out in outer boundary of the which which has R_max = 5e17cm. The length of lmn for this photon is already > 2 before any transport of extraction.

This means it must have happened during the generation of the photon, as you suspect Knox. I've found that the error is introduced here (in local_to_observer_frame),

```c
  for (i = 0; i < 3; i++)
  {
    p_out->lmn[i] = f_out / f_in * (p_in->lmn[i] + x * v[i]);
  }
```

I'm still trying to convince myself with my math, so correct me if I'm wrong, but should it be f_in / f_out instead?

**Comment by kslong** [comment]
I agree that this is the most likely line where the problem occurs.  I need to look back at the original equations.

**Comment by kslong** [comment]
Simply interchanging f_out and f_in did not work.  Sigh.  The outliers are not as big, but there are still outliers.

**Comment by kslong** [comment]
OK, every on one of the direction corrections had the same error.  Once the ratios of f_out and f_in were flipped in all of the routines, the problem has disappeared.

**Comment by kslong** [comment]
@saultyevil   With the changes that have been merged into dev, I believe this is now resolved.  Once you have confirmed this, please close the issue.

**Comment by saultyevil** [comment]
I've run the same model as in the original post now. No errors to do with an odd optical depth, so I believe we can close this issue.
