### ISSUE TITLE
Reverb.filter_lines is difficult to use

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#788]
Currently, `Reverb.filter_lines`/`Reverb.filter_line`  takes internal python sorted line list numbers. These differ based on the data files and wavelength range selected are not intuitive- the current easiest way to get them is to do a run, and check the dump file to see what photons exist in the wavelength range near the line you want, and figure out from there.

There's machinery in place to select specific macro-atom lines from their upper and lower levels in `setup_reverb.c`, but that was developed with the simple cases of Ha/Hb etc. in mind, not things like C-IV. It would be better if `filter_line` took a species and frequency and picked the closest line of that species to that frequency within a small window (to simplify issues with doublets/triplets).

**Comment by saultyevil** [comment]
Not to toot my horn too much, but I created a program a while back to explore the atomic data. One of the things you can do is select your atomic data, and query all the bound-bound transitions for a given element (or ion if you know the internal ion number, which you can figure out using the program too). You can use it to find the wavelength of the transition you're interested in and it'll say what the internal nres of it is.

Obviously not the proper solution, but could be a temporary help for anyone struggling to use Reverb.filter_line.

https://github.com/saultyevil/atomix

**Comment by jhmatthews** [comment]
The solution here is to amend the documentation so that Reverb.filter_lines parameter page includes Ed's above tip, i.e. use atomix as a helper routine. When this documentation is done, this issue can be closed.
