### ISSUE TITLE
"luminosity lost by being completely absorbed" counter is not what it should be!

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#794]
Looking at the stellar wind models - I generated only photons past the helium edge - and it is clear that they are all absorbed in the wind. 
The "luminosity lost by being completely absorbed" counter - which I though would be handy in diagnosing these things reports a very small value.
I think it is only counting the 'last little bit' of a photon that is absorbed rather than the original full weight of it. Is this the expected and correct behaviour?

**Comment by jhmatthews** [comment]
That seems right to me but I agree it's a but unclear - the rest of the energy is put into heating, so should come out in wind radiation or some other cooling process if we've done our book-keeping right?

**Comment by Higginbottom** [comment]
Ah OK - so its a case of "this is what we've thrown away" rather than converting into other forms.
Makes sense - I withdraw my bug!!
