### ISSUE TITLE
Possible requirement for high frequency cutoff in matrix_bb ionization mode

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#797]
During work on creating stellar wind models we were investigating 42000K stars with winds. The blackbody function for such a star has some power past the He2 ->3 edge at 54.41 eV, but the opacity for such photons is very high, and one would expect all those photons to be 'mopped' up in the first cell of a model.

However, if the cell spectra is modelled by a dilute blackbody, the spectra all tend to be around 42000K, because the mean frequency seen in a cell is little affected by cutting off the wein tail.

When computing the rate matrix, the photoionisation (PI) rates are computed using an integral over the blackbody, and this means that even though there are actually no photons above 54.41eV in a cell, there is still a He2->3 rate and so the weind ends up in a completely unrealistic ionization state of fully ionized He (and also Fe in Fe5 rather than 4). The way to fix this is to compute the integrals with a high frequency cutoff at the highest frequency photon packet seen in the cell. This number is stored and is a simple fix. 

But, it is still not a perfect fix since the real spectrum in the cell is clearly *not* just a truncated BB, so one could argue that the right way of doing it is using a power law model - properly split into sensible bands, and this type of fix is really just trying to tinker with a scheme which should not really be used....

Hmmmm

**Comment by kslong** [comment]
We should do this the right way, and solve the problem of banding, as the above comment in the end indicates.  I would colse this in favor of new issue regarding banding properly.
