### ISSUE TITLE
Mystery crash (likely associated with total memory issues) in simple_xrb model with macro atom 

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#812]
I've been trying to run an XRB model, (essentially the XRB_standard.pf model with macro atoms turned on.

Here is the .pf file

[XRB_macro.pf.txt](https://github.com/agnwinds/python/files/5920273/XRB_macro.pf.txt)

I'm running it on excession - if I run with the command:

mpirun -n 64 py85b -p 2 XRB_macro

it crashes with:  

Zeroth thread successfully received the normalised estimators. About to broadcast.
Zeroth thread successfully received the integer sum. About to broadcast.
--------------------------------------------------------------------------
mpirun noticed that process rank 31 with PID 0 on node excession exited on signal 9 (Killed).
--------------------------------------------------------------------------

whereas if I run with

mpirun -n 64 py85b -p 2 --rseed XRB_macro

it crashes with:
 
Zeroth thread successfully received the normalised estimators. About to broadcast.
Zeroth thread successfully received the integer sum. About to broadcast.
--------------------------------------------------------------------------
mpirun noticed that process rank 55 with PID 0 on node excession exited on signal 9 (Killed).
--------------------------------------------------------------------------

This seems to chime with KSL's suggestion that it is some kind of random number problem.
If I run it again I get a different core complaining.

There is nothing special at the end of any of the individual diag files in the diagonal directory - they all have 

 Ion. Cycle 1/60 of XRB_macro : Photon          0 of      15625 or    0.0 per cent 

as their last line....

**Comment by saultyevil** [comment]
I just had a peek at the logs on excession using `grep oom /var/log/*`, so it should grep out any out of memory (oom) messages. I saw this:

```
/var/log/syslog:Feb  3 17:33:24 srv02422 kernel: [4413499.476578] py85b invoked oom-killer: gfp_mask=0x14280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), nodemask=(null), order=0, oom_score_adj=0
```

So oom-killer is being called (on py85b I think) and I can also see on excession that the swap memory partition is completely full right now (usually a sign of running out of memory). So actually, I think you were right originally asking if Python is running out of memory. Have a look at htop whilst you run it to see how much is actually being used... Excession does only have 48 physical cores tho, so maybe try using that many instead of 64? I haven't had any trouble with similar resolution macro TDE model using 48 cores and 1e8 photons.

**Comment by Higginbottom** [comment]
I've not used htop before, but running my 64 core run:

The mem thing is green, showing 113G/126G
The swp is red - showing 7.99/8.00G

The stuff at the top of the info that python prints out regarding memory use seems to suggest its pretty modest:

The photon structure is 237.5Mb per process
The rest is:

Allocated      10928 bytes for each of  7458 elements of      plasma totaling       81.5 Mb 
Allocated        112 bytes for each of  7458 elements of photonstore totaling        0.8 Mb 
Allocated        104 bytes for each of  7458 elements of matomphotonstore totaling        0.8 Mb 
Allocated      19936 bytes for each of  7458 elements variable length plasma arrays totaling      192.8 Mb 
Allocated        200 bytes for each of  7458 elements of macro totaling        1.5 Mb 

 so about 500Mb per process - so 30Gb for 64 cores. Should be well within capacity...

Killing the job reduces memory use to 27Gb (there are other processes running) so it looks like it was using about 90Gb - 3x what the report suggested.

**Comment by Higginbottom** [comment]
OK, possibly more useful, I note that when the process fails it fails with: Exit 137:
According to google:

 This is a Linux error code which you may see on CircleCI when your container runs out of memory. Containers are given 4GB of RAM by default. If your build process consumes all of the container memory, your build will fail

**Comment by jhmatthews** [comment]
What about the macro-atom estimators? i.e. something like 
```Allocated X Mb for MA estimators ```

**Comment by jhmatthews** [comment]
Ah, that statement is Log_silent. We should change that. But also, when I run $PYTHON/examples/core/XRB_standard.pf with macro_atoms_thermal_trapping and data/h20_hetop_standard80 it says the estimators only take up 120 MB or so.

**Comment by Higginbottom** [comment]
Running of 48 cores or fewer works OK - but the simulation still stops - after 21 cycles with 

Aborting rank 0047: exiting all processes with error 1

Error summary for thread 47: summary prior to abort
Recurrences --  Description
        7 -- getatomic_data: line input f odd (may be OK if Macro): %s
        3 -- Ignored %d simple lines for macro-ion %d
        1 -- Ignored %d collision strengths with no matching line transition
        1 -- Ignored %d inner shell cross sections because no matching yields
        1 -- get_wind_params: zdom[ndom].rmax = 0 for wind type %d
        1 -- wind2d: Cell %3d (%2d,%2d) in domain %d has %d corners in wind, but zero volume
        1 -- check_grid: velocity changes by >1,000 km/s in %i cells
        1 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
    12981 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model
        5 -- error_count: This error will no longer be logged: %s
      558 -- spectral_estimators: Alpha cannot be bracketed (%e %e)in band %i cell %i- setting w to zero
      431 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
   100001 -- macro_pops: level %i has calculated pop. %8.4e in cell %i
     3846 -- macro_pops: found unreasonable populations in cell %i; use dilute BBody excitation w %8.4e t_r %8.4e

Its all in cell 7371....

**Comment by kslong** [comment]
@Higginbottom   I wonder with the changes in Python recently, Nick, whether you should run this again.  The macro_pops one is something that has been solved for some of the other times it was coming up.   We ought to try to make sure we know what the problem actually is, even if it is a fundamental one, like lack of memory or swap space.

**Comment by kslong** [comment]
@Higginbottom    This is another one we should recheck.  As I understand it there were two problems, one if you ran with more than 48 cores, and one that occurs when you run with less.

**Comment by Higginbottom** [comment]
Testing with the new version of python on excession

the command 
mpirun -n 64 py85b -p 2 XRB_macro
crashes with 
There are not enough slots available in the system to satisfy the 64 slots
that were requested by the application:
So something has changed outside python - I wonder if this was the underlying cause with the earlier crash - and someone has improved the way the kernel communicates??

Whatever, it does appear that it wasn't a memory issue. And in any case, I cannot run this any more in the same way...

Seeing if the changes in macro atom machinery allow it to run is really a different issue..

**Comment by Higginbottom** [comment]
Just to add interest to this - I've been getting exactly the same error with a new run with my hydro model running in macro mode.
On 40 cores, the code uses 100/126Gb of RAM on excision up to the point at which arrays are communicated, then it allocates more memory and the code crashes.

On 30 cores, it uses 76Gb normally, then when the arrays are communicated this goes up to 120Gb - still below the total physical memory and the simulation continues.

I wonder if there is something we should do to try and catch problems like this. We can in principle work out how much memory *will* be needed for exchanging data right at the start. It might be best for the code to crash right at the start if it is going to crash.- or better still stop and want the user that the code is going to want to use more RAM than available...

**Comment by kslong** [comment]
Do I understand correctly that this is always happening when we try to exchange data between the cores?  Is it happening at the point we allocate memory?    If so, perhaps we can look at reducing some of the memory requirements there.

**Comment by kslong** [comment]
Note that on at least one of my Macs, with the homebrew version of mpich installed, the program will not run if np is set to greater than the number of cores.  The is a switch one can use 

--use-hwthread-cpus

to use the number of threads instead.

**Comment by kslong** [comment]
This error has not b een seen for several years, so I am going to close it.  The code is sufficiently different today, it is unlikely what is here will help us much.
