### ISSUE TITLE
Delay errors for uncalculated responses

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#818]
When trying to generate a delay using a response function, on a transfer function that has not had a response calculated yet, the code should raise an error that the response has not yet been calculated. It currently just crashes with an empty array error.

**Comment by kslong** [comment]
@smangham  This looks like a very simple problem to fix.  Is there any possibility you could either make the change, provide an example, or tell me exactly what needs to be done.

**Comment by smangham** [comment]
Done!

**Comment by kslong** [comment]
Thank you, Sam
