### ISSUE TITLE
Problems generating bb spectrum from readin model

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#819]
In working to implement Karri's disk_ir_illum models, I am reading the temperature profile of a disk in from a file.  It is generating sane_checks in the routine get_rand_exp which is part of the bb spectrum generation process.  This is probably something to do with my inputs,  but that is an error that should be being trapped earlier.  This is just to document that I have to sort this out.

**Comment by kslong** [comment]
OK, I think I understand the problem.  In this case, I had read a temperature profile in for the disk, but the temperature profiel did not extend the full disk radius.  I thought, and I believe I read somewhere in our documentation that if one did this, one used the temperature profile for a steady state disk for the remainder.  But we don't read in mdot for the rest of the disk if we say the temperature profile is to be read in.  The options are:

- Ask for mdot if the temperature profile does not extend over the full disk
- Truncate the disk at the maximum radius (one might not even ask for the maximum radius in this case.
- Use the last value of the temperature in regions of the disk that exceed the maximum read in radius
- Check that the temperature profile extends at least as far, possibly further than the value set for the maximum, disk

@jhmatthews   @Higginbottom @saultyevil please comment on what you would like to happen, and also what your memory is of what was supposed to happen.

**Comment by saultyevil** [comment]
I came across this exact problem when I was working on the Eddington critical temperature profile. When I thought about a solution (which I never programmed, sorry!), I thought it would make the most intuitive sense to truncate the disc radius to whatever maximum radius is in the file. I think this would be a consistent approach with our other read-in models.

**Comment by Higginbottom** [comment]
I don't recall  engaging with this bit of code before, but I think Ed’s intuition feels right here - if you are defining a disk via a file, it seems right that the code doesn't then glue bits on the end….

Nick

**Comment by kslong** [comment]
I agree; that is what I will try to implement.  I will take the maximum disk radius to be last r value given in the data file

**Comment by kslong** [comment]
I have made the changes, as indicated above, and so am closing the issue.
