### ISSUE TITLE
Noisiness in spectra has increased

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#822]
Detailed spectra are noisier now than they were in the past.  The increased noises developed at commit 7022d5522bd90098a7750d2ce83e5655f06ebfe4 (py84h).  It was not there in the previous commit 8caf786bae8d9ca54cb3f867b85888549f25473b. (py84i)  The problem can be easily demonstrated with the cv.pf file in the regression test directory.  The ionization cycles look identical in these two commits (as well as in today's version of the program), so the issue is somehow related to the detailed spectra.  The difference is shown below:

![test](https://user-images.githubusercontent.com/2530901/109387198-8c241f00-78c5-11eb-82df-ff399e707c00.png)

**Comment by kslong** [comment]
This problem has to do with multiple threads.  If you run in single processor mode. The problem disappears and one obtains a result that looks like the better of the two cases.

**Comment by Higginbottom** [comment]
Maybe for some reason all the threads are producing the same set of random numbers….

**Comment by kslong** [comment]
I wondered about whether was a random number issue as well, @Higginbottom.  The other possibility is that something has gone wrong when the spectra are collected from the separate threads.  This commit was the one where the construction of the spectra within cells was added and this involved changing some of the bits of the code that collect and distribute information between the threads.  That is basically why I did a check to see if the results were sensitive to the number of threads.

**Comment by kslong** [comment]
So it seems unlikely that the problem has to do with using the same set of random numbers in different threads, since in that case one would expect that the number of times a photon scatters would be the same on all threads.  This is something that is written out in the logfile, and inspection shows that the numbers are different on different threads.

Inspection of the diff between the two commits suggests that the problem lies somewhere in para_update.c or wind_updates_2d.c (with an outside possibility that something happened in run.c).

**Comment by saultyevil** [comment]
This line looks a bit fishy to me.

https://github.com/agnwinds/python/blob/7022d5522bd90098a7750d2ce83e5655f06ebfe4/source/para_update.c#L427

I'm not sure there is a enough space for all the Emitted, Created, etc. angles plus the extracted inclinations spectra. Should it be something like `(NWAVE * (MSPEC + geo.nangles) + 2 * MSPEC * NWAVE`?

Also, is there any reason why we don't normalize `xxspec[i].lf`, `xxspec[i].f_wind`, `xxspec[i].lf_wind` across MPI processes as well during spectral cycles? I've always noticed that the log_spec files are always a lot nosier than the linear spectrum.

**Comment by saultyevil** [comment]
Actually, it looks like we also only normalizing over the first MSPEC spectra and not MSPEC + geo.nangles...

```c
 nspec = MSPEC;


  redhelper = calloc (sizeof (double), size_of_commbuffer);
  redhelper2 = calloc (sizeof (double), size_of_commbuffer);

  for (mpi_i = 0; mpi_i < NWAVE; mpi_i++)
  {
    for (mpi_j = 0; mpi_j < nspec; mpi_j++)
    {
      redhelper[mpi_i * nspec + mpi_j] = xxspec[mpi_j].f[mpi_i] / np_mpi_global;

      if (geo.ioniz_or_extract == CYCLE_IONIZ)
        redhelper[mpi_i * nspec + mpi_j + (NWAVE * nspec)] = xxspec[mpi_j].lf[mpi_i] / np_mpi_global;
    }
  }
```

**Comment by kslong** [comment]
Hmm, @saultyevil  That sound promising, since I have found that the problem with noise only affects the spectra extracted at particular angles, not the Created spectra (in the spectral cycles).   It also makes sense in that this is the part of the code that was being modified between the two commits. 

Also one of the changes was that the call to gather_spec_helper got changed between the two commits.

**Comment by kslong** [comment]
That is clearly it.  Here is what the calls to gather_spectra looked like in 84i

run.c:307:    gather_spectra_para (ioniz_spec_helpers, MSPEC);
run.c:581:    gather_spectra_para (spec_spec_helpers, nspectra);

where the first was for ionization cycles and the second was for spectral cycles.

**Comment by kslong** [comment]
OK, this issue should be resolved with the latest merge into dev.
