### ISSUE TITLE
Python completely stalls calculating cv macro atom model

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#829]
Keith Inight (who has been working with ksl on CVs) reported to me that he was having trouble getting the attached .pf file to run.  It stalls (for over a day) on our master b ranch version of python, when calculating the estimators for the start of the spectral cycles.  I have confirmed if fails similarly with the current dev version.  The program just sits there "forever" without any obvious progress.  This is not good.  It is using one of our standard macro atom files, with h20_hetop_standard80.dat; the same model runs fine with the analogous dataset with only 10 levels of H.  

[cv_stall.pf.txt](https://github.com/agnwinds/python/files/6151567/cv_stall.pf.txt)

**Comment by saultyevil** [comment]
My TDE models use h20_hetop_standard80, so it's probably not the data _it self_ as fault. 

If it's hanging without an error at the end, then maybe there's an MPI problem. If it hangs during calculating the emissitivies, then maybe it's stuck in a while loop.

I remember that there is a while loop in `macro_gov` along the lines of `while (escape == false)`. There doesn't seem to be a max iteration safety exit, even though we do keep track of how many times we've looped around. It probably wouldn't take long to add a max iteration exit to test to see if it hangs here.

**Comment by kslong** [comment]
The pf file above  is still failing, but not for the reasons indicated above.  It's failing both with the version immediately proir to the version that makes changes to the way cdf for bound free was changed and the version (xdev) after this was changed.  The problem now is not stalling, but rather it gets the following errors:

```
        7 -- getatomic_data: line input f odd (may be OK if Macro): %s
        3 -- Ignored %d simple lines for macro-ion %d
        1 -- Ignored %d collision strengths with no matching line transition
        1 -- Ignored %d inner shell cross sections because no matching yields
        1 -- get_wind_params: zdom[ndom].rmax = 0 for wind type %d
        1 -- wind2d: Cell %3d (%2d,%2d) in domain %d has %d corners in wind, but zero volume
        1 -- check_grid: velocity changes by >1,000 km/s in %i cells
        1 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
        6 -- rand_wind_thermal_trapping: photon had more than  %d internal scatters in cell %d at %e %e %e with p_norm %e zmin %e tau_min %e
        1 -- check_stimulated_recomb: cell %i had %i bf jumps where ne*n_u/n_l*alpha_st > gamma
    13861 -- macro_pops: bfu rate is %8.4e in cell/matom %i
    20609 -- macro_pops: level %i has calculated pop. %8.4e in cell %i
      338 -- macro_pops: found unreasonable populations in cell %i; use dilute BBody excitation w %8.4e t_r %8.4e
   100001 -- macro_pops: bbu rate is %8.4e in cell/matom %i
    17891 -- macro_pops: st. recomb rate is %8.4e in cell/matom %i
        6 -- error_count: This error will no longer be logged: %s
      338 -- macro_pops: ion %i has calculated frac. pop. %8.4e in cell %i
```

All of the errors look to be occurring in cell 117, or at least all of the ones that are printed out. The initial error is

cv_stall_3.diag:Error: macro_pops: bfu rate is -1.4982e+06 in cell/matom 117

**Comment by kslong** [comment]
Sigh ... the problem above does not appear if one runs with one thread.  That makes it harder to diagnose.  The model above was run with 8 threads.

**Comment by jhmatthews** [comment]
Just to check I'm following -The model used to fail in the spectral cycles, but with some recent changes it now fails in the ionization cycles with the above serious error? And this happens both before and after changes to the generation of matom bound-free photons?

**Comment by kslong** [comment]
Yes, but the fact that it depends on how many threads are running, means that this could mean this
* be an old, but very infrequent,  problem
* the problem of stalling may or may not actually still exist with fixes that have been made.

**Comment by kslong** [comment]
The initial problem is in this section of macro_gov.c.  
![screenshot_709](https://user-images.githubusercontent.com/2530901/115602811-fb563800-a2a4-11eb-87d6-189b6080c5df.png)
 
The problem appears to be that
 mplasma->gamma_old[config[index_lvl].bfu_indx_first + index_bfu]
is negative.  

so the question is how could a photoionization  rate coefficient become negative or have we somehow got a bad index

**Comment by kslong** [comment]
Further investigation shows that the reason that mplasma->gamma_old is negative is not surprisingly that mplasma->gamma is negative, but so far as I can tell there is only one place mplasma->gamma is calculated and when I checked the values there they seemed to be positive always.

Note that there is a very odd bit of code somewhat below what I showed above:

![screenshot_711](https://user-images.githubusercontent.com/2530901/115618113-dae3a900-a2b7-11eb-9808-add5123d41e8.png)

If this is really necessary, this code should come earlier.  If not, it should be removed, or some other justification provided.

**Comment by kslong** [comment]
@jhmatthews   perhaps you want to have a look at this.  The only place I can see where gamma is incremented is around at 
estimators_macro.c:165   but I put a check on whether gamma was ever less than 0 there and could not find any instances of a problem.

**Comment by kslong** [comment]
Aside - The call to mc_estimator_normalize is pretty odd.  In the call, we are in a loop that goes over plasma cells, but the actual call is by wind cell number.  The fist thing that mc_estimator normalize does is convert back to the plasma cell.  This really should be fixed. We do need the volume of the cell, which is part of wmain, however.  

The problem here is occurring in wind cell 0 (which for a CV wind is a cell in the wind., or at least it has a positive volume (since I have printed that out.)

Note  - In addition to finding a problem with mpirun -np 8, I hae found it with -np 4.  I still have not been able to create the problem in single processor mode.

**Comment by kslong** [comment]
I thought this was not the case, but get_gamma returning values of less than 0 in some cases.  However, this occurring later than the first problematic Error which is 

Error: mc_estimators_normalize: gamma_old -1.494664e+06 < 0 (-4.034963e+10,4.074098e+30) (1,0)

on the branch bug829_cv_stall which I have pushed.  (It is only different from dev, in that a lot of Error statements have been added to diagnose this problem)

Here is a typical error summary, at present, on the thread which failed:
```
Para:        19 -- mc_estimators_normalize: gamma_old %e < 0 (%e,%e) (%d,%d)
Para:         1 -- check_stimulated_recomb: cell %i had %i bf jumps where ne*n_u/n_l*alpha_st > gamma
Para:     13860 -- macro_pops: bfu rate is %8.4e in cell/matom %i  %g %g %g
Para:     20609 -- macro_pops: level %i has calculated pop. %8.4e in cell %i
Para:       338 -- macro_pops: found unreasonable populations in cell %i; use dilute BBody excitation w %8.4e t_r %8.4e
Para:     24674 -- get_gamma: gamma_value %e <0.0  (%e %e) %e %e 
Para:    100001 -- macro_pops: bbu rate is %8.4e in cell/matom %i
Para:     17891 -- macro_pops: st. recomb rate is %8.4e in cell/matom %i
Para:         7 -- error_count: This error will no longer be logged: %s
Para:       337 -- macro_pops: ion %i has calculated frac. pop. %8.4e in cell %i
```

The first error in the the diag file is the first one.

**Comment by saultyevil** [comment]
This may or may not be helpful, but I've run cv_stall using dev with the changes described in #849 and in PR #850. I've run it in two ways: 1) using `mpirun -n 8 py cv_stall` and 2) `mpirun -n 4 py -p 2 cv_stall`, both on Linux machines.

With method 2), I don't get any macro atom errors in the ion cycles. Spectral cycles seem to complete with just a single macro error for level 61. Here's the error summary,

```
Error summary: cv_stall
Collated errors for 4 processors
Recurrences --  number of threads with error -- Description
	 1992 --     4 -- rand_wind_thermal_trapping: photon had more than  %d internal scatters in cell %d at %e %e %e with p_norm %e zmin %e tau_min %e
	   92 --     4 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
	   28 --     4 -- getatomic_data: line input f odd (may be OK if Macro): %s
	   12 --     4 -- Ignored %d simple lines for macro-ion %d
	    4 --     4 -- Ignored %d collision strengths with no matching line transition
	    4 --     4 -- Ignored %d inner shell cross sections because no matching yields
	    4 --     4 -- check_grid: velocity changes by >1,000 km/s in %i cells
	    4 --     4 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
	    4 --     4 -- error_count: This error will no longer be logged: %s
	    4 --     3 -- extract: Should not have hit secondary
	    1 --     1 -- trans_phot: %ld photons were lost due to DFUDGE (%8.4e) pushing them outside of the wind after scatter
	    1 --     1 -- calc_matom_matrix: matom accelerator matrix has bad normalisation for level %d: %8.4e
```

And with method 1) I didn't see any macro_pops errors either. And the errors for this:

```
Error summary: cv_stall
Collated errors for 8 processors
Recurrences --  number of threads with error -- Description
	10842 --     8 -- rand_wind_thermal_trapping: photon had more than  %d internal scatters in cell %d at %e %e %e with p_norm %e zmin %e tau_min %e
	  648 --     8 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
	   56 --     8 -- getatomic_data: line input f odd (may be OK if Macro): %s
	   24 --     8 -- Ignored %d simple lines for macro-ion %d
	   18 --     4 -- extract: Should not have hit secondary
	    8 --     8 -- Ignored %d collision strengths with no matching line transition
	    8 --     8 -- Ignored %d inner shell cross sections because no matching yields
	    8 --     8 -- get_wind_params: zdom[ndom].rmax = 0 for wind type %d
	    8 --     8 -- wind2d: Cell %3d (%2d,%2d) in domain %d has %d corners in wind, but zero volume
	    8 --     8 -- check_grid: velocity changes by >1,000 km/s in %i cells
	    8 --     8 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
	    8 --     8 -- error_count: This error will no longer be logged: %s
	    1 --     1 -- trans_phot: %ld photons were lost due to DFUDGE (%8.4e) pushing them outside of the wind after scatter
```

**Comment by kslong** [comment]
I can confirm that .pf file that was the example for this problem now runs successfully.  It does have the errors indicated above but these are not stopping the program from running.  @saultyevil do you agree we can close this issue.

**Comment by saultyevil** [comment]
I think the original issue is been solved, yeah. We can close this. If there are a lot of negative gamma errors, then that might warrant an investigation with a new issue.

**Comment by kslong** [comment]
Given that the original issue has been solved, I am closing this issue.  As Ed notes, if it comes up again we can open a new issue that is targeted to the problem.
