### ISSUE TITLE
RNG state is not the same between restarts

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#841]
When a model is restarted, we initialize the RNG machinery the same way as if we were starting the model from scratch. By that I mean we use the same seed and start at the very beginning of the RNG chain. 

I've found this to be a problem when I'm trying to debug what's happening in ionization cycles past the first cycle, because when I care about a specific photon or ionization state and I restart the model, the RNG is different to what it was before it crashed. So there's every chance that I'm not going to end up in the same situation -- which has been the case for one model I'm currently debugging.

I think we should have some way to make the RNG persistent between restarts, so we can restart the photon transport from the same state. I know it shouldn't affect the results of the simulation (if the RNG is any good, which it is), but for debugging purposes I think this could be a very helpful advanced parameter.

GSL has functions to save/read the RNG state (https://www.gnu.org/software/gsl/doc/html/rng.html?#c.gsl_rng_fwrite) and I have a small test program working.

**Comment by kslong** [comment]
@saultyevil  I agree this is a desirable capability to have. Would it be sufficient to simple add a variable to geo and write out the state RNG state to this variable at the time the windsave file is written, or would it be better instead of doing that to write it to a file, possible a hidden file, e.g for a run called mytest.pf --> .mytest_rng.bin.  On restarts, we would just read it back.   Also, would there be any advantage to doing something similar for a model where we read in a "Previous" model.  Anyway, I would think we could get this off the issues page in about an hour.

**Comment by saultyevil** [comment]
I have a working prototype of this feature, which is enabled with a "-rng" flag currently. When enabled, the RNG state is saved at the end of every cycle to a 55 KB file named root.gsl_save. Upon model restart, just before either the ionization or spectral cycles starts, the RNG state is re-loaded back in from the state saved in root.gsl_save. So in principle the RNG should restart from exactly where it left off. It looks like it's working when I compare a set of randomly generated numbers.

But each MPI process has different RNG so we need to save the RNG for each one. It's not good enough to save the state for one since when that is read back in, every MPI process will have the same RNG -- not good! The simple fix is to just number the files, like we do with the diag files, and probably keep them in a hidden directory to keep the directory clean.

I'm in the final stage of testing for single processor mode right now. The RNG generation seems to be working as intended, but results are a bit different either because of (my) user error or because something is calculated a bit different upon model restart.

**Comment by saultyevil** [comment]
This has been added in with PR #858.
