### ISSUE TITLE
Check frame errors and long run time for some regression tests

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#842]
Running the regression tests with the latest version of dev produces some errors.

Firstly, agn_macro took 10,900 s to complete. For some unknown reason, the final spectrum cycle in MPI process 2 took over 10,000 s to complete and had a huge number of `scatter: kpkt probability (-1.0118e-03) < 0, zeroing` errors. I've tried running this model three times and get the same problem. Hopefully this is just on my machine, but if it isn't, then we should figure out what is happening.

Secondly, I see a fair amount of check frame errors. Ideally these shouldn't be happening, but the cv style and agn_gamma style of models are all reporting photons not being in the correct frame, about 1000 per MPI process. We should track these photons down and fix them to make sure it's not happening somewhere bad.

**Comment by saultyevil** [comment]
The check frame error in agn_gamma is happening in `extract()`,  here (extract.c:201):

```c
      if (rel_mode == REL_MODE_FULL && itype == PTYPE_WIND)
      {
        stuff_phot (&p_in, &p_dummy);
        p_dummy.frame = F_OBSERVER;
        stuff_v (xxspec[n].lmn, p_dummy.lmn);
        observer_to_local_frame (&p_dummy, &p_dummy);
        stuff_phot (&p_in, &pp);
        stuff_v (p_dummy.lmn, pp.lmn);
      }
      else if (rel_mode == REL_MODE_FULL && itype == PTYPE_DISK)
      {
        stuff_phot (&p_in, &p_dummy);
//        p_dummy.frame = F_OBSERVER;
        stuff_v (xxspec[n].lmn, p_dummy.lmn);
        observer_to_local_frame_disk (&p_dummy, &p_dummy);
        stuff_phot (&p_in, &pp);
        stuff_v (p_dummy.lmn, pp.lmn);
      }
```

The problem seems to be that p_in is in the local frame, so p_dummy will also be in the local frame. Note that for wind photons, p_dummy.frame is labelled as F_OBSERVER but this has been commented out for disk photons. 

I think labelling this photon as F_OBSERVER is used as a hack to avoid an error in the transformation functions. But for the purpose of what the code is doing, we are transforming an observer frame defined angle (the spectrum lmn) into a local frame angle, so this is the frame we want the photon to be in. We only care about the new direction and throw away the frequency etc, so I don't think we introduce an inconsistency here.

I suspect this was commented out for debugging reasons, or by accident. @kslong, can you remember why? I'll leave it as is if this is related to the recent extract/live or die issue.

FYI: adding that line back in removes the check frame errors.

**Comment by kslong** [comment]
@saultyevil   I agree that what is here looks odd, but I don't understand why either was needed.  Stuff_phot copies the frame.  Please check what was behind this.

**Comment by saultyevil** [comment]
p_in is in the local frame, but we use observer_to_local_frame to transform the the extract angle into the local frame for wind and disk photons. 

We tag p_dummy as F_OBSERVER to stop check frame errors when transforming the angle, as after stuff_phot p_dummy is tagged as F_LOCAL due to p_in being in the local frame, but it needs to be tagged F_OBSERVER to avoid a frame error. 

So I think tagging them as F_OBSERVER is what we want to do, short of putting the angle aberration code into a separate function to avoid having to use a dummy photon.

**Comment by kslong** [comment]
Great!  Thanks for the explanation.
K

**Comment by kslong** [comment]
If you have not @saultyevil please go ahead an merge the frame check errror fix into dev, so we are all working from the something similar.

**Comment by saultyevil** [comment]
I've made the changes which seem to work for the CV model in regress the directory. I'm running regression tests now to see if/how it changes results before I merge.

**Comment by saultyevil** [comment]
Okay so PR #847 fixes the check frame issues, but doesn't change why agn_macro takes so long to run in the final cycle. More perplexing is that agn_macro_gamma doesn't hang on the final cycle on my machine. The only difference is the treatment of SR effects.

**Comment by saultyevil** [comment]
The frames issue is fixed. I'm closing this and keeping track of the long run time issue in issue #849. It was probably a mistake to bring up two issues in the same issue thread!
