### ISSUE TITLE
Ionization modes defined by numbers

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#85]
We have a general problem in some portions of Python that modes of various types are defined by numbers and not by parameters, e.g using 1 instead of LTE for an ionization mode.  This is a good way for us to make mistakes.   

We should systematically correct this, and one place we should certainly do this is in the definition of ionization modes, which appear to be defined in saha.c as numbers and then used in various other portions of the code, e.g variable_temperature.c.  

We should correct this in the public release.

**Comment by kslong** [comment]
The parameter which carries the ionization mode, is geo.ioniz_mode, but rather than pass the variable through geo, it is passed directly in the call to nebular_concentrations from routines in ionization.c
where there appear to be changes in the mode numbers.   So this is not a completely trivial change.  

Rather it is part of the cleanup needed in the inputs of python for the public release.

**Comment by jhmatthews** [comment]
geo.ioniz_mode can be defined as the following, or something similar. This is the actual variable read in from the pf file and is used by ion_abundances, which decides whether to call nebular_concentrations directly, or to try and match heating and cooling and so call one_shot.

``` C
#define IONMODE_ML93_FIXTE 0                 // Lucy Mazzali using existing t_e (no HC balance)
#define IONMODE_TR 1                // LTE using t_r
#define IONMODE_FIXED 2          // Hardwired concentrations
#define IONMODE_ML93 3          // Lucy Mazzali
#define IONMODE_PAIRWISE_ML93 6          // pairwise version of Lucy Mazzali 
#define IONMODE_PAIRWISE_SPECTRALMODEL 7          // pariwise modeled J_nu approach
```

We call ion_abundances with this mode from either wind2d or wind_updates2d. The routines then either call one_shot or nebular_concentrations with modes which are slightly different. Here's a summary:

| geo.ioniz_mode | nebular_mode | Notes |
| :-: | :-: | :-: |
| 0 | 2 | calls nebular_concentrations directly, 2 means lucy mazzali |
| 1 | 1 | calls nebular_concentrations directly, 1 means T_r |
| 2 | - | calls fix_concentrations |
| 3 | 2 | calls one_shot, which calls nebular_concentrations with 2 meaning T_e |
| 6 | 6 | calls one_shot, which calls nebular_concentrations with 6 |
| 7 | 7 | calls one_shot, which calls nebular_concentrations with 7 |

so these can be controlled with some more definitions:

``` C
#define NEBULARMODE_LTE_TE 0          // LTE using t_e
#define NEBULARMODE_LTE_TR 1          // LTE using t_r
#define NEBULARMODE_ML93 2              // ML93 using correction
#define NEBULARMODE_PAIRWISE_ML93 6          // pairwise ML93
#define NEBULARMODE_PAIRWISE_SPECTRALMODEL 7          // pairwise spectral models
```

I'll start putting some of this in and open a pull request as it could get confusing. It occurs to me that this also might be a good time to come up with a good name for our ionization schemes.

It also seems there is a mistake here according to the comments, as geo.ioniz_mode=1 should apparently be LTE using T_r, yet the comment in the call to nebular_concentrations says it uses T_e in nebular mode 0.

**Comment by jhmatthews** [comment]
@kslong do you think our LTE mode should use the radiation temperature?

 I know it doesn't really matter as for any substantial deviation LTE is a bad approximation anyway, but I think T_r gives the closer representation. 

I'm running tests so if you're happy with fix I can merge once they're done.

**Comment by kslong** [comment]
I think T_r is probably what we want.  It gives us a cleaner way to create a situation where we calculate the best LTE we can.

I expect I was confused about this when I was experimenting with various modes.

Cheers,
Knox
