### ISSUE TITLE
Various forms of sigma_phot

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#86]
We have three routines, sigma_phot, sigma_phot_topbase, and sigma_phot_verner in radiation.c which calculate x-sections given certain information.  sigma_phot and sigma_phot_verner refer to two different verner datasets.  Apparently the difference is that sigma_phot uses a version of the verner data that includes inner shell ionization, but sigma_phot_verner does not.

I would have thought that sigma_phot should get the photoionization x-section regardless of the type of data that is supplied, but that is not the case.   

As a documentation issue, at least, we need to understand better the reason for the various versions of sigma_phot, and why they are used in different situations. It is possible that we rename sigma_phot to something else, and that we should create a new sigma_phot which can calculate the x-section in all situations.
(note that there are separate routines to calcuate partial x-sections).  

Comments & explanations are invited.

**Comment by jhmatthews** [comment]
This has been fixed by #143 so can be closed. See also discussions in #141
