### ISSUE TITLE
"readin" disk temperature profile doesn't work on restarts.

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#863]
If one uses a file to set the run of temperatures on a disk - then when restarting the temperatures (as output in the disk.diag file are odd - and the disk emissivity turns out to be zero - and no disk photons are made. 
The files to make this happen:
remove the .txt extensions.

[input.pf.txt](https://github.com/agnwinds/python/files/6467770/input.pf.txt)
[00000007.pluto.txt](https://github.com/agnwinds/python/files/6467771/00000007.pluto.txt)
[PSK_disk.dat.txt](https://github.com/agnwinds/python/files/6467772/PSK_disk.dat.txt)

Run for two cycles, then add a cycle and restart. 

You should see no disk flux and peculiar disk temperatures.

One would expect the disk temperature profile to be be saved and read back in the wind save - odd it isnt - restarts work fine with a 'normal' disk...

**Comment by Higginbottom** [comment]
Ok, so the disk and the qdisk structures are read in from the wind save file. The assumption must be that there is some kind of corruption going on when it is read back in....

Thats what I'm going to look into first.

**Comment by Higginbottom** [comment]
I bet its because the disk and qdisk structures have (by default) sizes NRINGS=3001, but this might not be the case if it is read in. So when it gets read back in - I expect things go all wrong...

**Comment by Higginbottom** [comment]
Hmmmmm, OK - so the way the imported disk profile works is totally different to the way the standard works. So we should probably work on reading in the file rather than trying to modify the import routine...

**Comment by Higginbottom** [comment]
Well, the solution appears to very simply be to insert the following lines into python.c

    if (geo.disk_tprofile == DISK_TPROFILE_READIN)
    {
      rdstr ("Disk.T_profile_file", files.tprofile);
      geo.diskrad = read_non_standard_disk_profile (files.tprofile);
      geo.disk_mdot = 0;
    }

they go in the conditional section after   if (restart_stat == TRUE)     around line 170 in python.c

**Comment by jhmatthews** [comment]
I think I'm seeing a reccurence of an issue like this. If I try to run a "previous" model that uses a model as a baseline, I get asked for disk.radmax, which shouldn't happen (radmax should I believe be set from the file). This suggests somethings going wrong with the basic logic of the program about disks when reading in. I will post more info here when I get a minute.

**Comment by kslong** [comment]
Hmm, I did not see this error when I ran the UV spectra for one of the models yesterday.  But I have seen a difference in 86b from 86a.  In particulary, windsave2table did not work using the 86b version, on a windsavefile that had been created with 86a.  I think @Higginbottom must have modified something in the structures in the two versions.

**Comment by Higginbottom** [comment]
There is a slight change in the windsave - hence the version change. Sorry - should have made it clearer!

Nick

**Comment by jhmatthews** [comment]
No idea what I was doing here. Seems fine now as long as I used the same version as originally used, so must have messed something up version-wise. Closing.
