### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#869]
travis-ci.org is shutting down on 31 May 2021, apparently we need to migrate our CI account into travis-ci.com to continue using Travis.

Migration is easy, and I quote, "simply sign up to travis-ci.com and link the repositories that you want to migrate. Your existing configurations will work as expected on travis-ci.com and you do not need to alter your build definitions." I'm not sure who has the details for the account, but we should migrate sooner or later if we want to keep our CI tests on Travis.

You can read more about it here https://blog.travis-ci.com/2021-05-07-orgshutdown.

**Comment by saultyevil** [comment]
If we don't want to use travis-ci, then [circle ci](https://circleci.com/) seems like it could be an alternative.

We should still have to worry about "credits", but the free tier has 2,500 credits/week, which corresponds to 250 minutes a week of build time. I think this should be OK for us.

Travis has 10,000 credits in the free tier, but I don't think this ever renews.

**Comment by kslong** [comment]
There is a comparison between the two

https://www.lambdatest.com/blog/circleci-vs-travis/

**Comment by kslong** [comment]
I asked at STScI about what to do and there were a number of suggestions that we look at github actions

**Comment by jhmatthews** [comment]
I'm closing this since we have moved to github actions (see #955 #956 )
