### ISSUE TITLE
gaunt_ff is very expensive time-wise

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#878]
For a macro atom model of an XRB, I am finding that most of the time is being spent in the following routines

 58.83   1985.51  1985.51 25204735     0.00     0.00  matom
 20.72   2684.93   699.43 1629624712     0.00     0.00  gaunt_ff
  5.53   2871.41   186.48                             mt_get_double

The reason this is happening is that the system is optically thick and the program is rattling around in maro atoms.  However even if this is the case, one would hope that gaunt_ff would not be such a time sink.  

One possibility is to try to avoid calling gaunt ff so many times.

Another would be to speed gaunt_ff up.

@Higginbottom  as I look at gaunt_ff it looks to me there would be several ways to speed gaunt_ff up. 

```
double
gaunt_ff (gsquared)
     double gsquared;           /* the gamma squared variable */
{
  int i, index;
  double gaunt;
  double log_g2;
  double delta;                 //The log difference between our G2 and the one in the table

  delta = 0.0;                  /* NSH 130605 to remove o3 compile error */
  index = 0;                    /* NSH 130605 to remove o3 compile error */
  log_g2 = log10 (gsquared);    //The data is in log format
  if (log_g2 < gaunt_total[0].log_gsqrd || log_g2 > gaunt_total[gaunt_n_gsqrd - 1].log_gsqrd)
  {
    return (1.0);
  }


  i = 0;
  while (gaunt_total[i].log_gsqrd < log_g2)
  {
    i++;
  }

  index = i - 1;
  delta = log_g2 - gaunt_total[index].log_gsqrd;

  /* The Southerland interpolation data is a spline fit to the gaunt function. */

  gaunt = gaunt_total[index].gff + delta * (gaunt_total[index].s1 + delta * (gaunt_total[index].s2 + gaunt_total[index].s3));
  return (gaunt);
```

First is the loop to find which starting point to use.  A I read the Sutherland paper, it looks to me that values in the table are presented in every 0.2 dex of log gssqrd.  Do you agree.  If that is the case we can simply predict which line of the the Sutherland table to use.   
Second, as I understand it the gaunt factor is just a function of gsqd so this means we do not have to do these calculations on the fly at all.  We can simply calculate them on whatever interval we chose and store that.  

Do you agree?   We could either do this once, outside of Python, or whenever we start Python up.

**Comment by kslong** [comment]
Even if I am right about the "slowness" of gaunt_ff itself,  one probably needs to see whether gaunt_ff can be called fewer times in matom

**Comment by Higginbottom** [comment]
I'll take a look at this in a bit - but I'm not that sure about the matom machinery, so I might have annoying questions!!

**Comment by kslong** [comment]
I tried saving the gaunt factor so that it was not recalculated if the input was the same.  This actually made things worse in the example I was trying.  I was surprised at that, but in looking at the problem gaunt_ff is typically called for each ion one after the other, and thus even if the temperature of the plasma is the same the input variable gsqrd changes every time it is called.  Thus storing the value of gauntt_ff does not help.   The calls to gaunt_ff occur mostly from ff  (which in turn is called by matom)

**Comment by kslong** [comment]
Although the gaunt_ff calculation could still be sped up,  I have now merged changes into dev reduce the number of times gaunt_ff is called. Specifically, the subroutine ff checks to see whether one can avoid calculating the "prefactor" for calculating f_nu.  This prefactor includes a calculating of gaunt_ff.  

After these changes were made,  gaunt_ff ceased to be a major time sink in the optical thick macro atom example I have been investigating.  The regression tests also seem slightly faster.  The resulting spectra were unchanged.

Given that the principle motivation of this issue was time realted,  I am closing the issue.
