### ISSUE TITLE
macro associated structures clean-up

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#884]
There are (at least) two locations where macro information is stored, plasmamain and macromain.  Both plasmamain and macromain have the same number of entries.  (If you look at calloc_macro, it the input parameters say it creates nelem elements, but if you look at where it is called you find calloc_macro (NPLASMA).  

The macro atom information in plasmamain is here

```
/* Beginning of macro information */
  double kpkt_emiss;            /*This is the specific emissivity due to the conversion k-packet -> r-packet in the cell
                                   in the frequency range that is required for the final spectral synthesis. (SS) */

  double kpkt_abs;              /* k-packet equivalent of matom_abs. (SS) */

  /* kbf_use and kbf_nuse are set by the routine kbf_need, and they provide indices into the photoinization processes
   * that are "significant" in a plasma cell, based on the density of a particular ion in a cell and the x-section 
   * at the photoinization edge.  This process was introduced as a means to speed the program up by ignoring those
   * bf processes that would contribute negligibly to the bf opacity
   */

  int *kbf_use;                 /* List of the indices of the photoionization processes to be used for kappa_bf.  */
  int kbf_nuse;                 /* Total number of photoionization processes to be used for kappa_bf. (SS) */

/* End of macro information */
```

This is very confusing and ought to be fixed so that all of the macro associated quantities are in macromain.  @jhmatthews @ssim  Do you agree?

**Comment by jhmatthews** [comment]
While I agree this is a bit confusing, I think it's actually necessary with the current code operation. We only allocate the macromain structure if we have macro-atom levels, but we have the option to use "macro-atom line transfer" (really indivisible packet line transfer) without any macro-atom levels. In this case, one could still have a k->r emissivity without having any macro-atom emissivity. Closing this one.
