### ISSUE TITLE
Input file causes segfault

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#885]
I'm trying to run an Athena file thruogh python. There is clearly something wrong with the datafile - probably velocities exactly the same in two cells - this causes an error:

calculate_ds: the frequency along the photon 11562 path's in cell 6083 is the same

which is not a bug - however immediately afterwards I get:

check_plasma -- radiation 
[uos-15962:41472] *** Process received signal ***
[uos-15962:41472] Signal: Segmentation fault: 11 (11)
[uos-15962:41472] Signal code: Address not mapped (1)
[uos-15962:41472] Failing at address: 0x7fb3c71e8ed0
[uos-15962:41472] [ 0] 0   libsystem_platform.dylib            0x00007fff70f075fd _sigtramp + 29
[uos-15962:41472] [ 1] 0   ???                                 0x0000000000000000 0x0 + 0
[uos-15962:41472] [ 2] 0   py85h                               0x000000010c906b9f translate_in_wind + 383
[uos-15962:41472] [ 3] 0   py85h                               0x000000010c906838 translate + 88
[uos-15962:41472] [ 4] 0   py85h                               0x000000010c912648 trans_phot_single + 216
[uos-15962:41472] [ 5] 0   py85h                               0x000000010c912477 trans_phot + 519
[uos-15962:41472] [ 6] 0   py85h                               0x000000010c967017 calculate_ionization + 1511
[uos-15962:41472] [ 7] 0   py85h                               0x000000010c8fe2ee main + 2830
[uos-15962:41472] [ 8] 0   libdyld.dylib                       0x00007fff70d0ecc9 start + 1
[uos-15962:41472] [ 9] 0   ???                                 0x0000000000000004 0x0 + 4
[uos-15962:41472] *** End of error message ***
Segmentation fault: 11

Which is not something we want to happen!!

here are the files:

[athena.pf.txt](https://github.com/agnwinds/python/files/6747137/athena.pf.txt)
[athena.mod.txt](https://github.com/agnwinds/python/files/6747141/athena.mod.txt)

Will briefly investigate....

**Comment by Higginbottom** [comment]
The code is crashing in kappa_ff - and it seems that a photon has got into a cell with zero temperature so it should not be in the wind. The problem is most likely with the input file.

**Comment by Higginbottom** [comment]
Hmmmm, the segfault is caused when the domain is set in kappa_ff - the photon finds itself in plasma cell 12288 (there are 96x128=12288 plasma cells - so the last one is 12287) which has wind cell -1 - because it isn't in the wind. 
The wind model is just the same as I've been using in terms of ghost cells etc - so *if* the model is correctly formatted - something is going wrong somewhere... This is probably a one in a million chance - but it is clearly showing something important - either my model files are wrong, and have by chance been working - or the model import code is doing something strange... or the photon transport is somehow shoving a photon into a guard cell...

**Comment by saultyevil** [comment]
Huh, I may have come across something similar with my imported TDE models, I think.

I made an experimental change where I turned this stuff in [wind.c](https://github.com/agnwinds/python/blob/6af06f40d910c36e2412d28e516ed27af6e42951/source/wind.c#L179) on line 179,

```c
    if (one_dom->wind_type == IMPORT)
    {
      one_dom = &zdom[ndom];

      n = where_in_grid (ndom, x);
      if (n >= 0)
      {
        *ndomain = ndom;
        ireturn = W_ALL_INWIND;
        break;
      }
    }
```

to this

```c
    if (one_dom->wind_type == IMPORT)
    {
      one_dom = &zdom[ndom];

      n = where_in_grid (ndom, x);
      if (n >= 0)
      {
        *ndomain = ndom;
        ireturn = wmain[n].inwind;  // this is the different line
        break;
      }
    }
```

I think the problem is that the dev version is basically assuming that everywhere which in the grid is also in the wind, as long as it passed all the other checks above. But the imported grid could actually disagree wiuth that and have inwind set to W_IGNORE or W_NOT_INWIND. So it's best to look up what the grid has to say for itself.

I thought I changed in with a previous set of bug fixes related to negative frequencies, but I clearly missed it. Could you try that change? I think I also have a few other fixes to do with imported models on my experimental TDE branch as well...

**Comment by Higginbottom** [comment]
Ok, so that fix certainly fixes the crash!

**Comment by saultyevil** [comment]
Great! So I've also tracked down the other changes I've made on my TDE branch and added them into dev in a branch named "import_fixes".

If that also works, I shall merge the changes into dev.

**Comment by kslong** [comment]
@Higginbottom   Is this still an issue?

**Comment by kslong** [comment]
@Higginbottom   I could not reproduce this error.  Could you please see if you can reproduce it with the current version of dev.  I am a bit suspicious that this is similar to #870 as it appears one has a photon that thinks it is in a wind cell that has no volume, and is getting pointed toward the dummy cell.  However I did not  see the error that I thought would show this.  Or maybe what @saultyevil  did has fixed it.  Anyway, if you can reproduce the error, please provide the details, e.g number of threads (hopefully not too many) and the commit number.  If you cannot reproduce it, then we should close it.

**Comment by Higginbottom** [comment]
I agree - it runs fine now!
