### ISSUE TITLE
How to define FRACTIONAL_ERROR

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#89]
This was a problem originally identified in #40 but as it is a specific problem I've created a new report here.

We use the variable FRACTIONAL_ERROR in the ionization routines, where we try and converge on a solution for ne. This is currently set to 0.03.

There is a problem here, and it is that there are cases (eg H recombination lines) where you have a very ionized plasma but are sensitive to the amount of neutral H. So there can be examples where your overall density is 1e13, with 1e6 of neutral H and ne is still roughly 1e13 - so a 0.03 change in 1e13 can clearly be order of magnitude changes in neutral H. Note that there is also a maximum number of iterations around the loop over ne 

I'm doing some tests but it's a tricky one. The code here is also a bit of a mess and may need reorganising.

**Comment by jhmatthews** [comment]
Currently we exit the loop when the following condition is satisfied

``` C
if (fabs ((xne - xnew) / (xnew)) < FRACTIONAL_ERROR || xnew < 1.e-6)
    break;
```

I propose changing this to (where newden[0] and old_neutral_h are the new and old H densities respectively.

``` C
      if ( ((fabs ( (xne - xnew) / xnew ) < FRACTIONAL_ERROR) && 
            (fabs ( (newden[0] - old_neutral_h) / newden[0] ) < FRACTIONAL_ERROR) )
            || xnew < 1.e-6)
        break;
```

so that we also check that neutral Hydrogen has converged reasonably well. I would also suggest that fractional_error might be one of the first "advanced" mode variables, partly because it would allow me to test this properly. 

Any thoughts welcomed.

**Comment by jhmatthews** [comment]
I've been looking at how this effects the speed, H alpha and neutral_h values for both the old approaches and new approach with a condition for neutral hydrogen also added. 

This loop can, unsurprisingly have a pretty big effect on speed. Bear in mind that all these plots are generated from a single ionization cycle, so the models are not converged in the sense of balancing heating and cooling properly, but they should still be able to test this proglem as really we are worried about it affecting the esimate of neutral H in dense ionized regions.

**With old method: Only converge on ne**

Speed and check if cells don't converge. X Axis is log FRACTIONAL_ERROR:

![speed_no_h_condition png](https://cloud.githubusercontent.com/assets/3007249/3672635/01b7b270-1263-11e4-8f78-b0a908d443b3.png)

Check of H alpha emissivity and neutral H by cell, KEY  is log FRACTIONAL_ERROR, black dotted line shows ne:

![emissivity_no_h_condition](https://cloud.githubusercontent.com/assets/3007249/3672638/06f67b54-1263-11e4-9585-122df7ccbdf6.png)

**With new method: converge on ne and neutral H**

Speed and check if cells don't converge, X Axis is log FRACTIONAL_ERROR::

![speed_with_h_condition png](https://cloud.githubusercontent.com/assets/3007249/3672049/c100b02e-1258-11e4-8aa3-6f80e5e0f93f.png)

Check of H alpha emissivity and neutral H by cell, KEY  is log FRACTIONAL_ERROR, black dotted line shows ne:

![emissivity_with_h_condition](https://cloud.githubusercontent.com/assets/3007249/3672041/abf2c820-1258-11e4-8df2-d90c3f1da967.png)

**Finally, a comparison of the old method with fractional error set to 0.01, and new method with fractional error set to 1e-3**

![emissivity_comp](https://cloud.githubusercontent.com/assets/3007249/3672045/b42a0896-1258-11e4-9391-50676fa0f677.png)

### proposed solution

**Short term:** for the CV paper release (which we'll now need another one of). 

Implement the loop in the comment above, which will test for ne and neutral H convergence. Set FRACTIONAL_ERROR ro 1e-3. Estimated maximum time penalty is from 110->120secs per ionization
cycle.  

**Long term:** Think carefully about better ways to solve for the ionization state, e.g. [this paper](http://iopscience.iop.org/0022-3727/33/8/314) which Knox sent me. This is related to a more general issue of making our ionization and recombination routines both more robust and simpler in terms of code organisation.

**Comment by Higginbottom** [comment]
Hi James. I've allowed myself to get a bit out of touch with this, partly because it was flagged as a macro atom problem… A couple of questions:
Is this still just a macro-atom problem? 
Do we need to modify the convergence criteria in variable temperature mode?
Do I need to consider these issues as I start to get into the matrix solver mode?

Nick

**Comment by jhmatthews** [comment]
The problem is that using a fractional change in ne as a convergence criteria is not a good idea if you care about the emission from e.g. neutral Hydrogen. There are plenty of examples where this is true, as recombination and collisionally excited emission can both occur from dense ionized plasmas where ne is much higher than n_HI. 

It's not just macro atom problem as this loop is entered regardless, and yes we should also modify variable_temperature as it uses a similar iterative procedure. 

Regarding rate matrix solver mode. At the moment we have to do this loop when using macro_pops, but this is because our estimate for ne affects our rate matrix and the estimate for ne is affected by the ions which you aren't treating as macro-atoms. I think it's going to depend on exactly how we implement it. If my understanding is correct one can construct one giant rate matrix in which one of the rows is for ne, but if you do individual species then iteration may be necessary.

**Comment by jhmatthews** [comment]
I've updated the above comment so it actually explains what the plots say (sorry). Would be good to get @kslong thoughts on fix.

The bottom line
- changing fractional error doesn't make much difference, but there are some differences in the H alpha emissivity. 
- It's a bit of a mystery to me why it doesn't affect neutral H more, but I guess the modified saha approach just happens to do a lot better than 0.03 accuracy?
- I would like to improve the criteria so they include a fractional change in neutral H as well, as a short term fix for CV paper. We may want to consider changing how we do things longer term.

**Comment by jhmatthews** [comment]
Christian and I talked about this recently, and Christian persuaded me that this probably isn't actually a big issue, because n_HI is calculated from rates involving ne, and so if ne changes you shouldn't expect n_HI to change by more than the factor it changed by squared, roughly. I'll write this up properly somewhere and need to test if this is really true, but what I've done above suggests it is. The question about how to set the value of FRACTIONAL_ERROR still remains. 

To avoid the speed hit, I'm keeping it set to 0.03. It makes next to no different to the neutral H anyway.
