### ISSUE TITLE
Update CITATION.cff

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#890]
GitHub now has a 'cite this repository' button that uses .cff files. Fortunately, I added one years ago! Unfortunately, that was years ago and it needs updating to work properly. It was supposed to refer to both the specific Python version, and also request users cite the Long & Knigge 2002 paper.

![Screenshot from 2021-07-29 16-39-39](https://user-images.githubusercontent.com/8093436/127522311-2f84b29f-0a46-4e5f-8907-de2b48b4bc8b.png)
(Overleaf's default template!)

In place of using the citation file to provide a citation for specific versions we should probably generate DOIs for releases via [Zenodo](http://www.zenodo.org), and have the citation file just refer to the 2002 paper, or the release paper when it's released.

**Comment by kslong** [comment]
Citation for github are discussed in 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

and here

Ours is clearly out of date.

**Comment by kslong** [comment]
See also

https://ui.adsabs.harvard.edu/abs/2022arXiv221212683A/abstract

**Comment by smangham** [comment]
Doing a quick test with my fork on sandbox.zenodo.org as it generates an up-to-date CITATION.cff template. Then I'll update the CFF on this repo.

For the actual release, there's a slight chicken-and-egg problem with Zenodo - as the DOI is generated on the release, you can't have a CITATION.cff file contain the DOI for its own release - and obviously we can't include the DOI for the release paper in the CITATION.cff until that's published too. There's a generic "Project DOI" we'd want, but the 'best solution' is:

1. Link repo to Zenodo
2. Create a release, that's code-final, with a CITATION.cff file containing the project DOI (e.g. commit #ABCDEF tagged 1.0)
3. Zenodo will generate a DOI for that release (containing the final code)
4. Once you get the Zenodo DOI for that commit and the paper DOI, modify the CITATION.cff to contain those DOIs, and create a new release on the same tag (e.g. commit #ABCDF0 tagged 1.0)

Now anyone who comes to the code directly from the URL has the CITATION.cff containing the correct DOI, and anyone who comes to the code via the DOI and downloads/checks out that one specific commit already has the DOI.

**Comment by smangham** [comment]
Copying from Slack for posterity: Just nailing down the CITATION.cff file and I think that requires a decision on which citations to request people use. We can include DOIs for:

* The GitHub repository on Zenodo (for all versions of Python)
* The specific GitHub release on Zenodo (e.g. 1.0)
* The release paper (as arXiv:1234.5678 or the journal DOI or whatever)
* Any other papers (e.g. the original 2002 paper, https://doi.org/10.1086/342879) (though the DOI for that is broken?)

Whilst we can include all of these in the CITATION.cff, which do we ask people to cite. The 'project DOI' and specific version is a way to ensure you don't end up making the code appear less widely used than it is by only having version DOIs, so the question is which. Historically, we've used the 2002 paper as the 'project paper', so:

* **Project:** Zenodo for GitHub repository, **specific:** release paper
* **Project:** Release paper (taking over from 2002 paper), **specific:** Zenodo for GitHub release
* **Project:** 2002 paper, **specific:** Zenodo for GitHub release
* **Project:** 2002 paper, **specific:** release journal paper

1 journal/1 Zenodo seems like a good balance, but I've not had a major role in submitting papers for a while so it'd be helpful to get  @jhmatthews' opinion. I'm not sure how important it would be to keep building on the 120 citations from the 2002 paper, or whether asking people to cite 3 is OK if one or two are Zenodo DOIs.

@rgupta106 Can I check - is this your ORCID? https://orcid.org/0000-0003-4905-7801

**Comment by smangham** [comment]
Hm, annoyingly the "Cite this repository" link on GitHub *only* includes a single DOI, specified as a top-level `doi` key. So there's a question there as well, if someone's not going to read our `CITATION.cff` file and is just going to get the BibTex out of GitHub for a single citation, what do we want the DOI to be.

**Comment by jhmatthews** [comment]
Just a note that, after discussions with Sam, we need to remember to update the citation.cff once the release paper is published to point towards the release paper DOI correctly, and make sure we acknowledge all contributors. There are various choices here, but the main thing is to make sure that users are clear about which version they used in a given paper and that they cite the correct software papers when using the code.
