### ISSUE TITLE
Disk luminosity does not appear to take account of disk heating

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#896]
Photons striking the disk are supposed to heat it up, and change the temperature profile. 
However, work with the rad-hydro CV model is confusing, because the disk temperature reported by the t_tot field in the disk.diag file matches the expected disk temperature as computed by the equations given by Proga-stone-drew however the flux above the disk does not match that temperature.

Previous investigations suggest that the irradiated disk temperature *is* used to compute the SED of the disk, however bizarrely the flux seems to always match the S+S disk profile.

I believe that the problem is that the disk luminosity, as computed by the function disk_init always uses the S+S temperature profile, rather than t_tot. Therefore the total luminosity of the disk, and the 

This is the first pass through, when the disk has not yet been irradiated...

!! xdefine_phot: lum_tot 3.40e+35 lum_star 0.00e+00 lum_bl 2.71e+35 lum_bh 0.00e+00 lum_disk 6.91e+34 lum_wind 0.00e+00

and after one cycle, when t_tot is very different

!! xdefine_phot: lum_tot 3.40e+35 lum_star 0.00e+00 lum_bl 2.71e+35 lum_bh 0.00e+00 lum_disk 6.91e+34 lum_wind 0.00e+00

the disk Lum is identical.

Reading in a temperature profile that uses the expected temperature profile from PSD (which matches the t_tot field)

!! xdefine_phot: lum_tot 4.02e+35 lum_star 0.00e+00 lum_bl 2.71e+35 lum_bh 0.00e+00 lum_disk 1.31e+35 lum_wind 0.00e+00

We should be using the same temperature field for computing the disk luminosity as we do for generating the disk photons... oooooops!

**Comment by kslong** [comment]
So Nick, is this what you saying?  When you use a disk that is supposed to have the temperature raised by absorption (and reradiate by the higher temperature), that we do not actually use the revised temperature to calculate a new luminosity, and that therefore the disk does not radiate enough photons because the disk luminosity has not been revised (even though the photons that it does radiate reflect the revised temperature)

**Comment by Higginbottom** [comment]
More or less - but it seems more complex than that - I'm writing up here: https://www.evernote.com/shard/s303/nl/133638373/401dc510-5ce8-4751-8173-726c85078163/

**Comment by Higginbottom** [comment]
Closing this - I think python is right - but that leaves the concerning problem that proga-stone-drew and Dannen-proga might be wrong....
