### ISSUE TITLE
Two level atom - improve radiative excitation

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#90]
The two level atom code in lines.c includes both collisional and radiative excitation from lower to upper level. However, the radiative excitation only permits a dilute blackbody model of the mean intensity.

An enhancement would be to permit the model of mean intensity (power law or exponential) to be used.

**Comment by Higginbottom** [comment]
This enhancement has been implemented with the following changes.

A new subroutine - mean intensity has been written in radiation.c. This returns a value for the specific mean intensity at a requested frequency, either using dilute blackbody or a model depending on the ionization mode. The reason for this new routine is that we will now have two locations where the mean intensity is calculated (two level atom, and induced compton). It is best practice to have a subroutine to do this rather than duplicate code.

The second change is simply to replace the code in induced compton that currently computes the mean intensity with a call to the new code.

Finally, the actual meat of the change is to call mean intensity, and then use the resulting value of J_nu in the two level atom equation in two_level_atom.

**Comment by jhmatthews** [comment]
This was done in pull request #88 and was merged via commit https://github.com/agnwinds/python/commit/540177551980d41474aabbbaa5bc72a950df460c
