### ISSUE TITLE
Error while trying to generate rootname.complete file using the py_wind routine

### ISSUE THREAD

**Issue by Subho-kar** [sirocco-rt/sirocco#903]
Hi all,

I have been using the Python 85 version to generate model spectra of massive stars and have been able to generate several output files using the usual py85 routine. Following the documentation, I have started to use the py_wind and windsave2table routines and have generated corresponding files. But, as I try to generate the "rootname.complete" file, I get an output dialog as quoted below:
**Choice (i) :1
Choice   1
Save ions as densities (0) or fractions? (1) (0) :
Save ions as densities (0) or fractions? (1) 0
This mode is recommended purely for file output
n	nplasma	inwind	i	j	x	z	v	vx	vy	vz	dvds_ave	vol	 rho	ne	te	tr	nphot	w	ave_freq	IP	conv	conv_tr	conv_te	conv_hc	 cool_tot	lum_tot	lum_rr	cool_rr	lum_ff	lum_lines	cool_adiabatic	cool_comp	cool_dr	cool_DI heat_tot	heat_photo	heat_auger	heat_lines	heat_ff	heat_comp	heat_ind_comp	heat_shock	 ionH1	ionH2	ionHe1	ionHe2	ionHe3	ionC3	ionC4	ionC5	ionN5	ionO6	ionSi4
py_wind_sub does not work yet**
 
I shall be grateful if anyone can help me with the same. 
Thanks in advance.

Regards,
Subhajit

**Comment by saultyevil** [comment]
Hi Subhajit, when you start `py_wind` to use the "onefile" mode, you need to use `Make_files(0=no,1=original,2=regrid_to_linear)` = 1 or 2 as this initializes `py_wind` to write the output to file.

I have also had a look at the code and I'm not fully convinced that this functionality of `py_wind` is fully complete just yet. You can get the exact same (and a bit more) output by using `windsave2table rootname` instead. `py_wind` exists mostly as a legacy tool at this point and a lot of the basic functionality of it has been superseded by `windsave2table`.

**Comment by Subho-kar** [comment]
Hi Edwards,

Thanks for the reply. I just tried your suggestion and it has successfully generated the "rootname.complete" file.
Thanks again for the help.

Regards,
Subhajit
