### ISSUE TITLE
No Macro atom data of Nitrogen/Oxygen ions in the 'atomic_macro' sub-directory

### ISSUE THREAD

**Issue by Subho-kar** [sirocco-rt/sirocco#904]
Hi all,

I have been trying to model the spectral lines of massive stars using the Python 85 version. In my case, I have been using the **h20_hetop_standard80.dat** as an input for Atomic data in the "filename.pf" file because most of the spectral lines are a consequence of NLTE-transitions which requires the macro atom information of the elements. From the literature survey of the targeted stellar objects, I have found that they have prominent nitrogen lines (of NIII, NIV ions) also. But in the sub-directory "atomic_macro" which is under the "xdata" subdirectory,  I couldn't find any macro atom data for Nitrogen/Oxygen ions.  In order to generate their spectral lines in my model, I tried to increase the maxnlte levels of NIII and NIV ions in the **h20_hetop_standard80_elem_ions.dat** file but it seems that without the corresponding _element_ion_top_levels.dat_, _element_ion_top_lines.dat_ and _element_ion_top_phot_macro.dat_, the expected results are not reproduced. 
It would be great if anyone can help me with their suggestions.

Thanks in advance,

Regards,
Subhajit Kar

**Comment by saultyevil** [comment]
@jhmatthews may want to chime in here, but as far as I know we do not currently have Nitrogen or Oxygen macro atoms in our atomic data, and we are focusing mostly on implementing Carbon macro atoms before N and O. The addition of more elements as macro atom is not the at top of our todo list either, as we are first improving the performance of macro atoms before we add more in (as more macro atoms means longer simulations).

Creating the atomic data to add more macro atoms is a difficult process, and unfortunately we don't have any "finished" documentation at the moment to help you out here.

**Comment by Subho-kar** [comment]
Thanks for the reply. I see, if that's the case, I shall try some other ways to solve the issue even though I won't be able to generate those spectral lines. If there's anything else that you or anyone can suggest, I shall be much obliged.

Regards,
Subhajit

**Comment by kslong** [comment]
This issue is being addressed in the context of preparation of the S/W release paper.  If a specific need arises, we can no provide macro-atom models for other ions, including CNO.
