### ISSUE TITLE
Macro-atom radiation field estimators not being normalised or packed correctly between threads

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#910]
This was originally documented as #898 but the root cause is different and is documented here more succinctly. The basic issue is a difference between models when run with different numbers of threads. 

In wind_updates2d.c we call the routine wind_update() which updates the properties of each wind cell including the temperature, radiation field estimators, and ionization state. This routine splits the cells up between threads evenly in the usual parallel way, and then uses MPI_Pack and MPI_Unpack to make sure each thread has a copy of each quantity it needs. 

The function ```normalise_macro_estimators``` is called inside this loop. This routine normalises the following macro-atom estimators and copies them to "old" version of themselves. These estimators are in the macromain structure and are called (in addition to the same estimators with _old subscript):
```
mplasma->jbar
mplasma->gamma
mplasma->gamma_e
mplasma->alpha_st_e
mplasma->alpha_st
```
As an example, for the jbar estimator, what is done is as follows:
```C
mplasma->jbar_old[config[i].bbu_indx_first + j] =
mplasma->jbar[config[i].bbu_indx_first + j] * VLIGHT * stimfac / 4. / PI / invariant_volume_time / line_freq;
mplasma->jbar[config[i].bbu_indx_first + j] = 0.0;
```
jbar is then incremented again in the next cycle, and jbar_old is used for the macro-atom jump probabilities, but this is only correct in some of the threads. 

The result of this is that the level populations will use the correct jbar_old, because they are calculated in the same loops, and jbar is zeroed before the next cycle in wind_rad_init. However, the macro-atom upwards jumps in the next cycle associated with these quantities will be using the wrong (probably initial) values of jbar_old. This will affect the passage of photon packets through the program and lead to inconsistent results between threads, and in some cases could lead to incorrect line luminosities. Initial investigations suggest it doesn't make much difference in a QSO model from the 2020 paper, but this should be checked more thoroughly including other models. 

**To fix:** A simple fix has been implemented in commit  https://github.com/agnwinds/python/commit/e12cc58c661903c356b0ce670b7f90fa84bf877e by moving the normalisation out of the parallel loop and into a loop over NPLASMA. If normalise_macro_estimators is important time wise, one could move it back inside the parallel loop but we must ensure in that case that the correct MPI_Pack statements are present.

**Comment by jhmatthews** [comment]
To show, briefly, how this changes things, from Nick's results. Before the fix, this was a comparison of an 8 v 12 thread run:
![diff](https://user-images.githubusercontent.com/3329213/136168997-b023dce5-f7b2-49fc-a3b4-32adf337b49d.png)


After the fix, this happens:
![diff](https://user-images.githubusercontent.com/3329213/136820342-0d7d98f8-f38f-4c0b-b3e7-f421ce1872bf.png)

Further details and commentary in #898

**Comment by jhmatthews** [comment]
Am I right in thinking this has now been merged and be closed, @kslong ?

**Comment by kslong** [comment]
Yes, this has been merged and can be closed, so I will do so.
