### ISSUE TITLE
Query about choice of wind.ionization type

### ISSUE THREAD

**Issue by Subho-kar** [sirocco-rt/sirocco#915]
Hi all,

As I have earlier mentioned that I have been trying to model the spectral lines of massive stars using the Python 85 version. In the input file 'filename.pf', I have a dilemma between the types of wind ionization that would be appropriate in defining the proper ionization structure of the stellar winds. I tried to look for the same in the Python Online Documentation (https://python-swm.readthedocs.io/en/latest/input/parameters/wind/Wind/Wind.ionization.html), but couldn't find any description about each of the available types. I will be thankful if anyone can kindly provide the information about **on.the.spot** and **ml93** wind.ionization types or refer me to the associated research articles where these have been discussed. 

Thanks in advance,

Regards,
Subhajit Kar

**Comment by saultyevil** [comment]
Hi Subhajit,

Our documentation is still a work in progress! The different wind ionization modes are just different ways in which the program can calculate the density of various ions in the simulation. Some are faster than others, but less accurate.

If you want to know about the on the spot approach, there is literature in the form of lecture slides, e.g. [here](https://www.astro.physik.uni-potsdam.de/~lida/TEACH.DIR/ism3.pdf) and [here](https://w.astro.berkeley.edu/~ay216/05/NOTES/Lecture03.pdf). On the spot is designed for optically thick winds, where photons are absorbed close to the point where they are generated.

The ML93 method implemented in Python is based on the method outlined by [Mazzali & Lucy 1993](https://ui.adsabs.harvard.edu/abs/1993A%26A...279..447M/abstract). Which, I think, is a modified version of the on the spot approximation. We are specifically using Eq. 11 to calculate the ionization state for this method.

The matrix_bb and matrix_pow modes are both more sophisticated schemes to calculate the ionization state. Matrix_bb assumes the radiation field is well described by a (dilute) blackbody, whilst matrix_pow creates a model of the radiation field. Information about these schemes can be found in Section 5.3 of [Nick Higginbottom's thesis](https://eprints.soton.ac.uk/368584/1/Higginbottom.pdf) or in Section 3.4.2.1 of [James Matthew's thesis](https://eprints.soton.ac.uk/400903/).

**Comment by Subho-kar** [comment]
Hi Edward,

I am extremely thankful to you for sharing all the references associated with the various wind ionization modes. I have found what I was looking for and now I will be able to distinguish between them properly and find the suitable one for my models.
Thanks again for the help.

Regards,
Subhajit Kar
