### ISSUE TITLE
Memory leak in wind_updates2d.c

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#92]
I'm trying to understand how much memory python uses, so I can spec out what HPC resources Daniel and I will need for the next few years. Simply using top, and watching how python uses memory I noted a memory leak - i.e. each cycle the RSIZE increases monotonically.

The leak is located in wind_updates, where memory is allocated to commbuffer - the array used to communicate the plasma structure between all MPI processes. This is never freed. So, in the example of a simple CV model, the size of commbuffer is 20 megabytes, and the memory used increases by this much each cycle. This is a big problem in a zeus model, where commbuffer is 461 562 576 bytes - so the memory used by the process increase by nearly 0.5 gigabytes per cycle.

Fortunately, the solution is simple - a free(commbuffer) command at the end of the communication loop - about line 592.

I'll let everyone take a quick look, in case I'm not correct with this, but clearly this is a very simple thing to fix…

Nick

**Comment by jhmatthews** [comment]
I agree- free(commbuffer) at end of wind_update.

**Comment by kslong** [comment]
Good catch, Nick. Memory leaks are often hard to find and it's a good thing to get rid of them.

Knox

**Comment by Higginbottom** [comment]
Closed with update 48586a7e0a8faebfa55d948652386b10fd7d8046

Nick
