### ISSUE TITLE
Convergence trouble (associated with upweighting) in the partially ionised regime

### ISSUE THREAD

**Issue by mattstepney** [sirocco-rt/sirocco#921]
In the current best 5548 model, the wind base is approx 7000K and partially ionised (the neutral hydrogen is dominating the hydrogen fraction). This seems to result in convergence problems. The radiation temperature converges to a point, and then randomly varies in proceeding cycles, as does the heating and cooling. Currently we believe this happens because of the large amount of shielding, in this partially ionised region, is preventing photon bundles tracking through the wind base. This is evident in the py_wind colour maps that show individual photon tracks in the radiation temperature plots and stochastic noise in the heating and cooling plots. Thus far, the spectra after 20, 25, 30 and 35 ionisation cycles seem near identical. This is likely due to the electron temperature converging in excess of 90% and remaining so for all proceeding cycles. Current understanding indicates that, provided that the line forming region of concern isn't in this partially ionised region, this shouldn't effect the credibility of the model. (Plots show UV spectra after 35, 30, 25 and 20 cycles respectively)
![Seyfert35](https://user-images.githubusercontent.com/71068182/143253730-057df471-9786-48f0-a408-128c17180af9.png)
![Seyfert30](https://user-images.githubusercontent.com/71068182/143253750-45ee7753-b58a-4baa-8fe9-f8177524e57d.png)
![Seyfert25](https://user-images.githubusercontent.com/71068182/143253784-3b833b97-cfb3-4f21-8179-f9c9ea6dcdbe.png)
![Seyfert20](https://user-images.githubusercontent.com/71068182/143253802-53df1b59-6384-40d2-9c89-0d412023a815.png)
![Seyfert_log_t_r](https://user-images.githubusercontent.com/71068182/143253868-74404d96-8add-4d00-9007-240922a36043.png)
![Seyfert_log_t_e](https://user-images.githubusercontent.com/71068182/143253896-3184e8bc-8d00-4839-a784-1335daa5f06e.png)
![Seyfert_log_cool_tot](https://user-images.githubusercontent.com/71068182/143253912-7d8bde9b-79d0-4059-9ba0-504bc537014e.png)
![Seyfert_log_heat_tot](https://user-images.githubusercontent.com/71068182/143253917-a9af5905-f985-4977-818e-dedda868bacd.png)

**Comment by kslong** [comment]
@mattstepney   Please add the parameter file to this issue, and, though I don't think it will matter in this case the version of Python you are running.

**Comment by jhmatthews** [comment]
What's going on with those weird tracks in the T_r plot?

**Comment by jhmatthews** [comment]
Also...quadruple peaked lines?

**Comment by kslong** [comment]
So, I did the following experiment.   I took a version of the Seyfert model that had been run without upweighting and was converged in 77% of the program, and then tried running additional cycles with upweighting turned on.

When I did this with 10^7 photons the convergence numbers stayed about the same.  To see if I could get the convergence to go up, I ran the same test, except that I increased the number of photons to 10^8.  Unfortunately, in this run the convergence dropped back to values between 50 and 60%.

**Comment by kslong** [comment]
We are agreed that this problem arises from effects of upweighting, and that an interim solution is simply to turn upweighting off in situations when convergence problems arise.    We still need an actual solution.

**Comment by kslong** [comment]
I have created  histograms of the upweighting values for several models.   This is simply an attempt to see what the range is and are histogram of all fo the upweighting values in all of the plasma cells 

This is a model similar to Matts with 10**7 photons per cycle that is in the neighborhood of 50% converged

![test_Upweight](https://user-images.githubusercontent.com/2530901/145085010-8e8996c0-8caa-43da-985e-c52c5f784661.png)

**Comment by kslong** [comment]
@jhmatthews   I know you are planning to write up something that describes what happens when we do upweighting and how it might lead tot he problem we are having with convergence.  I have two questions about all of this:
- As I understand our upweighting approach, in addition to upweighting itself, the upweighting scheme allows us to get recombinations from other atoms other than the one that caused the initial photoinization.   Are we actually sure that it's the upweighting itself that is a the problem, or could it be that the frequency range into which photons can be shifted is much larger with the new approach
- The second question is related a bit.  How hard would it be to make a macro atom for the higher z elements, that was only had the same jumps available as our current swimple atom model, that is to say no internal transitions between upper levels.

**Comment by jhmatthews** [comment]
I'm closing this issue since upweighting is now turned off by default given all the issues it caused, but it's closed with the caveat that was never exactly "fixed" when using upweighting.
