### ISSUE TITLE
Segfault with thin shell model, macro atom mode, multiple cores

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#928]
Trying to calculate optically thin heating and cooling rates, I have been running python with a thin shell. 
If I use either of the macro atom line transfer modes, and either of the macro atom transition modes I get vexingly intermittent crashes.

[Nicholass-MacBook-Pro:57307] *** Process received signal ***
[Nicholass-MacBook-Pro:57307] Signal: Segmentation fault: 11 (11)
[Nicholass-MacBook-Pro:57307] Signal code:  (0)
[Nicholass-MacBook-Pro:57307] Failing at address: 0x0
[Nicholass-MacBook-Pro:57307] [ 0] 0   libsystem_platform.dylib            0x00007fff204f2d7d _sigtramp + 29
[Nicholass-MacBook-Pro:57307] [ 1] 0   ???                                 0x1d7e141e7d250057 0x0 + 2125158195346604119
[Nicholass-MacBook-Pro:57307] [ 2] 0   py85j                               0x000000010fa49689 calculate_ds + 985
[Nicholass-MacBook-Pro:57307] [ 3] 0   py85j                               0x000000010fa3bd06 translate_in_wind + 150
[Nicholass-MacBook-Pro:57307] [ 4] 0   py85j                               0x000000010fa3ba88 translate + 88
[Nicholass-MacBook-Pro:57307] [ 5] 0   py85j                               0x000000010fa48188 trans_phot_single + 216
[Nicholass-MacBook-Pro:57307] [ 6] 0   py85j                               0x000000010fa47f97 trans_phot + 551
[Nicholass-MacBook-Pro:57307] [ 7] 0   py85j                               0x000000010faa0473 calculate_ionization + 1683
[Nicholass-MacBook-Pro:57307] [ 8] 0   py85j                               0x000000010fa330b2 main + 2802
[Nicholass-MacBook-Pro:57307] [ 9] 0   libdyld.dylib                       0x00007fff204c8f3d start + 1
[Nicholass-MacBook-Pro:57307] [10] 0   ???                                 0x0000000000000003 0x0 + 3
[Nicholass-MacBook-Pro:57307] *** End of error message ***

This is a parameter file that has crashed - although I can run it multiple times and it works OK. Grrr
[input.pf.txt](https://github.com/agnwinds/python/files/7691659/input.pf.txt)

This is the script that does the loop that makes the input file - obviously remove the .txts and ./py83_loop.py xi_0.param

[py83_loop.py.txt](https://github.com/agnwinds/python/files/7691672/py83_loop.py.txt)
[xi_0.param.txt](https://github.com/agnwinds/python/files/7691667/xi_0.param.txt)

**Comment by kslong** [comment]
This sounds nasty.  I can confirm I also get an error on my Mac with the current dev branch version of py85j and also one about a month ago.  When I run the input.pf file that is left when the failure happens, I don't get the error.

**Comment by Higginbottom** [comment]
I find that if you run the input.pf file a few times, on multiple cores, it will eventually fail...

**Comment by Higginbottom** [comment]
I wonder if it matters that its always the rank 3 process that fails. does this mean anything?
Scratch that - just ran with six cores and it failed on rank 0 process..

**Comment by Higginbottom** [comment]
With 6 cores, when it fails it fails on rank0, so the error gets put to the command line and the last thing that happens is 
 Ion. Cycle 1/2 of input : Photon      33332 of     166666 or   20.0 per cent 
 Ion. Cycle 1/2 of input : Photon      49998 of     166666 or   30.0 per cent 
 Ion. Cycle 1/2 of input : Photon      66664 of     166666 or   40.0 per cent 
 Ion. Cycle 1/2 of input : Photon      83330 of     166666 or   50.0 per cent 
 Ion. Cycle 1/2 of input : Photon      99996 of     166666 or   60.0 per cent 
 Ion. Cycle 1/2 of input : Photon     116662 of     166666 or   70.0 per cent 
spherical: ds_in_cell s and smax returning VERY_BIG in cell 0 nudging photon by DFUDGE
translate_in_wind: Grid cell 0 of photon is not in wind, moving photon 1.00e-03
translate_in_wind: photon 131654 position: x 5.93756e+10 y -5.14206e+10 z 6.18907e+10
calculate_ds: the frequency along the photon 0 path's in cell 1 is the same

Its intermittent, but when it fails it always fails at the same point. The error message is always produced, even if it continues...

**Comment by Higginbottom** [comment]
As a (possibly) side issue, the error message that produces this error is a little wrong:

    Error ("calculate_ds: the frequency along the photon %d path's in cell %d is the same\n", one->nwind, p_now.np);

the photon number should be the first thing out, and the cell the second. Interestingly, the p_now.np number is coming back as 1 - even though we are thousands of photons through the run. Is this relevant? Is the p_now not being set up correctly, so there is no photon there to be printed out?

**Comment by Higginbottom** [comment]
Another thing about this test, is that we check to see if the freqencies along the path are the same, but if they are we do exactly the same thing as if they aren't, we just throw an error..

**Comment by Higginbottom** [comment]
Still unsure that this is the fundamental problem, but the reason p_new is not set is because for this photon smax is equal to zero for some reason, and so the while loop 

  while (smax > wmain[p->grid].dfudge)

is never excuted this sets the p_now structure up. 

So this is why the error message has no information about the photon. Still unsure as to what the actual crash is related to - but I'm suspecting its nothing to do with matom - it may well be a random thing and its just pure chance that the random number generator spits out this pathological photon with the matom options turned on!

**Comment by Higginbottom** [comment]
This seems rather odd..
Investigating it looks like this might be what is going on..

For some reason, the test to see if a photon is in the wind is triggered in smax_in_cell. This pathological photon is in cell 0 , which is outside the wind, and so it is moved by a tiny amount - 1e-3cm (the shell is only 1cm thick). However, there is not a test to update the grid that the photon is in. So despite the fact that is has been properly pushed into cell1, it still thinks it is in cell0. 

It still thinks this when the error is triggered in calculate_ds. It is moving 0 cm at this point - perhaps because it is not actually in the cell it thinks it is.

The fix to stop the crash seems to be simply to update the cell in which the photon reports it is after it has been nudged so around line 550 in photon2d.c, after the call to move_phot, we do 
    p->grid = where_in_grid (wmain[p->grid].ndom, p->x);
so now the photon thinks it is in the grid - and presumably the segfault where at some point the code tries to access a density or something in a cell that isn't in the wind isn't triggered.

However, there is a test *before* smax_in_cell is called, around line 421 in photon2d.c which is supposed to quit if the photon isn't in the wind - so why does it report being in the wind here, but then when smax_in_cell is called a few lines later, it isn't in the wind.... Hmmmm. - EDIT - nope, that's fine - the first test is to see if the photon is in the grid. Which it is. Just not in the wind. But if this is a problem,, why doesn't it happen more often?

**Comment by Higginbottom** [comment]
The reason smax is equal to zero once the photon gets to calculate_ds is that smax_in_cell returns p->istat rather than smax if *any* of the errors are triggered, this seems like odd behaviour, because if we dont return smax, we should probably do something with the return value rather than treat it as smax.

**Comment by Higginbottom** [comment]
To summarise:

The problem here is that a pathological photon is winding up just outside the wind.

An error is triggered in smax_in_cell - and the photon is moved inside the wind, but the actual cell the photon resides in isn't updated. In addition, the return value from smax_in_cell which the code expects to be the distance the photon can move is set to zero.

When the actual ds in cell is computed in calculate_ds, I think that a call is made somewhere which attempts to reference some quantity in a non-existent wind cell - hence the segfault.

The most simple solution is just to update the cell in which the photon resides when the error is triggered in smax_in_cell.

A possibly more elegant solution is to modify the return value from smax_in_cell to something like -1 if the photon is not in the wind. Then, rather than try to track the photon through the cell, exit translate_in_wind and allow the translation routine to compute a new smax...

**Comment by kslong** [comment]
We thought we closed a very similar issue #870 once before.  We need to understand what happened to re-invent it.

**Comment by Higginbottom** [comment]
I’m hoping to talk about this on Tuesday.

**Comment by kslong** [comment]
@Higginbottom   Hopefully someone will look back to what was done for the earlier error, and verify that the code that fixed this has not been removed somehow.  It would also be useful to understand if this is exactly the same procedure the generated the original problem.

**Comment by Higginbottom** [comment]
Just checked it out. A totally different error.

**Comment by mandyhewitt** [comment]
I appear to be hitting this issue consistently (even when not using multiple cores) after I tried to merge dev into my stable polarization branch. I'm using a very short fiducial agn .pf - so perhaps the problem commit was introduced after 2 August 2021? When I switch to dev I don't see the issue immediately but do recall having intermittent seg faults in the past. I'll see if I can narrow down exactly which commit creates the immediate seg fault in my branch. 
[seg_fault11.txt](https://github.com/agnwinds/python/files/8123704/seg_fault11.txt)
[fid_agn_mat_test_vshort_test_pf.txt](https://github.com/agnwinds/python/files/8123736/fid_agn_mat_test_vshort_test_pf.txt)
[seg_11_single_core.txt](https://github.com/agnwinds/python/files/8123828/seg_11_single_core.txt)
.

**Comment by Higginbottom** [comment]
hmmmm. this runs fine (well without error) for me on dev.
I assume you have done "make all" or make clean before make python..
just checking...

**Comment by mandyhewitt** [comment]
Yes - many make cleans :) Same for me it works fine on dev but my branch is causing it immediately - so there is something in there recreating this fault. I've a hunch it could be something to do with some sprintfs perhaps...will check it out when I get a chance.

**Comment by kslong** [comment]
@mandyhewitt   I cannot reproduce this error any more (with the current version of Python) and so I am going to close this issue.  If you have a modern example, please document it here, and reopen the issue.
