### ISSUE TITLE
Speeding up Python for rad hydro

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#949]
@Higginbottom has noted that the limiting factor for rad hydro calculations is python, and that photon generation is a significant part of the problem. Specifically, he states that because the initialization needed for photon generation is not parallelized one does not get good scaling with the number of processors.  This issue is intended to allow us a discussion space for addressing this problem.

Nick if you could provide an example .pf file with appropriate other files, then we will all be working from the same page.

Since the actual generation of photons is parallelized, ksl's working assumption is that issue is associated with initialization

Inspection of the code in photon_gen.c shows that the top level routine for photon generation is define_phot, and that this routine differentiates between two main modes, one without frequncy sampling (used for creating detailed spectra) and one with frequency sampling (used in ionization cycles).

With no frequency sampling, the routine just calles two routines, xdefine_phot which does the initialization between the frequency interval that is given.

With frequency sample, the routine firsts calls populate_bands, to determine how many photons belong to each band, and then is cycles through the bands calling xdefine_phot for each of the bands before generating photons.  xdefine_phot populates variables in geo that are then used by xmake_photons which just generates the photons.  (There are also routines for generating photons from kpkts, which somewhat complicate the situation.

As NIck has pointed out, this section of the code is complicated, reflecting it's ancient history.  In principle, a lot of the initialization could be moved to the part of the code where we calculate the ionization balance (which is done in parallel).  Alternatively, we could parallelize this part of the code as a separate step.  Whatever we do, it seems likely that we want to convert the parameter in geo that are associated with photon generation from simple numbers to arrays.

This merits some kind of discussion among all of us before proceeding.

**Comment by Higginbottom** [comment]
We did a load of work on this before - talked about here: https://www.evernote.com/shard/s303/nl/49713906/2334e798-f1ef-950e-f9fe-44730df22ece?title=CV%20Rad-hydro%202022%20-%20Why%20is%20Python%20so%20slow?

The files I was using were:
[input.pf.txt](https://github.com/agnwinds/python/files/8683541/input.pf.txt)
[00000504.pluto.txt](https://github.com/agnwinds/python/files/8683543/00000504.pluto.txt)

**Comment by kslong** [comment]
There is no obvious reason to keep this issue open at this point, since no near term effort is planned.  The low hanging fruit has likely been harvested.
