### ISSUE TITLE
possible regression issue with dev

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#954]
Ive been trying to do regression. tests on the speed branch - to check my changes are OK, but I've found problems relating the bracnch back to dev, and indeed problems in dev. I'd appreciate someone else checking my work!

I did a commit to dev on 12/5 - 728b16... it seems to have done nothing - everything is identical to 0ccc7cc on the 10/5. This is the point at which the speed branch was forked..

James then did a commit on the 16/5 - I think it was to try and fix my commit - there are large differences between that and the previous 728b16 commit 

There is then another commit on 16/5 "minor docs change" 8bc7c... and that again seems to have very significant differences to the other commit of the same day, and also big differences to 728b16 etc.

I'm unsure as to when (or indeed if) problems started to creep in - I may be mistaken in all this - but until I can work out what commit is correct - I'm struggling to reconnect the speed branch to dev...

Help??

**Comment by jhmatthews** [comment]
Hmm, sorry, I think I've made a bad mistake here. I was experimenting with turning collisions off and it seems I accidentally left them off...REALLY SORRY, hope I haven't wasted too much of your time. It seems I accidentally did this in commit https://github.com/agnwinds/python/commit/c903b4ffb9eda4d7aa5751471816915372207720

you can see the error by doing, e.g. 
```
git diff 8bc7c2f580240cc5508e15174a095f6bad44e634 728b16cc189c8388273f671933d9a8cad17bc455 
```

I've just fixed this in dev with https://github.com/agnwinds/python/commit/e91c24706b6e3be186006965c995fd92a3db85b1

...my bad.

**Comment by Higginbottom** [comment]
Aaaaaah OK. Although I hadn't gone back that far with my tests - so I'm still a bit confused about the changes (or lack of change) with some of the other commits. I'm going too carry on and do some more comparisons. I'll take the commit before c903b... as 'truth' !!

**Comment by jhmatthews** [comment]
Bear in mind that commits in between merges might not necessarily have that in - for example your commit 728b16cc189c8388273f671933d9a8cad17bc455 has collisions in but my commits before and after don't. So I could imagine having diffs being a bit weird if there's been a merge above. Thanks for doing the tests! I'm working on getting an automatic test up and running again which may or may not pick up stuff like this!

**Comment by jhmatthews** [comment]
I think this is OK now right Nick? Can we close?

**Comment by jhmatthews** [comment]
Pretty sure this turned out to be due just to my collisions mistake, so I'm closing. Reopen if that's wrong!
