### ISSUE TITLE
Unexpected error on CV model restart: 'interfaces to pillbox is impossible'

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#97]
While testing the fix for issue #93, with the cv_standard model I noticed an odd error. 

The test I was carrying out was to run 4 ionization cycles, then restart the simulation to complete an extra ionization cycle and a spectral cycle.

At the completion of the restarted simulation, an error is reported that is not seen if the simulation if it is run all the way through (5 ionization cycles and 1 special cycle) in one go. The error is

pillbox 1 interfaces to pillbox is impossible

and it is generated during the photon transport phase of the spectral cycle.

This error is in the version of python before dynamic allocation, so that is not the cause..

**Comment by kslong** [comment]
We are not sure how to reproduce this, and so we are closing it.
