### ISSUE TITLE
Potential Documentation Improvements/Notes From First-Time Use

### ISSUE THREAD

**Issue by AustenWallis** [sirocco-rt/sirocco#982]
Documented Notes from Austen's Python install on fresh versions of Jammy Jellyfish Ubunutu 22.04 LTS and macOS Ventura 13.0.1

Problems encountered - 

- Ensure OpenMPI is installed as a prerequisite so the code installs/complies using mpicc. 

(This document helped me with step by step instructions, ensure most recent stable version is installed, https://edu.itp.phys.ethz.ch/hs12/programming_techniques/openmpi.pdf)

OpenMPI Steps:

1. Download most recent stable OpenMPI version
2. extract files to temp directory
3. `./configure --prefix=$HOME/opt/openmpi`
4. `make all`
5. `make install`
6. remove temp directory
7. Add MPI to PATH and LD_LIBRARY_PATH in `$HOME/.bashrc` or `$HOME/.zshrc` for Mac 
8. 	`$ export PATH=$PATH:$HOME/opt/openmpi/bin`
9. 	`$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/opt/openmpi/lib`

	
In turn, the code may attempt to use other potential enviroments with a mpicc complier such as 'Anaconda'. Make sure to deactivate the '(conda)' environment before use so OpenMPI's is used. 

- When starting a python run, it is useful to contain the each run in separate directories/folders.

- When running multiprocessor runs, make sure the parameter file (root.pf) has the necessary inputs before starting a run. Parameters cannot be inputted interactively when in multiprocessor mode. 
Hence, if no 'roof.pf' is created yet, you would need to start a single processor run first (py root.pf), interactively enter parameter inputs/values and then cancel the run as the code begins to process. 

- Advanced diagnostics are activated using the -d switch when running python, however it wasn't necessarily clear where the descriptions of these tools were. 
They are located in /inputs/parameters/Other and start with Diag.xxx

Several options including Diag.(make_ioncylce_tables/save_extract_photons/save_photons/track_resonant_scatters) do not have any descriptive factors of what the tool does, a couple lines can help. 
Other Diag tools such as diag.(use_jumps_for_emissivities_in_detailed_spectra/turn_off_upweighting_of_simple_macro_atoms) are missing completely. I can't necessarily be sure how many more aren't listed unless I go through and activate every tool on every possible run.
A new section in the docs collecting the diag tool names might help. 

That's everything I have noted so far. End :)

**Comment by kslong** [comment]
Thanks for doing this @AustenWallis 

On the details, I question a bit whether we need to tell folks how to install mpi, and Python should work with mpich as well

On ubunto machines, one can install either without as much trouble using commands like those described here

https://installati.one/ubuntu/20.04/openmpi-bin/


On MACS, one can use homebrew, or someting else.

Also,as a comment, I don't actually put runs in different folders. Python is explicitly designed so that is not entirely necessary (though this is something that could be improved).  

This is why all of the files start with the rootname of a run and why the diagnostic files are put in a folder of their own.  The place where it might be improved (right now) is that it might be a better idea to push more of the files into the subfolder, especailly those made by windsave2table

**Comment by AustenWallis** [comment]
Yes I would largely agree. The explicit instructions typed out would probably not be necessary. 

However, I would think it would be useful to have a hyperlink to some place with installation instructions for something like OpenMPI. Understanding OpenMPI's docs was quite confusing for an installation when you haven't used it before. 
For example, pythons docs description line at the moment could be improved with?

- For linux machines, two common libraries are [Open-MPI](https://www.open-mpi.org/) ([install steps](https://installati.one/ubuntu/20.04/openmpi-bin/)) and [MPICH](https://www.mpich.org/) [install](another link for mpich). If not already installed, one should install them.

I might be very much an edge case in this sense as I had not used macOS at all before but one other benefit would be that it insures consistent install procedures. As homebrew for example, I didn't have installed either.

And true with the runs put into different folders. This is likely a very individual way of working. I'm very much a person that maintains an empty email inbox, downloads folders and every document/screenshot is in a designated folder. 

I do like the idea of maybe pushing the outputted files automatically into the subfolders, or a subfolder for each run though. Although I will hold my tongue with this as I am not sure how much work it would be to implement this, whether it would be simple or quite complex.
